### ISSUE TITLE
trace无法查看经过cglib加强之前的代码执行情况

### ISSUE THREAD

**Issue by 18518933040** [alibaba/arthas#1018]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：未知
* Arthas 版本: 未知
* 操作系统版本: center os6
* 目标进程的JVM版本: 1.7
* 执行`arthas-boot`的版本: 未知

### 重现问题的步骤

1. trace 一个经过cglib加强之后的代码，trace未输出对应业务代码的执行逻辑

### 期望的结果
cglib加强之前的代码执行情况
What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
`---ts=2020-02-03 22:01:47;thread_name=/api/internal/ticket@f181f438d735e3c5;id=148;is_daemon=true;priority=5;TCCL=org.apache.catalina.loader.WebappClassLoader@584cb528
    `---[217.131297ms] a.b.c.product.service.impl.product.ProductQueryService$$EnhancerByCGLIB$$bf7bb5ef:queryProductInfoByCondition()
        `---[217.065603ms] net.sf.cglib.proxy.MethodInterceptor:intercept() #0
```

**Comment by hengyunabc** [comment]
最好有可重现的demo

**Comment by zhugw** [comment]
@hengyunabc 
想反馈同样的问题 高并发的情况下 接口很慢 定位到Mybatic查询慢 
```
`---ts=2020-03-07 15:57:19;thread_name=http-nio-9090-exec-104;id=ab;is_daemon=true;priority=5;TCCL=org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader@5f5effb0
    `---[4795.964944ms] com.sun.proxy.$Proxy76:selectByDataCodeAndType()
```

但是想要的是 类似jstack一样的更详细的信息 如下
```
"http-nio-9090-exec-171" #239 daemon prio=5 os_prio=31 tid=0x00007ff38ab2ee40 nid=0x12e07 waiting on condition [0x000070000f396000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007a0bad000> (a java.util.concurrent.SynchronousQueue$TransferQueue)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferQueue.awaitFulfill(SynchronousQueue.java:764)
	at java.util.concurrent.SynchronousQueue$TransferQueue.transfer(SynchronousQueue.java:695)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:157)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:173)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:157)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:82)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:68)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:336)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.prepareStatement(MybatisSimpleExecutor.java:93)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:66)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
	at sun.reflect.GeneratedMethodAccessor215.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	at com.sun.proxy.$Proxy75.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:89)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:62)
	at com.sun.proxy.$Proxy76.selectByDataCodeAndType(Unknown Source)
```
这样的话 就知道时间都花在等待数据库连接池中的可用连接上了 便于知道如何优化

**Comment by hengyunabc** [comment]
@zhugw trace是只有两层的。trace是要付出代价的。

**Comment by wrkaiser** [comment]
同问，貌似我trace的一个ES自定义插件的方法也是被cglib已增强的

**Comment by hengyunabc** [comment]
@zhugw @wrkaiser  关于代理，可以看下这个偷跑的Demo，里面有怎么跟踪代理实现的。

https://github.com/hengyunabc/arthas-mybatis-demo
