### ISSUE TITLE
invalid CEN header (bad signature)

### ISSUE THREAD

**Issue by aohanhongzhi** [alibaba/arthas#1045]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。
是的
### 环境信息
centos
* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.7
* Arthas 版本: 3.1.7
* 操作系统版本: centos 7 x64
* 目标进程的JVM版本: open-jdk11
* 执行`arthas-boot`的版本: 3.1.7

### 重现问题的步骤

1. 使用jad反编译代码
2.   使用mc命令编译修改后的 代码出现异常。
3. 然后没有下文了

### 期望的结果

What do you expected from the above steps？
反编译出class文件，然后导出
### 实际运行的结果
报错

命令行提示信息如下
```
Memory compiler error, exception message: Compilation Error
line: 29 , message: 无法访问com.ctcc.misas.common.service.impl
  invalid CEN header (bad signature) , 
, please check $HOME/logs/arthas/arthas.log for more details. 
Affect(row-cnt:0) cost in 976 ms.

```
arthas的日志信息如下
```
01 2020-03-05 14:44:43.771 WARN [as-command-execute-daemon:arthas] [] [] [] Memory compiler error
com.taobao.arthas.compiler.DynamicCompilerException: Compilation Error
line: 29 , message: 无法访问com.ctcc.misas.common.service.impl
  invalid CEN header (bad signature) , 

	at com.taobao.arthas.compiler.DynamicCompiler.buildByteCodes(DynamicCompiler.java:132)
	at com.taobao.arthas.core.command.klass100.MemoryCompilerCommand.process(MemoryCompilerCommand.java:106)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by hengyunabc** [comment]
https://alibaba.github.io/arthas/mc mc有可能失败。
