### ISSUE TITLE
JRocket JDK1.6.0_45无法支持

### ISSUE THREAD

**Issue by jiangwh** [alibaba/arthas#1059]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.7
* Arthas 版本: 3.1.7
* 操作系统版本: window 10
* 目标进程的JVM版本: JRocket JDK1.6.0_45
* 执行`arthas-boot`的版本: JRocket JDK1.6.0_45
### 重现问题的步骤

1. java -jar arthas-demo.jar
2. java -jar arthas-boot.jar
3. 选择arthas-demo 进程。
4.arthas attach 失败。

### 期望的结果
可以成功挂载。

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```
[ERROR] Start arthas failed, exception stack trace:
java.lang.InternalError: Remote thread failed for unknown reason
        at sun.tools.attach.WindowsVirtualMachine.enqueue(Native Method)
        at sun.tools.attach.WindowsVirtualMachine.execute(WindowsVirtualMachine.java:78)
        at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:40)
        at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:61)
        at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:85)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:104)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:123)
[ERROR] attach fail, targetPid: 6640

**Comment by hengyunabc** [comment]
只测试过 hotspot，其它的都可能有问题。
