### ISSUE TITLE
使用stack追踪System.exit异常

### ISSUE THREAD

**Issue by Lyeenn** [alibaba/arthas#1067]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.7
* Arthas 版本: 3.1.7
* 操作系统版本: Linux version 3.10.0-693.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) )
* 目标进程的JVM版本: 1.8

### 重现问题的步骤
参考use-case：https://github.com/alibaba/arthas/issues/20

1. 运行java实例
2. 执行脚本./as.sh -b -f system_exit.as  17623 > system_exit.out 2>&1 &

### 期望的结果
在system_exit.out里打印出System.exit的调用栈

### 实际运行的结果

Arthas script version: 3.1.7
[INFO] JAVA_HOME: /usr/local/java-1.8.0/jdk1.8.0_144
Arthas home: /root/.arthas/lib/3.1.7/arthas
Calculating attach execution time...
Attaching to -b using version /root/.arthas/lib/3.1.7/arthas...
[ERROR] Start arthas failed, exception stack trace: 
com.taobao.middleware.cli.InvalidValueException: The value '-b' is not accepted by 'pid'
        at com.taobao.middleware.cli.impl.DefaultCommandLine.create(DefaultCommandLine.java:342)
        at com.taobao.middleware.cli.impl.DefaultCommandLine.getValue(DefaultCommandLine.java:267)
        at com.taobao.middleware.cli.impl.DefaultCommandLine.getOptionValue(DefaultCommandLine.java:91)
        at com.taobao.arthas.core.Arthas.parse(Arthas.java:53)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:123)
Caused by: java.lang.IllegalArgumentException: java.lang.NumberFormatException: For input string: "-b"
        at com.taobao.middleware.cli.converters.ConstructorBasedConverter.fromString(ConstructorBasedConverter.java:70)
        at com.taobao.middleware.cli.converters.Converters.create(Converters.java:52)
        at com.taobao.middleware.cli.impl.DefaultCommandLine.create(DefaultCommandLine.java:339)
        ... 5 more
Caused by: java.lang.NumberFormatException: For input string: "-b"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.<init>(Integer.java:867)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.taobao.middleware.cli.converters.ConstructorBasedConverter.fromString(ConstructorBasedConverter.java:67)
        ... 7 more
attach to target jvm (-b) failed, check /root/logs/arthas/arthas.log or stderr of target jvm for any exceptions.
```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
这个是传参问题，试下把 -b 放最后。

**Comment by hengyunabc** [comment]
仔细看了下脚本，实际上是没有 `-b`这个参数的，文档里写错了。后面更新修复掉。

**Comment by hengyunabc** [comment]
参考： https://github.com/alibaba/arthas/issues/1072
