### ISSUE TITLE
先trace后stop导致的奇怪的空指针异常

### ISSUE THREAD

**Issue by zhugw** [alibaba/arthas#1094]
发现线上有奇怪的空指针异常 百思不得其解

```
04:04 21:51:08.368 [pool-6-thread-2] [ERROR] [c.c.p.o.service.BaseOracle2EsService] - indexFromRedisQueue failed
java.lang.NullPointerException: null
	at com.foo.oracle2es.service.PersonCompanyPostFullUpdateService.batchQueryAndIndex(PersonCompanyPostFullUpdateService.java:112)
	at com.foo.oracle2es.service.BaseOracle2EsService.indexFromRedisQueue(BaseOracle2EsService.java:86)
	at com.foo.oracle2es.service.BaseOracle2EsService.lambda$oracle2Es$1(BaseOracle2EsService.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
112行代码如下
```
        return idList.size();
```
若idList为空的话 前面的代码就会报错  不会等到最后return的时候才报错 一直想不明白

最后偶然发现规律是 当执行了arthas `trace`命令后 在执行`stop` 紧接着会产生这个奇怪的异常
```
trace com.foo.oracle2es.service.PersonCompanyPostFullUpdateService batchQueryAndIndex
```
本地也复现了

问 为什么`trace`后 在`stop` 就会有这个异常呢？

### 其他信息补充：

arthas版本： 3.1.8
JDK: 1.8.0_192
另外执行`watch` 也有同样的问题

其实上面的异常 是本地复现时的异常 线上的异常更奇怪 直接`Unknow Source`
```
04:03 22:41:51.275 [pool-6-thread-6] [ERROR] [c.c.p.o.service.BaseOracle2EsService] - indexFromRedisQueue failed
java.lang.NullPointerException: null
        at com.foo.oracle2es.service.PersonCompanyPostFullUpdateService.batchQueryAndIndex(Unknown Source)
```

**Comment by hengyunabc** [comment]
重现问题后，用这个工具dump class，再反编译看下具体为什么： https://github.com/hengyunabc/dumpclass

**Comment by zhugw** [comment]
@hengyunabc  看不懂啊 觉得很奇怪呢

就拿最后的return来说吧
```
return idList.size();
```
变成了
```
                                        int var122 = idList.size();
                                        var112 = null;
                                        var10003 = true;
                                        var10002 = false;
                                        Spy.ON_RETURN_METHOD.invoke((Object)null, new Integer(var122));
                                        var10001 = true;
                                        var10003 = false;
                                        var113 = null;
                                        var112 = null;
                                        var10003 = true;
                                        var10002 = false;
                                        Spy.ON_RETURN_METHOD.invoke((Object)null, new Integer(var122));
                                        var10001 = true;
                                        var10003 = false;
                                        var113 = null;
                                        var112 = null;
                                        var10003 = true;
                                        var10002 = false;
                                        Spy.ON_RETURN_METHOD.invoke((Object)null, new Integer(var122));
                                        var10001 = true;
                                        var10003 = false;
                                        var113 = null;
                                        var112 = null;
                                        var10003 = true;
                                        var10002 = false;
                                        Spy.ON_RETURN_METHOD.invoke((Object)null, new Integer(var122));
                                        var10001 = true;
                                        var10003 = false;
                                        var113 = null;
                                        var112 = null;
                                        var10003 = true;
                                        var10002 = false;
                                        Spy.ON_RETURN_METHOD.invoke((Object)null, new Integer(var122));
                                        var10001 = true;
                                        var10003 = false;
                                        var113 = null;
                                        var112 = null;
                                        var10003 = true;
                                        var10002 = false;
                                        Spy.ON_RETURN_METHOD.invoke((Object)null, new Integer(var122));
                                        var10001 = true;
                                        var10003 = false;
                                        var113 = null;
                                        var112 = null;
                                        var10003 = true;
                                        var10002 = false;
                                        Spy.ON_RETURN_METHOD.invoke((Object)null, new Integer(var122));
                                        var10001 = true;
                                        var10003 = false;
                                        var113 = null;
                                        var112 = null;
                                        var10003 = true;
                                        var10002 = false;
                                        Spy.ON_RETURN_METHOD.invoke((Object)null, new Integer(var122));
                                        var10001 = true;
                                        var10003 = false;
                                        var113 = null;
                                        return var122;
```

怎么感觉重复执行了(下面的代码执行了8次呢) 这正常吗？
```
Spy.ON_RETURN_METHOD.invoke((Object)null, new Integer(var122));
```

**Comment by hengyunabc** [comment]
@zhugw arthas目前多次 trace，会多次增强字节码。 可以执行reset 命令清除掉。

可以提供可重现的demo不？

**Comment by zhugw** [comment]
@hengyunabc 已提供了复现的demo
git@github.com:zhugw/arthas_trace_bug_demo.git

**Comment by hengyunabc** [comment]
在应用的标准输出里，打印的是：

```java
java.lang.NullPointerException
	at ArthasTraceBugDemoApplication.process(ArthasTraceBugDemoApplication.java:63)
	at ArthasTraceBugDemoApplication.lambda$1(ArthasTraceBugDemoApplication.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

在 `~/logs/arthas/arthas.log` 里，打印的是：

```java
2020-04-08 01:26:56 [pool-1-thread-5] WARN  c.t.arthas.core.advisor.AdviceWeaver -advice returning failed.
java.lang.IllegalStateException: Cannot write to standard output when terminated
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessImpl.write(ProcessImpl.java:454)
        at com.taobao.arthas.core.command.monitor200.AbstractTraceAdviceListener.finishing(AbstractTraceAdviceListener.java:90)
        at com.taobao.arthas.core.command.monitor200.AbstractTraceAdviceListener.afterReturning(AbstractTraceAdviceListener.java:56)
        at com.taobao.arthas.core.advisor.ReflectAdviceListenerAdapter.afterReturning(ReflectAdviceListenerAdapter.java:133)
        at com.taobao.arthas.core.advisor.AdviceWeaver.afterReturning(AdviceWeaver.java:324)
        at com.taobao.arthas.core.advisor.AdviceWeaver.methodOnEnd(AdviceWeaver.java:165)
        at com.taobao.arthas.core.advisor.AdviceWeaver.methodOnReturnEnd(AdviceWeaver.java:118)
        at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at ArthasTraceBugDemoApplication.process(ArthasTraceBugDemoApplication.java:63)
        at ArthasTraceBugDemoApplication.lambda$1(ArthasTraceBugDemoApplication.java:46)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

---

问题是：到底是在哪里有空指针？ 也许用jdk14的新特性比较容易找出来。。

实际是上 `java.arthas.Spy.destroy()` ，这里会把这些 method 置为 null ，但是应用的线程还在跑。当跑到要获取这些 method，再invoke时，就会抛出 NullPointerException 。

Arthas在stop时，com.taobao.arthas.core.server.ArthasBootstrap.cleanUpSpyReference() 会调用 `java.arthas.Spy.destroy()`

```java
    // -- 各种Advice的钩子引用 --
    public static volatile Method ON_BEFORE_METHOD;
    public static volatile Method ON_RETURN_METHOD;
    public static volatile Method ON_THROWS_METHOD;
    public static volatile Method BEFORE_INVOKING_METHOD;
    public static volatile Method AFTER_INVOKING_METHOD;
    public static volatile Method THROW_INVOKING_METHOD;

    /**
     * Clean up the reference to com.taobao.arthas.agent.AgentLauncher$1
     * to avoid classloader leak.
     */
    public static void destroy() {
        CLASSLOADER = null;
        ON_BEFORE_METHOD = null;
        ON_RETURN_METHOD = null;
        ON_THROWS_METHOD = null;
        BEFORE_INVOKING_METHOD = null;
        AFTER_INVOKING_METHOD = null;
        THROW_INVOKING_METHOD = null;
        // clear the reference to ArthasClassLoader in AgentLauncher
        if (AGENT_RESET_METHOD != null) {
            try {
                AGENT_RESET_METHOD.invoke(null);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        AGENT_RESET_METHOD = null;
    }
```

**Comment by zhugw** [comment]
@hengyunabc 提醒下 不单单trace watch 也会有同样的问题

**Comment by hengyunabc** [comment]
@zhugw trace/watch都是一样的。可以试下这个测试包

[arthas-3.1.9-SNAPSHOT-bin.zip](https://github.com/alibaba/arthas/files/4448046/arthas-3.1.9-SNAPSHOT-bin.zip)
