### ISSUE TITLE
Linux/Connection refused (Connection refused)

### ISSUE THREAD

**Issue by rhythmdai** [alibaba/arthas#1100]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.1.8
* Arthas 版本: 3.1.8
* 操作系统版本: linux
* 目标进程的JVM版本: 1.8.0_112
* 执行`arthas-boot`的版本: 3.1.8

### 重现问题的步骤

1.wget https://maven.aliyun.com/repository/public/com/taobao/arthas/arthas-packaging/3.1.8/arthas-packaging-3.1.8-bin.zip 下载zip文件并解压到工作目录下

2.sudo java -jar ./arthas-boot.jar 出现java 进程列表 选择想要 attach的jvm eg:3

3.arthas home: /home/myname/arthas
[INFO] Try to attach process 22817
[ERROR] Start arthas failed, exception stack trace: 
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
        at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
        at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:85)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:123)
[INFO] Attach process 22817 success.
[INFO] arthas-client connect 127.0.0.1 3658
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
        at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:249)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:547)

机器安装了telnet  使用sudo权限运行  ;  sudo netstat -anltp |grep '3658'  端口未被占用
想要attach的进程是使用一个非sudo权限的账号起的

**Comment by hengyunabc** [comment]
只能用对应用户来 attach。其它用户会失败。
