### ISSUE TITLE
pid连接错误

### ISSUE THREAD

**Issue by tofindnorthstar** [alibaba/arthas#1106]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.8
* Arthas 版本: 3.1.8
* 操作系统版本: linux
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本:3.1.8

### 重现问题的步骤

1. 执行java -jar arthas-boot.jar
 * [1]: 32705 -----------------
  [2]: 19413 ./JettyRuntime/server.jar
  [3]: 6550 
  [4]: 13590 
  [5]: 6554 JettyRuntime/server.jar
  [6]: 13162 
  [7]: 2187 
  [8]: 6557 
  [9]: 6559 
2. 输入2
3. 显示如下
wiki      https://alibaba.github.io/arthas                                      
tutorials https://alibaba.github.io/arthas/arthas-tutorials                     
version   3.1.8                                                                 
pid       6550                                                                  
time      2020-04-11 10:45:59

### 期望的结果

pid应该连接19413

### 实际运行的结果

shutdown后重启：连接2，报错如下

```

[INFO] arthas home: /root/.arthas/lib/3.1.8/arthas
[INFO] Try to attach process 19413
[INFO] Attach process 19413 success.
[INFO] arthas-client connect 127.0.0.1 3658
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: 拒绝连接
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
        at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:249)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:547)
Usage: arthas-client [--help] [-c <value>] [-f <value>] [-w <value>] [-h
       <value>] [target-ip] [port]

```

**Comment by hengyunabc** [comment]
检查 `~/logs/arthas/arthas.log`
