### ISSUE TITLE
Connect to telnet server error: 127.0.0.1 3658

### ISSUE THREAD

**Issue by zhanglegen** [alibaba/arthas#1108]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.2.0
* Arthas 版本: 3.2.0
* 操作系统版本: centos6.9
* 目标进程的JVM版本: 1.8.0_181
* 执行`arthas-boot`的版本: 3.2.0

错误代码
=============================================
[root@centos6 ~]# java -jar arthas-boot.jar 
[INFO] arthas-boot version: 3.2.0
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 2338 org.apache.catalina.startup.Bootstrap
  [2]: 24270 arthas-demo.jar
2
[INFO] arthas home: /root/.arthas/lib/3.2.0/arthas
[INFO] Try to attach process 24270
[INFO] Attach process 24270 success.
[INFO] arthas-client connect 127.0.0.1 3658
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: 拒绝连接 (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
        at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:249)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:547)
Usage: arthas-client [--help] [-c <value>] [-f <value>] [-w <value>] [-h
       <value>] [target-ip] [port]

Arthas Telnet Client

EXAMPLES:
  java -jar arthas-client.jar 127.0.0.1 3658
  java -jar arthas-client.jar -c 'dashboard -n 1'
  java -jar arthas-client.jar -f batch.as 127.0.0.1

Options and Arguments:
    --help                 Print usage
 -c,--command <value>      Command to execute, multiple commands separated by ;
 -f,--batch-file <value>   The batch file to execute
 -w,--width <value>        The terminal width
 -h,--height <value>       The terminal height
 <target-ip>               Target ip
 <port>                    The remote server port
==========================================
启动时候报这个错 是为啥
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: 拒绝连接 (Connection refused)

**Comment by hengyunabc** [comment]
查看 `~/logs/arthas/arthas.log` ，另外可以先停止 arthas-demo，检查是否有应用已占用 3658 端口。

**Comment by robert-guangzhou** [comment]
我也遇到这个问题，3.4.1 版本[root@140 arthas]# java -jar arthas-boot.jar 
[INFO] arthas-boot version: 3.4.1
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 12960 /root/nacos/target/nacos-server.jar
  [2]: 14203 arthas-demo.jar
1
[INFO] arthas home: /root/.arthas/lib/3.4.1/arthas
[INFO] Try to attach process 12960
[INFO] Attach process 12960 success.
[INFO] arthas-client connect 127.0.0.1 3658
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
        at com.taobao.arthas.client.TelnetConsole.process(TelnetConsole.java:309)
        at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:166)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:549)
连接另外的java 进程，没有问题。

**Comment by tyzou** [comment]
我也遇到了这个问题，重启了一下tomcat就可以了
