### ISSUE TITLE
有时候绑定项目不成功，需要重启该项目之后，才可以绑定，而且有时候也不一定能成功

### ISSUE THREAD

**Issue by wangdayewjf** [alibaba/arthas#1116]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. quit quit stop stop 这种操作顺序连续关闭重启，出现以下问题

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
[INFO] Try to attach process 3551
[INFO] Attach process 3551 success.
[INFO] arthas-client connect 127.0.0.1 3658
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
        at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:249)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:547)

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
arthas什么版本的？ 用 arthas-demo.jar 能重现不?

**Comment by netbuffer** [comment]
同样遇到过，重新下载了最新版3.2.0还是不行

[INFO] arthas home: /root/.arthas/lib/3.2.0/arthas
[INFO] Try to attach process 17867
[INFO] Attach process 17867 success.
[INFO] arthas-client connect 127.0.0.1 3658
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
	at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:547)
Usage: arthas-client [--help] [-c <value>] [-f <value>] [-w <value>] [-h
       <value>] [target-ip] [port]

Arthas Telnet Client

EXAMPLES:
  java -jar arthas-client.jar 127.0.0.1 3658
  java -jar arthas-client.jar -c 'dashboard -n 1'
  java -jar arthas-client.jar -f batch.as 127.0.0.1

Options and Arguments:
    --help                 Print usage
 -c,--command <value>      Command to execute, multiple commands separated by ;
 -f,--batch-file <value>   The batch file to execute
 -w,--width <value>        The terminal width
 -h,--height <value>       The terminal height
 <target-ip>               Target ip
 <port>                    The remote server port

**Comment by hengyunabc** [comment]
@netbuffer 检查 ~/logs/arthas/arthas.log

**Comment by netbuffer** [comment]
@hengyunabc 

这是日志

2020-04-27 11:41:14 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x95504e67, L:/127.0.0.1:3658] READ: [id: 0xa0d39812, L:/127.0.0.1:3658 - R:/127.0.0.1:52452]
2020-04-27 11:41:14 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x95504e67, L:/127.0.0.1:3658] READ COMPLETE
2020-04-27 11:41:14 [nioEventLoopGroup-2-3] INFO  c.t.a.core.shell.term.impl.Helper -Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
2020-04-27 11:41:46 [as-command-execute-daemon] INFO  c.t.arthas.core.advisor.Enhancer -Success to reset classes: []
2020-04-27 11:41:46 [nioEventLoopGroup-2-3] INFO  c.t.a.c.shell.impl.ShellServerImpl -Session c1c63178-1ae7-4bf5-b215-3115b99c398b closed, so terminate foreground job, id: 5, line: stop
2020-04-27 11:41:46 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x95504e67, L:/127.0.0.1:3658] INACTIVE
2020-04-27 11:41:46 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x95504e67, L:/127.0.0.1:3658] UNREGISTERED
2020-04-27 11:41:46 [nioEventLoopGroup-3-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x08fe3f4c, L:/127.0.0.1:8563] CLOSE
2020-04-27 11:41:46 [nioEventLoopGroup-3-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x08fe3f4c, L:/127.0.0.1:8563] INACTIVE
2020-04-27 11:41:46 [nioEventLoopGroup-3-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x08fe3f4c, L:/127.0.0.1:8563] UNREGISTERED
2020-04-27 11:41:46 [as-command-execute-daemon] INFO  c.t.a.core.server.ArthasBootstrap -as-server destroy completed.
Arthas server agent start...
2020-04-27 11:43:11 [arthas-binding-thread] INFO  c.t.arthas.core.util.ArthasBanner -arthas version: 3.2.0
2020-04-27 11:43:11 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x1e1b46ad] REGISTERED
2020-04-27 11:43:11 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x1e1b46ad] BIND: /127.0.0.1:3658
2020-04-27 11:43:11 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x1e1b46ad, L:/127.0.0.1:3658] ACTIVE
2020-04-27 11:43:11 [nioEventLoopGroup-3-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0xe927a78d] REGISTERED
2020-04-27 11:43:11 [nioEventLoopGroup-3-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0xe927a78d] BIND: /127.0.0.1:8563
2020-04-27 11:43:11 [nioEventLoopGroup-3-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0xe927a78d, L:/127.0.0.1:8563] ACTIVE
2020-04-27 11:43:11 [arthas-binding-thread] INFO  c.t.a.core.server.ArthasBootstrap -as-server listening on network=127.0.0.1;telnet=3658;http=8563;timeout=6000;
2020-04-27 11:43:11 [arthas-binding-thread] INFO  c.t.a.core.server.ArthasBootstrap -as-server started in 278 ms
Arthas server already bind.
2020-04-27 11:43:11 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x1e1b46ad, L:/127.0.0.1:3658] READ: [id: 0xc21bc891, L:/127.0.0.1:3658 - R:/127.0.0.1:52520]
2020-04-27 11:43:11 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x1e1b46ad, L:/127.0.0.1:3658] READ COMPLETE
2020-04-27 11:43:11 [nioEventLoopGroup-2-2] INFO  c.t.a.core.shell.term.impl.Helper -Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
2020-04-27 11:43:15 [as-command-execute-daemon] INFO  c.t.arthas.core.advisor.Enhancer -Success to reset classes: []
2020-04-27 11:43:15 [nioEventLoopGroup-2-2] INFO  c.t.a.c.shell.impl.ShellServerImpl -Session e30d99ea-81da-47a5-97d1-38228305d0d7 closed, so terminate foreground job, id: 1, line: stop
2020-04-27 11:43:15 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x1e1b46ad, L:/127.0.0.1:3658] INACTIVE
2020-04-27 11:43:15 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x1e1b46ad, L:/127.0.0.1:3658] UNREGISTERED
2020-04-27 11:43:15 [nioEventLoopGroup-3-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0xe927a78d, L:/127.0.0.1:8563] CLOSE
2020-04-27 11:43:15 [nioEventLoopGroup-3-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0xe927a78d, L:/127.0.0.1:8563] INACTIVE
2020-04-27 11:43:15 [nioEventLoopGroup-3-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0xe927a78d, L:/127.0.0.1:8563] UNREGISTERED
2020-04-27 11:43:15 [as-command-execute-daemon] INFO  c.t.a.core.server.ArthasBootstrap -as-server destroy completed.
Arthas server agent start...
2020-04-27 13:54:06 [arthas-binding-thread] INFO  c.t.arthas.core.util.ArthasBanner -arthas version: 3.2.0
2020-04-27 13:54:07 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0xe6761d22] REGISTERED
2020-04-27 13:54:07 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0xe6761d22] BIND: /127.0.0.1:3658
2020-04-27 13:54:07 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0xe6761d22, L:/127.0.0.1:3658] ACTIVE
2020-04-27 13:54:07 [nioEventLoopGroup-3-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x1125cc0f] REGISTERED
2020-04-27 13:54:07 [nioEventLoopGroup-3-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x1125cc0f] BIND: /127.0.0.1:8563
2020-04-27 13:54:07 [nioEventLoopGroup-3-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x1125cc0f, L:/127.0.0.1:8563] ACTIVE
2020-04-27 13:54:07 [arthas-binding-thread] INFO  c.t.a.core.server.ArthasBootstrap -as-server listening on network=127.0.0.1;telnet=3658;http=8563;timeout=6000;
2020-04-27 13:54:07 [arthas-binding-thread] INFO  c.t.a.core.server.ArthasBootstrap -as-server started in 270 ms
Arthas server already bind.
2020-04-27 13:54:07 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0xe6761d22, L:/127.0.0.1:3658] READ: [id: 0xb86071b6, L:/127.0.0.1:3658 - R:/127.0.0.1:56734]
2020-04-27 13:54:07 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0xe6761d22, L:/127.0.0.1:3658] READ COMPLETE
2020-04-27 13:54:07 [nioEventLoopGroup-2-2] INFO  c.t.a.core.shell.term.impl.Helper -Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc

**Comment by hengyunabc** [comment]
@netbuffer 可以稳定重现不？ 在一个空的机器上，用arthas-demo.jar 做例子。

**Comment by BLHSmilence** [comment]
一样有，有时候exit，shutdown，quit之类的之后，就发现重新连不上了，需要重启服务，怎么解决的
![图片](https://user-images.githubusercontent.com/20475321/86213670-a679f180-bbac-11ea-9246-8cf90eb66aa2.png)

**Comment by sang556** [comment]
我也遇到一样的问题，一直报 Connection refused ，连不上3658端口

**Comment by BLHSmilence** [comment]
谢谢您的来信！————…^_^我已经收到咯哦！Thanks for your letter!I have received it now!
