### ISSUE TITLE
macOS 普通用户启动Arthas报错找不到方法ArthasBootstrap.bind

### ISSUE THREAD

**Issue by kylixs** [alibaba/arthas#1120]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.2.0
* Arthas 版本: 3.2.0
* 操作系统版本: macOS 10.15.4
* 目标进程的JVM版本: "1.8.0_151"
* 执行`arthas-boot`的版本:  3.2.0

### 重现问题的步骤

1. 在macOS创建普通用户user1
2. 在terminal切换到user1 :  su - user1
3. 在user1 shell执行：java -jar arthas-demo.jar
4. 在user1 shell执行：java -jar arthas-boot.jar， 选择注入上面的arthas-demo.jar

另外补充一下，在管理员用户下启动arthas正常。
### 期望的结果

What do you expected from the above steps？

期望成功注入arthas-demo进程

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

实际执行报错
```
[INFO] Try to attach process 19455
[INFO] Attach process 19455 success.
[INFO] arthas-client connect 127.0.0.1 3658
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
	at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:539)
Usage: arthas-client [--help] [-c <value>] [-f <value>] [-w <value>] [-h
       <value>] [target-ip] [port]
```

arthas.log日志中的错误信息：
```
Arthas server agent start...
Arthas start to bind...
Arthas server port binding failed! Please check $HOME/logs/arthas/arthas.log for more details.
java.lang.NoSuchMethodException: com.taobao.arthas.core.server.ArthasBootstrap.bind(java.lang.String)
	at java.lang.Class.getMethod(Class.java:1786)
	at com.taobao.arthas.agent3.AgentBootstrap.bind(AgentBootstrap.java:199)
	at com.taobao.arthas.agent3.AgentBootstrap.access$000(AgentBootstrap.java:21)
	at com.taobao.arthas.agent3.AgentBootstrap$1.run(AgentBootstrap.java:164)
```

**Comment by yuhui0531** [comment]
我也碰到类似的问题，请问目前有什么解决方案吗？

**Comment by xuchmao** [comment]
com.taobao.arthas.core.server.ArthasBootstrap.bind(String args)方法在2020/3/31日的提交中remove掉了

**Comment by hengyunabc** [comment]
@xuchmao 出现这个问题的主要原因是，之前用旧版本的 arthas attach过了，然后 arthas-agent.jar在 应用的 system classloader里了。 下次修改了api，用新版本的 arthas attach之后，尽管 新的 arthas-agent 加到了 system classloader里。但应用再也加载不到了。

所以就会出现类似的异常。 所以现在arthas发新版本，都尽量改一个 pakcage名，避免冲突。
