### ISSUE TITLE
thread及mbean列出的信息包括了其它java 进程的信息

### ISSUE THREAD

**Issue by radishgz** [alibaba/arthas#1125]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar`  ： 3.2.0
* Arthas 版本: 3.2.0
* 操作系统版本: 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux ，CentOS Linux release 7.6.1810 (Core) 
* 目标进程的JVM版本:  openjdk version "1.8.0_212"
* 执行`arthas-boot`的版本: openjdk version "1.8.0_212"

### 重现问题的步骤

1. 启动 java -jar arthas-demo.jar
2. 启动zookeeper 
3. 确认启动正常
[root@localhost arthas]# ps -ef|grep java|grep demo
root      10574   9769  0 20:18 pts/0    00:00:00 java -jar arthas-demo.jar
4. 连接demo
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 9806 org.apache.zookeeper.server.quorum.QuorumPeerMain
  [2]: 10574 arthas-demo.jar
2
[INFO] arthas home: /root/.arthas/lib/3.2.0/arthas
[INFO] Try to attach process 10574
[INFO] Attach process 10574 success.
[INFO] arthas-client connect 127.0.0.1 3658
5. 使用thread 1查看，发现是zookeeper 进程
 
[arthas@9806]$ thread 1
"main" Id=1 WAITING on java.util.concurrent.CountDownLatch$Sync@7ebbda5c
    at sun.misc.Unsafe.park(Native Method)
    -  waiting on java.util.concurrent.CountDownLatch$Sync@7ebbda5c
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
    at org.apache.zookeeper.server.ZooKeeperServerMain.runFromConfig(ZooKeeperServerMain.java:162)
    at org.apache.zookeeper.server.ZooKeeperServerMain.initializeAndRun(ZooKeeperServerMain.java:106)
    at org.apache.zookeeper.server.ZooKeeperServerMain.main(ZooKeeperServerMain.java:64)
    at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:128)
    at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)

[arthas@9806]$ mbean
java.lang:type=MemoryPool,name=Survivor Space
org.apache.ZooKeeperService:name0=StandaloneServer_port2181,name1=InMemoryDataTree

### 期望的结果
应该是 demo的main 及mbean 信息

### 实际运行的结
zookeeper 的main 及mbean 信息

**Comment by hengyunabc** [comment]
先执行 `stop` 退出在zk进程里跑的arthas。

**Comment by radishgz** [comment]
@hengyunabc  stop后正常了，谢谢
