### ISSUE TITLE
trace 方法时,报方法太长,怎么解决

### ISSUE THREAD

**Issue by xjwxiao** [alibaba/arthas#1138]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.1.1
* 操作系统版本: 
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: 3.1.1

### 重现问题的步骤

1. trace className method

### 期望的结果

能正常打印堆栈

### 实际运行的结果

 org.objectweb.asm.MethodTooLargeException: Method too large:  class.newQuestion (Ljava/lang/String;)Ljava/lang/String;
        at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2089) ~[arthas-core.jar:3.1.1]
        at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:458) ~[arthas-core.jar:3.1.1]
        at com.taobao.arthas.core.advisor.Enhancer.transform(Enhancer.java:163) [arthas-core.jar:3.1.1]
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188) [na:1.7.0_51]
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424) [na:1.7.0_51]
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method) [na:1.7.0_51]
        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144) [na:1.7.0_51]
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:304) [arthas-core.jar:3.1.1]
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:111) [arthas-core.jar:3.1.1]
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:66) [arthas-core.jar:3.1.1]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82) [arthas-core.jar:3.1.1]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18) [arthas-core.jar:3.1.1]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111) [arthas-core.jar:3.1.1]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108) [arthas-core.jar:3.1.1]
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370) [arthas-core.jar:3.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_51]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]

**Comment by wjwisme** [comment]
https://github.com/alibaba/arthas/issues/47

**Comment by yzhou452** [comment]
怎么解决的？
