### ISSUE TITLE
Unsupported class file major version 57

### ISSUE THREAD

**Issue by devenfan** [alibaba/arthas#1146]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.1.7
* Arthas 版本: 3.1.7
* 操作系统版本: CentOS 7.4
* 目标进程的JVM版本:  Open JDK 13
* 执行`arthas-boot`的版本: 3.1.7
* Tomcat 8.5

### 重现问题的步骤

1. OpenJdk13 + Tomcat 8.5 运行应用
2. 启动arthus
3. 使用watch命令

### 期望的结果

What do you expected from the above steps？

期望能够watch到输出或异常

### 实际运行的结果

No class or method is affected, try:
1. sm CLASS_NAME METHOD_NAME to make sure the method you are tracing actually exists (it might be in your parent class).
2. reset CLASS_NAME and try again, your method body might be too large.
3. check arthas log: /root/logs/arthas/arthas.log
4. visit https://github.com/alibaba/arthas/issues/47 for more details.

```
把异常信息贴到这里
```
01 2020-04-30 11:01:31.324 WARN [as-command-execute-daemon:arthas] [] [] [] transform loader[ParallelWebappClassLoader
  context: atpco-shopping
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@544fe44c
]:class[com/example/biz/service/impl/ServiceImpl] failed.
java.lang.IllegalArgumentException: Unsupported class file major version 57
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:184)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
        at com.taobao.arthas.core.advisor.Enhancer.transform(Enhancer.java:117)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:304)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:111)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:66)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by hengyunabc** [comment]
用最新的 3.2.0 版本

**Comment by devenfan** [comment]
升级到 Arthas 3.2.0就好了
