### ISSUE TITLE
【trace使用】对于springboot的control类无法使用

### ISSUE THREAD

**Issue by medal003** [alibaba/arthas#1147]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.2.0
* Arthas 版本: 3.2.0
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

trace springboot的controll方法，如
com.abc.qida.api.controller.ExportController test

### 期望的结果

希望打印方法中调用方法耗时，最好可以展示多级，目前只能展示1级

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
Error during processing the command: null

```
把异常信息贴到这里
2020-04-30 16:39:41 [as-command-execute-daemon] ERROR c.t.a.c.s.system.impl.ProcessImpl -Error during processing the command:
java.lang.ClassFormatError: null
at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:303)
at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:112)
at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:67)
at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:371)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by hengyunabc** [comment]
检查有没有其它的agent，比如 skywalking之类的。

**Comment by RainElohim** [comment]
> 检查有没有其它的agent，比如 skywalking之类的。

有会怎么样，怎么解决 ，我这也遇到了，确实用了sky的agent。。。

**Comment by hengyunabc** [comment]
和 arthas无关，参考： #1141
