### ISSUE TITLE
arthas 3.2.0 attach不上catalina

### ISSUE THREAD

**Issue by Jacquesomnus** [alibaba/arthas#1155]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.2.0
* Arthas 版本: 3.2.0
* 操作系统版本: CentOS 7.8.2003
* 目标进程的JVM版本: 1.8.0_252
* 执行`arthas-boot`的版本: 3.2.0

### 重现问题的步骤

1. java -jar arthas-boot.jar
2. input 3（3代表是catalina的相关进程）
3. enter

### 期望的结果

进入arthas界面

### 实际运行的结果

[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
        at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:104)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:123)
[ERROR] attach fail, targetPid: 3240

**Comment by hengyunabc** [comment]
检查 ~/logs/arthas/arthas.log
