### ISSUE TITLE
使用mc命令进行内存编译的时候报错，编译失败。

### ISSUE THREAD

**Issue by bluesaiz** [alibaba/arthas#1158]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：
 arthas-boot version: 3.2.0
* Arthas 版本: xxx
* 操作系统版本: 
CentOS Linux release 7.7.1908 (Core)
* 目标进程的JVM版本: 
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

* 执行`arthas-boot`的版本: 
java -jar arthas-boot.jar --version
[INFO] arthas-boot version: 3.2.0
### 重现问题的步骤

利用jad反编译有问题的类
jad --source-only com.abc.cloud.zuul.filter.post.ReplaceFilter > /tmp/ReplaceFilter.java
查找classloader
sc -d com/abc/cloud/zuul/filter/post/ReplaceFilter
...                                                                                                         
 classLoaderHash   681a9515 

进行内存编译
mc -c 681a9515 /tmp/ReplaceFilter.java -d /tmp/

### 期望的结果

应该正确编译出class文件

### 实际运行的结果

Memory compiler error, exception message: Compilation Error
line: 110 , message: incompatible types: java.lang.Object cannot be converted to org.dom4j.Element , 
, please check $HOME/logs/arthas/arthas.log for more details. 
Affect(row-cnt:0) cost in 6254 ms.

```
log文件里面的内容：
2020-05-09 09:28:40 [as-command-execute-daemon] WARN  c.t.a.c.c.k.MemoryCompilerCommand -Memory compiler error
com.taobao.arthas.compiler.DynamicCompilerException: Compilation Error
line: 110 , message: incompatible types: java.lang.Object cannot be converted to org.dom4j.Element , 

	at com.taobao.arthas.compiler.DynamicCompiler.buildByteCodes(DynamicCompiler.java:132)
	at com.taobao.arthas.core.command.klass100.MemoryCompilerCommand.process(MemoryCompilerCommand.java:106)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:371)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by hengyunabc** [comment]
mc 不保证成功： https://arthas.gitee.io/mc

**Comment by bluesaiz** [comment]
> mc 不保证成功： https://arthas.gitee.io/mc

哪些情况下会失败？可以说明一下吗

**Comment by hengyunabc** [comment]
> > mc 不保证成功： https://arthas.gitee.io/mc
> 
> 哪些情况下会失败？可以说明一下吗

1. 代码本身语法不对，比如用 jad反编译的结果就不一定合语法
2. 可能会有类加载问题，编译本质上是要找到语法单元，也就是要找到类名，函数名等。mc不一定能找到所有加载的类。

**Comment by songshengping** [comment]
您好！
我也碰到了相同的问题。
我使用源Java文件可以 编译成class.
但是使用class --mc-->java
在从java-->mc-->class 就报错。

**Comment by songshengping** [comment]
解决办法： 1.上传本地Java文件进行修改后编译即可（也就是绕过反编译阶段）

**Comment by huan415** [comment]
我也是一直mc失败
1.每次jad之后直接mc失败，没有修改反编译后的文件。
2.直接上传java再mc是成功的，所以估计是jad反编译的语法问题

**Comment by Curtaingit** [comment]
@songshengping  我也遇到了一样的问题    我的解决方式是通过 核对修改编译后的java文件格式来解决的 你可以尝试一下
 1.打开jad 反编译后的java文件
 2.检查文件头部及尾部内容    是否符合格式    不符合删除多余内容    保存
3.重新执行 mc

**Comment by JansonJo** [comment]
> 解决办法： 1.上传本地Java文件进行修改后编译即可（也就是绕过反编译阶段）

我是上传文件修改后mc编译失败，报错：
2021-12-09 19:30:11 [arthas-command-execute] WARN  c.t.a.c.c.k.MemoryCompilerCommand -Memory compiler error
com.taobao.arthas.compiler.DynamicCompilerException: Compilation Error
line: 94 , message: cannot find symbol
  symbol:   variable log
