### ISSUE TITLE
java -jar arthas-boot.jar 报错：Agent JAR loaded but agent failed to initialize

### ISSUE THREAD

**Issue by rockythd** [alibaba/arthas#1159]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.2.0
* Arthas 版本: 3.2.0
* 操作系统版本: Cent OS 6.7
* 目标进程的JVM版本: 1.6
* 执行`arthas-boot`的版本: 3.2.0

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
[root@IDC-PRO-OAapp]# /weaver/jdk/bin/java -jar arthas-boot.jar
[INFO] arthas-boot version: 3.2.0
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 19178 com.caucho.server.resin.Resin
  [2]: 27638 com.caucho.boot.WatchdogManager
  [3]: 19137 com.caucho.boot.WatchdogManager
  [4]: 27697 com.caucho.server.resin.Resin
  [5]: 11542 org.apache.catalina.startup.Bootstrap
1
[INFO] arthas home: /root/arthas
[INFO] Try to attach process 19178
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:103)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:104)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:123)
[ERROR] attach fail, targetPid: 19178
```
### 其他说明

   诊断进程 19137 是OK的， 19137是19178的父进程
```
[root@IDC-PRO-OAapp]# ps -ef | grep  19178
root      4502  3403  0 13:27 pts/2    00:00:00 grep 19178
root     19178 19137  8 May07 ?        03:46:55 /weaver/jdk/bin/java -Djava.util.logging.manager=com.caucho.log.LogManagerImpl -Djava.system.class.loader=com.caucho.loader.SystemClassLoader -Djavax.management.builder.initial=com.caucho.jmx.MBeanServerBuilderImpl -Djava.awt.headless=true -Dresin.home=/weaver/resin/ -Xmx4096m -Xms4096m -Xss256k -XX:PermSize=512m -XX:MaxPermSize=512m -XX:ParallelGCThreads=20 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+DisableExplicitGC -javaagent:wagent.jar -Djava.awt.headless=true -Djava.util.logging.manager=com.caucho.log.LogManagerImpl -Djavax.management.builder.initial=com.caucho.jmx.MBeanServerBuilderImpl -Djava.awt.headless=true -Dresin.home=/weaver/resin/ -Dresin.root=/weaver/resin/ -Dcom.sun.management.jmxremote -Djava.awt.headless=true -Djava.util.logging.manager=com.caucho.log.LogManagerImpl -Djavax.management.builder.initial=com.caucho.jmx.MBeanServerBuilderImpl -Djava.awt.headless=true -Dresin.home=/weaver/resin/ -Dresin.root=/weaver/resin/ -Dcom.sun.management.jmxremote -Djava.awt.headless=true com.caucho.server.resin.Resin --root-directory /weaver/resin/ -conf /weaver/resin/conf/resin.conf -socketwait 45390 start
```

**Comment by hengyunabc** [comment]
Resin 目前有问题，在issue里搜下。
