### ISSUE TITLE
java.net.ConnectException: 拒绝连接

### ISSUE THREAD

**Issue by nanquxiaozu** [alibaba/arthas#1172]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.2.0
* Arthas 版本: 3.2.0
* 操作系统版本: x86_64 GNU/Linux
* 目标进程的JVM版本: 1.7.0_55
* 执行`arthas-boot`的版本:  3.2.0

### 重现问题的步骤

1. 运行java进程
2. java -jar arthas-demo.jar
3. 通过arthas-boot.jar分别连接arthas-demo与java进程

### 期望的结果

What do you expected from the above steps？
arthas-demo与java进程都能连接，同时可以查看进程信息

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
1.arthas-demo对应的进行可连接，并打印LOGO；
2.其他java程序进程无法连接，提示连接被拒绝；
```
把异常信息贴到这里
[INFO] arthas-boot version: 3.2.0
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 29241 mmiconsole.MMIConsole
  [2]: 30467 newModel.lanuch.ModelManagerLauncher
  [3]: 12667 arthas-demo.jar
2
[INFO] arthas home: /home/d5000/peidiao/arthas
[INFO] Try to attach process 30467
[INFO] Attach process 30467 success.
[INFO] arthas-client connect 127.0.0.1 3658
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: 拒绝连接
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
	at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:547)
Usage: arthas-client [--help] [-c <value>] [-f <value>] [-w <value>] [-h
       <value>] [target-ip] [port]

Arthas Telnet Client

**Comment by hengyunabc** [comment]
检查 `~/logs/arthas/arthas.log`

**Comment by nanquxiaozu** [comment]
Arthas server agent start...
2020-05-14 14:39:38 [arthas-binding-thread] INFO  c.t.arthas.core.util.ArthasBanner -arthas version: 3.2.0
2020-05-14 14:39:39 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x2576c34f] REGISTERED
2020-05-14 14:39:39 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x2576c34f] BIND: /127.0.0.1:3658
2020-05-14 14:39:39 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x2576c34f, L:/127.0.0.1:3658] ACTIVE
2020-05-14 14:39:41 [arthas-binding-thread] ERROR c.t.a.c.s.term.impl.HttpTermServer -Error listening to port 8563
java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:96)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:91)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:44)
	at com.taobao.arthas.core.shell.term.impl.http.NettyWebsocketTtyBootstrap.start(NettyWebsocketTtyBootstrap.java:58)
	at com.taobao.arthas.core.shell.term.impl.http.NettyWebsocketTtyBootstrap.start(NettyWebsocketTtyBootstrap.java:80)
	at com.taobao.arthas.core.shell.term.impl.HttpTermServer.listen(HttpTermServer.java:46)
	at com.taobao.arthas.core.shell.impl.ShellServerImpl.listen(ShellServerImpl.java:128)
	at com.taobao.arthas.core.server.ArthasBootstrap.bind(ArthasBootstrap.java:290)
	at com.taobao.arthas.core.server.ArthasBootstrap.<init>(ArthasBootstrap.java:95)
	at com.taobao.arthas.core.server.ArthasBootstrap.getInstance(ArthasBootstrap.java:352)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.taobao.arthas.agent3.AgentBootstrap.bind(AgentBootstrap.java:194)
	at com.taobao.arthas.agent3.AgentBootstrap.access$000(AgentBootstrap.java:21)
	at com.taobao.arthas.agent3.AgentBootstrap$1.run(AgentBootstrap.java:164)
Caused by: io.netty.channel.ChannelException: failed to open a new selector
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:175)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:142)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:146)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:37)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	... 21 common frames omitted
Caused by: java.io.IOException: 打开的文件过多
	at sun.nio.ch.EPollArrayWrapper.epollCreate(Native Method)
	at sun.nio.ch.EPollArrayWrapper.<init>(EPollArrayWrapper.java:130)
	at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:68)
	at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:173)
	... 25 common frames omitted
2020-05-14 14:39:41 [arthas-binding-thread] ERROR c.t.a.c.shell.handlers.BindHandler -Error listening term server:
java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:96)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:91)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:44)
	at com.taobao.arthas.core.shell.term.impl.http.NettyWebsocketTtyBootstrap.start(NettyWebsocketTtyBootstrap.java:58)
	at com.taobao.arthas.core.shell.term.impl.http.NettyWebsocketTtyBootstrap.start(NettyWebsocketTtyBootstrap.java:80)
	at com.taobao.arthas.core.shell.term.impl.HttpTermServer.listen(HttpTermServer.java:46)
	at com.taobao.arthas.core.shell.impl.ShellServerImpl.listen(ShellServerImpl.java:128)
	at com.taobao.arthas.core.server.ArthasBootstrap.bind(ArthasBootstrap.java:290)
	at com.taobao.arthas.core.server.ArthasBootstrap.<init>(ArthasBootstrap.java:95)
	at com.taobao.arthas.core.server.ArthasBootstrap.getInstance(ArthasBootstrap.java:352)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.taobao.arthas.agent3.AgentBootstrap.bind(AgentBootstrap.java:194)
	at com.taobao.arthas.agent3.AgentBootstrap.access$000(AgentBootstrap.java:21)
	at com.taobao.arthas.agent3.AgentBootstrap$1.run(AgentBootstrap.java:164)
Caused by: io.netty.channel.ChannelException: failed to open a new selector
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:175)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:142)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:146)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:37)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	... 21 common frames omitted
Caused by: java.io.IOException: 打开的文件过多
	at sun.nio.ch.EPollArrayWrapper.epollCreate(Native Method)
	at sun.nio.ch.EPollArrayWrapper.<init>(EPollArrayWrapper.java:130)
	at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:68)
	at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:173)
	... 25 common frames omitted
2020-05-14 14:39:41 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x2576c34f, L:/127.0.0.1:3658] INACTIVE
2020-05-14 14:39:41 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x2576c34f, L:/127.0.0.1:3658] UNREGISTERED
2020-05-14 14:39:41 [arthas-binding-thread] WARN  i.n.util.concurrent.DefaultPromise -An exception was thrown by com.taobao.arthas.core.shell.term.impl.http.NettyWebsocketTtyBootstrap$2.operationComplete()
java.lang.NullPointerException: null
	at com.taobao.arthas.core.shell.term.impl.http.NettyWebsocketTtyBootstrap$2.operationComplete(NettyWebsocketTtyBootstrap.java:95)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:183)
	at io.netty.channel.group.DefaultChannelGroupFuture.addListener(DefaultChannelGroupFuture.java:147)
	at io.netty.channel.group.DefaultChannelGroupFuture.addListener(DefaultChannelGroupFuture.java:41)
	at com.taobao.arthas.core.shell.term.impl.http.NettyWebsocketTtyBootstrap.stop(NettyWebsocketTtyBootstrap.java:89)
	at com.taobao.arthas.core.shell.term.impl.http.NettyWebsocketTtyBootstrap.stop(NettyWebsocketTtyBootstrap.java:103)
	at com.taobao.arthas.core.shell.term.impl.HttpTermServer.close(HttpTermServer.java:73)
	at com.taobao.arthas.core.shell.term.impl.HttpTermServer.close(HttpTermServer.java:67)
	at com.taobao.arthas.core.shell.handlers.server.TermServerListenHandler.handle(TermServerListenHandler.java:40)
	at com.taobao.arthas.core.shell.handlers.server.TermServerListenHandler.handle(TermServerListenHandler.java:15)
	at com.taobao.arthas.core.shell.term.impl.HttpTermServer.listen(HttpTermServer.java:55)
	at com.taobao.arthas.core.shell.impl.ShellServerImpl.listen(ShellServerImpl.java:128)
	at com.taobao.arthas.core.server.ArthasBootstrap.bind(ArthasBootstrap.java:290)
	at com.taobao.arthas.core.server.ArthasBootstrap.<init>(ArthasBootstrap.java:95)
	at com.taobao.arthas.core.server.ArthasBootstrap.getInstance(ArthasBootstrap.java:352)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.taobao.arthas.agent3.AgentBootstrap.bind(AgentBootstrap.java:194)
	at com.taobao.arthas.agent3.AgentBootstrap.access$000(AgentBootstrap.java:21)
	at com.taobao.arthas.agent3.AgentBootstrap$1.run(AgentBootstrap.java:164)
2020-05-14 14:39:41 [arthas-binding-thread] INFO  c.t.a.core.server.ArthasBootstrap -as-server listening on network=127.0.0.1;telnet=3658;http=8563;timeout=6000;
2020-05-14 14:39:41 [arthas-binding-thread] INFO  c.t.a.core.server.ArthasBootstrap -as-server started in 2541 ms
Arthas start to bind...
Arthas server port binding failed! Please check $HOME/logs/arthas/arthas.log for more details.
java.lang.NoSuchMethodException: com.taobao.arthas.core.server.ArthasBootstrap.bind(java.lang.String)
	at java.lang.Class.getMethod(Class.java:1665)
	at com.taobao.arthas.agent3.AgentBootstrap.bind(AgentBootstrap.java:199)
	at com.taobao.arthas.agent3.AgentBootstrap.access$000(AgentBootstrap.java:21)
	at com.taobao.arthas.agent3.AgentBootstrap$1.run(AgentBootstrap.java:164)

**Comment by hengyunabc** [comment]
```
java.lang.NoSuchMethodException: com.taobao.arthas.core.server.ArthasBootstrap.bind(java.lang.String)
```

说明可能以前有旧的arthas attatch过，然后新版本的 arthas 找不到对旧版本的 method。

试下删掉下载的arthas文件，重启应用进程，再次attach。
