### ISSUE TITLE
arthas执行thread命令时，可能导致应用抛出 java.lang.InterruptedException: sleep interrupted

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#1175]
当执行 `thread -n 5`时，应用抛出异常

```
Caused by: java.lang.InterruptedException: sleep interrupted
        at java.lang.Thread.sleep0(Native Method)
        at java.lang.Thread.sleep(Thread.java:398)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.processBatchCallback(HConnectionManager.java:2040)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.processBatch(HConnectionManager.java:1874)
        at org.apache.hadoop.hbase.client.HTable.executeConnectionBatch(HTable.java:2026)
        at org.apache.hadoop.hbase.client.HTable.get(HTable.java:1130)
        ... 33 common frames omitted
```

发现执行 dashboard 命令不会出异常。执行 thread -n 5 必现。

dashboard里执行的是： java.lang.management.ThreadMXBean.getThreadCpuTime(long)

thread 命令里执行了： java.lang.management.ThreadMXBean.getThreadInfo(long[], boolean, boolean)

java.lang.management.ThreadMXBean.getThreadCpuTime(long)

java.lang.management.ThreadMXBean.dumpAllThreads(boolean, boolean)

---

执行下面三个都会触发：

```
ognl '@java.lang.management.ManagementFactory@getThreadMXBean().dumpAllThreads(true, true)'

ognl '@java.lang.management.ManagementFactory@getThreadMXBean().dumpAllThreads(false, true)'

ognl '@java.lang.management.ManagementFactory@getThreadMXBean().dumpAllThreads(true, false)'
```

传入 false时，不会触发：

```
ognl '@java.lang.management.ManagementFactory@getThreadMXBean().dumpAllThreads(false, false)'
```

---

**Comment by hengyunabc** [comment]
参考： https://gist.github.com/rednaxelafx/2223542
