### ISSUE TITLE
arthas-tunnel-server web控制台过段时间不连接arthas-boot，再次连接就会出现无法连接

### ISSUE THREAD

**Issue by maofan0314** [alibaba/arthas#1178]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* 阿里云k8s容器服务部署`arthas-boot.jar` ，`arthas-tunnel-server.jar`也部署在k8s中
* Arthas 版本: 3.2.0
* 操作系统版本: centos7.6
* 目标进程的JVM版本: jdk8u212
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. 单独使用k8s部署arthas-tunnel-server容器服务，作为web管理，连接agent
2. k8s集中部署的其他java服务部署arthas-boo.jar
3. arthas-tunnel-server控制台，连接任意一个java服务，刚开始正常，大约30分钟左右不连接agent之后，再通过web控制台就无法连接agent

### 期望的结果

我在公司内网环境部署的arthas-tunnel-server与arthas-boot，已经运行好几天了，web控制台随时连接agent都没有问题，为啥阿里云的会有这种问题，部署方法也没有什么区别

### 实际运行的结果
查看arthas中有一些错误日志
```
2020-05-16 12:26:57.561  INFO 1 --- [ntLoopGroup-2-1] io.netty.handler.logging.LoggingHandler  : [id: 0xbb61072e, L:/0.0.0.0:7777] READ COMPLETE
2020-05-16 12:26:57.561  WARN 1 --- [ntLoopGroup-3-1] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_211]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_211]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_211]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_211]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_211]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133) ~[netty-buffer-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.45.Final.jar!/:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_211]
```
```
2020-05-15 23:36:53.630  INFO 32339 --- [ntLoopGroup-2-1] io.netty.handler.logging.LoggingHandler  : [id: 0x27cae744, L:/0.0.0.0:7777] READ: [id: 0xd047e858, L:/172.19.69.133:7777 - R:/172.19.69.132:60075]
2020-05-15 23:36:53.631  INFO 32339 --- [ntLoopGroup-2-1] io.netty.handler.logging.LoggingHandler  : [id: 0x27cae744, L:/0.0.0.0:7777] READ COMPLETE
2020-05-15 23:36:53.708  INFO 32339 --- [tLoopGroup-3-14] c.a.a.t.server.TunnelSocketFrameHandler  : websocket handshake complete, uri: /ws?method=connectArthas&id=sup-order-testk8s
2020-05-15 23:36:53.709  INFO 32339 --- [tLoopGroup-3-14] c.a.a.t.server.TunnelSocketFrameHandler  : try to connect to arthas agent, id: sup-order-testk8s
2020-05-15 23:36:53.709  INFO 32339 --- [tLoopGroup-3-14] c.a.a.t.server.TunnelSocketFrameHandler  : random clientConnectionId: 095JEKHOA2WLUMRJYMHZ
2020-05-15 23:36:53.709  INFO 32339 --- [tLoopGroup-3-14] c.a.a.t.server.TunnelSocketFrameHandler  : startTunnel response: response:/?method=startTunnel&id=sup-order-testk8s&clientConnectionId=095JEKHOA2WLUMRJYMHZ
2020-05-15 23:36:53.709  INFO 32339 --- [tLoopGroup-3-14] c.a.a.t.server.TunnelSocketFrameHandler  : browser connect waitting for arthas agent open tunnel
2020-05-15 23:37:13.709 ERROR 32339 --- [tLoopGroup-3-14] c.a.a.t.server.TunnelSocketFrameHandler  : browser connect wait for arthas agent open tunnel timeout, agentId: [sup-order-testk8s], clientConnectionId: 095JEKHOA2WLUMRJYMHZ
2020-05-15 23:52:21.974  WARN 32339 --- [tLoopGroup-3-10] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

java.io.IOException: Connection timed out
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_212]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_212]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_212]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_212]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_212]
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133) ~[netty-buffer-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.45.Final.jar!/:4.1.45.Final]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
```

**Comment by hengyunabc** [comment]
大概可能的原因是， arthas本身有一个默认的 session的timeout 时间，就是30分钟。

`./as.sh -h` 可以看到。 可能是运行在应用里的 arthas server把超过30分钟没活动的 session关掉了。所以再也连不上了。

**Comment by dupengcheng** [comment]
我这里的情况是启动5分钟左右，刷新web控制台，连接就断开了，也无法重连。尝试kill tunnel server 触发重连，发现agent并没有发起重连。

目前 tunnel server 已被 kill。pid 35是 agent client进程，如何检测并关闭这些处于 close wait的链接。
![image](https://user-images.githubusercontent.com/11847818/86094726-7dd9f500-bae3-11ea-920d-9b7be0c46c44.png)

**Comment by dupengcheng** [comment]
cat  ~/logs/arthas/arthas.log 
发现异常如下
```
exceptionCaught
io.netty.util.concurrent.BlockingOperationException: DefaultChannelPromise@3df7d36e(incomplete)
	at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:461)
	at io.netty.channel.DefaultChannelPromise.checkDeadLock(DefaultChannelPromise.java:159)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:246)
	at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:131)
	at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:30)
	at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:403)
	at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:119)
	at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:30)
	at com.alibaba.arthas.tunnel.client.ForwardClient.start(ForwardClient.java:98)
	at com.alibaba.arthas.tunnel.client.TunnelClientSocketClientHandler.channelRead0(TunnelClientSocketClientHandler.java:77)
	at com.alibaba.arthas.tunnel.client.TunnelClientSocketClientHandler.channelRead0(TunnelClientSocketClientHandler.java:23)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.Utf8FrameValidator.channelRead(Utf8FrameValidator.java:82)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by hengyunabc** [comment]
@dupengcheng arthas 是什么版本的？ 可以稳定重现不？

**Comment by dupengcheng** [comment]
昨天讨论后，分离EventLoopGroup后，checkDeadLock 问题暂时没有再发现，kill tunnel server也可以自动重连了。


另一个问题 TtyWebSocketFrameHandler context.writeAndFlush 可能需要判断一下 context.channel().isActive()
```
java.nio.channels.ClosedChannelException: null
	at io.netty.handler.stream.ChunkedWriteHandler.discard(ChunkedWriteHandler.java:192)
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:202)
	at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:133)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:748)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:740)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:726)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:748)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:763)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:788)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:756)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:806)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
	at io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker.handshake(WebSocketServerHandshaker.java:221)
	at io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker.handshake(WebSocketServerHandshaker.java:169)
	at io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandshakeHandler.channelRead(WebSocketServerProtocolHandshakeHandler.java:92)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:59)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:368)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by hengyunabc** [comment]
@dupengcheng 参考： https://github.com/alibaba/arthas/issues/1284

另外，关于 `TtyWebSocketFrameHandler context.writeAndFlush`，欢迎提交PR来修复。

**Comment by hengyunabc** [comment]
已修复

**Comment by aliyunk8s** [comment]
我遇到了楼主同样的问题，请问下怎么解决的呀
