### ISSUE TITLE
基于bytekit的arthas版本测试

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#1184]
bytekit的PR：https://github.com/alibaba/arthas/pull/1182 （已合并到master)

bytekit本来计划在4.0里实现的，但是因为4.0的内容太多，所以把功能拆解为小功能到 3.* 版本里。

新版本主要改动了 字节码增强部分，所以主要测试 watch/trace/tt/monitor/stack 等命令的兼容性。

对比旧版本的一些亮点：

* 新版本解决了重复增强的问题，旧版本多次执行 trace命令的话，很快就会有 method too large的异常
* 增强后多个窗口之间不干扰，可以一个窗口执行trace，另一个窗口执行watch
* 旧版本执行 jad会导致原来 执行的watch等中断，新版本不会，并且会输出实际增强结果
* 新版本大幅降低了增强后的 代码执行的开销，去掉了很多反射相关的操作

支持动态trace/wath: https://github.com/alibaba/arthas/issues/1207

测试方式：

* 下载zip，或者在master分支打包

updated: 2020-05-25

[arthas-3.2.1-SNAPSHOT-bin.zip](https://github.com/alibaba/arthas/files/4674188/arthas-3.2.1-SNAPSHOT-bin.zip)

* 解压zip，执行 as.sh 或者 java -jar arthas-boot.jar

期待您的反馈 :)

**Comment by hengyunabc** [comment]
bytekit的文档： https://github.com/alibaba/arthas/blob/master/bytekit/README.md

**Comment by hengyunabc** [comment]
@RainElohim 我不能重现你说的`Timer already cancelled` ，我是这样子执行的：

```
java -jar arthas-demo.jar
```

然后执行 `./as.sh` attach。

再执行：

```
trace demo.MathGame print
```

---

你执行 arthas-demo可以重现不？

```
tt -t demo.MathGame print
```

**Comment by RainElohim** [comment]
> @RainElohim 我不能重现你说的`Timer already cancelled` ，我是这样子执行的：
> 
> ```
> java -jar arthas-demo.jar
> ```
> 
> 然后执行 `./as.sh` attach。
> 
> 再执行：
> 
> ```
> trace demo.MathGame print
> ```
> 
> 你执行 arthas-demo可以重现不？
> 
> ```
> tt -t demo.MathGame print
> ```

这样是不行的，需要用skywalking的agent 而且trace的需要是controller

**Comment by hengyunabc** [comment]
> > @RainElohim 我不能重现你说的`Timer already cancelled` ，我是这样子执行的：
> > ```
> > java -jar arthas-demo.jar
> > ```
> > 
> > 
> > 然后执行 `./as.sh` attach。
> > 再执行：
> > ```
> > trace demo.MathGame print
> > ```
> > 
> > 
> > 你执行 arthas-demo可以重现不？
> > ```
> > tt -t demo.MathGame print
> > ```
> 
> 这样是不行的，需要用skywalking的agent 而且trace的需要是controller

我下载最新的 apache-skywalking-apm-7.0.0.tar.gz ，测试没有问题。 jdk 1.8。

**Comment by RainElohim** [comment]
> > > @RainElohim 我不能重现你说的`Timer already cancelled` ，我是这样子执行的：
> > > ```
> > > java -jar arthas-demo.jar
> > > ```
> > > 
> > > 
> > > 然后执行 `./as.sh` attach。
> > > 再执行：
> > > ```
> > > trace demo.MathGame print
> > > ```
> > > 
> > > 
> > > 你执行 arthas-demo可以重现不？
> > > ```
> > > tt -t demo.MathGame print
> > > ```
> > 
> > 
> > 这样是不行的，需要用skywalking的agent 而且trace的需要是controller
> 
> 我下载最新的 apache-skywalking-apm-7.0.0.tar.gz ，测试没有问题。 jdk 1.8。
我觉得可能是你的姿势不对？
springboot 2.2.1
空项目，只有一个controller：
`@RestController
public class ArthasDemoController {

    @GetMapping("/hello")
    public String hello() {
        return "hello";
    }
}`

启动这个jar的命令：
`java -javaagent:/data/app/arthas/apache-skywalking-apm-bin/agent/skywalking-agent.jar -Dskywalking.agent.service_name=arthas-demo-2 -Dskywalking.collector.backend_service=10.16.0.22:11800 -jar demo-0.0.1-SNAPSHOT.jar`

arthas里的命令：
`[arthas@294892]$ trace com.example.demo.ArthasDemoController hello -n 5 '1==1'
Error during processing the command, exception type: java.lang.ClassFormatError, message:null, please check $HOME/logs/arthas/arthas.log for more details.
[arthas@294892]$
[arthas@294892]$ stop
Timer already cancelled.
[arthas@294892]$
[arthas@294892]$ dashboard
Timer already cancelled.
[arthas@294892]$`


然后这次我在被arthas attach的的项目日志里发现了这段报错：
`
Exception in thread "arthas-timer" java.lang.NullPointerException
	at com.taobao.arthas.core.advisor.AdviceListenerManager$1.run(AdviceListenerManager.java:71)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)`

辛苦您看下有没有帮助

**Comment by tz826** [comment]
> > @RainElohim 我不能重现你说的`Timer already cancelled` ，我是这样子执行的：
> > ```
> > java -jar arthas-demo.jar
> > ```
> > 
> > 
> > 然后执行 `./as.sh` attach。
> > 再执行：
> > ```
> > trace demo.MathGame print
> > ```
> > 
> > 
> > 你执行 arthas-demo可以重现不？
> > ```
> > tt -t demo.MathGame print
> > ```
> 
> 这样是不行的，需要用skywalking的agent 而且trace的需要是controller

我的和RainElohim 是一样的.很多命令都Timer already cancelled.
Attach success.
telnet connecting to arthas server... current timestamp is 1590157889
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
  ,---.  ,------. ,--------.,--.  ,--.  ,---.   ,---.                           
 /  O  \ |  .--. ''--.  .--'|  '--'  | /  O  \ '   .-'                          
|  .-.  ||  '--'.'   |  |   |  .--.  ||  .-.  |`.  `-.                          
|  | |  ||  |\  \    |  |   |  |  |  ||  | |  |.-'    |                         
`--' `--'`--' '--'   `--'   `--'  `--'`--' `--'`-----'                          
                                                                                

wiki      https://alibaba.github.io/arthas                                      
tutorials https://alibaba.github.io/arthas/arthas-tutorials                     
version   3.2.1-SNAPSHOT                                                        
pid       17                                                                    
time      2020-05-22 22:24:30                                                   

[arthas@17]$ dashboard
Timer already cancelled.
[arthas@17]$ dashboard
Timer already cancelled.
[arthas@17]$ 
[arthas@17]$ dashboard
Timer already cancelled.
[arthas@17]$ dashboard
Timer already cancelled.
[arthas@17]$ 
[arthas@17]$ 
[arthas@17]$ dashboard
Timer already cancelled.
[arthas@17]$ 
[arthas@17]$ 
[arthas@17]$ 
[arthas@17]$ dashboard
Timer already cancelled.
[arthas@17]$ stop
Timer already cancelled.
[arthas@17]$ thread 
Timer already cancelled.

**Comment by tz826** [comment]
刚又测试了下,刚开始进入基本的dashboard, thread 命令都是正常的,但是执行trace  com.worktrans.hr.core.biz.facade.impl.HrSearchFacadeImpl findByFormCodeList报错后, 命令全都是Timer already cancelled.


[arthas@17]$ sm  com.worktrans.hr.core.biz.facade.impl.HrSearchFacadeImpl findByFormCodeList
com.worktrans.hr.core.biz.facade.impl.HrSearchFacadeImpl findByFormCodeList(Ljava/lang/Long;Ljava/util/List;)Ljava/util/List;
Affect(row-cnt:1) cost in 63 ms.
[arthas@17]$ 
[arthas@17]$ 
[arthas@17]$ 
[arthas@17]$ 
[arthas@17]$ 
[arthas@17]$ 
[arthas@17]$ 
[arthas@17]$ 
[arthas@17]$ trace  com.worktrans.hr.core.biz.facade.impl.HrSearchFacadeImpl findByFormCodeList
Error during processing the command, exception type: java.lang.ClassFormatError, message:null, please check $HOME/logs/arthas/arthas.log for more details. 
[arthas@17]$ trace  com.worktrans.hr.core.biz.facade.impl.HrSearchFacadeImpl findByFormCodeList
Timer already cancelled.
[arthas@17]$ 
[arthas@17]$ 
[arthas@17]$ trace  com.worktrans.hr.core.biz.facade.impl.HrSearchFacadeImpl findByFormCodeList
Timer already cancelled.
[arthas@17]$ trace  com.worktrans.hr.core.biz.facade.impl.HrSearchFacadeImpl findByFormCodeList
Timer already cancelled.
[arthas@17]$ trace  com.worktrans.hr.core.biz.facade.impl.HrSearchFacadeImpl findByFormCodeList
Timer already cancelled.
[arthas@17]$ trace  com.worktrans.hr.core.biz.facade.impl.HrSearchFacadeImpl findByFormCodeList
Timer already cancelled.
[arthas@17]$ trace  com.worktrans.hr.core.biz.facade.impl.HrSearchFacadeImpl findByFormCodeList
Timer already cancelled.
[arthas@17]$ 
[arthas@17]$ 
[arthas@17]$ dashboard 
Timer already cancelled.
[arthas@17]$ thread -n 1
Timer already cancelled.


相关日志
Arthas server already bind.
2020-05-22 22:42:39 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x68433dfa, L:/127.0.0.1:3658] READ: [id: 0x0ce4c14f, L:/127.0.0.1:3658 - R:/127.0.0.1:49814]
2020-05-22 22:42:39 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0x68433dfa, L:/127.0.0.1:3658] READ COMPLETE
2020-05-22 22:42:40 [nioEventLoopGroup-2-2] INFO  c.t.a.core.shell.term.impl.Helper -Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
2020-05-22 22:43:01 [as-command-execute-daemon] WARN  c.t.arthas.core.advisor.Enhancer -transform loader[sun.misc.Launcher$AppClassLoader@18b4aac2]:class[com/worktrans/hr/core/biz/facade/impl/HrSearchFacadeImpl] failed.
java.lang.TypeNotPresentException: Type com/worktrans/hr/core/domain/request/organizationNew/WorkUnitApprovalRequest not present
        at com.alibaba.arthas.deps.org.objectweb.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:1026)
        at com.alibaba.arthas.deps.org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202)
        at com.alibaba.arthas.deps.org.objectweb.asm.Frame.merge(Frame.java:1299)
        at com.alibaba.arthas.deps.org.objectweb.asm.Frame.merge(Frame.java:1197)
        at com.alibaba.arthas.deps.org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
        at com.alibaba.arthas.deps.org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
        at com.alibaba.arthas.deps.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769)
        at com.alibaba.arthas.deps.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
        at com.alibaba.arthas.deps.org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:465)
        at com.taobao.arthas.bytekit.utils.AsmUtils.toBytes(AsmUtils.java:59)
        at com.taobao.arthas.core.advisor.Enhancer.transform(Enhancer.java:301)
        at com.taobao.arthas.core.advisor.TransformerManager$1.transform(TransformerManager.java:41)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:439)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:117)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:72)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:372)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.worktrans.hr.core.domain.request.organizationNew.WorkUnitApprovalRequest
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at com.taobao.arthas.agent.ArthasClassloader.loadClass(ArthasClassloader.java:34)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.alibaba.arthas.deps.org.objectweb.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:1024)
        ... 26 common frames omitted
2020-05-22 22:43:01 [as-command-execute-daemon] ERROR c.t.a.c.s.system.impl.ProcessImpl -Error during processing the command:
java.lang.ClassFormatError: null
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:439)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:117)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:72)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:372)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by hengyunabc** [comment]
@RainElohim @tz826 已经更新最新的zip包了，修复了 timer cancelled 的问题。

skywalking的问题参考： https://github.com/alibaba/arthas/issues/1141#issuecomment-633105984
