### ISSUE TITLE
attach fail求帮忙看看

### ISSUE THREAD

**Issue by leeyc0704** [alibaba/arthas#1190]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0.5.2
* Arthas 版本: 3.0.5.2
* 操作系统版本: Linux version 3.10.0-327.el7.x86_64 (mockbuild@x86-034.build.eng.bos.redhat.com) 
* 目标进程的JVM版本:1.8.0_252
* 执行`arthas-boot`的版本: 3.0.5.2

### 重现问题的步骤

1. 通过ps -ef | grep "appname"找到pid
2. 执行java -jar arthas-boot.jar pid

### 期望的结果

进入arthas

### 实际运行的结果

报错

```
[INFO] arthas home: /root/.arthas/lib/3.2.0/arthas
[INFO] Try to attach process 50432
[ERROR] Start arthas failed, exception stack trace: 
java.lang.InternalError: instrument library is missing in target VM
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:105)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:104)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:123)
Caused by: com.sun.tools.attach.AgentLoadException: Failed to load agent library
	at sun.tools.attach.LinuxVirtualMachine.execute(LinuxVirtualMachine.java:224)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:58)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:79)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:103)
	... 3 more
[ERROR] attach fail, targetPid: 50432

```

**Comment by hengyunabc** [comment]
安装完整的  jdk，而不是 jre。

**Comment by leeyc0704** [comment]
> 安装完整的 jdk，而不是 jre。

$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
这不是完整的jdk嘛，而且很奇怪，之前是可以进的，就昨天突然不能进了，各种排查。

**Comment by hengyunabc** [comment]
可以参考下这个： https://github.com/alibaba/arthas/issues/174
