### ISSUE TITLE
AttachNotSupportedException：The VM does not support the attach mechanism

### ISSUE THREAD

**Issue by apa7** [alibaba/arthas#1196]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* Arthas 版本: 最新
* 操作系统版本: centos7
* 目标进程的JVM版本: jdk11
* 执行`arthas-boot`的版本: 最新

### 重现问题的步骤
1. wget https://alibaba.github.io/arthas/arthas-boot.jar
2. java -jar arthas-boot.jar
3. 1

### 实际运行的结果
启动，选择pid，报错

```
[ERROR] Start arthas failed, exception stack trace: 
com.sun.tools.attach.AttachNotSupportedException: The VM does not support the attach mechanism
	at jdk.attach/sun.tools.attach.HotSpotAttachProvider.testAttachable(HotSpotAttachProvider.java:153)
	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:56)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:83)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:123)
```

**Comment by apa7** [comment]
spring-boot:1.1.6

**Comment by apa7** [comment]
只能查看arthas-demo.jar的进程

**Comment by hengyunabc** [comment]
检查jvm是否有这个参数： `-XX:+DisableAttachMechanism`
