### ISSUE TITLE
3.3.0版本没有重写 getCommonSuperClass ，导致ClassNotFoundException

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#1218]
会有类似的异常栈信息：

```
Caused by: java.lang.ClassNotFoundException: com.zz.core.domain.request.organizationNew.WorkUnitApprovalRequest
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at com.taobao.arthas.agent.ArthasClassloader.loadClass(ArthasClassloader.java:34)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.alibaba.arthas.deps.org.objectweb.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:1024)
```

**Comment by hengyunabc** [comment]
修复版测试： [arthas-3.3.1-SNAPSHOT-bin.zip](https://github.com/alibaba/arthas/files/4700294/arthas-3.3.1-SNAPSHOT-bin.zip)
