### ISSUE TITLE
3.3.1 版本里对spring aop生成的类做 trace/watch时出错： java.lang.VerifyError: null

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#1223]
比如：

```
[arthas@29539]$ watch com.taobao.container.App * target
Error during processing the command, exception type: java.lang.VerifyError, message:null, please check $HOME/logs/arthas/arthas.log for more details.
```

使用sc命令来查看，可以发现，实际上有两个类：

```
[arthas@29539]$ sc com.taobao.container.App
com.taobao.container.App
com.taobao.container.App$$EnhancerBySpringCGLIB$$a05d41dd
```

单独对这个spring aop类做 watch，可以发现同样出错。

打开dump开关：

```
options dump true
```

可以把增强结果保存到本地。

使用 asm 来校验下：

```
java.lang.VerifyError: null
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:436)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:135)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:87)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:372)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

使用 `com.taobao.arthas.bytekit.utils.VerifyUtils.asmVerify(byte[], boolean)` 对生成的字节码结果校验，发现抛出异常：

```
Exception in thread "main" java.lang.IllegalArgumentException: ldc of a constant class requires at least version 1.5
	at com.alibaba.arthas.deps.org.objectweb.asm.util.CheckMethodAdapter.checkLdcConstant(CheckMethodAdapter.java:1165)
	at com.alibaba.arthas.deps.org.objectweb.asm.util.CheckMethodAdapter.visitLdcInsn(CheckMethodAdapter.java:797)
	at com.alibaba.arthas.deps.org.objectweb.asm.ClassReader.readCode(ClassReader.java:2392)
	at com.alibaba.arthas.deps.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1488)
	at com.alibaba.arthas.deps.org.objectweb.asm.ClassReader.accept(ClassReader.java:718)
	at com.alibaba.arthas.deps.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at com.alibaba.arthas.deps.org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1043)
	at com.alibaba.arthas.deps.org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1025)
	at com.taobao.arthas.bytekit.utils.VerifyUtils.asmVerify(VerifyUtils.java:26)
```

---

所以原因明确了，是因为 bytekit里使用了 ldc命令直接来获取 `Class` 对象，但因为 spring aop生成字节码的jvm版本设置为 46，也就是Java 1.2 。

据asm的提示，至少要到 Java 5 ， major version 49 才支持。

所以，要对加载的字节码的 major version  做判断，如果小于 49 ，则直接设置为 49 。

**Comment by hengyunabc** [comment]
修复测试版本： [arthas-3.3.2-SNAPSHOT-bin.zip](https://github.com/alibaba/arthas/files/4710517/arthas-3.3.2-SNAPSHOT-bin.zip)
