### ISSUE TITLE
连接失败——io.termd.core.io_error NullPointerException异常

### ISSUE THREAD

**Issue by xiongwenjia** [alibaba/arthas#1245]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.8 ~ 3.3.2
* Arthas 版本: 3.1.8 ~ 3.3.2
* 操作系统版本: Ubuntu-16.04
* 目标进程的JVM版本: openj9/8u222  |  openjdk 1.8.0_252
* 执行`arthas-boot`的版本: 3.1.8 ~ 3.3.2

### 重现问题的步骤

1. 使用arthas-boot 连接 java应用， attach success
2. 发现无论是原应用进程重连， 还是重启应用进程，都出现 Connection reset 的错误
3. java 应用切换成arthas-demo , 依然复现
4. 最开始使用3.2.0版本，有尝试其他多个版本 3.1.8 ~ 3.3.2 (切换有删除环境  ~/.arthas 等)，依然复现
5. 目标环境原有JDK 为 OpenJ9 ，切换到openjdk 1.8.0_252 ， 依然复现
6. 有尝试 --attach-only , 再使用webconsole 连接。 attach过程成功， webconsole 点击连接显示失败，arthas.log 出现同样错误
----------

### 其他信息
 - 曾经一段时间是可用的，应用经历了几次重新发布，连接不了了
 - 有尝试到镜像环境，问题复现
 - 报错和termd 关联较大

### 期望的结果

期望能正常运行

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
- 启动报错
```
[DEBUG] Start arthas-core.jar args: [-jar, /home/amy/arthas/arthas-core.jar, -pid, 70991, -target-ip, 127.0.0.1, -telnet-port, 3658, -http-port, 8563, -core, /home/amy/arthas/arthas-core.jar, -agent, /home/amy/arthas/arthas-agent.jar]
[DEBUG] Found java: /opt/openj9-jdk/8u222/jre/bin/java
[DEBUG] Found java: /opt/openj9-jdk/8u222/jre/../bin/java
[DEBUG] Found tools.jar: /opt/openj9-jdk/8u222/jre/../lib/tools.jar
[INFO] Attach process 70991 success.
[INFO] arthas-client connect 127.0.0.1 3658
[DEBUG] Start arthas-client.jar args: [127.0.0.1, 3658]
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at org.apache.commons.net.telnet.TelnetInputStream.__read(TelnetInputStream.java:132)
	at org.apache.commons.net.telnet.TelnetInputStream.run(TelnetInputStream.java:603)
	at java.lang.Thread.run(Thread.java:819)

```
- arthas.log
```
2020-06-05 03:15:51 [arthas-binding-thread] INFO  c.t.a.core.server.ArthasBootstrap -as-server listening on network=127.0.0.1;telnet=3658;http=8563;timeout=6000;                          
2020-06-05 03:15:51 [arthas-binding-thread] INFO  c.t.a.core.server.ArthasBootstrap -as-server started in 342 ms                                                                           
Arthas server already bind.                                                                                                                                                                
2020-06-05 03:15:51 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0xb6a5e4bd, L:/127.0.0.1:3658] READ: [id: 0x707cc2aa, L:/127.0.0.1:3658 - R:/127.0.0.1:37530]   
2020-06-05 03:15:51 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler -[id: 0xb6a5e4bd, L:/127.0.0.1:3658] READ COMPLETE                                                    
2020-06-05 03:15:51 [nioEventLoopGroup-2-2] INFO  c.t.a.core.shell.term.impl.Helper -Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc                     
2020-06-05 03:15:51 [nioEventLoopGroup-2-2] ERROR io.termd.core.io_error -Reported io error => closing                                                                                     
java.lang.NullPointerException: null                                                                                                                                                       
        at io.termd.core.readline.Readline.<init>(Readline.java:56)                                                                                                                        
        at com.taobao.arthas.core.shell.term.impl.TermImpl.<init>(TermImpl.java:50)                                                                                                        
        at com.taobao.arthas.core.shell.term.impl.httptelnet.HttpTelnetTermServer$1.accept(HttpTelnetTermServer.java:53)                                                                   
        at com.taobao.arthas.core.shell.term.impl.httptelnet.HttpTelnetTermServer$1.accept(HttpTelnetTermServer.java:50)                                                                   
        at io.termd.core.telnet.TelnetTtyConnection.checkAccept(TelnetTtyConnection.java:174)                                                                                              
        at io.termd.core.telnet.TelnetTtyConnection.onOpen(TelnetTtyConnection.java:165)                                                                                                   
        at io.termd.core.telnet.TelnetConnection.onInit(TelnetConnection.java:63)                                                                                                          
        at io.termd.core.telnet.netty.TelnetChannelHandler.channelActive(TelnetChannelHandler.java:56)                                                                                     
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:228)                                                                      
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:214)                                                                      
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:207)                                                                        
        at com.taobao.arthas.core.shell.term.impl.httptelnet.ProtocolDetectHandler.channelRead(ProtocolDetectHandler.java:80)                                                              
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)                                                                        
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)                                                                        
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)                                                                          
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)                                                                               
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)                                                                        
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)                                                                        
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)                                                                                        
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)                                                                                 
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)                                                                                                     
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)                                                                                           
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)                                                                                                    
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)                                                                                                                    
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)                                                                                    
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)                                                                                                       
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                                                                                           
        at java.lang.Thread.run(Thread.java:819)                                                                                                                                           
```

**Comment by hengyunabc** [comment]
termd里出异常的话，仔细检查下，前面应该还有一个异常信息：

```java
public class TermInfo {

  private static TermInfo loadDefault() {
    try {
      InputStream in = TermInfo.class.getResourceAsStream("terminfo.src");
      TermInfoParser parser = new TermInfoParser(new InputStreamReader(in, "US-ASCII"));
      TermInfoBuilder builder = new TermInfoBuilder();
      parser.parseDatabase(builder);
      return builder.build();
    } catch (Throwable t) {
      t.printStackTrace();
      return null;
    }
  }

  private static final TermInfo DEFAULT = loadDefault();

  /**
   * @return the default term info database loaded from the {@code terminfo.src} resource
   */
  public static TermInfo defaultInfo() {
    return DEFAULT;
  }
```

**Comment by xiongwenjia** [comment]
arthas日志只看到上述这些，确实很疑惑，是有其他日志输出的地方么。
环境内又跑了个测试项目，里面运行 new Readline(keymap) , 运行正常输出"End"，更疑惑了

``` java
    public static void main(String[] args) {
        try {
            Keymap keymap = new Keymap(new Test().loadInputRcFile());
            Readline readline = new Readline(keymap);
        }catch (Exception e){
            e.printStackTrace();
        }
        System.out.println("End");
    }

    public InputStream loadInputRcFile() {
        InputStream inputrc = this.getClass().getResourceAsStream("/inputrc"); //arthas项目里的 inputrc 文件
        return inputrc;
    }
```

**Comment by hengyunabc** [comment]
> arthas日志只看到上述这些，确实很疑惑，是有其他日志输出的地方么。
> 环境内又跑了个测试项目，里面运行 new Readline(keymap) , 运行正常输出"End"，更疑惑了
> 
> ```java
>     public static void main(String[] args) {
>         try {
>             Keymap keymap = new Keymap(new Test().loadInputRcFile());
>             Readline readline = new Readline(keymap);
>         }catch (Exception e){
>             e.printStackTrace();
>         }
>         System.out.println("End");
>     }
> 
>     public InputStream loadInputRcFile() {
>         InputStream inputrc = this.getClass().getResourceAsStream("/inputrc"); //arthas项目里的 inputrc 文件
>         return inputrc;
>     }
> ```

应该是直接打印到应用的 标准输出了里，检查下应用本身的日志。

**Comment by xiongwenjia** [comment]
在 arthas-demo  console输出里发现这一段。 
出现在Attach成功后，client尝试连接的时候, 而且只有第一次attach出现。
之后走到“The target process already listen port {}, skip attach.” 分支。 而且从lsof 看，这个端口就一直被应用进程监听且保持，怀疑这个连接估计一直就没好过
```
io.termd.core.term.TokenMgrError: Lexical error at line 2, column 50.  Encountered: "\n" (10), after : ""
	at io.termd.core.term.TermInfoParserTokenManager.getNextToken(TermInfoParserTokenManager.java:1461)
	at io.termd.core.term.TermInfoParser.jj_ntk_f(TermInfoParser.java:971)
	at io.termd.core.term.TermInfoParser.parseHeaderLine(TermInfoParser.java:184)
	at io.termd.core.term.TermInfoParser.parseDevice(TermInfoParser.java:146)
	at io.termd.core.term.TermInfoParser.parseDatabase(TermInfoParser.java:126)
	at io.termd.core.term.TermInfo.loadDefault(TermInfo.java:36)
	at io.termd.core.term.TermInfo.<clinit>(TermInfo.java:44)
	at io.termd.core.readline.Readline.<init>(Readline.java:56)
	at com.taobao.arthas.core.shell.term.impl.TermImpl.<init>(TermImpl.java:50)
	at com.taobao.arthas.core.shell.term.impl.httptelnet.HttpTelnetTermServer$1.accept(HttpTelnetTermServer.java:53)
	at com.taobao.arthas.core.shell.term.impl.httptelnet.HttpTelnetTermServer$1.accept(HttpTelnetTermServer.java:50)
	at io.termd.core.telnet.TelnetTtyConnection.checkAccept(TelnetTtyConnection.java:174)
	at io.termd.core.telnet.TelnetTtyConnection.onOpen(TelnetTtyConnection.java:165)
	at io.termd.core.telnet.TelnetConnection.onInit(TelnetConnection.java:63)
	at io.termd.core.telnet.netty.TelnetChannelHandler.channelActive(TelnetChannelHandler.java:56)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:228)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:214)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:207)
	at com.taobao.arthas.core.shell.term.impl.httptelnet.ProtocolDetectHandler.channelRead(ProtocolDetectHandler.java:80)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748) 
```

```
[DEBUG] Found tools.jar: /usr/lib/jvm/java-8-openjdk-amd64/jre/../lib/tools.jar
[INFO] Attach process 156703 success.
[INFO] arthas-client connect 127.0.0.1 3665
[DEBUG] Start arthas-client.jar args: [127.0.0.1, 3665]
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at org.apache.commons.net.telnet.TelnetInputStream.__read(TelnetInputStream.java:132)
        at org.apache.commons.net.telnet.TelnetInputStream.run(TelnetInputStream.java:603)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by hengyunabc** [comment]
这个可以在docker里重现不？ 能提供一个可重现的环境不？

**Comment by hengyunabc** [comment]
仔细看了下代码： https://github.com/alibaba/termd/blob/termd-core-1.1.7.9/src/main/java/io/termd/core/readline/Readline.java#L56 

发现其实这个 `device`，并没有被使用。可以考虑直接去掉。。

```java
public class Readline {
  private final Device device;
  public Readline(Keymap keymap) {
    this.device = TermInfo.defaultInfo().getDevice("xterm"); // For now use xterm
```

**Comment by xiongwenjia** [comment]
找到了直接原因，之前的Jar是从windows平台打包（源码没变），发现这些包运行起来会出现这个问题（linux, windows 运行都报错）。
结合这句错误信息，怀疑和系统换行符有关系。
```
io.termd.core.term.TokenMgrError: Lexical error at line 2, column 50.  Encountered: "\n" (10),
```

**Comment by yinyuhang** [comment]
有兼容Windows平台打包的计划么

**Comment by yinyuhang** [comment]
> 
> 
> 找到了直接原因，之前的Jar是从windows平台打包（源码没变），发现这些包运行起来会出现这个问题（linux, windows 运行都报错）。
> 结合这句错误信息，怀疑和系统换行符有关系。
> 
> ```
> io.termd.core.term.TokenMgrError: Lexical error at line 2, column 50.  Encountered: "\n" (10),
> ```

顺便问下有兼容Windows平台打包的计划么
