### ISSUE TITLE
Docker容器中运行出现错误 Can not find tools.jar under java home

### ISSUE THREAD

**Issue by derekzhan** [alibaba/arthas#1276]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.3.3
* Arthas 版本:  3.3.3
* 操作系统版本: (Red Hat 4.8.5-36) Linux version 3.10.0-957.5.1.el7.x86_64
* 目标进程的JVM版本: java version "1.8.0_202"
* 执行`arthas-boot`的版本: 3.3.3

### 重现问题的步骤

1. docker exec -it xxx /bin/bash -c "wget https://alibaba.github.io/arthas/arthas-boot.jar && java -jar arthas-boot.jar"

### 期望的结果

正常运行

### 实际运行的结果

```
bash-4.4# ps xf
PID   USER     TIME  COMMAND
    1 root      7:57 java -Djava.security.egd=file:/dev/./urandom -jar -Xms128m -Xmx512m -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:logs/spider-store/gc.log xxx-store.jar
  740 root      0:00 /bin/bash
  762 root      0:00 ps xf
bash-4.4# java -jar arthas-boot.jar 1
[INFO] arthas-boot version: 3.3.3
[INFO] Start download arthas from remote server: https://maven.aliyun.com/repository/public/com/taobao/arthas/arthas-packaging/3.3.3/arthas-packaging-3.3.3-bin.zip
[INFO] Download arthas success.
[INFO] arthas home: /root/.arthas/lib/3.3.3/arthas
[INFO] Try to attach process 1
Exception in thread "main" java.lang.IllegalArgumentException: Can not find tools.jar under java home: /opt/jdk1.8.0_202/jre, please try to start arthas-boot with full path java. Such as /opt/jdk/bin/java -jar arthas-boot.jar
	at com.taobao.arthas.boot.ProcessUtils.findJavaHome(ProcessUtils.java:222)
	at com.taobao.arthas.boot.ProcessUtils.startArthasCore(ProcessUtils.java:233)
	at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:515)
bash-4.4# java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

bash-4.4# /opt/jdk/bin/java -jar arthas-boot.jar 1
[INFO] arthas-boot version: 3.3.3
[INFO] arthas home: /root/.arthas/lib/3.3.3/arthas
[INFO] Try to attach process 1
Exception in thread "main" java.lang.IllegalArgumentException: Can not find tools.jar under java home: /opt/jdk1.8.0_202/jre, please try to start arthas-boot with full path java. Such as /opt/jdk/bin/java -jar arthas-boot.jar
	at com.taobao.arthas.boot.ProcessUtils.findJavaHome(ProcessUtils.java:222)
	at com.taobao.arthas.boot.ProcessUtils.startArthasCore(ProcessUtils.java:233)
	at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:515)
```

**Comment by jiangwh** [comment]
目测是docker中java环境。

**Comment by hengyunabc** [comment]
要装安完整的jdk，在issue里可以找到不少相关的讨论。
