### ISSUE TITLE
trace异常：JSR/RET are not supported with computeFrames option

### ISSUE THREAD

**Issue by adminzgb** [alibaba/arthas#1304]
### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.3.6
* Arthas 版本: 3.3.6
* 操作系统版本: Ubuntu 16.04.4 LTS
* 目标进程的JVM版本: 1.8.0_131
* 执行`arthas-boot`的版本:1.8.0_131

### 重现问题的步骤

1. 目标进程使用Spring boot作为服务端，启动一段时间后arthas attach成功
2. 在arthas控制内中执行trace com.mysql.jdbc.PreparedStatement executeInternal -n 2 '#cost > 10'
3. 报错
Enhance error! exception: java.lang.IllegalArgumentException: JSR/RET are not supported with computeFrames option

**Comment by hengyunabc** [comment]
什么版本的 mysql driver？可以给出一个demo不？

**Comment by adminzgb** [comment]
Driver版本：mysql-connector-java:5.1.34
异常堆栈：
`[as-command-execute-daemon] WARN  c.t.arthas.core.advisor.Enhancer -transform loader[org.springframework.boot.loader.LaunchedURLClassLoader@439f5b3d]:class[com/mysql/jdbc/PreparedStatement] failed.
java.lang.IllegalArgumentException: JSR/RET are not supported with computeFrames option
        at com.alibaba.arthas.deps.org.objectweb.asm.Frame.execute(Frame.java:1017)
        at com.alibaba.arthas.deps.org.objectweb.asm.MethodWriter.visitJumpInsn(MethodWriter.java:1145)
        at com.alibaba.arthas.deps.org.objectweb.asm.tree.JumpInsnNode.accept(JumpInsnNode.java:79)
        at com.alibaba.arthas.deps.org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
        at com.alibaba.arthas.deps.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:751)
        at com.alibaba.arthas.deps.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
        at com.alibaba.arthas.deps.org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:465)
        at com.taobao.arthas.bytekit.utils.AsmUtils.toBytes(AsmUtils.java:61)
        at com.taobao.arthas.core.advisor.Enhancer.transform(Enhancer.java:231)
        at com.taobao.arthas.core.advisor.TransformerManager$1.transform(TransformerManager.java:41)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:366)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:135)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:87)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by hengyunabc** [comment]
试下这个版本，清除掉了jsr指令，可能要重启应用：[arthas-bin.zip](https://github.com/alibaba/arthas/files/4911937/arthas-bin.zip)

**Comment by adminzgb** [comment]
本地调试，trace后依然报错。
`2020-07-13 19:53:39 [as-command-execute-daemon] WARN  c.t.arthas.core.advisor.Enhancer -transform loader[sun.misc.Launcher$AppClassLoader@18b4aac2]:class[com/mysql/jdbc/CallableStatement] failed.
java.lang.IllegalArgumentException: JSR/RET are not supported with computeFrames option
        at com.alibaba.arthas.deps.org.objectweb.asm.Frame.execute(Frame.java:1017)
        at com.alibaba.arthas.deps.org.objectweb.asm.MethodWriter.visitJumpInsn(MethodWriter.java:1145)
        at com.alibaba.arthas.deps.org.objectweb.asm.tree.JumpInsnNode.accept(JumpInsnNode.java:79)
        at com.alibaba.arthas.deps.org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
        at com.alibaba.arthas.deps.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:751)
        at com.alibaba.arthas.deps.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
        at com.alibaba.arthas.deps.org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:465)
        at com.taobao.arthas.bytekit.utils.AsmUtils.toBytes(AsmUtils.java:61)
        at com.taobao.arthas.core.advisor.Enhancer.transform(Enhancer.java:235)
        at com.taobao.arthas.core.advisor.TransformerManager$1.transform(TransformerManager.java:41)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:370)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:135)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:87)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
        at java.util.concurrent.FutureTask.run(FutureTask.java)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-07-13 19:53:39 [as-command-execute-daemon] WARN  c.t.arthas.core.advisor.Enhancer -transform loader[sun.misc.Launcher$AppClassLoader@18b4aac2]:class[com/mysql/jdbc/PreparedStatement] failed.
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
        at java.util.ArrayList$Itr.next(ArrayList.java:859)
        at com.taobao.arthas.core.advisor.Enhancer.transform(Enhancer.java:149)
        at com.taobao.arthas.core.advisor.TransformerManager$1.transform(TransformerManager.java:41)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:370)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:135)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:87)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
        at java.util.concurrent.FutureTask.run(FutureTask.java)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by hengyunabc** [comment]
再试下这个新的，上面的没有彻底去掉jsr指令： [arthas-bin.zip](https://github.com/alibaba/arthas/files/4912301/arthas-bin.zip)

**Comment by adminzgb** [comment]
试过没问题了。是ASM不支持JSR指令了吗

**Comment by hengyunabc** [comment]
> 试过没问题了。是ASM不支持JSR指令了吗

JSR是JVM里废弃了的指令，在一些旧版本的jar，或者是要支持jdk 5的jar里可能有这个指令。当做了类增强之后，asm要重启计算frame，就会抛出异常。所以要在类增强之前，先把JSR指令转换移除掉。
