### ISSUE TITLE
linux环境使用jre启动的Java进程 attach不到

### ISSUE THREAD

**Issue by sandy0823** [alibaba/arthas#1444]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.3.9
* Arthas 版本: 3.3.9
* 操作系统版本: Linux version 3.10.0-957.5.1.el7.x86_64
* 目标进程的JVM版本: 8
* 执行`arthas-boot`的版本: 8

### 重现问题的步骤

1. war包安装在tomcat中
2. tomcat通过jre启动

### 期望的结果

使用 arthas 可以 attach到jre启动的tomcat进程

### 实际运行的结果

1、使用命令 java -jar arthas-boot.jar 50957

```
[INFO] arthas-boot version: 3.3.9
[INFO] arthas home: /opt/wf/arthas
[INFO] Try to attach process 50957
[ERROR] Start arthas failed, exception stack trace: 
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:84)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:124)
[ERROR] attach fail, targetPid: 50957
```

**Comment by kylixs** [comment]
这个错误提示是attach失败了
1）使用jdk运行arthas-boot.jar，如果指定了pid，必须保证pid是java/tomcat的进程
2）检查日志文件 ~/logs/arthas/arthas.log

**Comment by livem** [comment]
Duplicate of #347
