### ISSUE TITLE
Pivotal Cloud Foundry 上使用 arthas 启动失败

### ISSUE THREAD

**Issue by zjh-coder** [alibaba/arthas#1487]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： arthas-spring-boot-starter 3.4.0
* Arthas 版本: 3.4.0
* 操作系统版本: 16.04.1-Ubuntu 
* 目标进程的JVM版本: OpenJDK Runtime Environment (build 1.8.0_265-b01)
* 执行`arthas-boot`的版本: OpenJDK Runtime Environment (build 1.8.0_265-b01)

### 重现问题的步骤

1. 将arthas-spring-boot-starter添加到maven依赖
2. 部署到PCF上，因为PCF上使用的是jre，所以在启动前将 tool.jar copy到了jre/lib下，然后启动程序

### 期望的结果

arthas 可以成功 attach 部署的service，之后用web console调试

### 实际运行的结果

2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'arthasAgent' defined in class path resource [com/alibaba/arthas/spring/ArthasConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.taobao.arthas.agent.attach.ArthasAgent]: Factory method 'arthasAgent' threw exception; nested exception is java.lang.IllegalStateException: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@46dc6087
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:635)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:893)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at com.garmin.gcc.root.RootApplication.main(RootApplication.java:42)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at java.lang.reflect.Method.invoke(Method.java:498)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.taobao.arthas.agent.attach.ArthasAgent]: Factory method 'arthasAgent' threw exception; nested exception is java.lang.IllegalStateException: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@46dc6087
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] ... 28 common frames omitted
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] Caused by: java.lang.IllegalStateException: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@46dc6087
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at com.taobao.arthas.agent.attach.ArthasAgent.init(ArthasAgent.java:104)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at com.alibaba.arthas.spring.ArthasConfiguration.arthasAgent(ArthasConfiguration.java:49)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at java.lang.reflect.Method.invoke(Method.java:498)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] ... 29 common frames omitted
2020-09-10T14:00:58.601+08:00 [APP/PROC/WEB/0] [OUT] Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@46dc6087
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:613)
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:586)
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:538)
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:515)
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] at com.taobao.arthas.agent.attach.ArthasAgent.init(ArthasAgent.java:63)
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] ... 35 common frames omitted
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] Caused by: java.lang.reflect.InvocationTargetException: null
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] at java.lang.reflect.Method.invoke(Method.java:498)
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] at net.bytebuddy.agent.Attacher.install(Attacher.java:106)
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608)
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] ... 39 common frames omitted
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] Caused by: java.lang.UnsatisfiedLinkError: no attach in java.library.path
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] at java.lang.Runtime.loadLibrary0(Runtime.java:871)
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] at java.lang.System.loadLibrary(System.java:1124)
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] at sun.tools.attach.LinuxVirtualMachine.<clinit>(LinuxVirtualMachine.java:342)
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
2020-09-10T14:00:58.602+08:00 [APP/PROC/WEB/0] [OUT] ... 45 common frames omitted
2020-09-10T14:00:59.913+08:00 [APP/PROC/WEB/0] [OUT] Exit status 1
2020-09-10T14:00:59.916+08:00 [CELL/SSHD/0] [OUT] Exit status 0
2020-09-10T14:00:59.946+08:00 [APP/PROC/WEB/SIDECAR/SIDECAR/0] [OUT] Exit status 143
2020-09-10T14:01:16.632+08:00 [CELL/0] [OUT] Cell 49e9e877-cc32-4bc9-8a72-639dc448c065 stopping instance b4239c81-55be-49d5-5436-5ec3
2020-09-10T14:01:16.632+08:00 [CELL/0] [OUT] Cell 49e9e877-cc32-4bc9-8a72-639dc448c065 destroying container for instance b4239c81-55be-49d5-5436-5ec3
2020-09-10T14:01:16.637+08:00 [API/1] [OUT] Process has crashed with type: "web"

**Comment by zjh-coder** [comment]
在本地试过把tool.jar copy到jre/lib下然后启动，不知为何PCF上会有这个问题

**Comment by hengyunabc** [comment]
可能是他们改造过的jdk，Pivotal Cloud Foundry 不能选jdk？很多应用都要有jdk才能跑。

**Comment by zjh-coder** [comment]
PCF上应该可以选择，但是公司内部的IT部门限制太多，再跟他们继续沟通
