### ISSUE TITLE
as.bat的脚本有错误

### ISSUE THREAD

**Issue by jufeng98** [alibaba/arthas#1488]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* Arthas 版本: 3.4.0
* 操作系统版本: Windows10
* 目标进程的JVM版本: 1.8.131
* 执行`arthas-boot`的版本: 3.4.0

### 重现问题的步骤

1. 使用as.bat PID启动

### 实际运行的结果
启动失败:
```
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AttachNotSupportedException: 拒绝访问。
        at sun.tools.attach.WindowsVirtualMachine.<init>(WindowsVirtualMachine.java:64)
        at sun.tools.attach.WindowsAttachProvider.attachVirtualMachine(WindowsAttachProvider.java:69)
        at com.sun.tools.attach.spi.AttachProvider.attachVirtualMachine(AttachProvider.java:194)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:86)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:124)
```
经我重复排查，发现是as.bat脚本的错误导致，第100行 set JAVACMD="%JAVA_HOME%"\bin\java
不仅多余而且写错

**Comment by hengyunabc** [comment]
可以提交PR修复不？

**Comment by jufeng98** [comment]
好的
