### ISSUE TITLE
使用trace命令报错UnsupportedOperationException

### ISSUE THREAD

**Issue by flyluv** [alibaba/arthas#1502]
### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4.1
* Arthas 版本: 3.4.1
* 操作系统版本: windows 10家庭版 1909
* 目标进程的JVM版本: 1.8.0_261
* 执行`arthas-boot`的JVM版本:  1.8.0_261

### 重现问题的步骤

1. java -jar arthas-boot.jar
2. 输入进程序号
3. trace *InfoController info

### 期望的结果

看到方法链路信息

### 实际运行的结果

```
Enhance error! exception: java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces
error happens when enhancing class: class redefinition failed: attempted to change superclass or interfaces, check arthas log: C:\Users\Administrator/logs/arthas/arthas.log

2020-09-16 00:01:59 [arthas-command-execute] INFO  c.t.arthas.core.advisor.Enhancer -enhance matched classes: [class com.louhong.call.web.InfoController]
2020-09-16 00:01:59 [arthas-command-execute] ERROR c.t.arthas.core.advisor.Enhancer -Enhancer error, matchingClasses: [class com.louhong.call.web.InfoController]
java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:368)
	at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:149)
	at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:96)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by flyluv** [comment]
已找到其他已解决的issue，[#1141](https://github.com/alibaba/arthas/issues/1141)
