### ISSUE TITLE
3.4.1 无法attach到目标程序

### ISSUE THREAD

**Issue by devpage** [alibaba/arthas#1505]
Arthas home: /root/.arthas/lib/3.4.1/arthas
Calculating attach execution time...
Attaching to 6205 using version /root/.arthas/lib/3.4.1/arthas...
[ERROR] Start arthas failed, exception stack trace: 
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:86)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:124)
attach to target jvm (6205) failed, check /root/logs/arthas/arthas.log or stderr of target jvm for any exceptions.

3.3.6 没有问题, 另外如何回退版本, 使用指定的3.3.6？谢谢

**Comment by keith-java** [comment]
可以检查一下启动java进程的用户和你启动arthas的用户是否一致
