### ISSUE TITLE
用JDK 11启动arthas-boot.jar注入JDK 8的Java进程提示失败，但实际注入成功

### ISSUE THREAD

**Issue by kylixs** [alibaba/arthas#1519]
### 环境信息
* 操作系统： macOS 
* Arthas 版本: 3.4.2
* 目标进程的JVM版本:  jdk 11.0.7
* 执行`arthas-boot`的版本: jdk 1.8.0_151-b12

### 重现问题的步骤

1.  jdk8/bin/java -jar  arthas-demo.jar
2. jdk11/bin/java -jar arthas-boot.jar
```
[INFO] Try to attach process 97218
[WARN] Current VM java version: 1.8 do not match target VM java version: 11, attach may fail.
[WARN] Target VM JAVA_HOME is /Library/Java/JavaVirtualMachines/jdk-11.0.7.jdk/Contents/Home, arthas-boot JAVA_HOME is /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre, try to set the same JAVA_HOME.
[ERROR] Start arthas failed, exception stack trace:
java.io.IOException: Non-numeric value found - int expected
	at sun.tools.attach.HotSpotVirtualMachine.readInt(HotSpotVirtualMachine.java:299)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:63)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:79)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:103)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:105)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:124)
[ERROR] attach fail, targetPid: 97218
g
```
但实际上Arthas注入成功，3658端口已打开，可以使用`telnet  127.1 3658`连接进去
```
arthas-packaging-3.4.2-bin % lsof -P -i:3658
COMMAND   PID      USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
java    97218 gongdewei  117u  IPv6 0xf2a4d7ae35cab39      0t0  TCP localhost:3658 (LISTEN)
```

**Comment by kylixs** [comment]
jdk 8 启动arthas-boot.jar 注入 jdk11的进程也提示错误，但实际上3658端口已经打开。
```
[INFO] Try to attach process 6710
[WARN] Current VM java version: 11 do not match target VM java version: 1.8, attach may fail.
[WARN] Target VM JAVA_HOME is /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre, arthas-boot JAVA_HOME is /Library/Java/JavaVirtualMachines/jdk-11.0.7.jdk/Contents/Home, try to set the same JAVA_HOME.
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AgentLoadException: 0
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:108)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:119)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:147)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:105)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:124)
[ERROR] attach fail, targetPid: 6710
arthas-bin % lsof -P -i:3658
COMMAND   PID      USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
java     6710 gongdewei  130u  IPv6 0xf2a4d7adfdbf059      0t0  TCP localhost:3658 (LISTEN)
java    98841 gongdewei    5u  IPv6 0xf2a4d7ae35c7a39      0t0  TCP localhost:57071->localhost:3658 (CLOSE_WAIT)
```

**Comment by skrbug** [comment]
我也遇到类似的问题，只不过不是用的这个项目。 注入方和java进程是不同的jdk版本会出现莫名其妙的问题。但实际上已经注入成功
