### ISSUE TITLE
3.3.7版本在jdk1.8下的异常

### ISSUE THREAD

**Issue by syygl1027** [alibaba/arthas#1522]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.3.7
* Arthas 版本: 3.3.7
* 操作系统版本:  centos 7
* 目标进程的JVM版本: 1.6
* 执行`arthas-boot`的版本: 3.3.7

### 重现问题的步骤

启动arthas后 attach weblogic 的应用时报以下异常

[ERROR] start arthas failed, exception stack trace:
java.io.IOException: Premature EOF
   at sun.tools.attach.HotSpotVirtualMachine.readInt(HotSpotVirtualMachine.java:226)
   at sun.tools.attach.LinuxVirtualMachine.execute(LinuxVirtualMachine.java:175)
   at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:40)
   at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:62)
   at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:85)
   at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:105)
   at com.taobao.arthas.core.Arthas.<init>(Arthas.java:29)
   at com.taobao.arthas.core.Arthas.main(Arthas.java:124)

**Comment by littledotdot** [comment]
解决了吗？ 我的jdk 1.6 也是这样的错误
