### ISSUE TITLE
不能把byteBuffer 转化为可读字符

### ISSUE THREAD

**Issue by ericens** [alibaba/arthas#1541]
- [] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

希望监控SocketChannel的 write方法的  入参，转化为string 打印输出。 byteBuffer的不能转换为期望的String

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4.1
* Arthas 版本: 3.4.1
* 操作系统版本: mac 10.15.7
* 目标进程的JVM版本:  OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
* 执行`arthas-boot`的版本: 3.4.1

### 重现问题的步骤

使用socketChanel发送数据socketChanel.write(writeBuffer)，主要监控 writeBuffer，             

```java
 
public class Client { 
 
    ByteBuffer writeBuffer = ByteBuffer.allocate(1024);
    ByteBuffer readBuffer = ByteBuffer.allocate(1024);
    int i=0;

    @Test
    public void test() {

        ByteBuffer buffer = ByteBuffer.allocate(1024);
        buffer.put("合欢花".getBytes());
        buffer.flip();

        if(buffer instanceof ByteBuffer)
        System.out.println( new java.lang.String(buffer.array(),0,buffer.limit()));
    }

    public void start() throws IOException, InterruptedException {
        // 打开socket通道  
        SocketChannel socketChanel = SocketChannel.open();
        //设置为非阻塞
        socketChanel.configureBlocking(false);
        //连接服务器地址和端口
        socketChanel.connect(new InetSocketAddress("localhost", 8001));
        //打开选择器
        Selector selector = Selector.open(); 
        //注册连接服务器socket的动作
        socketChanel.register(selector, SelectionKey.OP_CONNECT);
        
        Scanner scanner = new Scanner(System.in); 
        while (true) { 
            //选择一组键，其相应的通道已为 I/O 操作准备就绪。  
            //此方法执行处于阻塞模式的选择操作。
            selector.select();
            //返回此选择器的已选择键集。
            Set<SelectionKey> keys = selector.selectedKeys(); 
            System.out.println("keys=" + keys.size()); 
            Iterator<SelectionKey> keyIterator = keys.iterator(); 
            while (keyIterator.hasNext()) { 
                SelectionKey key = keyIterator.next(); 
                keyIterator.remove(); 
                // 判断此通道上是否正在进行连接操作。 
                if (key.isConnectable()) { 
                    socketChanel.finishConnect();
                    socketChanel.register(selector, SelectionKey.OP_WRITE);
                    System.out.println("server connected..."); 
                    break; 
                } else if (key.isWritable()) { //写数据 
                    System.out.print("please input message:"); 
                    String message = "ssssss "+i++;
                    Thread.sleep(1000*3);

                    //ByteBuffer writeBuffer = ByteBuffer.wrap(message.getBytes()); 
                    writeBuffer.clear();
                    writeBuffer.put(message.getBytes());
                    writeBuffer.flip();
                    socketChanel.write(writeBuffer);
                    
                    //注册写操作,每个chanel只能注册一个操作，最后注册的一个生效
                    //如果你对不止一种事件感兴趣，那么可以用“位或”操作符将常量连接起来
                    //int interestSet = SelectionKey.OP_READ | SelectionKey.OP_WRITE;
                    //使用interest集合
                    socketChanel.register(selector, SelectionKey.OP_READ);
                    socketChanel.register(selector, SelectionKey.OP_WRITE);
                    socketChanel.register(selector, SelectionKey.OP_READ);
                    
                } else if (key.isReadable()){//读取数据
                    System.out.print("receive message:");
                    SocketChannel client = (SocketChannel) key.channel();
                    //将缓冲区清空以备下次读取 
                    readBuffer.clear();
                    int num = client.read(readBuffer);
                    System.out.println(new String(readBuffer.array(),0, num));
                    //注册读操作，下一次读取
                    socketChanel.register(selector, SelectionKey.OP_WRITE);
                }
            } 
        } 
    } 
 
    public static void main(String[] args) throws IOException, InterruptedException {
        new Client().start(); 
    } 
}

```

使用命令1
watch sun.nio.ch.SocketChannelImpl write 'params[0].{ new java.lang.String(#this.array(),0,#this.limit())}' -v -n 1 -x 3 'params.length==1 && params[0] instanceof java.nio.ByteBuffer && params[0]!=null && params[0].hasArray()'

或者命令2
watch sun.nio.ch.SocketChannelImpl write 'params[0].{ @java.nio.charset.Charset@forName("utf-8").decode(#this) }' -v -n 5 -x 3 'params.length==1 && params[0] instanceof java.nio.ByteBuffer && params[0].hasArray()'

### 期望的结果

byteBuffer 转为String 打印

### 实际运行的结果

1.使用命令1, 通过new String 报错如下

```
2020-10-15 22:12:09 [arthas-command-execute] INFO  c.t.arthas.core.advisor.Enhancer -enhance matched classes: [class sun.nio.ch.SocketChannelImpl]
2020-10-15 22:12:10 [arthas-command-execute] INFO  c.t.arthas.core.advisor.Enhancer -Success to batch transform classes: [class sun.nio.ch.SocketChannelImpl]
2020-10-15 22:12:12 [main] ERROR c.t.a.c.command.express.OgnlExpress -Error during evaluating the expression:
ognl.MethodFailedException: Method "array" failed for object com.taobao.arthas.core.advisor.Advice@4517d9a3
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1556)
	at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68)
	at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1620)
	at ognl.ASTMethod.getValueBody(ASTMethod.java:91)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTChain.getValueBody(ASTChain.java:141)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTCtor.getValueBody(ASTCtor.java:89)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTProject.getValueBody(ASTProject.java:66)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTChain.getValueBody(ASTChain.java:141)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.Ognl.getValue(Ognl.java:470)
	at ognl.Ognl.getValue(Ognl.java:572)
	at ognl.Ognl.getValue(Ognl.java:542)
	at com.taobao.arthas.core.command.express.OgnlExpress.get(OgnlExpress.java:37)
	at com.taobao.arthas.core.advisor.AdviceListenerAdapter.getExpressionResult(AdviceListenerAdapter.java:123)
	at com.taobao.arthas.core.command.monitor200.WatchAdviceListener.watching(WatchAdviceListener.java:86)
	at com.taobao.arthas.core.command.monitor200.WatchAdviceListener.finishing(WatchAdviceListener.java:70)
	at com.taobao.arthas.core.command.monitor200.WatchAdviceListener.afterReturning(WatchAdviceListener.java:54)
	at com.taobao.arthas.core.advisor.AdviceListenerAdapter.afterReturning(AdviceListenerAdapter.java:57)
	at com.taobao.arthas.core.advisor.SpyImpl.atExit(SpyImpl.java:67)
	at java.arthas.SpyAPI.atExit(SpyAPI.java:64)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.zlx.rpc.socket.Client.start(Client.java:60)
	at org.zlx.rpc.socket.Client.main(Client.java:85)
Caused by: java.lang.NoSuchMethodException: com.taobao.arthas.core.advisor.Advice.array()
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1497)
	... 31 common frames omitted
2020-10-15 22:12:12 [main] WARN  c.t.a.c.c.m.WatchAdviceListener -watch failed.
com.taobao.arthas.core.command.express.ExpressException: ognl.MethodFailedException: Method "array" failed for object com.taobao.arthas.core.advisor.Advice@4517d9a3 [java.lang.NoSuchMethodException: com.taobao.arthas.core.advisor.Advice.array()]
	at com.taobao.arthas.core.command.express.OgnlExpress.get(OgnlExpress.java:40)
	at com.taobao.arthas.core.advisor.AdviceListenerAdapter.getExpressionResult(AdviceListenerAdapter.java:123)
	at com.taobao.arthas.core.command.monitor200.WatchAdviceListener.watching(WatchAdviceListener.java:86)
	at com.taobao.arthas.core.command.monitor200.WatchAdviceListener.finishing(WatchAdviceListener.java:70)
	at com.taobao.arthas.core.command.monitor200.WatchAdviceListener.afterReturning(WatchAdviceListener.java:54)
	at com.taobao.arthas.core.advisor.AdviceListenerAdapter.afterReturning(AdviceListenerAdapter.java:57)
	at com.taobao.arthas.core.advisor.SpyImpl.atExit(SpyImpl.java:67)
	at java.arthas.SpyAPI.atExit(SpyAPI.java:64)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.zlx.rpc.socket.Client.start(Client.java:60)
	at org.zlx.rpc.socket.Client.main(Client.java:85)
Caused by: ognl.MethodFailedException: Method "array" failed for object com.taobao.arthas.core.advisor.Advice@4517d9a3
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1556)
	at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68)
	at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1620)
	at ognl.ASTMethod.getValueBody(ASTMethod.java:91)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTChain.getValueBody(ASTChain.java:141)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTCtor.getValueBody(ASTCtor.java:89)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTProject.getValueBody(ASTProject.java:66)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTChain.getValueBody(ASTChain.java:141)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.Ognl.getValue(Ognl.java:470)
	at ognl.Ognl.getValue(Ognl.java:572)
	at ognl.Ognl.getValue(Ognl.java:542)
	at com.taobao.arthas.core.command.express.OgnlExpress.get(OgnlExpress.java:37)
	... 10 common frames omitted
Caused by: java.lang.NoSuchMethodException: com.taobao.arthas.core.advisor.Advice.array()
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1497)
	... 31 common frames omitted
2020-10-15 22:12:12 [arthas-NettyHttpTelnetBootstrap-3-2] WARN  c.t.a.c.c.m.WatchAdviceListener -watch failed.
java.lang.IllegalStateException: Cannot write to standard output when terminated
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessImpl.write(ProcessImpl.java:476)
	at com.taobao.arthas.core.command.monitor200.WatchAdviceListener.watching(WatchAdviceListener.java:82)
	at com.taobao.arthas.core.command.monitor200.WatchAdviceListener.finishing(WatchAdviceListener.java:70)
	at com.taobao.arthas.core.command.monitor200.WatchAdviceListener.afterReturning(WatchAdviceListener.java:54)
	at com.taobao.arthas.core.advisor.AdviceListenerAdapter.afterReturning(AdviceListenerAdapter.java:57)
	at com.taobao.arthas.core.advisor.SpyImpl.atExit(SpyImpl.java:67)
	at java.arthas.SpyAPI.atExit(SpyAPI.java:64)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
	at com.alibaba.arthas.deps.io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:423)
	at com.alibaba.arthas.deps.io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:930)
	at com.alibaba.arthas.deps.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
	at com.alibaba.arthas.deps.io.netty.channel.nio.AbstractNioByteChannel$1.run(AbstractNioByteChannel.java:54)
	at com.alibaba.arthas.deps.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at com.alibaba.arthas.deps.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at com.alibaba.arthas.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at com.alibaba.arthas.deps.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at com.alibaba.arthas.deps.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at com.alibaba.arthas.deps.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

2.使用命令2, 通过Charset decode报错如下

```
2020-10-15 22:13:31 [arthas-command-execute] INFO  c.t.arthas.core.advisor.Enhancer -enhance matched classes: [class sun.nio.ch.SocketChannelImpl]
2020-10-15 22:13:31 [arthas-command-execute] INFO  c.t.arthas.core.advisor.Enhancer -Success to batch transform classes: [class sun.nio.ch.SocketChannelImpl]
2020-10-15 22:13:33 [main] ERROR c.t.a.c.command.express.OgnlExpress -Error during evaluating the expression:
java.lang.IllegalArgumentException: Unable to convert type com.taobao.arthas.core.advisor.Advice of com.taobao.arthas.core.advisor.Advice@5caf905d to type of java.nio.ByteBuffer
	at ognl.OgnlOps.convertValue(OgnlOps.java:616)
	at ognl.OgnlOps.convertValue(OgnlOps.java:510)
	at ognl.DefaultTypeConverter.convertValue(DefaultTypeConverter.java:50)
	at ognl.DefaultTypeConverter.convertValue(DefaultTypeConverter.java:55)
	at ognl.OgnlRuntime.getConvertedType(OgnlRuntime.java:1218)
	at ognl.OgnlRuntime.getConvertedTypes(OgnlRuntime.java:1235)
	at ognl.OgnlRuntime.getConvertedMethodAndArgs(OgnlRuntime.java:1333)
	at ognl.OgnlRuntime.getAppropriateMethod(OgnlRuntime.java:1317)
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1474)
	at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68)
	at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1620)
	at ognl.ASTMethod.getValueBody(ASTMethod.java:91)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTChain.getValueBody(ASTChain.java:141)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTProject.getValueBody(ASTProject.java:66)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTChain.getValueBody(ASTChain.java:141)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.Ognl.getValue(Ognl.java:470)
	at ognl.Ognl.getValue(Ognl.java:572)
	at ognl.Ognl.getValue(Ognl.java:542)
	at com.taobao.arthas.core.command.express.OgnlExpress.get(OgnlExpress.java:37)
	at com.taobao.arthas.core.advisor.AdviceListenerAdapter.getExpressionResult(AdviceListenerAdapter.java:123)
	at com.taobao.arthas.core.command.monitor200.WatchAdviceListener.watching(WatchAdviceListener.java:86)
	at com.taobao.arthas.core.command.monitor200.WatchAdviceListener.finishing(WatchAdviceListener.java:70)
	at com.taobao.arthas.core.command.monitor200.WatchAdviceListener.afterReturning(WatchAdviceListener.java:54)
	at com.taobao.arthas.core.advisor.AdviceListenerAdapter.afterReturning(AdviceListenerAdapter.java:57)
	at com.taobao.arthas.core.advisor.SpyImpl.atExit(SpyImpl.java:67)
	at java.arthas.SpyAPI.atExit(SpyAPI.java:64)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.zlx.rpc.socket.Client.start(Client.java:60)
	at org.zlx.rpc.socket.Client.main(Client.java:85)
2020-10-15 22:13:33 [main] WARN  c.t.a.c.c.m.WatchAdviceListener -watch failed.
com.taobao.arthas.core.command.express.ExpressException: java.lang.IllegalArgumentException: Unable to convert type com.taobao.arthas.core.advisor.Advice of com.taobao.arthas.core.advisor.Advice@5caf905d to type of java.nio.ByteBuffer
	at com.taobao.arthas.core.command.express.OgnlExpress.get(OgnlExpress.java:40)
	at com.taobao.arthas.core.advisor.AdviceListenerAdapter.getExpressionResult(AdviceListenerAdapter.java:123)
	at com.taobao.arthas.core.command.monitor200.WatchAdviceListener.watching(WatchAdviceListener.java:86)
	at com.taobao.arthas.core.command.monitor200.WatchAdviceListener.finishing(WatchAdviceListener.java:70)
	at com.taobao.arthas.core.command.monitor200.WatchAdviceListener.afterReturning(WatchAdviceListener.java:54)
	at com.taobao.arthas.core.advisor.AdviceListenerAdapter.afterReturning(AdviceListenerAdapter.java:57)
	at com.taobao.arthas.core.advisor.SpyImpl.atExit(SpyImpl.java:67)
	at java.arthas.SpyAPI.atExit(SpyAPI.java:64)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.zlx.rpc.socket.Client.start(Client.java:60)
	at org.zlx.rpc.socket.Client.main(Client.java:85)
Caused by: java.lang.IllegalArgumentException: Unable to convert type com.taobao.arthas.core.advisor.Advice of com.taobao.arthas.core.advisor.Advice@5caf905d to type of java.nio.ByteBuffer
	at ognl.OgnlOps.convertValue(OgnlOps.java:616)
	at ognl.OgnlOps.convertValue(OgnlOps.java:510)
	at ognl.DefaultTypeConverter.convertValue(DefaultTypeConverter.java:50)
	at ognl.DefaultTypeConverter.convertValue(DefaultTypeConverter.java:55)
	at ognl.OgnlRuntime.getConvertedType(OgnlRuntime.java:1218)
	at ognl.OgnlRuntime.getConvertedTypes(OgnlRuntime.java:1235)
	at ognl.OgnlRuntime.getConvertedMethodAndArgs(OgnlRuntime.java:1333)
	at ognl.OgnlRuntime.getAppropriateMethod(OgnlRuntime.java:1317)
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1474)
	at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68)
	at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1620)
	at ognl.ASTMethod.getValueBody(ASTMethod.java:91)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTChain.getValueBody(ASTChain.java:141)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTProject.getValueBody(ASTProject.java:66)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTChain.getValueBody(ASTChain.java:141)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.Ognl.getValue(Ognl.java:470)
	at ognl.Ognl.getValue(Ognl.java:572)
	at ognl.Ognl.getValue(Ognl.java:542)
	at com.taobao.arthas.core.command.express.OgnlExpress.get(OgnlExpress.java:37)
	... 10 common frames omitted

```

**Comment by hengyunabc** [comment]
贴出watch的命令

**Comment by ericens** [comment]
使用命令1
watch sun.nio.ch.SocketChannelImpl write 'params[0].{ new java.lang.String(#this.array(),0,#this.limit())}' -v -n 1 -x 3 'params.length==1 && params[0] instanceof java.nio.ByteBuffer && params[0]!=null && params[0].hasArray()'

或者命令2
watch sun.nio.ch.SocketChannelImpl write 'params[0].{ @java.nio.charset.Charset@forName("utf-8").decode(#this) }' -v -n 5 -x 3 'params.length==1 && params[0] instanceof java.nio.ByteBuffer && params[0].hasArray()'
