### ISSUE TITLE
启动arthas选择进程后异常退出，且进程被kill

### ISSUE THREAD

**Issue by whb1028** [alibaba/arthas#1571]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4.4
* Arthas 版本: 3.4.4
* 操作系统版本: Red Hat 4.4.7-17
* 目标进程的JVM版本: java version "1.6.0_29"
* 执行`arthas-boot`的版本: 3.4.4

执行后报错：
crmbp@hostname[/arthas-bin]#java -jar  arthas-boot.jar 
[INFO] arthas-boot version: 3.4.4
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 31348 com.ztesoft.zsmart.zmc.agent.AgentStarter
  [2]: 5428 com.ztesoft.zsmart.zmc.daemon.daemon
1
[INFO] arthas home: /arthas-bin
[INFO] Try to attach process 31348
[ERROR] Start arthas failed, exception stack trace: 
java.io.IOException: Premature EOF
        at sun.tools.attach.HotSpotVirtualMachine.readInt(HotSpotVirtualMachine.java:226)
        at sun.tools.attach.LinuxVirtualMachine.execute(LinuxVirtualMachine.java:175)
        at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:40)
        at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:61)
        at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:85)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:110)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:26)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:129)
[ERROR] attach fail, targetPid: 31348

在看进程，已经不存在了。
crmbp@hostname[/ztesoft/r81/arthas-bin]#jps
5428 daemon
2655 Jps

**Comment by hengyunabc** [comment]
进程异常退出会生成一个 err log的，看下有没有。另外检查下有没有其它的agent已经在运行的。
