### ISSUE TITLE
arthas进入失败

### ISSUE THREAD

**Issue by bravewind** [alibaba/arthas#1579]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： as.sh
* Arthas 版本: 3.4.4
* 操作系统版本: 3.10.0-514.21.2.el7.centos.plus.x86_64
* 目标进程的JVM版本: Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤
1. 启动./as.sh --http-port 8080
2. 执行 curl -Ss -XPOST http://localhost:8080/api -d '
  {
  "action":"exec",
  "command":"stop"
  }
  '
3. 退出之后再执行./as.sh --http-port 8080 报错

```
$./as.sh --http-port 8080
Arthas script version: 3.4.4
[INFO] JAVA_HOME: /app/jdk/jdk1.8.0_25
Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 836 com.kkk.AgentServer
  [2]: 743 com.alibaba.dubbo.container.Main
2
Arthas home: /home/appdeploy/arthas
Calculating attach execution time...
Attaching to 743 using version /home/appdeploy/arthas...

real    0m0.178s
user    0m0.339s
sys     0m0.074s
Attach success.
telnet connecting to arthas server... current timestamp is 1605405715
Trying 127.0.0.1...

```

日志报错

```
2020-11-13 18:35:22 [arthas-command-execute] ERROR c.t.a.c.s.system.impl.ProcessImpl -Error during processing the command:
java.lang.NullPointerException: null
        at com.taobao.arthas.core.shell.session.impl.SessionManagerImpl.close(SessionManagerImpl.java:93)
        at com.taobao.arthas.core.server.ArthasBootstrap.destroy(ArthasBootstrap.java:430)
        at com.taobao.arthas.core.command.basic1000.ShutdownCommand.shutdown(ShutdownCommand.java:47)
        at com.taobao.arthas.core.command.basic1000.StopCommand.process(StopCommand.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
```

### 期望的结果

如何重新开启Arthas ，正常进入？

**Comment by station19** [comment]
换个端口嘛

**Comment by bravewind** [comment]
不行

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: station19 <notifications@github.com&gt;
发送时间: 2020年12月2日 17:46
收件人: alibaba/arthas <arthas@noreply.github.com&gt;
抄送: bravewind <522728146@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[alibaba/arthas] arthas进入失败 (#1579)





 
换个端口嘛
