### ISSUE TITLE
增强 java.lang.ClassLoader#loadClass(String) 函数，解决一些ClassLoader加载不到 SpyAPI的问题

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#1596]
表现是在watch/trace 一些classloader加载的类时，会匹配不到类，并且在arthas.log里有：

```
the classloader can not load SpyAPI, ignore it.
```

https://github.com/alibaba/arthas/issues/566 

https://github.com/alibaba/arthas/issues/1400

**Comment by hengyunabc** [comment]
测试包： 
[arthas-bin.zip](https://github.com/alibaba/arthas/files/5616501/arthas-bin.zip)

**Comment by hengyunabc** [comment]
```
2020-12-01 14:36:16 [arthas-command-execute] ERROR c.t.arthas.core.advisor.Enhancer -the classloader can not load SpyAPI, ignore it. classloader: org.jboss.modules.ModuleClassLoader, className: com/xxx/controller/LoginController
java.lang.ClassNotFoundException: java.arthas.SpyAPI from [Module "deployment.console.war" from Service Module Loader]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
        at com.taobao.arthas.core.advisor.Enhancer.transform(Enhancer.java:113)
        at com.taobao.arthas.core.advisor.TransformerManager$1.transform(TransformerManager.java:39)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:372)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:149)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:96)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by wxw1111** [comment]
这个问题解决了吗？拉最新的3.4.5还有这个问题哎

**Comment by hengyunabc** [comment]
> 这个问题解决了吗？拉最新的3.4.5还有这个问题哎

说明具体的场景和出错信息，最好有可重现的demo

**Comment by wxw1111** [comment]
2020-12-04 08:30:55 [arthas-command-execute] ERROR c.t.arthas.core.advisor.Enhancer -the classloader can not load SpyAPI, ignore it. classloader: org.jboss.modules.ModuleClassLoader, className: org/keycloak/services/resources/Cors
java.lang.ClassNotFoundException: java.arthas.SpyAPI from [Module "org.keycloak.keycloak-services" version 11.0.3 from local module loader @db57326 (finder: local module finder @34a875b3 (roots: /opt/jboss/keycloak/modules,/opt/jboss/keycloak/modules/system/layers/keycloak,/opt/jboss/keycloak/modules/system/layers/base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at com.taobao.arthas.core.advisor.Enhancer.transform(Enhancer.java:113)
	at com.taobao.arthas.core.advisor.TransformerManager$1.transform(TransformerManager.java:39)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
	at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:372)
	at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:149)
	at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:96)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by hengyunabc** [comment]
@wxw1111 检查下应用加载的arthas是否是对的。可能以前有启动过。

另外，执行下 `jad java.lang.ClassLoader loadClass`检查有没有类似下面的代码：

```java
public Class<?> loadClass(String name) throws ClassNotFoundException {
    ClassLoader extClassLoader;
    if (name.startsWith("java.arthas.") && (extClassLoader = ClassLoader.getSystemClassLoader().getParent()) != null) {
        String string = name;
        ClassLoader classLoader = extClassLoader;
        return classLoader.loadClass(string, false);
    }
    String string = name;
    ClassLoader classLoader = this;
    Class<?> clazz = classLoader.loadClass(string, false);
    return clazz;
}
```

同理也执行下  `jad org.jboss.modules.ConcurrentClassLoader loadClass` ，看有没有被增强。

**Comment by MohnSnow** [comment]
> jad org.jboss.modules.ConcurrentClassLoader loadClass



> jad org.jboss.modules.ConcurrentClassLoader loadClass
执行了jad命令，如下所示
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/13119917/215260920-d5e8f27e-7702-4252-85cf-cfc4f7baafd8.png">
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/13119917/215260928-a02fa634-af6e-4562-a87e-d92c38780dfe.png">
执行trace还是不行
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/13119917/215261001-d2245d71-5064-49fd-abf3-4d223c1354ac.png">
但是日志没发现错误
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/13119917/215261018-e9c8025a-6194-488d-8575-87de3e76fc11.png">
这种怎么解决呢？

**Comment by sheng-wang-i** [comment]
arthas version: 3.7.2
target 是 jboss 7.4
使用trace时无法找到类， log中
```
java.lang.ClassNotFoundException: java.arthas.SpyAPI from [Module "org.keycloak.keycloak-services" version 11.0.3 from local module loader @db57326 (finder: local module finder @34a875b3 (roots: /opt/jboss/keycloak/modules,/opt/jboss/keycloak/modules/system/layers/keycloak,/opt/jboss/keycloak/modules/system/layers/base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
```
```
[arthas@7290]$ jad java.lang.ClassLoader loadClass

ClassLoader:

Location:

        public Class<?> loadClass(String string) throws ClassNotFoundException {
/*351*/     return this.loadClass(string, false);
        }
        /*
         * WARNING - Removed try catching itself - possible behaviour change.
         */
        protected Class<?> loadClass(String string, boolean bl) throws ClassNotFoundException {
/*398*/     Object object = this.getClassLoadingLock(string);
            synchronized (object) {
/*400*/         Class<?> clazz = this.findLoadedClass(string);
/*401*/         if (clazz == null) {
/*402*/             long l = System.nanoTime();
                    try {
                        clazz = this.parent != null ? this.parent.loadClass(string, false) : this.findBootstrapClassOrNull(string);
                    }
                    catch (ClassNotFoundException classNotFoundException) {
                        // empty catch block
                    }
/*414*/             if (clazz == null) {
/*417*/                 long l2 = System.nanoTime();
/*418*/                 clazz = this.findClass(string);
/*421*/                 PerfCounter.getParentDelegationTime().addTime(l2 - l);
/*422*/                 PerfCounter.getFindClassTime().addElapsedTimeFrom(l2);
/*423*/                 PerfCounter.getFindClasses().increment();
                    }
                }
/*426*/         if (bl) {
/*427*/             this.resolveClass(clazz);
                }
/*429*/         return clazz;
            }
        }
```

```
[arthas@7290]$ jad org.jboss.modules.ConcurrentClassLoader loadClass

ClassLoader:
+-sun.misc.Launcher$AppClassLoader@18b4aac2
  +-sun.misc.Launcher$ExtClassLoader@5c30a9b0

Location:
/home/booxware/www2/sportbet-jboss-4-eap/jboss-modules.jar

        @Override
        public final Class<?> loadClass(String className) throws ClassNotFoundException {
/*116*/     return this.performLoadClass(className, false, false);
        }
        @Override
        public final Class<?> loadClass(String className, boolean resolve) throws ClassNotFoundException {
/*128*/     return this.performLoadClass(className, false, resolve);
        }
```

**Comment by sheng-wang-i** [comment]
```
arthas.enhanceLoaders=java.lang.ClassLoader,org.jboss.modules.ConcurrentClassLoader
``` 
is also added to `~/.arthas/lib/3.7.2/arthas/arthas.properties`

**Comment by DamianSheldon** [comment]
查找 arthas.properties 的过程可能有点瑕疵，通过 -Darthas.config.location=/opt/arthas/arthas.properties 显示指定后，arthas.enhanceLoaders=java.lang.ClassLoader,org.jboss.modules.ConcurrentClassLoader 的配置生效了。
