### ISSUE TITLE
debug and got com.sun.tools.attach.spi.AttachProvider: Provider issue

### ISSUE THREAD

**Issue by rechardguo** [alibaba/arthas#1603]
Hi,

refer [debug](https://github.com/alibaba/arthas/issues/222)

below is my command

```
java -agentlib:jdwp=transport=dt_socket,address=8002,server=y,suspend=y -Djava.awt.headless=true -Xbootclasspath/a:D:\dev-env\jdk8\lib\tools.jar -cp D:\dev-env\jdk8\lib\tools.jar -jar C:\Users\sdrag\.arthas\lib\3.4.5\arthas\arthas-core.jar -pid 2904 -target-ip 127.0.0.1 -telnet-port 3658 -core C:\Users\sdrag\.arthas\lib\3.4.5\arthas\arthas-core.jar -agent C:\Users\sdrag\.arthas\lib\3.4.5\arthas\arthas-agent.jar
Listening for transport dt_socket at address: 8002
```
but fail as:

> java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Provider sun.tools.attach.WindowsAttachProvider could not be instantiated
> [ERROR] Start arthas failed, exception stack trace:
> com.sun.tools.attach.AttachNotSupportedException: no providers installed
>         at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:203)
>         at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:89)
>         at com.taobao.arthas.core.Arthas.<init>(Arthas.java:26)
>         at com.taobao.arthas.core.Arthas.main(Arthas.java:129)

**Comment by xplx** [comment]
这个问题解决没，我的也是这样

**Comment by hengyunabc** [comment]
要用jdk，不行就试下全路径的 jdk启动。 `/opt/jdk/bin/java` 之类的。或者 cd到有 jstack 命令下的目录来执行 java。
