### ISSUE TITLE
arthas启动出错ArthasBanner.welcome  ExceptionInInitializerError 

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#1611]
```
01 2020-12-07 16:38:11.365 INFO [arthas-binding-thread:arthas] [] [] [] arthas version: 3.1.4
01 2020-12-07 16:38:11.369 ERROR [arthas-binding-thread:arthas] [] [] [] Error during bind to port 3658
java.lang.ExceptionInInitializerError: null
	at com.taobao.arthas.core.util.ArthasBanner.welcome(ArthasBanner.java:108)
	at com.taobao.arthas.core.util.ArthasBanner.welcome(ArthasBanner.java:99)
	at com.taobao.arthas.core.shell.ShellServerOptions.<clinit>(ShellServerOptions.java:29)
	at com.taobao.arthas.core.server.ArthasBootstrap.bind(ArthasBootstrap.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:82)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.taobao.arthas.agent.AgentBootstrap.bind(AgentBootstrap.java:180)
	at com.taobao.arthas.agent.AgentBootstrap.access$000(AgentBootstrap.java:16)
	at com.taobao.arthas.agent.AgentBootstrap$1.run(AgentBootstrap.java:140)
Caused by: java.lang.NullPointerException: null
Arthas server port binding failed! Please check $HOME/logs/arthas/arthas.log for more details.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:82)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.taobao.arthas.agent.AgentBootstrap.bind(AgentBootstrap.java:180)
	at com.taobao.arthas.agent.AgentBootstrap.access$000(AgentBootstrap.java:16)
	at com.taobao.arthas.agent.AgentBootstrap$1.run(AgentBootstrap.java:140)
Caused by: java.lang.ExceptionInInitializerError
	at com.taobao.arthas.core.util.ArthasBanner.welcome(ArthasBanner.java:108)
	at com.taobao.arthas.core.util.ArthasBanner.welcome(ArthasBanner.java:99)
	at com.taobao.arthas.core.shell.ShellServerOptions.<clinit>(ShellServerOptions.java:29)
	at com.taobao.arthas.core.server.ArthasBootstrap.bind(ArthasBootstrap.java:114)
	... 7 more
Caused by: java.lang.NullPointerException
Arthas server agent start...
```

**Comment by hengyunabc** [comment]
检查了下代码，可能是这里出错的： https://github.com/alibaba/arthas/blob/arthas-all-3.1.4/common/src/main/java/com/taobao/arthas/common/PidUtils.java#L15 

```java
String jvmName = ManagementFactory.getRuntimeMXBean().getName();
```

`ManagementFactory.getRuntimeMXBean()`返回了 null，然后异常再转化为 `ExceptionInInitializerError`

**Comment by hengyunabc** [comment]
修复的测试包： [arthas-bin.zip](https://github.com/alibaba/arthas/files/5663374/arthas-bin.zip)
