### ISSUE TITLE
sandbox 可能导致死锁问题 

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#1627]
```java
	at com.alibaba.jvm.sandbox.core.classloader.ClassLoadingLock.loadingInLock(ClassLoadingLock.java:53)
	- waiting to lock <0x000000076b1de4d0> (a java.lang.Object)
	at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader.loadClass(RoutingURLClassLoader.java:62)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at com.taobao.arthas.core.advisor.Enhancer.transform(Enhancer.java:113)
	at com.taobao.arthas.core.advisor.TransformerManager$1.transform(TransformerManager.java:39)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:788)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader.access$400(RoutingURLClassLoader.java:20)
	at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader$1.loadClass(RoutingURLClassLoader.java:89)
	at com.alibaba.jvm.sandbox.core.classloader.ClassLoadingLock.loadingInLock(ClassLoadingLock.java:55)
	- locked <0x000000076b1de578> (a java.lang.Object)
	at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader.loadClass(RoutingURLClassLoader.java:62)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at ch.qos.logback.core.rolling.helper.TimeBasedArchiveRemover.cleanAsynchronously(TimeBasedArchiveRemover.java:227)
	at ch.qos.logback.core.rolling.TimeBasedRollingPolicy.rollover(TimeBasedRollingPolicy.java:182)
	at ch.qos.logback.core.rolling.RollingFileAppender.attemptRollover(RollingFileAppender.java:211)
	at ch.qos.logback.core.rolling.RollingFileAppender.rollover(RollingFileAppender.java:190)
	at ch.qos.logback.core.rolling.RollingFileAppender.subAppend(RollingFileAppender.java:231)
	- locked <0x000000076b1dd0d8> (a ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.core.AsyncAppenderBase$Worker.run(AsyncAppenderBase.java:265)
```

**Comment by Deecyn** [comment]
你好，能说下这个死锁问题的具体场景吗或者原因吗？

**Comment by hengyunabc** [comment]
> 你好，能说下这个死锁问题的具体场景吗或者原因吗？

只有一个异常栈，没有更多的信息了。

**Comment by Deecyn** [comment]
> > 你好，能说下这个死锁问题的具体场景吗或者原因吗？
> 
> 只有一个异常栈，没有更多的信息了。

我们在准备用 arthas 和 sandbox。这里信息太少，不好定位出原因，也不好采取预防措施😂
