### ISSUE TITLE
attach IBM JDK1.8运行的WebSphere进程失败，报错not supported

### ISSUE THREAD

**Issue by programmerlc** [alibaba/arthas#1630]
- [*] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4.5
* Arthas 版本: 3.4.5
* 操作系统版本: Linux 4.4.73-5(SUSE Linux)
* 目标进程的JVM版本: IBM JDK1.8
* 执行`arthas-boot`的版本: IBM JDK1.8

### 重现问题的步骤

1. 在Linux 4.4.73的机器上安装并启动IBM WebSphere容器
2. 查询WebSphere进程PID
3. 运行arthas的as.sh脚本attach到WebSphere进程(sh as.sh PID)

### 期望的结果

attach success，attach成功，窗口输出arthas图标，运行arthas命令正常。

### 实际运行的结果

Attach success
telnet connecting to arthas server ... current timestamp is 1608187161
Trying IP地址...
telnet:Connect to address IP地址：Connection refused。
连接被拒绝。

```
Arthas server agent start...
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at com.taobao.arthas.agent334.AgentBootstrap.bind(AgentBootstrap.java:182)
        at com.taobao.arthas.agent334.AgentBootstrap.access$000(AgentBootstrap.java:20)
        at com.taobao.arthas.agent334.AgentBootstrap$1.run(AgentBootstrap.java:152)
Caused by: java.lang.UnsupportedOperationException: adding retransformable transformers is not supported in this environment
        at sun.instrument.InstrumentationImpl.addTransformer(InstrumentationImpl.java:100)
        at com.taobao.arthas.core.server.ArthasBootstrap.enhanceClassLoader(ArthasBootstrap.java:215)
        at com.taobao.arthas.core.server.ArthasBootstrap.<init>(ArthasBootstrap.java:136)
        at com.taobao.arthas.core.server.ArthasBootstrap.getInstance(ArthasBootstrap.java:534)
        at com.taobao.arthas.core.server.ArthasBootstrap.getInstance(ArthasBootstrap.java:522)
        ... 7 more
```

**Comment by hengyunabc** [comment]
参考： https://github.com/alibaba/arthas/issues/693

**Comment by programmerlc** [comment]
看了一下，WebSphere容器添加启动参数-Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n
确实可以attach成功，但是WebSphere一般不用debug模式启动。而且测试过有不以debug模式启动的WebSphere进程可以attach成功的。

**Comment by lenggggg** [comment]
> 看了一下，WebSphere容器添加启动参数-Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n 确实可以attach成功，但是WebSphere一般不用debug模式启动。而且测试过有不以debug模式启动的WebSphere进程可以attach成功的。

怎么能不以debug模式启动的WebSphere进程attach成功呢

**Comment by AquariusFu** [comment]
IBM JDK1.8  没有jps命令  导致arthas 无法使用

**Comment by lenggggg** [comment]
你好，你的邮件已收到

**Comment by AquariusFu** [comment]
能否开发一个适用于ibm jdk的arthas  如将其中的jps命令改为jcmd命令等
