### ISSUE TITLE
应用引入 arthas-spring-boot-starter 后通过java -jar方式启动失败

### ISSUE THREAD

**Issue by Sooth1ngRain** [alibaba/arthas#1631]
尝试引入arthas-spring-boot-starter，在idea中调试启动是ok的，但是打成jar包java -jar方式启动报错：
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'arthasAgent' defined in class path resource [com/alibaba/arthas/spring/ArthasConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.taobao.arthas.agent.attach.ArthasAgent]: Factory method 'arthasAgent' threw exception; nested exception is java.lang.IllegalStateException: java.lang.IllegalStateException: No compatible attachment provider is available
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:657) ~[spring-beans-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:637) ~[spring-beans-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[spring-beans-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176) ~[spring-beans-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[spring-beans-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405) [spring-boot-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at com.example.demo.DemoApplication.main(DemoApplication.java:10) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_151]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [demo-0.0.1-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) [demo-0.0.1-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [demo-0.0.1-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [demo-0.0.1-SNAPSHOT.jar:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.taobao.arthas.agent.attach.ArthasAgent]: Factory method 'arthasAgent' threw exception; nested exception is java.lang.IllegalStateException: java.lang.IllegalStateException: No compatible attachment provider is available
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:652) ~[spring-beans-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        ... 28 common frames omitted
Caused by: java.lang.IllegalStateException: java.lang.IllegalStateException: No compatible attachment provider is available
        at com.taobao.arthas.agent.attach.ArthasAgent.init(ArthasAgent.java:128) ~[arthas-agent-attach-3.4.3.jar!/:3.4.3]
        at com.alibaba.arthas.spring.ArthasConfiguration.arthasAgent(ArthasConfiguration.java:49) ~[arthas-spring-boot-starter-3.4.3.jar!/:3.4.3]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_151]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        ... 29 common frames omitted
Caused by: java.lang.IllegalStateException: No compatible attachment provider is available
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:602) ~[byte-buddy-agent-1.10.18.jar!/:na]
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:586) ~[byte-buddy-agent-1.10.18.jar!/:na]
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:538) ~[byte-buddy-agent-1.10.18.jar!/:na]
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:515) ~[byte-buddy-agent-1.10.18.jar!/:na]
        at com.taobao.arthas.agent.attach.ArthasAgent.init(ArthasAgent.java:87) ~[arthas-agent-attach-3.4.3.jar!/:3.4.3]
        ... 35 common frames omitted

**Comment by hengyunabc** [comment]
搜索 `java.lang.IllegalStateException: No compatible attachment provider is available` 。 要用jdk启动，jre不行。

或者试下全路径的 /opt/jdk/bin/java -jar xxx.jar 这样子来启动。

**Comment by Sooth1ngRain** [comment]
> 搜索 `java.lang.IllegalStateException: No compatible attachment provider is available` 。 要用jdk启动，jre不行。
> 
> 或者试下全路径的 /opt/jdk/bin/java -jar xxx.jar 这样子来启动。

感谢回答，换成jdk启动确实可以了。
但是我对此表示疑惑，我无法保证应用运行时是使用jdk还是jre，当使用jre运行时，有没有比较优雅不报错的方式，目前这样会导致springboot无法启动。

**Comment by hengyunabc** [comment]
有一个 `slientInit`的配置，配了就不抛异常了。

**Comment by Sooth1ngRain** [comment]
> 有一个 `slientInit`的配置，配了就不抛异常了。
确实如你所言，不抛异常了。
arthas-spring-boot-starter 这个包推荐在生产环境中使用吗，是否会导致风险

**Comment by hengyunabc** [comment]
> > 有一个 `slientInit`的配置，配了就不抛异常了。
> > 确实如你所言，不抛异常了。
> > arthas-spring-boot-starter 这个包推荐在生产环境中使用吗，是否会导致风险

* 纯启动arthas没有风险
* 最决于执行的命令

**Comment by Sooth1ngRain** [comment]
@hengyunabc 痛点仍在，希望大佬不吝赐教
我们的开发测试机不能随意登录，并且有些应用是在容器中运行，不便于使用arthas-boot.jar。因此我希望通过应用中集成arthas-spring-boot-starter，便于从本地的tunnel连过去进行诊断分析。
但是开发测试服务器和容器环境中都是以jre运行应用的，因为没有jdk因此无法使用arthas-spring-boot-starter 。
有没有好办法能满足远程诊断的场景。

**Comment by hengyunabc** [comment]
> @hengyunabc 痛点仍在，希望大佬不吝赐教
> 我们的开发测试机不能随意登录，并且有些应用是在容器中运行，不便于使用arthas-boot.jar。因此我希望通过应用中集成arthas-spring-boot-starter，便于从本地的tunnel连过去进行诊断分析。
> 但是开发测试服务器和容器环境中都是以jre运行应用的，因为没有jdk因此无法使用arthas-spring-boot-starter 。
> 有没有好办法能满足远程诊断的场景。

绝大部分java应用都是以jdk启动的。以jre启动后续也用不了 arthas，少了tools.jar的话，arthas attach不了目标进程。

另外，java 8之后，jvm本身不再区分 jdk/jre，没这个概念了。

你需要做的是统一公司的java环境，统一使用jdk。

**Comment by huanfion** [comment]
> 

为什么我用的openjdk:8-jdk-alpine也出现同样的错误呢？我这启动了2个服务，一个就可以，另一个就报错。。两个服务使用的都是同一个基础镜像openjdk:8-jdk-alpine。
报错信息：
Caused by: java.lang.IllegalStateException: No compatible attachment provider is available
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:597) ~[byte-buddy-agent-1.9.16.jar!/:?]
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:581) ~[byte-buddy-agent-1.9.16.jar!/:?]
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:533) ~[byte-buddy-agent-1.9.16.jar!/:?]
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:510) ~[byte-buddy-agent-1.9.16.jar!/:?]
        at com.taobao.arthas.agent.attach.ArthasAgent.init(ArthasAgent.java:90) ~[arthas-agent-attach-3.6.2.jar!/:3.6.2]
        at com.alibaba.arthas.spring.ArthasConfiguration.arthasAgent(ArthasConfiguration.java:69) ~[arthas-spring-boot-starter-3.6.2.jar!/:3.6.2]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]

**Comment by yudong520Y** [comment]
openjdk:8-jdk  可以使用

**Comment by LZMIEN** [comment]
> openjdk:8-jdk 可以使用

感谢提醒，果然将openjdk:8-jdk-alpline换成openjdk:8-jdk就可以了，亲测有效
