### ISSUE TITLE
com.sun.tools.attach.AttachNotSupportedException: 拒绝访问

### ISSUE THREAD

**Issue by xuxiaohongok** [alibaba/arthas#1647]
D:\testArt>java -jar arthas-boot.jar
[INFO] arthas-boot version: 3.2.0
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 10948
  [2]: 13656 org.jetbrains.jps.cmdline.Launcher
  [3]: 13896 com.xxx.BastTest
  [4]: 13468 org.jetbrains.idea.maven.server.RemoteMavenServer
3
[INFO] arthas home: C:\Users\Admin\.arthas\lib\3.4.5\arthas
[INFO] Try to attach process 13896
[INFO] Found java home from System Env JAVA_HOME: D:\Program Files\Java\jdk1.8.0_211
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AttachNotSupportedException: 拒绝访问。
        at sun.tools.attach.WindowsVirtualMachine.<init>(WindowsVirtualMachine.java:64)
        at sun.tools.attach.WindowsAttachProvider.attachVirtualMachine(WindowsAttachProvider.java:69)
        at com.sun.tools.attach.spi.AttachProvider.attachVirtualMachine(AttachProvider.java:194)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:91)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:26)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:129)
[ERROR] attach fail, targetPid: 13896

**Comment by guaidaokakaxi** [comment]
jdk版本多少

**Comment by hengyunabc** [comment]
参考: https://arthas.aliyun.com/doc/faq.html ，试下 jstack， 检查是否用的同样的jvm。
