### ISSUE TITLE
使用 java -jar arthas-boot.jar --telnet-port xx --http-port -1 无法正常attach.

### ISSUE THREAD

**Issue by horizonzy** [alibaba/arthas#1664]
### 环境信息

* Arthas 版本: 3.1.1
* 操作系统版本: Linux 3.10.0-957.5.1.el7.x86_64.
* 目标进程的JVM版本: 1.8.0_60
* 执行`arthas-boot`的版本:3.1.1

### 重现问题的步骤

1. 执行 java -jar arthas-boot.jar --telnet-port 19988 --http-port -1
2. 选择attch的进程
3. 报错提示:Connect to telnet server error: 127.0.0.1 19988 java.net.ConnectException: Connection refused，日志提示了 Attach process 25212 success。推测是在arthas-client connect的时候，19988还未监听成功。

### 期望的结果
attach指定--telnet-port 能够正常attach.

### 实际运行的结果
无法attch，提示connection refused.

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
一下进程信息就不贴了，我选择的是一个存在的进程。

```
java -jar arthas-boot.jar --telnet-port 19988 --http-port -1
[INFO] arthas-boot version: 3.1.1
[INFO] Found existing java process, please choose one and hit RETURN.
进程信息省略。
//这里我选择了49位的进程进行attch，进程号为25212.
49

[INFO] arthas home: /home/xxx
[INFO] Try to attach process 25212
[INFO] Attach process 25212 success.
[INFO] arthas-client connect 127.0.0.1 19988
Connect to telnet server error: 127.0.0.1 19988
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
	at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:268)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:503)
Usage: arthas-client [--help] [-c <value>] [-f <value>] [-w <value>] [-h
       <value>] [target-ip] [port]

Arthas Telnet Client

EXAMPLES:
  java -jar arthas-client.jar 127.0.0.1 3658
  java -jar arthas-client.jar -c 'dashboard -n 1'
  java -jar arthas-client.jar -f batch.as 127.0.0.1

Options and Arguments:
    --help                 Print usage
 -c,--command <value>      Command to execute, multiple commands separated by ;
 -f,--batch-file <value>   The batch file to execute
 -w,--width <value>        The terminal width
 -h,--height <value>       The terminal height
 <target-ip>               Target ip
 <port>                    The remote server port

```

**Comment by hengyunabc** [comment]
用最新版本

**Comment by horizonzy** [comment]
使用最新版本后，该问题解决。
