### ISSUE TITLE
无法获取到java进程号

### ISSUE THREAD

**Issue by zzllkk2003** [alibaba/arthas#1681]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.4.6
* 操作系统版本: 
* [root@iZbp1cqhiw1za1thckxolsZ log]# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.8.2003 (Core)
Release:	7.8.2003
Codename:	Core

* 目标进程的JVM版本: 
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)

* 执行`arthas-boot`的版本: 3.4.6

### 重现问题的步骤

1. xxx
2. xxx
3. xxx

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

[root@iZbp1cqhiw1za1thckxolsZ log]# /usr/lib/jvm/jre-1.8.0/bin/java -jar ~/arthas-packaging-3.4.6-bin/arthas-boot.jar
[INFO] arthas-boot version: 3.4.6
[INFO] Can not find java process. Try to pass <pid> in command line.
Please select an available pid.
[root@iZbp1cqhiw1za1thckxolsZ log]# /usr/lib/jvm/jre-1.8.0/bin/java -jar ~/arthas-packaging-3.4.6-bin/arthas-boot.jar 11973
[INFO] arthas-boot version: 3.4.6
[INFO] arthas home: /root/arthas-packaging-3.4.6-bin
[INFO] Try to attach process 11973
Exception in thread "main" java.lang.IllegalArgumentException: Can not find tools.jar under java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-0.el7_9.x86_64/jre, please try to start arthas-boot with full path java. Such as /opt/jdk/bin/java -jar arthas-boot.jar
	at com.taobao.arthas.boot.ProcessUtils.findJavaHome(ProcessUtils.java:222)
	at com.taobao.arthas.boot.ProcessUtils.startArthasCore(ProcessUtils.java:233)
	at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:523)

**Comment by zzllkk2003** [comment]
yum install java-1.8. 0-openjdk-devel
后即可以。
