### ISSUE TITLE
Connect to telnet server error: Connection refused 换端口也不行

### ISSUE THREAD

**Issue by hcoona** [alibaba/arthas#1686]
- [ x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.4.6
* Arthas 版本: 3.4.6
* 操作系统版本: Debian 9
* 目标进程的JVM版本: 1.8.0_131 Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
* 执行`arthas-boot`的版本: 3.4.6

### 重现问题的步骤

1. `java -jar arthas-boot.jar 2456922`
2. `java -jar arthas-boot.jar 2456922 --telnet-port 19999 --http-port -1`
3. `java -jar arthas-boot.jar 2456922 --telnet-port 29999 --http-port -1`

### 期望的结果

可以正常使用

### 实际运行的结果

```
$ java -jar arthas-boot.jar 2456922 --telnet-port 29999 --http-port -1
[INFO] arthas-boot version: 3.4.6
[INFO] arthas home: /home/tiger/.arthas/lib/3.4.6/arthas
[INFO] Try to attach process 2456922
[INFO] Attach process 2456922 success.
[INFO] arthas-client connect 127.0.0.1 29999
Connect to telnet server error: 127.0.0.1 29999
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
        at com.taobao.arthas.client.TelnetConsole.process(TelnetConsole.java:309)
        at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:166)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:566)
Usage: arthas-client [--help] [-c <value>] [-f <value>] [-w <value>] [-t
       <value>] [-h <value>] [target-ip] [port]

Arthas Telnet Client

EXAMPLES:
  java -jar arthas-client.jar 127.0.0.1 3658
  java -jar arthas-client.jar -c 'dashboard -n 1'
  java -jar arthas-client.jar -f batch.as 127.0.0.1

Options and Arguments:
    --help                        Print usage
 -c,--command <value>             Command to execute, multiple commands
                                  separated by ;
 -f,--batch-file <value>          The batch file to execute
 -w,--width <value>               The terminal width
 -t,--execution-timeout <value>   The timeout (ms) of execute commands or batch
                                  file
 -h,--height <value>              The terminal height
 <target-ip>                      Target ip
 <port>                           The remote server port
```

```
$ cat ~/logs/arthas/arthas.log
Arthas server agent start...
Arthas server already bind.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
```

### 已经排查过：

1. 通过 `netstat -anlp` 和 `lsof -i :3658` 排查过没有人占用这些端口
2. 检查过目标进程使用的 java 就是启动 arthas 的 java（通过 `ls -lh /proc/2456922/exe`）
3. 检查过当前使用的账户就是启动目标进程的账户
4. 检查过当前没有其他 arthas 进程（通过 `ps aux | grep arthas`）
5. `jstack` 可以打出目标进程的栈

**Comment by hengyunabc** [comment]
启动一个 arthas-demo.jar ，再试下 attach arthas-demo。

**Comment by hengyunabc** [comment]
另外，也有可能以前有arthas attach过。试下重启进程，再attach。

**Comment by mejinke** [comment]
一样有这个问题

**Comment by zheng-zy** [comment]
这个问题解决了没 遇到同样的问题 试了都不行

**Comment by zqw961025** [comment]
同样的问题，不知道大家解决没有，升级版有没有用

**Comment by JoinFyc** [comment]
我也有这个问题，另外我不理解这个问题怎么被关闭了

**Comment by iyangpengyu** [comment]
亲测低版本没有该问题，3.1.4可以；3.6.7一直报错。[难过]

**Comment by crazyzh1984** [comment]
> 亲测低版本没有该问题，3.1.4可以；3.6.7一直报错。[难过]

试了下3.1.7也可以，3.1.8就不行了。

`
[INFO] arthas-boot version: 3.2.0
[INFO] arthas home: /home/sa_cluster/arthas
[INFO] Try to attach process 4388
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:104)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:123)
[ERROR] attach fail, targetPid: 4388
`

**Comment by hengyunabc** [comment]
> > 亲测低版本没有该问题，3.1.4可以；3.6.7一直报错。[难过]
> 
> 试了下3.1.7也可以，3.1.8就不行了。
> 
> ```shell
> [INFO] arthas-boot version: 3.2.0
> [INFO] Try to attach process 4388
> [ERROR] Start arthas failed, exception stack trace:
> com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
> 	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
> 	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:104)
> 	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
> 	at com.taobao.arthas.core.Arthas.main(Arthas.java:123)
> [ERROR] attach fail, targetPid: 4388
> ```

很有可能是因为之前用旧版本的 arthas attach过，再使用新版本去 attach 时，出现了不兼容的情况。 试下把目标应用的进程重启了，再重新 attach。

**Comment by crazyzh1984** [comment]
> > > 亲测低版本没有该问题，3.1.4可以；3.6.7一直报错。[难过]
> > 
> > 
> > 试了下3.1.7也可以，3.1.8就不行了。
> > ```shell
> > [INFO] arthas-boot version: 3.2.0
> > [INFO] Try to attach process 4388
> > [ERROR] Start arthas failed, exception stack trace:
> > com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
> > 	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
> > 	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:104)
> > 	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
> > 	at com.taobao.arthas.core.Arthas.main(Arthas.java:123)
> > [ERROR] attach fail, targetPid: 4388
> > ```
> 
> 很有可能是因为之前用旧版本的 arthas attach过，再使用新版本去 attach 时，出现了不兼容的情况。 试下把目标应用的进程重启了，再重新 attach。

应该不是，开始先用的新版连的，连不上，才查到这个issue。
重启后试了下，错误一样：
```sh
$ sbpadmin arthas 30747
[INFO] arthas-boot version: 3.5.5
[INFO] Start download arthas from remote server: https://arthas.aliyun.com/download/3.7.1?mirror=aliyun
[INFO] Download arthas success.
[INFO] arthas home: /home/xxx/.arthas/lib/3.7.1/arthas
[INFO] Try to attach process 30747
[INFO] Attach process 30747 success.
[INFO] arthas-client connect 127.0.0.1 3658
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
	at com.taobao.arthas.client.TelnetConsole.process(TelnetConsole.java:306)
	at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:615)
```

看着是端口没bind上？
进程是flink job。

**Comment by crazyzh1984** [comment]
> ```java
> AnsiLog
> ```

我们的找到问题了。
有个研发写的代码，强制把slot=0的shutdown hook位置占了，导致arthas的AnsiLog获取System.Console

**Comment by hengyunabc** [comment]
@crazyzh1984     是不是在 AnsiLog static 初始化时加一个 try/catch 就可以了？ 可以提个 pr 来改进下。
