### ISSUE TITLE
trace/watch 增强 cglib 生成代理类 EnhancerBySpringCGLIB 时，抛出 java.lang.VerifyError 

### ISSUE THREAD

**Issue by scp114514810** [alibaba/arthas#1690]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4.6
* Arthas 版本: 3.4.6
* 操作系统版本: centos7
* 目标进程的JVM版本: openjdk version "1.8.0_265"
* 执行`arthas-boot`的版本: 3.4.6

### 重现问题的步骤

1. 建立springboot单体项目，项目pom依赖可参照结尾的依赖

2. 使用上述依赖中的dynamic-datasource-spring-boot-starter配置多个数据源，可参照下图配置
![image](https://user-images.githubusercontent.com/52482499/106555257-2d82b400-6558-11eb-85cc-ccc1436ca8a8.png)
![image](https://user-images.githubusercontent.com/52482499/106555279-34a9c200-6558-11eb-9b16-21237382a33a.png)

3. 在某个service类上使用org.springframework.stereotype.Service @Service 和 com.baomidou.dynamic.datasource.annotation.DS @DS注解 ，比如@DS("master")
4. 启动该单点springboot项目
5. 启动arthas 并attach该项目，并试图trace该service类
### 期望的结果
期望可以正常trace
 

### 实际运行的结果
实际trace失败 返回verifyError
 

```
java.lang.VerifyError
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:387)
	at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:163)
	at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:110)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

项目部分依赖如下：

```
<repositories>
        <repository>
            <id>Alibaba</id>
            <name>Alibaba Repository</name>
            <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
        </repository>
    </repositories>

    <properties>
        <java.version>1.8</java.version>
        <skipTests>true</skipTests>
        <spring-cloud.version>Finchley.SR1</spring-cloud.version>
        <jira-client.version>5.2.1</jira-client.version>
        <alibaba-fastjson.version>1.2.68</alibaba-fastjson.version>
        <atlassian-fugue.version>4.7.2</atlassian-fugue.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
            <version>2.4.2</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-quartz</artifactId>
        </dependency>


        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
        </dependency>



        <!--  http client-->

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>2.2.6.RELEASE</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.vaadin.external.google</groupId>
                    <artifactId>android-json</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.2.0</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- https://mvnrepository.com/artifact/mysql/mysql-connector-java -->
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.16</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/io.swagger/swagger-models -->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.47</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.1.21</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>RELEASE</version>
            <scope>compile</scope>
        </dependency>


    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <!-- not append assembly id in release file name -->
                    <appendAssemblyId>false</appendAssemblyId>
                    <descriptors>
                        <!--打包的详细描述，需要配置额外文件-->
                        <descriptor>src/main/resources/assembly.xml</descriptor>
                    </descriptors>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

```

**Comment by hengyunabc** [comment]
最好有一个可以直接执行的demo，不然我也是要自己尝试构建出一个才能跑。

**Comment by hengyunabc** [comment]
对比了下字节码，很可能是因为增强后的类因为 常量池扩展，要使用 `ldc_w`指令导致的。

**Comment by kylixs** [comment]
我有空看一下这个问题，看是否可以调试JVM找出根因

**Comment by kylixs** [comment]
在Java15上调试，定位<init>方法第85条指令: `168: astore        10` 校验失败，错误为：`Register 0 contains wrong type`
将栈顶的数据保存到局部变量index为10的操作类型不匹配，但由于缺少本地变量表（此类用javap -v 查看没有显示LocalVariableTable相关信息），需要结合arthas增强字节码的逻辑来判断。

```
         0: aload_0
         1: dup
         2: invokespecial #303                // Method com/asdffdsa/service/TestService."<init>":()V
         5: aload_0
         6: ldc           #2                  // class com/asdffdsa/service/TestService$$EnhancerBySpringCGLIB$$4a11960f
         8: ldc_w         #368                // String <init>|()V
        11: iconst_0
        12: anewarray     #91                 // class java/lang/Object
        15: astore        4
        17: astore_3
        18: astore_2
        19: astore_1
        20: aload_2
        21: aload_3
        22: aload_1
        23: aload         4
        25: invokestatic  #374                // Method java/arthas/SpyAPI.atEnter:(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/Object;[Ljava/lang/Object;)V
        28: goto          31
        31: aload_0
        32: ldc           #2                  // class com/asdffdsa/service/TestService$$EnhancerBySpringCGLIB$$4a11960f
        34: ldc_w         #376                // String com/asdffdsa/service/TestService$$EnhancerBySpringCGLIB$$4a11960f|CGLIB$BIND_CALLBACKS|(Ljava/lang/Object;)V|-1
        37: astore        18
        39: astore        17
        41: astore        16
        43: aload         17
        45: aload         18
        47: aload         16
        49: invokestatic  #380                // Method java/arthas/SpyAPI.atBeforeInvoke:(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/Object;)V
        52: goto          55
        55: invokestatic  #55                 // Method CGLIB$BIND_CALLBACKS:(Ljava/lang/Object;)V
        58: goto          96
        61: astore        10
        63: aload_0
        64: ldc           #2                  // class com/asdffdsa/service/TestService$$EnhancerBySpringCGLIB$$4a11960f
        66: ldc_w         #376                // String com/asdffdsa/service/TestService$$EnhancerBySpringCGLIB$$4a11960f|CGLIB$BIND_CALLBACKS|(Ljava/lang/Object;)V|-1
        69: aload         10
        71: astore        25
        73: astore        24
        75: astore        23
        77: astore        22
        79: aload         23
        81: aload         24
        83: aload         22
        85: aload         25
        87: invokestatic  #384                // Method java/arthas/SpyAPI.atInvokeException:(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Throwable;)V
        90: goto          93
        93: aload         10
        95: athrow
        96: aload_0
        97: ldc           #2                  // class com/asdffdsa/service/TestService$$EnhancerBySpringCGLIB$$4a11960f
        99: ldc_w         #376                // String com/asdffdsa/service/TestService$$EnhancerBySpringCGLIB$$4a11960f|CGLIB$BIND_CALLBACKS|(Ljava/lang/Object;)V|-1
       102: astore        21
       104: astore        20
       106: astore        19
       108: aload         20
       110: aload         21
       112: aload         19
       114: invokestatic  #387                // Method java/arthas/SpyAPI.atAfterInvoke:(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/Object;)V
       117: goto          120
       120: aload_0
       121: ldc           #2                  // class com/asdffdsa/service/TestService$$EnhancerBySpringCGLIB$$4a11960f
       123: ldc_w         #368                // String <init>|()V
       126: iconst_0
       127: anewarray     #91                 // class java/lang/Object
       130: aconst_null
       131: astore        9
       133: astore        8
       135: astore        7
       137: astore        6
       139: astore        5
       141: aload         6
       143: aload         7
       145: aload         5
       147: aload         8
       149: aload         9
       151: invokestatic  #391                // Method java/arthas/SpyAPI.atExit:(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/Object;[Ljava/lang/Object;Ljava/lang/Object;)V
       154: goto          157
       157: return
       158: athrow
       159: new           #75                 // class java/lang/reflect/UndeclaredThrowableException
       162: dup_x1
       163: swap
       164: invokespecial #78                 // Method java/lang/reflect/UndeclaredThrowableException."<init>":(Ljava/lang/Throwable;)V
       167: athrow
       168: astore        10	//<=== verfiy error: Register 0 contains wrong type
       170: aload_0
       171: ldc           #2                  // class com/asdffdsa/service/TestService$$EnhancerBySpringCGLIB$$4a11960f
       173: ldc_w         #368                // String <init>|()V
       176: iconst_0
       177: anewarray     #91                 // class java/lang/Object
       180: aload         10
       182: astore        15
       184: astore        14
       186: astore        13
       188: astore        12
       190: astore        11
       192: aload         12
       194: aload         13
       196: aload         11
       198: aload         14
       200: aload         15
       202: invokestatic  #395                // Method java/arthas/SpyAPI.atExceptionExit:(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/Object;[Ljava/lang/Object;Ljava/lang/Throwable;)V
       205: goto          208
       208: aload         10
       210: athrow
```

**Comment by kylixs** [comment]
最终发现是Exception table的try-catch block的范围不正确导致校验失败。
Spring Cglib生成的构造函数方法如下：
```
  public com.asdffdsa.service.TestService$$EnhancerBySpringCGLIB$$fe2946f8();
    descriptor: ()V
    flags: ACC_PUBLIC
    Code:
      stack=3, locals=1, args_size=1
         0: aload_0
         1: dup
         2: invokespecial #303                // Method com/asdffdsa/service/TestService."<init>":()V
         5: invokestatic  #55                 // Method CGLIB$BIND_CALLBACKS:(Ljava/lang/Object;)V
         8: return
         9: athrow
        10: new           #75                 // class java/lang/reflect/UndeclaredThrowableException
        13: dup_x1
        14: swap
        15: invokespecial #78                 // Method java/lang/reflect/UndeclaredThrowableException."<init>":(Ljava/lang/Throwable;)V
        18: athrow
      Exception table:
         from    to  target type
             0     9     9   Class java/lang/RuntimeException  //<=== from 为0
             0     9     9   Class java/lang/Error
             0     9    10   Class java/lang/Throwable
```
注意： Exception table 中3条try-catch block的起始位置(from)都是0。

接着看javac编译的普通抛出异常的构造函数的字节码：
```
  public com.alibaba.bytekit.asm.interceptor.SampleService();
    descriptor: ()V
    flags: ACC_PUBLIC
    Code:
      stack=3, locals=6, args_size=1
         0: aload_0
         1: invokespecial #15                 // Method com/alibaba/bytekit/asm/interceptor/TestService."<init>":()V
         4: aload_0
         5: invokestatic  #21                 // Method com/alibaba/bytekit/asm/interceptor/SampleServiceHolder.register:(Lcom/alibaba/bytekit/asm/interceptor/SampleService;)V
         8: goto          24
        11: astore_1
        12: aload_1
        13: athrow
        14: astore_1
        15: new           #23                 // class java/lang/reflect/UndeclaredThrowableException
        18: dup
        19: aload_1
        20: invokespecial #26                 // Method java/lang/reflect/UndeclaredThrowableException."<init>":(Ljava/lang/Throwable;)V
        23: athrow
        24: return
        25: astore_2
        26: aload_0
        27: ldc           #2                  // class com/alibaba/bytekit/asm/interceptor/SampleService
        29: aload_2
        30: astore        5
        32: astore        4
        34: astore_3
        35: aload         5
        37: aload_3
        38: aload         4
        40: invokestatic  #32                 // Method com/alibaba/bytekit/asm/interceptor/SpyAPI.atExceptionExit:(Ljava/lang/Throwable;Ljava/lang/Object;Ljava/lang/Class;)V
        43: goto          46
        46: aload_2
        47: athrow
      Exception table:
         from    to  target type
             4     8    11   Class java/lang/Error
             4     8    11   Class java/lang/RuntimeException
             4     8    14   Class java/lang/Throwable
             4    25    25   Class java/lang/Throwable
```
try-catch from为4，刚好是invokespecial  xxx <init>之后的指令，而不是从0开始。
Java语法规定构造函数的第一行必须是super()，try-catch是不能将super()包起来的。

修正try-catch block的范围后，class字节码校验通过：
```
      Exception table:
         from    to  target type
            55    61    61   Class java/lang/Throwable
            31   168   168   Class java/lang/Throwable
             5   158   158   Class java/lang/RuntimeException
             5   158   158   Class java/lang/Error
             5   158   159   Class java/lang/Throwable
```
相关pr： https://github.com/alibaba/bytekit/pull/4

**Comment by kylixs** [comment]
> * 同样测试了下 `trace com.asdffdsa.BackendApplication *`，这个也是会被spring aop增强，但出不会报错。

应为BackendApplication代理类的构造函数没有throw异常，Exception table为空，不会与Arthas增强字节码添加的try-catch block发生冲突。

**Comment by kylixs** [comment]
@scp114514810  麻烦测试一下
[arthas-bin.zip](https://github.com/alibaba/arthas/files/5926287/arthas-bin.zip)

**Comment by hengyunabc** [comment]
本质上是cglib的 UndeclaredThrowableStrategy 问题，spring官方也知道这个问题。在后续的版本里改用了别的方式来实现。

https://github.com/spring-projects/spring-framework/commit/9bd3a535cd524cf771423e67feeea523ac985f87

而 cglib项目本身已经不活跃了。。
