### ISSUE TITLE
使用dashboard命令卡主

### ISSUE THREAD

**Issue by RuvikVan** [alibaba/arthas#1700]
当我是用dashboard命令以后，一直卡主，没有反应。

**Comment by hengyunabc** [comment]
用 jstack 看下，具体卡在哪里

**Comment by RuvikVan** [comment]
"Thread-3" #16 prio=6 os_prio=0 tid=0x00007f11ec2d9800 nid=0x1126 in Object.wait() [0x00007f11d598e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076dc97d90> (a [I)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.commons.net.telnet.TelnetInputStream.read(TelnetInputStream.java:383)
	- locked <0x000000076dc97d90> (a [I)
	at org.apache.commons.net.telnet.TelnetInputStream.read(TelnetInputStream.java:526)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x000000076dc99ff0> (a java.io.BufferedInputStream)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x000000076df57298> (a java.io.InputStreamReader)
	at sun.nio.cs.StreamDecoder.read0(StreamDecoder.java:127)
	- locked <0x000000076df57298> (a java.io.InputStreamReader)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:112)
	at java.io.InputStreamReader.read(InputStreamReader.java:168)
	at com.taobao.arthas.client.IOUtil$2.run(IOUtil.java:47)


看了一下 好像是这个卡主了

**Comment by hengyunabc** [comment]
@RuvikVan 
上面貌似是 arthas-boot进程的栈。

看下应用进程的 jstack，看dashboard 命令执行的栈。

**Comment by RuvikVan** [comment]
和dashboard有关的线程都是RUNNABLE
找到一个命令执行一直waiting的

"arthas-command-execute" #49 daemon prio=5 os_prio=0 tid=0x00007f27380e2800 nid=0xd83 waiting on condition [0x00007f27643de000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000077da59048> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by hengyunabc** [comment]
@RuvikVan 试下用 `telnet localhost 3658` 连接，再执行 dashboard，看会不会卡住 ？

另外，这个是必现的不？

**Comment by RuvikVan** [comment]
我尝试了一下 一直是卡住了  这个是只有dashboard命令会卡住 其他不会。

**Comment by hengyunabc** [comment]
@RuvikVan 可能机器上有进程 listen 了 8006 端口，然后 dashboard command会尝试连接 8006端口去读 tomcat的信息。
检查下有没有 listen 8006 和相关的链接信息。

**Comment by hengyunabc** [comment]
@RuvikVan 可以执行 stop 之后，解压这个版本试下。设置了 timeout 时间，应该可以解决阻塞问题。

[arthas-bin.zip](https://github.com/alibaba/arthas/files/6014438/arthas-bin.zip)

**Comment by RuvikVan** [comment]
新版本这个问题解决了 谢谢
