### ISSUE TITLE
3.4.6版本Arthas http接口使用一段时间后无法使用

### ISSUE THREAD

**Issue by cc19931002** [alibaba/arthas#1704]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.4.6
* Arthas 版本:3.4.6
* 操作系统版本: 3.10.0-1062.18.1.el7.x86_64
* 目标进程的JVM版本: 1.8.0
* 执行`arthas-boot`的版本:1.4.6

### 异常日志
```
2021-02-23 07:00:21 [arthas-TermServer-1-1] ERROR c.t.a.c.s.t.i.h.api.HttpApiHandler -Exec command failed:null, command:thread
java.lang.NullPointerException: null
	at com.taobao.arthas.core.util.FileUtils.saveCommandHistoryString(FileUtils.java:161)
	at com.taobao.arthas.core.shell.history.impl.HistoryManagerImpl.saveHistory(HistoryManagerImpl.java:27)
	at com.taobao.arthas.core.shell.term.impl.http.api.HttpApiHandler.createJob(HttpApiHandler.java:589)
	at com.taobao.arthas.core.shell.term.impl.http.api.HttpApiHandler.processExecRequest(HttpApiHandler.java:401)
	at com.taobao.arthas.core.shell.term.impl.http.api.HttpApiHandler.dispatchRequest(HttpApiHandler.java:249)
	at com.taobao.arthas.core.shell.term.impl.http.api.HttpApiHandler.processRequest(HttpApiHandler.java:230)
	at com.taobao.arthas.core.shell.term.impl.http.api.HttpApiHandler.handle(HttpApiHandler.java:95)
	at com.taobao.arthas.core.shell.term.impl.http.HttpRequestHandler.channelRead0(HttpRequestHandler.java:80)
	at com.taobao.arthas.core.shell.term.impl.http.HttpRequestHandler.channelRead0(HttpRequestHandler.java:39)
	at com.alibaba.arthas.deps.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:59)
	at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:368)
	at com.alibaba.arthas.deps.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at com.alibaba.arthas.deps.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at com.alibaba.arthas.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at com.alibaba.arthas.deps.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at com.alibaba.arthas.deps.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at com.alibaba.arthas.deps.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hengyunabc** [comment]
参考这个： https://github.com/alibaba/termd/issues/44
