### ISSUE TITLE
arthas 启动时oom 

### ISSUE THREAD

**Issue by totalo** [alibaba/arthas#1728]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 的版本： 3.4.5
* Arthas 版本: 3.4.5
* 操作系统版本: 3.18.6-2.el7.centos.x86_64 #1 SMP Mon Oct 24 13:01:33 CST 2016 x86_64 x86_64 x86_64 GNU/Linux
* 目标进程的JVM版本: openjdk version "1.8.0_202"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.202-b08, mixed mode)
* 执行`arthas-boot`的版本: 3.4.5

### 重现问题的步骤

1. java -jar arthas-boot.jar 

### 期望的结果

What do you expected from the above steps？
正常启动

### 实际运行的结果

arthas.log如下，产生oom

```
2021-03-08 10:39:43 [arthas-binding-thread] INFO  c.t.arthas.core.util.ArthasBanner -Current arthas version: 3.4.8, recommend latest version: 3.4.8
2021-03-08 10:39:43 [arthas-binding-thread] INFO  c.t.arthas.core.util.ArthasBanner -Current arthas version: 3.4.8, recommend latest version: 3.4.8
2021-03-08 10:39:51 [arthas-NettyHttpTelnetBootstrap-3-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x24584a9f] REGISTERED
2021-03-08 10:39:51 [arthas-NettyHttpTelnetBootstrap-3-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x24584a9f] BIND: /127.0.0.1:3658
2021-03-08 10:39:51 [arthas-NettyHttpTelnetBootstrap-3-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x24584a9f, L:/127.0.0.1:3658] ACTIVE
2021-03-08 10:39:51 [arthas-NettyWebsocketTtyBootstrap-4-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0xb0ed424e] REGISTERED
2021-03-08 10:39:51 [arthas-NettyWebsocketTtyBootstrap-4-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0xb0ed424e] BIND: /127.0.0.1:8563
2021-03-08 10:39:51 [arthas-NettyWebsocketTtyBootstrap-4-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0xb0ed424e, L:/127.0.0.1:8563] ACTIVE
2021-03-08 10:39:51 [arthas-NettyWebsocketTtyBootstrap-4-2] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x553f0604] REGISTERED
2021-03-08 10:39:51 [arthas-NettyWebsocketTtyBootstrap-4-2] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x553f0604] BIND: local:arthas-netty-localaddress
2021-03-08 10:39:51 [arthas-NettyWebsocketTtyBootstrap-4-2] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x553f0604, L:local:arthas-netty-localaddress] ACTIVE
2021-03-08 10:40:11 [arthas-binding-thread] ERROR c.t.a.core.server.ArthasBootstrap -Error during start as-server
java.lang.OutOfMemoryError: Java heap space
2021-03-08 10:40:13 [arthas-NettyHttpTelnetBootstrap-3-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x24584a9f, L:/127.0.0.1:3658] INACTIVE
2021-03-08 10:40:16 [arthas-NettyHttpTelnetBootstrap-3-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x24584a9f, L:/127.0.0.1:3658] UNREGISTERED
2021-03-08 10:40:27 [arthas-NettyWebsocketTtyBootstrap-4-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0xb0ed424e, L:/127.0.0.1:8563] CLOSE
2021-03-08 10:40:27 [arthas-NettyWebsocketTtyBootstrap-4-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0xb0ed424e, L:/127.0.0.1:8563] INACTIVE
2021-03-08 10:40:27 [arthas-NettyWebsocketTtyBootstrap-4-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0xb0ed424e, L:/127.0.0.1:8563] UNREGISTERED
2021-03-08 10:40:27 [arthas-NettyWebsocketTtyBootstrap-4-2] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x553f0604, L:local:arthas-netty-localaddress] INACTIVE
2021-03-08 10:40:27 [arthas-NettyWebsocketTtyBootstrap-4-2] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x553f0604, L:local:arthas-netty-localaddress] UNREGISTERED
2021-03-08 10:40:51 [arthas-binding-thread] INFO  c.t.a.core.server.ArthasBootstrap -as-server destroy completed.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.taobao.arthas.agent334.AgentBootstrap.bind(AgentBootstrap.java:182)
	at com.taobao.arthas.agent334.AgentBootstrap.access$000(AgentBootstrap.java:20)
	at com.taobao.arthas.agent334.AgentBootstrap$1.run(AgentBootstrap.java:152)
Caused by: java.lang.OutOfMemoryError: Java heap space
Arthas server agent start...
2021-03-08 10:42:46 [arthas-binding-thread] INFO  c.t.arthas.core.util.ArthasBanner -Current arthas version: 3.4.8, recommend latest version: 3.4.8
2021-03-08 10:42:46 [arthas-binding-thread] INFO  c.t.arthas.core.util.ArthasBanner -Current arthas version: 3.4.8, recommend latest version: 3.4.8
2021-03-08 10:42:53 [arthas-NettyHttpTelnetBootstrap-3-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x2b66e80f] REGISTERED
2021-03-08 10:42:53 [arthas-NettyHttpTelnetBootstrap-3-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x2b66e80f] BIND: /127.0.0.1:3658
2021-03-08 10:42:53 [arthas-NettyHttpTelnetBootstrap-3-1] IN
```

**Comment by hengyunabc** [comment]
1. 使用最新版本 3.4.8
2. 检查下应用本身是不是快 oom了。启动arthas本身也是要消耗内存的。

**Comment by totalo** [comment]
应该是快oom了，我换了台机器，就好了，感谢~
