### ISSUE TITLE
Attach进程时报错Non-zero decimal digits:{0}和IO异常(There is not enough space in the file system)

### ISSUE THREAD

**Issue by programmerlc** [alibaba/arthas#1731]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4.8
* Arthas 版本: 3.4.8
* 操作系统版本: Aix7.1
* 目标进程的JVM版本: IBM JDK1.6.0(IBM J9 VM)
* 执行`arthas-boot`的版本: IBM JDK1.6.0(IBM J9 VM)

### 重现问题的步骤

1. 在Aix7.1的机器上安装arthas3.4.8
2. IBM WebSphere容器中运行有多个java应用进程
3. 用启动IBM WebSphere中Java进程的IBM JDK1.6.0执行java -jar arthas-boot <pid>去attach到某一websphere的java进程
4. attach失败，打印报错信息

### 期望的结果

attach success，进入arthas控制台

### 实际运行的结果

报错:AttachNotSupportedException、IOException和NullPointException
```
[INFO] arthas-boot version: 3.4.8
[INFO] arthas home: /home/wasadmin/lightops/lightops_agent/arthas
[INFO] Try to attach process 13959360
com.ibm.tools.attach.AttachNotSupportedException: Non-zero decimal digits: {0}
        at com.ibm.tools.attach.javaSE.VirtualMachineImpl.tryAttachTarget(VirtualMachineImpl.java:360)
        at com.ibm.tools.attach.javaSE.VirtualMachineImpl.attachTarget(VirtualMachineImpl.java:94)
        at com.ibm.tools.attach.javaSE.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:37)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:262)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:91)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:26)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:129)
Caused by: java.io.IOException: There is not enough space in the file system.
        at java.io.RandomAccessFile.writeBytes(RandomAccessFile.java:1079)
        at com.ibm.tools.attach.javaSE.Reply.writeReply(Reply.java:64)
        at com.ibm.tools.attach.javaSE.VirtualMachineImpl.tryAttachTarget(VirtualMachineImpl.java:354)
        ... 6 more
[ERROR] Start arthas failed, exception stack trace:
java.lang.NullPointerException
        at ibm.tools.attach.J9VirtualMachine.detach(J9VirtualMachine.java:104)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:114)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:26)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:129)
[INFO] Attach process 13959360 success.
[INFO] arthas-client connect 0.0.0.0 12212
Connect to telnet server error: 0.0.0.0 12212
java.net.ConnectException: A remote host refused an attempted connect operation.
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:412)
        at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:269)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:258)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:376)
        at java.net.Socket.connect(Socket.java:546)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
        at com.taobao.arthas.client.TelnetConsole.process(TelnetConsole.java:309)
        at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:166)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
        at java.lang.reflect.Method.invoke(Method.java:611)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:566)
Usage: arthas-client [--help] [-c <value>] [-f <value>] [-t <value>] [-w
       <value>] [-h <value>] [target-ip] [port]
```

**Comment by hengyunabc** [comment]
没有测试过ibm jvm，不能保证支持。
