### ISSUE TITLE
Arthas在Kali无法启动

### ISSUE THREAD

**Issue by WillieMatthewLiu** [alibaba/arthas#1773]
### 环境信息

* Arthas 版本: 3.5.0
* 操作系统版本: Kali Linux 2021.1

### 重现问题的步骤
oot@ok2kali:~/logs/arthas# as.sh --telent-port -1 --http-port -1
Arthas script version: 3.5.0
[INFO] JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
lsof: unknown service -1 for tcp in: -i TCP:-1
lsof 4.93.2
 latest revision: https://github.com/lsof-org/lsof
 latest FAQ: https://github.com/lsof-org/lsof/blob/master/00FAQ
 latest (non-formatted) man page: https://github.com/lsof-org/lsof/blob/master/Lsof.8
 usage: [-?abhKlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-E] [+|-e s] [+|-f[gG]]
 [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+m [m]] [+|-M] [-o [o]] [-p s]
 [+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]
Use the ``-h'' option to get more help information.
Arthas home: /root/.arthas/lib/3.5.0/arthas
Calculating attach execution time...
Attaching to --telent-port using version /root/.arthas/lib/3.5.0/arthas...
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
[ERROR] Start arthas failed, exception stack trace: 
com.taobao.middleware.cli.InvalidValueException: The value '--telent-port' is not accepted by 'pid'
        at com.taobao.middleware.cli.impl.DefaultCommandLine.create(DefaultCommandLine.java:342)
        at com.taobao.middleware.cli.impl.DefaultCommandLine.getValue(DefaultCommandLine.java:267)
        at com.taobao.middleware.cli.impl.DefaultCommandLine.getOptionValue(DefaultCommandLine.java:91)
        at com.taobao.arthas.core.Arthas.parse(Arthas.java:57)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:26)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:137)
Caused by: java.lang.IllegalArgumentException: java.lang.NumberFormatException: For input string: "--telent-port"
        at com.taobao.middleware.cli.converters.ConstructorBasedConverter.fromString(ConstructorBasedConverter.java:70)
        at com.taobao.middleware.cli.converters.Converters.create(Converters.java:52)
        at com.taobao.middleware.cli.impl.DefaultCommandLine.create(DefaultCommandLine.java:339)
        ... 5 more
Caused by: java.lang.NumberFormatException: For input string: "--telent-port"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Long.parseLong(Long.java:692)
        at java.base/java.lang.Long.<init>(Long.java:1317)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.taobao.middleware.cli.converters.ConstructorBasedConverter.fromString(ConstructorBasedConverter.java:67)
        ... 7 more

real    0m0.087s
user    0m0.055s
sys     0m0.072s
attach to target jvm (--telent-port) failed, check /root/logs/arthas/arthas.log or stderr of target jvm for any exceptions.

**Comment by hengyunabc** [comment]
拼写错了： `--telent-port` 

应该是这： `--telnet-port`
