### ISSUE TITLE
Agent JAR not found or no Agent-Class attribute

### ISSUE THREAD

**Issue by fengyouliang** [alibaba/arthas#1803]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.1
* Arthas 版本: 3.5.1
* 操作系统版本: centos7
* 目标进程的JVM版本: OpenJDK 14.0.2
* 执行`arthas-boot`的版本: 3.5.1

### 重现问题的步骤

我是直接运行以下命令的

```
curl -O https://arthas.aliyun.com/arthas-boot.jar
java -jar arthas-boot.jar
```

```
* [1]: 28974 org.apache.catalina.startup.Bootstrap
  [2]: 29087 qunar.tc.bistoury.indpendent.agent.Main
```
选择2，arthas正常运行；选择1，arthas报错

### 期望的结果

正常使用Arthas

### 实际运行的结果

```
# java -jar arthas-boot.jar
[INFO] arthas-boot version: 3.5.1
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 28974 org.apache.catalina.startup.Bootstrap
  [2]: 29087 qunar.tc.bistoury.indpendent.agent.Main
1
[INFO] arthas home: /root/.arthas/lib/3.5.1/arthas
[INFO] Try to attach process 28974
[ERROR] Start arthas failed, exception stack trace: 
com.sun.tools.attach.AgentLoadException: Agent JAR not found or no Agent-Class attribute
        at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:159)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:118)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:26)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:137)
[INFO] Attach process 28974 success.
[INFO] arthas-client connect 127.0.0.1 3658
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:589)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
        at java.base/java.net.Socket.connect(Socket.java:648)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
        at com.taobao.arthas.client.TelnetConsole.process(TelnetConsole.java:309)
        at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:166)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:595)
Usage: arthas-client [--help] [-c <value>] [-f <value>] [-w <value>] [-t
       <value>] [-h <value>] [target-ip] [port]

Arthas Telnet Client

EXAMPLES:
  java -jar arthas-client.jar 127.0.0.1 3658
  java -jar arthas-client.jar -c 'dashboard -n 1'
  java -jar arthas-client.jar -f batch.as 127.0.0.1

Options and Arguments:
    --help                        Print usage
 -c,--command <value>             Command to execute, multiple commands
                                  separated by ;
 -f,--batch-file <value>          The batch file to execute
 -w,--width <value>               The terminal width
 -t,--execution-timeout <value>   The timeout (ms) of execute commands or batch
                                  file
 -h,--height <value>              The terminal height
 <target-ip>                      Target ip
 <port>                           The remote server port

```

**Comment by hengyunabc** [comment]
可能网络问题，下载arthas zip失败，或者不完整。可以下载全量包，解压使用。 https://arthas.aliyun.com/doc/download.html

**Comment by fengyouliang** [comment]
> 可能网络问题，下载arthas zip失败，或者不完整。可以下载全量包，解压使用。 https://arthas.aliyun.com/doc/download.html

发现了，是用户的问题，tomcat和arthas在不同用户下运行导致的。

PS:一个进程可以，一个不行，这会是包不完整的问题吗？

**Comment by xinxinClean** [comment]
这个如何解决呢

**Comment by fengyouliang** [comment]
> 这个如何解决呢

用同一个用户运行arthas和target app就行
