### ISSUE TITLE
enableDetatilPages字段拼写错误

### ISSUE THREAD

**Issue by aresLD** [alibaba/arthas#1806]
### 环境信息

* Arthas 版本:3.5.1

### 重现问题的步骤

见com.alibaba.arthas.tunnel.server.app.configuration.ArthasProperties类

### 期望的结果

enableDetatilPages->enableDetailPages

**Comment by hengyunabc** [comment]
😂，欢迎提PR修复

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/pull/1807

**Comment by dynastqin** [comment]
使用java -jar arthas-tunnel-server-xxx-fatjar.jar连接远程agent时可能出现如下异常java.lang.IllegalAccessError: not allow，详细如下：
`
 [Handler dispatch failed; nested exception is java.lang.IllegalAccessError: not allow] with root cause

java.lang.IllegalAccessError: not allow
	at com.alibaba.arthas.tunnel.server.app.web.DetailAPIController.tunnelApps(DetailAPIController.java:45) ~[classes!/:3.6.7]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
`
可考虑如下方式启动跳过校验
java -jar arthas-tunnel-server-xxx-fatjar.jar --arthas.enableDetailPages=true
