### ISSUE TITLE
elasticsearch环境下使用arthas跑不起来

### ISSUE THREAD

**Issue by qi20088** [alibaba/arthas#1846]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4.5
* Arthas 版本:  3.4.5
* 操作系统版本: xxx
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本:  3.4.5
* ES版本：5.6.4

### 实际运行的结果
[es@host-10-10-10-155 local]$ ./as.sh 
Arthas script version: 3.4.5
[INFO] JAVA_HOME: /usr/java/jdk1.8.0_152
Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 23048 org.elasticsearch.bootstrap.Elasticsearch
1
Arthas home: /usr/local
Calculating attach execution time...
Attaching to 23048 using version /usr/local...

real	0m1.506s
user	0m0.286s
sys	0m0.038s
Attach success.
telnet connecting to arthas server... current timestamp is 1625666153
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
bash: /opt/usermonitor/usermonitor.out: Permission denied

详细的日志，异常栈。
Arthas server agent start...
2021-07-07 21:51:26 [arthas-binding-thread] INFO  c.t.arthas.core.util.ArthasBanner -Current arthas version: 3.4.5, recommend latest version: 3.5.2
2021-07-07 21:51:27 [arthas-binding-thread] INFO  c.t.arthas.core.util.ArthasBanner -Current arthas version: 3.4.5, recommend latest version: 3.5.2
2021-07-07 21:51:27 [arthas-NettyHttpTelnetBootstrap-3-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x961964d3] REGISTERED
2021-07-07 21:51:27 [arthas-NettyHttpTelnetBootstrap-3-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x961964d3] BIND: /127.0.0.1:3658
2021-07-07 21:51:27 [arthas-NettyHttpTelnetBootstrap-3-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x961964d3] CLOSE
2021-07-07 21:51:27 [arthas-NettyHttpTelnetBootstrap-3-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x961964d3] UNREGISTERED
2021-07-07 21:51:27 [arthas-binding-thread] ERROR c.t.a.c.s.t.i.h.HttpTelnetTermServer -Error listening to port 3658
java.security.AccessControlException: access denied ("java.net.SocketPermission" "localhost:3658" "listen,resolve")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkListen(SecurityManager.java:1131)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:221)
        at com.alibaba.arthas.deps.io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:550)
        at com.alibaba.arthas.deps.io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:504)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:489)
        at com.alibaba.arthas.deps.io.netty.handler.logging.LoggingHandler.bind(LoggingHandler.java:221)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:504)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:489)
        at com.alibaba.arthas.deps.io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannel.bind(AbstractChannel.java:248)
        at com.alibaba.arthas.deps.io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
        at com.alibaba.arthas.deps.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at com.alibaba.arthas.deps.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at com.alibaba.arthas.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at com.alibaba.arthas.deps.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at com.alibaba.arthas.deps.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at com.alibaba.arthas.deps.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
2021-07-07 21:51:27 [arthas-NettyWebsocketTtyBootstrap-4-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x5e4272cc] REGISTERED
2021-07-07 21:51:27 [arthas-NettyWebsocketTtyBootstrap-4-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x5e4272cc] BIND: /127.0.0.1:8563
2021-07-07 21:51:27 [arthas-NettyWebsocketTtyBootstrap-4-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x5e4272cc] CLOSE
2021-07-07 21:51:27 [arthas-NettyWebsocketTtyBootstrap-4-1] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0x5e4272cc] UNREGISTERED
2021-07-07 21:51:27 [arthas-binding-thread] ERROR c.t.a.c.s.term.impl.HttpTermServer -Error listening to port 8563
java.security.AccessControlException: access denied ("java.net.SocketPermission" "localhost:8563" "listen,resolve")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkListen(SecurityManager.java:1131)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:221)
        at com.alibaba.arthas.deps.io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:550)
        at com.alibaba.arthas.deps.io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:504)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:489)
        at com.alibaba.arthas.deps.io.netty.handler.logging.LoggingHandler.bind(LoggingHandler.java:221)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:504)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:489)
        at com.alibaba.arthas.deps.io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannel.bind(AbstractChannel.java:248)
        at com.alibaba.arthas.deps.io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
        at com.alibaba.arthas.deps.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at com.alibaba.arthas.deps.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at com.alibaba.arthas.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at com.alibaba.arthas.deps.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at com.alibaba.arthas.deps.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at com.alibaba.arthas.deps.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
2021-07-07 21:51:27 [arthas-binding-thread] ERROR c.t.a.c.shell.handlers.BindHandler -Error listening term server:
java.security.AccessControlException: access denied ("java.net.SocketPermission" "localhost:8563" "listen,resolve")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkListen(SecurityManager.java:1131)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:221)
        at com.alibaba.arthas.deps.io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:550)
        at com.alibaba.arthas.deps.io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:504)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:489)
        at com.alibaba.arthas.deps.io.netty.handler.logging.LoggingHandler.bind(LoggingHandler.java:221)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:504)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:489)
        at com.alibaba.arthas.deps.io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannel.bind(AbstractChannel.java:248)
        at com.alibaba.arthas.deps.io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
        at com.alibaba.arthas.deps.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at com.alibaba.arthas.deps.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at com.alibaba.arthas.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at com.alibaba.arthas.deps.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at com.alibaba.arthas.deps.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at com.alibaba.arthas.deps.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
2021-07-07 21:51:27 [arthas-NettyWebsocketTtyBootstrap-4-2] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0xa9df139e] REGISTERED
2021-07-07 21:51:27 [arthas-NettyWebsocketTtyBootstrap-4-2] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0xa9df139e] BIND: local:arthas-netty-localaddress
2021-07-07 21:51:27 [arthas-NettyWebsocketTtyBootstrap-4-2] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0xa9df139e, L:local:arthas-netty-localaddress] ACTIVE
2021-07-07 21:51:27 [arthas-NettyWebsocketTtyBootstrap-4-2] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0xa9df139e, L:local:arthas-netty-localaddress] INACTIVE
2021-07-07 21:51:27 [arthas-NettyWebsocketTtyBootstrap-4-2] INFO  c.a.a.d.i.n.h.logging.LoggingHandler -[id: 0xa9df139e, L:local:arthas-netty-localaddress] UNREGISTERED
2021-07-07 21:51:27 [arthas-binding-thread] ERROR c.t.a.core.server.ArthasBootstrap -Error during start as-server
java.lang.IllegalStateException: Arthas failed to bind telnet or http port.
        at com.taobao.arthas.core.server.ArthasBootstrap.bind(ArthasBootstrap.java:404)
        at com.taobao.arthas.core.server.ArthasBootstrap.<init>(ArthasBootstrap.java:141)
        at com.taobao.arthas.core.server.ArthasBootstrap.getInstance(ArthasBootstrap.java:534)
        at com.taobao.arthas.core.server.ArthasBootstrap.getInstance(ArthasBootstrap.java:522)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.taobao.arthas.agent334.AgentBootstrap.bind(AgentBootstrap.java:182)
        at com.taobao.arthas.agent334.AgentBootstrap.access$000(AgentBootstrap.java:20)
        at com.taobao.arthas.agent334.AgentBootstrap$1.run(AgentBootstrap.java:152)
2021-07-07 21:51:27 [arthas-binding-thread] INFO  c.t.a.core.server.ArthasBootstrap -as-server destroy completed.
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.taobao.arthas.agent334.AgentBootstrap.bind(AgentBootstrap.java:182)
        at com.taobao.arthas.agent334.AgentBootstrap.access$000(AgentBootstrap.java:20)
        at com.taobao.arthas.agent334.AgentBootstrap$1.run(AgentBootstrap.java:152)
Caused by: java.lang.IllegalStateException: Arthas failed to bind telnet or http port.
        at com.taobao.arthas.core.server.ArthasBootstrap.bind(ArthasBootstrap.java:404)
        at com.taobao.arthas.core.server.ArthasBootstrap.<init>(ArthasBootstrap.java:141)
        at com.taobao.arthas.core.server.ArthasBootstrap.getInstance(ArthasBootstrap.java:534)
        at com.taobao.arthas.core.server.ArthasBootstrap.getInstance(ArthasBootstrap.java:522)
        ... 7 more

**Comment by hengyunabc** [comment]
最简单办法是把es的jvm安全配置去掉 😂

**Comment by hengyunabc** [comment]
参考： https://github.com/alibaba/arthas/issues/156
