### ISSUE TITLE
使用mc命令时候@Valid注解会报错

### ISSUE THREAD

**Issue by WANGLULU9802** [alibaba/arthas#1862]
具体报错信息，大神求教！
2021-07-15 21:19:39 [arthas-command-execute] WARN  c.t.a.c.c.k.MemoryCompilerCommand -Memory compiler error
com.taobao.arthas.compiler.DynamicCompilerException: Compilation Error
line: 105 , message: javax.validation.Valid is not a repeatable annotation type , 
line: 165 , message: javax.validation.Valid is not a repeatable annotation type , 
line: 180 , message: javax.validation.Valid is not a repeatable annotation type , 
line: 195 , message: javax.validation.Valid is not a repeatable annotation type , 

        at com.taobao.arthas.compiler.DynamicCompiler.buildByteCodes(DynamicCompiler.java:132)
        at com.taobao.arthas.core.command.klass100.MemoryCompilerCommand.process(MemoryCompilerCommand.java:137)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by MissingNone** [comment]
报错说得很清楚了，根据报错信息看你要编译的java文件中同一个位置重复使用了多个@Valid，去掉多余的就可以了.

**Comment by MissingNone** [comment]
报错说得很清楚了，根据报错信息看你要编译的java文件中同一个位置重复使用了多个@Valid，去掉多余的就可以了。

**Comment by hengyunabc** [comment]
https://arthas.aliyun.com/doc/mc  ， mc 不保证成功，可以本地编译后上传。
