### ISSUE TITLE
CPU使用率很高，但线程堆栈都是在park

### ISSUE THREAD

**Issue by soocold** [alibaba/arthas#1917]
Threads Total: 588, NEW: 0, RUNNABLE: 68, BLOCKED: 0, WAITING: 404, TIMED_WAITIN
G: 116, TERMINATED: 0        
CPU使用率使用率最高的几个线程堆栈：
"pool-thread-1" Id=1234 cpuUsage=3% WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1dc24107
    at sun.misc.Unsafe.park(Native Method)
    -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1dc24107
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
    at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)

"pool-thread-6" Id=12345cpuUsage=2% WAITING on java.util.concurrent.locks.ReentrantLock$NonfairSync@335e0479
    at sun.misc.Unsafe.park(Native Method)
    -  waiting on java.util.concurrent.locks.ReentrantLock$NonfairSync@335e0479
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireInterruptibly(AbstractQueuedSynchronizer.java:897)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1222)
    at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)

请问这个情况是哪个地方占用了CPU呢？正常park不应该不占用CPU吗？

**Comment by hengyunabc** [comment]
这个是juc的锁，只能说明某个用了juc的类库被很高频调用。用profiler生成火焰图，再看具体的应用热点在哪里。
