### ISSUE TITLE
watch 命令 出现 class redefinition failed: attempted to delete a method

### ISSUE THREAD

**Issue by futureLidong** [alibaba/arthas#1966]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.4
* Arthas 版本: 3.5.4
* 操作系统版本: Red Hat 4.8.5-39
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.5.4

### 重现问题的步骤

1.java -jar arthas-boot.jar 进入arthas界面
2. watch com.lid.XXX.XXController  method  
3. 报错java.lang.UnsupportedOperationException: class redefinition failed: attempted to delete a method

### 期望的结果

找到原因解决问题

### 实际运行的结果

java.lang.UnsupportedOperationException: class redefinition failed: attempted to delete a method
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:396)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:168)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:115)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
        at com.netease.dsf2.tracer.core.async.TracerRunnable.run(TracerRunnable.java:49)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by hengyunabc** [comment]
参考： https://github.com/alibaba/arthas/issues?q=label%3Aquestion-answered+UnsupportedOperationException%3A+class+redefinition+failed%3A+is%3Aclosed
