### ISSUE TITLE
attach fail

### ISSUE THREAD

**Issue by littledotdot** [alibaba/arthas#2072]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar： 3.5.4
* Arthas 版本: xxx
* 操作系统版本: linux
* 目标进程的JVM版本: 1.6
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. 下载
2. 启动

### 期望的结果

正常使用

### 实际运行的结果

[weblogic@b2b-90 ~]$ java -jar arthas-boot.jar
[INFO] arthas-boot version: 3.5.4
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 15477 weblogic.Server
1
[INFO] arthas home: /home/weblogic/.arthas/lib/3.5.4/arthas
[INFO] Try to attach process 15477
[ERROR] Start arthas failed, exception stack trace: 
java.io.IOException: Premature EOF
	at sun.tools.attach.HotSpotVirtualMachine.readInt(HotSpotVirtualMachine.java:226)
	at sun.tools.attach.LinuxVirtualMachine.execute(LinuxVirtualMachine.java:175)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:40)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:62)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:85)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:120)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:27)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:139)
[ERROR] attach fail, targetPid: 15477

```
[ERROR] Start arthas failed, exception stack trace: 
java.io.IOException: Premature EOF
	at sun.tools.attach.HotSpotVirtualMachine.readInt(HotSpotVirtualMachine.java:226)
	at sun.tools.attach.LinuxVirtualMachine.execute(LinuxVirtualMachine.java:175)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:40)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:62)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:85)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:120)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:27)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:139)
[ERROR] attach fail, targetPid: 15477
```

**Comment by hengyunabc** [comment]
在 issue里可以搜下关键字  readInt 或者 weblogic

**Comment by littledotdot** [comment]
> 在 issue 里可以搜下关键字 readInt 或者 weblogic

实际上 同样的环境 我再win10 下是正常使用  可能与weblogic关系不大。查看了 其他的issue 没有明确的解决方法

**Comment by LALAnimeimei** [comment]
我也遇到这个问题了，我的稳定复现，原因是传递的properties参数太长
不排除还有网络问题或者防火墙的问题
