### ISSUE TITLE
arthas attach 失败

### ISSUE THREAD

**Issue by wujunbin** [alibaba/arthas#2088]
失败日志如下
`Arthas server agent start...
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.taobao.arthas.agent334.AgentBootstrap.bind(AgentBootstrap.java:182)
	at com.taobao.arthas.agent334.AgentBootstrap.access$000(AgentBootstrap.java:20)
	at com.taobao.arthas.agent334.AgentBootstrap$1.run(AgentBootstrap.java:152)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.taobao.arthas.common.AnsiLog
	at com.taobao.arthas.core.util.LogUtil.initLooger(LogUtil.java:59)
	at com.taobao.arthas.core.server.ArthasBootstrap.<init>(ArthasBootstrap.java:147)
	at com.taobao.arthas.core.server.ArthasBootstrap.getInstance(ArthasBootstrap.java:577)
	at com.taobao.arthas.core.server.ArthasBootstrap.getInstance(ArthasBootstrap.java:565)
	... 7 more`

**Comment by hengyunabc** [comment]
这个有点诡异，看起来是初始化`com.taobao.arthas.common.AnsiLog`时出错了。 检查下应用的标准输出，看下有没有具体的异常信息。

**Comment by xubin2016** [comment]
同遇到这个问题～官网下载 sftp搞到内网虚机 启动报这个错。启动命令: ./as.sh --attach-only @0.0.0.0:${port}:${port1}

**Comment by hengyunabc** [comment]
@xubin2016 试下可以debug不？ 参考： https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md#debug-1

**Comment by 15324657850** [comment]
com.sun.tools.attach.AttachOperationFailedException: java.lang.NoClassDefFoundError: Could not initialize class sun.util.calendar.ZoneInfoFile
这个有遇到过吗
