### ISSUE TITLE
monitor、watch、trace相关无法使用

### ISSUE THREAD

**Issue by jlynet** [alibaba/arthas#2106]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.5
* Arthas 版本: 3.5.5
* 操作系统版本: linux
* 目标进程的JVM版本: 
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
* 执行`arthas-boot`的版本: 3.5.5

### 重现问题的步骤

1. xxx
2. xxx
3. xxx

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

[arthas@47054]$ trace com.xxx.xxx.web.ee.controller.scenefacing.xxx.H5OrderGoodsController processingPage
Affect(class count: 1 , method count: 1) cost in 87 ms, listenerId: 11
Enhance error! exception: java.lang.ClassFormatError
error happens when enhancing class: null, check arthas log: /app/xx/logs/arthas/arthas.log

```
2022-02-14 12:06:38 [arthas-command-execute] INFO  c.t.arthas.core.advisor.Enhancer -enhance matched classes: [class com.xxx.xxx.web.ee.controller.scenefacing.xxx.H5OrderGoodsController]
2022-02-14 12:06:38 [arthas-command-execute] ERROR c.t.arthas.core.advisor.Enhancer -Enhancer error, matchingClasses: [class com.xxx.xxx.web.ee.controller.scenefacing.xxx.H5OrderGoodsController]
java.lang.ClassFormatError: null
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:396)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:162)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:109)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by hengyunabc** [comment]
参考这个： https://github.com/alibaba/arthas/issues/1847#issuecomment-875726607 ， dump 字节码后分析下。
