### ISSUE TITLE
启动arthas之后，输入dashboard报错：process dashboard failed: Memory Pool not found

### ISSUE THREAD

**Issue by Oliverwqcwrw** [alibaba/arthas#2120]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.5.5
* 操作系统版本: Centos 7
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 1.8

### 重现问题的步骤

1. 启动arthas
2. 输入dashboard
3. 出现process dashboard failed: Memory Pool not found

### 期望的结果

What do you expected from the above steps？
展示结果信息

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里

process dashboard failed: Memory Pool not found

**Comment by Oliverwqcwrw** [comment]
2022-03-02 17:53:21 [Timer-for-arthas-dashboard-f0c465a6-0736-4d7f-a507-4a24a3df493b] ERROR c.t.a.c.c.m.DashboardCommand -proc
ess dashboard failed: Memory Pool not found
java.lang.InternalError: Memory Pool not found
        at sun.management.MemoryPoolImpl.getUsage0(Native Method)
        at sun.management.MemoryPoolImpl.getUsage(MemoryPoolImpl.java:96)
        at com.taobao.arthas.core.command.monitor200.DashboardCommand.addMemoryInfo(DashboardCommand.java:161)
        at com.taobao.arthas.core.command.monitor200.DashboardCommand.access$200(DashboardCommand.java:57)
        at com.taobao.arthas.core.command.monitor200.DashboardCommand$DashboardTimerTask.run(DashboardCommand.java:316)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

**Comment by Oliverwqcwrw** [comment]
确实是jdk的bug

**Comment by Oliverwqcwrw** [comment]
知道问题了，系统剩余内存只有300M了，然后输入dashboard之后就报错了，加了1G内存之后没有问题了
