### ISSUE TITLE
linux安装后启动有问题 sh as.sh

### ISSUE THREAD

**Issue by arzes** [alibaba/arthas#215]
01 2018-10-11 17:33:08.453 ERROR [arthas-binding-thread:arthas] [] [] [] Error during bind to port 3658
java.lang.ExceptionInInitializerError: null
        at com.taobao.arthas.core.shell.ShellServerOptions.<clinit>(ShellServerOptions.java:29) ~[na:na]
        at com.taobao.arthas.core.server.ArthasBootstrap.bind(ArthasBootstrap.java:82) ~[arthas-core.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
        at com.taobao.arthas.agent.AgentBootstrap.bind(AgentBootstrap.java:158) [arthas-agent.jar:na]
        at com.taobao.arthas.agent.AgentBootstrap.access$000(AgentBootstrap.java:15) [arthas-agent.jar:na]
        at com.taobao.arthas.agent.AgentBootstrap$1.run(AgentBootstrap.java:125) [arthas-agent.jar:na]
Caused by: java.lang.NullPointerException: null
        at java.io.Reader.<init>(Reader.java:78) ~[na:1.8.0_181]
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72) ~[na:1.8.0_181]
        at com.taobao.arthas.core.util.IOUtils.toString(IOUtils.java:134) ~[arthas-core.jar:na]
        at com.taobao.arthas.core.util.ArthasBanner.<clinit>(ArthasBanner.java:33) ~[na:na]
        ... 9 common frames omitted
Arthas server port binding failed! Please check $HOME/logs/arthas/arthas.log for more details.
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.taobao.arthas.agent.AgentBootstrap.bind(AgentBootstrap.java:158)
        at com.taobao.arthas.agent.AgentBootstrap.access$000(AgentBootstrap.java:15)
        at com.taobao.arthas.agent.AgentBootstrap$1.run(AgentBootstrap.java:125)
Caused by: java.lang.ExceptionInInitializerError
        at com.taobao.arthas.core.shell.ShellServerOptions.<clinit>(ShellServerOptions.java:29)
        at com.taobao.arthas.core.server.ArthasBootstrap.bind(ArthasBootstrap.java:82)
        ... 7 more
Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
        at com.taobao.arthas.core.util.IOUtils.toString(IOUtils.java:134)
        at com.taobao.arthas.core.util.ArthasBanner.<clinit>(ArthasBanner.java:33)
        ... 9 more
就是按照官网的curl 安装后 sh as.sh 选择了 pid后  就挂了 日志 输出 这样，我看了代码，好像是 资源取不到，请问这个是什么问题,怎么解决

**Comment by arzes** [comment]
Environment
Arthas version: 3.0.5.2018101114330
Operating System version: Linux version 2.6.32-754.6.3.el6.x86_64 (mockbuild@x86-01.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC) ) #1 SMP Tue Oct 9 17:27:49 UTC 2018
Java version of target JVM: 1.8.0_181-b13
Java version of JVM used to attach: 1.8.0_181-b13

**Comment by Hearen** [comment]
@arzes #171

**Comment by arzes** [comment]
问题找到了，curl安装后，会丢失文件
/home/qktest/.arthas/lib 下 会有3.0.4xx下面最后到基础jar
但是我安装后也没报错，同样的lib下东西全丢失，然后手工从别的机器把jar全部拷贝进来就可以了
操作系统
CentOS release 6.10 (Final)

**Comment by arzes** [comment]
用的不是root权限，用户权限安装的
