### ISSUE TITLE
通过 tunnel server连接时，如果watch命令输出结果过大，会导致连接断开，用户界面卡住

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#2152]
```
2022-04-18 10:48:09 [arthas-forward-client-connect-local-7-1] ERROR c.a.a.tunnel.client.RelayHandler -RelayHandler error
com.alibaba.arthas.deps.io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Max frame length of 65536 has been exceeded.
        at com.alibaba.arthas.deps.io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:424)
        at com.alibaba.arthas.deps.io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:286)
        at com.alibaba.arthas.deps.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at com.alibaba.arthas.deps.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
        at com.alibaba.arthas.deps.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at com.alibaba.arthas.deps.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at com.alibaba.arthas.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at com.alibaba.arthas.deps.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at com.alibaba.arthas.deps.io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
        at com.alibaba.arthas.deps.io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
        at com.alibaba.arthas.deps.io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
        at com.alibaba.arthas.deps.io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
        at com.alibaba.arthas.deps.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at com.alibaba.arthas.deps.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at com.alibaba.arthas.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at com.alibaba.arthas.deps.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at com.alibaba.arthas.deps.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at com.alibaba.arthas.deps.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:857)
```

**Comment by hengyunabc** [comment]
测试本地直接连接 localhost:8563 ，不会卡住。原因是只访问本地时，netty只是一个server，写出的数据经过`io.netty.handler.codec.http.websocketx.WebSocketFrameEncoder` 转换为byte[]。

这个数据直接发送到浏览器，浏览器本身能处理这么大的数据包。

issue里的异常是`WebSocket08FrameDecoder`抛出来的，是因为arthas client在本地有一个 proxy，而proxy里的 `WebSocket08FrameDecoder`处理不了这么大的数据包，然后抛出的异常。

**Comment by hengyunabc** [comment]
在`ObjectView`里，目前最大允许值是 10M，考虑把nettry WebSocket08FrameDecoder的最大值设置为一样的。

```
public class ObjectView implements View {
    private final static int MAX_OBJECT_LENGTH = 10 * 1024 * 1024; // 10M
```
