### ISSUE TITLE
-d and -D are not working as expected in tt

### ISSUE THREAD

**Issue by Hearen** [alibaba/arthas#219]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.0.5.2018101114330
* Operating System version: ubuntu 16.04
* Java version of target JVM: jdk1.8.0_144
* Java version of JVM used to attach: jdk1.8.0_144

### Steps to reproduce this issue

1. 1. follow this to create the demo first: https://github.com/Hearen/arthas/blob/doc-with-consistent-demo/site/src/site/sphinx/en/quick-start.md

```
$ bin/as.sh

$ 3 # select the demo

$ tt -t -n 3 *Demo addTwoLists
Press Ctrl+C to abort.
Affect(class-cnt:1 , method-cnt:1) cost in 54 ms.
 INDEX        TIMESTAMP                      COST(ms)        IS-RET      IS-EXP       OBJECT                  CLASS                                          METHOD                                        
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000         2018-10-11 19:21:58            1.930901        true        false        NULL                    Demo                                           addTwoLists                                   
 1001         2018-10-11 19:21:58            0.096511        true        false        NULL                    Demo                                           addTwoLists                                   
 1002         2018-10-11 19:21:58            0.09073         true        false        NULL                    Demo                                           addTwoLists                                   
Command execution times exceed limit: 3, so command will exit. You can set it with -n option.
$ tt -l
 INDEX        TIMESTAMP                      COST(ms)        IS-RET      IS-EXP       OBJECT                  CLASS                                          METHOD                                        
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000         2018-10-11 19:21:58            1.930901        true        false        NULL                    Demo                                           addTwoLists                                   
 1001         2018-10-11 19:21:58            0.096511        true        false        NULL                    Demo                                           addTwoLists                                   
 1002         2018-10-11 19:21:58            0.09073         true        false        NULL                    Demo                                           addTwoLists                                   
Affect(row-cnt:3) cost in 3 ms.
$ tt -D
Error during processing the command: Time fragment index is expected, please type -i to specify
```

### Expected Result

delete all recorded items

### Actual Result

```
$ tt -D
Error during processing the command: Time fragment index is expected, please type -i to specify
```

### F.Y.I

```
01 2018-10-11 19:22:03.551 ERROR [as-command-execute-daemon:arthas] [] [] [] Error during processing the command:
java.lang.IllegalArgumentException: Time fragment index is expected, please type -i to specify
        at com.taobao.arthas.core.command.monitor200.TimeTunnelCommand.checkArguments(TimeTunnelCommand.java:209) ~[arthas-core.jar:3.0.5-SNAPSHOT]
        at com.taobao.arthas.core.command.monitor200.TimeTunnelCommand.process(TimeTunnelCommand.java:241) ~[arthas-core.jar:3.0.5-SNAPSHOT]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82) ~[arthas-core.jar:3.0.5-SNAPSHOT]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18) ~[arthas-core.jar:3.0.5-SNAPSHOT]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111) ~[arthas-core.jar:3.0.5-SNAPSHOT]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108) ~[arthas-core.jar:3.0.5-SNAPSHOT]
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370) ~[arthas-core.jar:3.0.5-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]

```

**Comment by Hearen** [comment]
I just debugged it locally using `log`

```
// in com/taobao/arthas/core/command/monitor200/TimeTunnelCommand.java
private void checkArguments() {
        LogUtil.getArthasLogger().error("", "isDelete: " + isDelete + ", " + isDeleteAll);
        // 检查d/p参数是否有i参数配套
        if ((isDelete || isPlay) && !isDeleteAll && null == index) {
            throw new IllegalArgumentException("Time fragment index is expected, please type -i to specify");
        }
```

```
$ tt -d
```

the log is 

```
01 2018-10-11 19:41:39.141 ERROR [as-command-execute-daemon:arthas] [] [] [] isDelete: false, true
```

**Comment by Hearen** [comment]
@ralf0131 @hengyunabc You can check this #220 branch.

Open another terminal, tracking the realtime log via `tail -n 100 -f ~/logs/arthas/arthas.log`

And then re-produce it as:

create a demo following: https://github.com/Hearen/arthas/blob/doc-with-consistent-demo/site/src/site/sphinx/en/quick-start.md

```
$ ./as-package.sh 

$ bin/as.sh 

1 # select demo/Demo

$ tt -t -n 3 *Demo addTwoLists
Press Ctrl+C to abort.
Affect(class-cnt:1 , method-cnt:1) cost in 55 ms.
 INDEX      TIMESTAMP                 COST(ms)     IS-RET     IS-EXP    OBJECT              CLASS                                  METHOD                                 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000       2018-10-11 22:24:17       1.053566     true       false     NULL                Demo                                   addTwoLists                            
 1001       2018-10-11 22:24:17       0.093237     true       false     NULL                Demo                                   addTwoLists                            
 1002       2018-10-11 22:24:17       0.262977     true       false     NULL                Demo                                   addTwoLists                            
Command execution times exceed limit: 3, so command will exit. You can set it with -n option.
$ tt -l
 INDEX      TIMESTAMP                 COST(ms)     IS-RET     IS-EXP    OBJECT              CLASS                                  METHOD                                 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000       2018-10-11 22:24:17       1.053566     true       false     NULL                Demo                                   addTwoLists                            
 1001       2018-10-11 22:24:17       0.093237     true       false     NULL                Demo                                   addTwoLists                            
 1002       2018-10-11 22:24:17       0.262977     true       false     NULL                Demo                                   addTwoLists                            
Affect(row-cnt:3) cost in 3 ms.
$ tt -d
Time fragments are cleaned.
Affect(row-cnt:3) cost in 1 ms.
```

**Comment by Hearen** [comment]
But if I replaced `-D` with `-Q` in this #221 I will get error as

```
$ tt -d
Error during processing the command: Time fragment index is expected, please type -i to specify
$ tt -D
Error during processing the command: Time fragment index is expected, please type -i to specify
$ tt -Q
Time fragments are cleaned.
Affect(row-cnt:3) cost in 0 ms.
```

while `tt -Q` will remove all records. @hengyunabc

**Comment by Hearen** [comment]
Since I can debug `arthas.core` now #222, it can be easily re-produced as:

```
$ rm -rf ~/.arthas/lib/3.0.5.2018101* # remove all local except 3.0.4 (avoid downloading)
$ ls ~/.arthas/lib/
3.0.4
$ ./as-package.sh
$ bin/as.sh
2 

$ tt -t -n 3 *Demo addTwoLists
Press Ctrl+C to abort.
Affect(class-cnt:1 , method-cnt:1) cost in 71 ms.
 INDEX        TIMESTAMP                      COST(ms)        IS-RET      IS-EXP       OBJECT                  CLASS                                          METHOD                                        
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000         2018-10-12 10:52:44            1.889076        true        false        NULL                    Demo                                           addTwoLists                                   
 1001         2018-10-12 10:52:44            0.089873        true        false        NULL                    Demo                                           addTwoLists                                   
 1002         2018-10-12 10:52:44            0.087219        true        false        NULL                    Demo                                           addTwoLists                                   
Command execution times exceed limit: 3, so command will exit. You can set it with -n option.

$ tt -d -i 1000
```

![image](https://user-images.githubusercontent.com/10859176/46845211-08109000-ce0d-11e8-9c54-a12649e7a412.png)

**Comment by Hearen** [comment]
There is a **bug** in the option parser which directly caused this issue comparingIgnoreCase in  `/home/hearen/.m2/repository/com/alibaba/middleware/cli/1.0.1/cli-1.0.1.jar!/com/taobao/middleware/cli/impl/DefaultParser.class` 


![image](https://user-images.githubusercontent.com/10859176/46930605-2c70a480-d079-11e8-873f-43ad7043836c.png)



`while(!opt.equalsIgnoreCase(option.getShortName()) && !opt.equalsIgnoreCase(option.getLongName()));`
