### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by feelgood3000** [alibaba/arthas#22]
```
Connecting to arthas server... current timestamp is 1536904847
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host
```

日志内容

```
Arthas server agent start...
Arthas start to bind...
01 2018-09-14 14:04:01.241 ERROR [arthas-binding-thread:arthas] [] [] [] Error during bind to port 3658
java.lang.ExceptionInInitializerError: null
	at com.taobao.arthas.core.shell.ShellServerOptions.<clinit>(ShellServerOptions.java:29) ~[na:na]
	at com.taobao.arthas.core.server.ArthasBootstrap.bind(ArthasBootstrap.java:82) ~[arthas-core.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at com.taobao.arthas.agent.AgentBootstrap.bind(AgentBootstrap.java:158) [arthas-agent.jar:na]
	at com.taobao.arthas.agent.AgentBootstrap.access$000(AgentBootstrap.java:15) [arthas-agent.jar:na]
	at com.taobao.arthas.agent.AgentBootstrap$1.run(AgentBootstrap.java:125) [arthas-agent.jar:na]
Caused by: java.lang.NullPointerException: null
	at java.io.Reader.<init>(Reader.java:78) ~[na:1.8.0_162]
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72) ~[na:1.8.0_162]
	at com.taobao.arthas.core.util.IOUtils.toString(IOUtils.java:134) ~[arthas-core.jar:na]
	at com.taobao.arthas.core.util.ArthasBanner.<clinit>(ArthasBanner.java:33) ~[na:na]
	... 9 common frames omitted
Arthas server port binding failed! Please check $HOME/logs/arthas/arthas.log for more details.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.taobao.arthas.agent.AgentBootstrap.bind(AgentBootstrap.java:158)
	at com.taobao.arthas.agent.AgentBootstrap.access$000(AgentBootstrap.java:15)
	at com.taobao.arthas.agent.AgentBootstrap$1.run(AgentBootstrap.java:125)
Caused by: java.lang.ExceptionInInitializerError
	at com.taobao.arthas.core.shell.ShellServerOptions.<clinit>(ShellServerOptions.java:29)
	at com.taobao.arthas.core.server.ArthasBootstrap.bind(ArthasBootstrap.java:82)
	... 7 more
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at com.taobao.arthas.core.util.IOUtils.toString(IOUtils.java:134)
	at com.taobao.arthas.core.util.ArthasBanner.<clinit>(ArthasBanner.java:33)
	... 9 more
```

**Comment by hengyunabc** [comment]
具体什么版本，怎么运行的?

**Comment by zhaog** [comment]
我也遇到这个问题
Arthas script version: 3.0.2
Found existing java process, please choose one and hit RETURN.
* [1]: 827352 Demo
1
Calculating attach execution time...
Attaching to 827352 using version 3.0.0-RC...

real    0m0.772s
user    0m0.220s
sys     0m0.033s
Attach success.
Connecting to arthas server... current timestamp is 1536907560
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused

**Comment by sadhen** [comment]
尴尬，刚刚在企业微信安利，结果也遇到这个问题

**Comment by hengyunabc** [comment]
可以跑下master分支上的代码，执行 `as-package.sh`来打包，再跑下看有没有问题。

**Comment by hengyunabc** [comment]
这个问题已经修复了，https://github.com/alibaba/arthas/commit/61e4467ac40aa10250eeb89b5ea4b715c7b245cb

目前还是 `3.0.0-RC` 版本，今天会发一个正式的 release版本出来。

**Comment by sadhen** [comment]
as-package.sh 这个脚本稍微有点问题

**Comment by wanhuhou** [comment]
> 这个问题已经修复了，[61e4467](https://github.com/alibaba/arthas/commit/61e4467ac40aa10250eeb89b5ea4b715c7b245cb)
> 
> 目前还是 `3.0.0-RC` 版本，今天会发一个正式的 release版本出来。

我刚跑的还是同一个问题啊

**Comment by hhxx1994** [comment]
遇到同样问题,以下是debug中的几张图
![image](https://user-images.githubusercontent.com/26454067/45538296-40867380-b839-11e8-9f06-26ae2ce90882.png)

应是找不到动态写入的version
![image](https://user-images.githubusercontent.com/26454067/45538407-92c79480-b839-11e8-8284-9959a75e45b8.png)

version的写入逻辑是怎么样的
![image](https://user-images.githubusercontent.com/26454067/45538441-ac68dc00-b839-11e8-80d4-ac44b8a1120f.png)

**Comment by hengyunabc** [comment]
已发布 3.0.4 版本到maven仓库，大家可以再试下，直接执行 `as.sh`会自动下载新版本。

**Comment by hengyunabc** [comment]
更新了安装文档： https://alibaba.github.io/arthas/install-detail.html
