### ISSUE TITLE
Unsupported class file major version 61 using arthas 3.6.3

### ISSUE THREAD

**Issue by Shoothzj** [alibaba/arthas#2201]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.6.3
* Operating System version: EulerOs
* Java version of target JVM: jdk17
* Java version of JVM used to attach: jdk17

### Steps to reproduce this issue

1. use jdk17 run pulsar
2. arthas `trace org.apache.pulsar.broker.stats.prometheus.PulsarPrometheusMetricsServlet   generateMetrics`

### Actual Result

```
01 2022-06-14 12:27:27.599 WARN [as-command-execute-daemon:arthas] [] [] [] transform loader[jdk.internal.loader.ClassLoaders$AppClassLoader@35fb3008]:class[org/apache/pulsar/broker/stats/prometheus/PulsarPrometheusMetricsServlet] failed.
java.lang.IllegalArgumentException: Unsupported class file major version 61
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:184)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
        at com.taobao.arthas.core.advisor.Enhancer.transform(Enhancer.java:117)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(Unknown Source)
        at java.instrument/sun.instrument.TransformerManager.transform(Unknown Source)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(Unknown Source)
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(Unknown Source)
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:304)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:111)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:66)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by hengyunabc** [comment]
这个看起来像自己打包的修改版本，arthas里的应该是这个repackage过的：

com.alibaba.deps.org.objectweb.asm.ClassReader

**Comment by Shoothzj** [comment]
@hengyunabc It's download from the official site. It's about the environment.
I think I have figured out scene.
The java process is first attached by lower version arthas which not support jdk17 (of courese it will fail). 
After I restart the process, it will attach sucesss.

**Comment by hengyunabc** [comment]
arthas的二进制包是不会有 org.objectweb.asm.ClassReader 这个package的 `.class`文件的，有可能是有其它的agent，或者其它的原因，导致有一个 `org.objectweb.asm.ClassReader `的 jar加到了 SystemClassLoader的 parent 的 urls里了。

然后ArthasClassLoader才有可能加载到。

**Comment by wwulfric** [comment]
请问现在是否支持jdk21？
```
java.lang.IllegalArgumentException: Unsupported class file major version 65
        at com.alibaba.deps.org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
        at com.alibaba.deps.org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at com.alibaba.deps.org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at com.alibaba.bytekit.utils.AsmUtils.toClassNode(AsmUtils.java:61)
        at com.taobao.arthas.core.advisor.Enhancer.transform(Enhancer.java:123)
        at com.taobao.arthas.core.advisor.TransformerManager$1.transform(TransformerManager.java:51)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:610)
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:225)
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:443)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:162)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:109)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

com.alibaba.deps.org.objectweb.asm.ClassReader 是repackage的版本，但不清楚哪个com.alibaba:repackage-asm 支持jdk21.
https://asm.ow2.io/versions.html  asm这里看到24 March 2023: ASM 9.5开始支持jdk21

**Comment by hengyunabc** [comment]
@wwulfric  已经支持 jdk 21。 

* https://github.com/alibaba/arthas/blob/arthas-all-3.7.2/pom.xml#L137
* https://github.com/hengyunabc/arthas-repackage-deps/blob/0.0.13/pom.xml#L54

**Comment by sjx782392329** [comment]
@hengyunabc 请问什么时候可以支持 jdk22
```
2024-07-01 17:52:52 [arthas-command-execute] WARN  c.t.arthas.core.advisor.Enhancer -transform loader[PluginClassLoader{plugin=kudu, identityHash=@24287e5e}]:class[io/trino/plugin/kudu/TypeHelper] failed.
java.lang.IllegalArgumentException: Unsupported class file major version 66
        at com.alibaba.deps.org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
        at com.alibaba.deps.org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at com.alibaba.deps.org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at com.alibaba.bytekit.utils.AsmUtils.toClassNode(AsmUtils.java:62)
        at com.taobao.arthas.core.advisor.Enhancer.transform(Enhancer.java:134)
        at com.taobao.arthas.core.advisor.TransformerManager$1.transform(TransformerManager.java:51)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:242)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:610)
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:225)
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:446)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:173)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:120)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1570)
```
