### ISSUE TITLE
Connect to telnet server error: 0.0.0.0 3658 尝试过其他issue解决方案没有成功

### ISSUE THREAD

**Issue by zheng-zy** [alibaba/arthas#2252]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.0
* Arthas 版本: 3.5.0
* 操作系统版本: centos7.9
* 目标进程的JVM版本: jdk1.8.0_191-b12
* 执行`arthas-boot`的版本:  jdk1.8.0_191-b12
>防火墙已关闭，端口也没有被占用

### 重现问题的步骤

java -jar arthas-boot.jar --target-ip 0.0.0.0

### 期望的结果

成功进入界面
![image](https://user-images.githubusercontent.com/13825054/185087439-8d523c4d-8cd8-45ed-a868-e2414deebe04.png)

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
[root@vm-bigdata-openapi-1 openapi]# art 4042
[INFO] arthas-boot version: 3.5.0
[INFO] arthas home: /usr/local/arthas/lib/3.5.0/arthas
[INFO] Try to attach process 4042
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
        at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
        at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:97)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:26)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:137)
[ERROR] attach fail, targetPid: 4042

```

arthas日志
```
[root@vm-bigdata-3data-1 arthas]# cat ~/logs/arthas/arthas.log
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.

```

**Comment by hengyunabc** [comment]
[target process not responding or HotSpot VM not loaded](https://arthas.aliyun.com/doc/faq.html#target-process-not-responding-or-hotspot-vm-not-loaded)
