### ISSUE TITLE
执行java -jar arthas-boot.jar出现Connection refused (Connection refused)，查看日志 Caused by: java.io.IOException: Too many open files

### ISSUE THREAD

**Issue by sanwangdian** [alibaba/arthas#2255]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.6.1
* Arthas 版本: 3.6.1
* 操作系统版本: unbuntu18
* 目标进程的JVM版本: openjdk 11
* 执行`arthas-boot`的版本: openjdk 11

### 重现问题的步骤

1. java -jar arthas-boot.jar

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
	at com.taobao.arthas.client.TelnetConsole.process(TelnetConsole.java:306)
	at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:166)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:615)

```
把异常信息贴到这里
```
2022-08-23 16:26:49 [arthas-binding-thread] INFO  c.t.arthas.core.util.ArthasBanner -Current arthas version: 3.6.1, recommend latest version: 
2022-08-23 16:26:50 [arthas-binding-thread] INFO  c.t.arthas.core.util.ArthasBanner -Current arthas version: 3.6.1, recommend latest version: 
2022-08-23 16:26:52 [arthas-binding-thread] ERROR c.t.a.core.server.ArthasBootstrap -Error during start as-server
java.lang.IllegalStateException: failed to create a child event loop
	at com.alibaba.arthas.deps.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at com.alibaba.arthas.deps.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:60)
	at com.alibaba.arthas.deps.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:49)
	at com.alibaba.arthas.deps.io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at com.alibaba.arthas.deps.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
	at com.alibaba.arthas.deps.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
	at com.alibaba.arthas.deps.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61)
	at com.taobao.arthas.core.server.ArthasBootstrap.bind(ArthasBootstrap.java:417)
	at com.taobao.arthas.core.server.ArthasBootstrap.<init>(ArthasBootstrap.java:156)
	at com.taobao.arthas.core.server.ArthasBootstrap.getInstance(ArthasBootstrap.java:581)
	at com.taobao.arthas.core.server.ArthasBootstrap.getInstance(ArthasBootstrap.java:569)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.taobao.arthas.agent334.AgentBootstrap.bind(AgentBootstrap.java:182)
	at com.taobao.arthas.agent334.AgentBootstrap.access$000(AgentBootstrap.java:20)
	at com.taobao.arthas.agent334.AgentBootstrap$1.run(AgentBootstrap.java:152)
Caused by: com.alibaba.arthas.deps.io.netty.channel.ChannelException: failed to open a new selector
	at com.alibaba.arthas.deps.io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:178)
	at com.alibaba.arthas.deps.io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:145)
	at com.alibaba.arthas.deps.io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:183)
	at com.alibaba.arthas.deps.io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:38)
	at com.alibaba.arthas.deps.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	... 17 common frames omitted
Caused by: java.io.IOException: Too many open files
	at java.base/sun.nio.ch.EPoll.create(Native Method)
	at java.base/sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:79)
	at java.base/sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
	at com.alibaba.arthas.deps.io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:176)
	... 21 common frames omitted
2022-08-23 16:26:52 [arthas-binding-thread] INFO  c.t.a.core.server.ArthasBootstrap -as-server destroy completed.

**Comment by hengyunabc** [comment]
这个是进程本身是打开太多文件，或者网络连接了，没办法再打开更多了。可能是内存不够，也可能是linux本身的os限制。google下相关内容。
