### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by kangyu06** [alibaba/arthas#2282]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息
arthas-boot version: 3.6.6

### 重现问题的步骤

![image](https://user-images.githubusercontent.com/53601447/189082919-22d3f3da-2d24-43ef-839a-93661f48a1e9.png)
![image](https://user-images.githubusercontent.com/53601447/189082952-1e6e3391-d637-4fad-9901-cf78b24b9d49.png)

[ERROR] Start arthas failed, exception stack trace: 
java.io.IOException: Connection reset by peer
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.read(Native Method)
	at jdk.attach/sun.tools.attach.VirtualMachineImpl$SocketInputStream.read(VirtualMachineImpl.java:260)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.readInt(HotSpotVirtualMachine.java:328)
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.execute(VirtualMachineImpl.java:192)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.executeCommand(HotSpotVirtualMachine.java:309)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.getSystemProperties(HotSpotVirtualMachine.java:190)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:105)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:27)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:161)
[ERROR] attach fail, targetPid: 26816

大佬救命啊。

**Comment by lang-hu** [comment]
可能是两个运用启动的用户权限不一致
