### ISSUE TITLE
使用ognl创建PB对象报错OgnlException: source is null for getProperty

### ISSUE THREAD

**Issue by acelxiao** [alibaba/arthas#2345]
[arthas@402]$ ognl '#a=com.yy.spf.girgir.proto.OriginIm.CallbackBeforeP2PChatRequest.newBuilder().setAppId(11111L).build()'

Failed to execute ognl, exception message: ognl.OgnlException: source is null for getProperty(null, "com"), please check $HOME/logs/arthas/arthas.log for more details.

2022-11-16 00:44:12 [arthas-command-execute] ERROR c.t.a.c.command.express.OgnlExpress -Error during evaluating the expression:
ognl.OgnlException: source is null for getProperty(null, "com")
        at ognl.OgnlRuntime.getProperty(OgnlRuntime.java:2709)
        at ognl.ASTProperty.getValueBody(ASTProperty.java:114)
        at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
        at ognl.SimpleNode.getValue(SimpleNode.java:258)
        at ognl.ASTChain.getValueBody(ASTChain.java:141)
        at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
        at ognl.SimpleNode.getValue(SimpleNode.java:258)
        at ognl.ASTAssign.getValueBody(ASTAssign.java:52)
        at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
        at ognl.SimpleNode.getValue(SimpleNode.java:258)
        at ognl.Ognl.getValue(Ognl.java:470)
        at ognl.Ognl.getValue(Ognl.java:572)
        at ognl.Ognl.getValue(Ognl.java:542)
        at com.taobao.arthas.core.command.express.OgnlExpress.get(OgnlExpress.java:40)
        at com.taobao.arthas.core.command.klass100.OgnlCommand.process(OgnlCommand.java:105)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2022-11-16 00:44:12 [arthas-command-execute] WARN  c.t.a.c.command.klass100.OgnlCommand -ognl: failed execute express: #a=com.yy.spf.girgir.proto.OriginIm.CallbackBeforeP2PChatRequest.newBuilder().setAppId(11111L).build()
com.taobao.arthas.core.command.express.ExpressException: ognl.OgnlException: source is null for getProperty(null, "com")
        at com.taobao.arthas.core.command.express.OgnlExpress.get(OgnlExpress.java:43)
        at com.taobao.arthas.core.command.klass100.OgnlCommand.process(OgnlCommand.java:105)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: ognl.OgnlException: source is null for getProperty(null, "com")
        at ognl.OgnlRuntime.getProperty(OgnlRuntime.java:2709)
        at ognl.ASTProperty.getValueBody(ASTProperty.java:114)
        at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
        at ognl.SimpleNode.getValue(SimpleNode.java:258)
        at ognl.ASTChain.getValueBody(ASTChain.java:141)
        at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
        at ognl.SimpleNode.getValue(SimpleNode.java:258)
        at ognl.ASTAssign.getValueBody(ASTAssign.java:52)
        at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
        at ognl.SimpleNode.getValue(SimpleNode.java:258)
        at ognl.Ognl.getValue(Ognl.java:470)
        at ognl.Ognl.getValue(Ognl.java:572)
        at ognl.Ognl.getValue(Ognl.java:542)
        at com.taobao.arthas.core.command.express.OgnlExpress.get(OgnlExpress.java:40)
        ... 13 common frames omitted

**Comment by hengyunabc** [comment]
看ognl的帮助文档， `newBuilder`应该是一个static method，调用方法应该是 `@xxxClass@methodName()`。
