### ISSUE TITLE
arthas-boot.jar telnet随机端口

### ISSUE THREAD

**Issue by Shashengzhe** [alibaba/arthas#2355]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.6.7
* Arthas 版本: 3.6.7
* 操作系统版本: centos7
* 目标进程的JVM版本: openjdk-8
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. java -jar arthas-boot.jar --repo-mirror aliyun --use-http --telnet-port 0

### 期望的结果

What do you expected from the above steps？

1. telnet server通过随机端口正常启动
2. telnet客户端通过相同端口去连接server

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

1. telnet server通过随机端口正常启动
2. telnet客户端通过0端口连接导致失败

```
把异常信息贴到这里

[INFO] arthas-client connect 127.0.0.1 0
[DEBUG] Start arthas-client.jar args: [127.0.0.1, 0]
Connect to telnet server error: 127.0.0.1 0
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
	at com.taobao.arthas.client.TelnetConsole.process(TelnetConsole.java:306)
	at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:629)

```

**Comment by gaochengyidlmu** [comment]
你的用法有问题，流程应该是：
1. 仅在目标进程上启动 arthas-server
2. 去 ~/logs/arthas/arthas.log 查看日志，找到随机的端口号是多少
3. 使用 arthas-client.jar 去指定端口连接

```bash
> java -jar arthas-boot.jar 10701 --telnet-port 0 --http-port -1 --attach-only
> tail -n 20 ~/logs/arthas/arthas.log
2023-02-23 10:10:55 [arthas-binding-thread] INFO  c.t.a.core.server.ArthasBootstrap -as-server listening on network=127.0.0.1;telnet=47388;http=8563;timeout=6000;

> java -jar arthas-client.jar 127.0.0.1 47388
```
