### ISSUE TITLE
A JNI error has occurred, please check your installation and try again

### ISSUE THREAD

**Issue by guqifan** [alibaba/arthas#2379]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: alpine3.5
* 目标进程的JVM版本: oracle jdk8
* 执行`arthas-boot`的版本: 3.6

### 重现问题的步骤

1. 使用alpine3.5制作oraclejdk8镜像
2. 镜像装了glibc
3. 镜像装了arthas3.6
4. attach失败

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

[INFO] arthas-boot version: 3.6.0
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 1 demo-gqf.jar
1
[INFO] arthas home: /app/arthas_home
[INFO] Try to attach process 1
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.io.IOException: Bad pathname
        at java.lang.ClassLoader.findBootstrapClass(Native Method)
        at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1015)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:413)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
[ERROR] attach fail, targetPid: 1

**Comment by hengyunabc** [comment]
pid 1 问题，看下 faq。
