### ISSUE TITLE
JDK 17 thread/dashboard 无法显示JVM内部线程的问题

### ISSUE THREAD

**Issue by kylixs** [alibaba/arthas#2380]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息
* Arthas 版本: 3.6.7

### 重现问题的步骤

1. Arthas 注入 Java/Jdk 17 的进程，thread/dashboard 无法显示JVM内部线程（GC Thread/VM Thread/C2 CompilerThread等）

### 异常信息
Remote Debug 抓到的异常:
```
java.lang.IllegalAccessError: class com.taobao.arthas.core.command.monitor200.ThreadSampler (in unnamed module @0x7c5d2dcf) cannot access class sun.management.ManagementFactoryHelper (in module java.management) because module java.management does not export sun.management to unnamed module @0x7c5d2dcf
        at com.taobao.arthas.core.command.monitor200.ThreadSampler.getInternalThreadCpuTimes(ThreadSampler.java:160)
        at com.taobao.arthas.core.command.monitor200.ThreadSampler.sample(ThreadSampler.java:50)
        at com.taobao.arthas.core.command.monitor200.ThreadCommand.processAllThreads(ThreadCommand.java:167)
        at com.taobao.arthas.core.command.monitor200.ThreadCommand.process(ThreadCommand.java:126)
```

### 解决办法
目标进程添加JVM参数：`--add-opens java.management/sun.management=ALL-UNNAMED`

### 结果
```
ID    NAME                             GROUP            PRIORITY   STATE      %CPU       DELTA_TIME  TIME       INTERRUPTE DAEMON
31    http-nio-8080-exec-4             main             5          RUNNABLE   33.59      0.671       0:40.906   false      true
68    http-nio-8080-exec-19            main             5          WAITING    32.81      0.656       0:31.468   false      true
85    http-nio-8080-exec-35            main             5          WAITING    32.81      0.656       0:29.296   false      true
77    http-nio-8080-exec-27            main             5          WAITING    31.25      0.625       0:29.609   false      true
80    http-nio-8080-exec-30            main             5          WAITING    31.25      0.625       0:29.156   false      true
33    http-nio-8080-exec-6             main             5          WAITING    30.47      0.609       0:41.843   false      true
88    http-nio-8080-exec-38            main             5          WAITING    28.12      0.562       0:29.171   false      true
29    http-nio-8080-exec-2             main             5          RUNNABLE   27.34      0.546       0:41.359   false      true
36    http-nio-8080-exec-9             main             5          TIMED_WAIT 25.78      0.515       0:41.437   false      true
93    http-nio-8080-exec-43            main             5          WAITING    25.78      0.515       0:28.546   false      true
39    http-nio-8080-Acceptor           main             5          RUNNABLE   25.0       0.500       2:37.578   false      true
38    http-nio-8080-ClientPoller       main             5          RUNNABLE   24.22      0.484       2:42.203   false      true
-1    GC Thread#9                      -                -1         -          4.69       0.093       0:19.531   false      true
-1    GC Thread#5                      -                -1         -          4.69       0.093       0:19.046   false      true
-1    GC Thread#6                      -                -1         -          4.69       0.093       0:19.687   false      true
-1    GC Thread#7                      -                -1         -          4.69       0.093       0:19.171   false      true
-1    GC Thread#8                      -                -1         -          4.69       0.093       0:19.281   false      true
-1    GC Thread#1                      -                -1         -          4.69       0.093       0:19.000   false      true
-1    GC Thread#2                      -                -1         -          4.69       0.093       0:19.031   false      true
-1    GC Thread#3                      -                -1         -          4.69       0.093       0:19.625   false      true
-1    GC Thread#4                      -                -1         -          4.69       0.093       0:19.078   false      true
-1    GC Thread#0                      -                -1         -          4.69       0.093       0:19.593   false      true
2     Reference Handler                system           10         RUNNABLE   0.0        0.000       0:0.000    false      true
3     Finalizer                        system           8          WAITING    0.0        0.000       0:0.000    false      true
4     Signal Dispatcher                system           9          RUNNABLE   0.0        0.000       0:0.000    false      true
Memory                       used     total     max      usage     GC
heap                         206M     512M      512M     40.41%    gc.g1_young_generation.count      4983
g1_eden_space                57M      274M      -1       20.80%    gc.g1_young_generation.time(ms)   24013
g1_old_gen                   141M     229M      512M     27.65%    gc.g1_old_generation.count        0
g1_survivor_space            8M       9M        -1       92.81%    gc.g1_old_generation.time(ms)     0
nonheap                      86M      91M       -1       94.18%
codeheap_'non-nmethods'      1M       2M        5M       24.14%
metaspace                    54M      55M       -1       99.13%
codeheap_'profiled_nmethods' 12M      16M       117M     11.09%
compressed_class_space       6M       6M        1024M    0.63%
codeheap_'non-profiled_nmeth 10M      10M       117M     9.10%
ods'
mapped                       0K       0K        -        0.00%
direct                       16M      16M       -        100.00%
Runtime
os.name                                                            Windows 10
os.version                                                         10.0
java.version                                                       17.0.5
java.home                                                          D:\Java\corretto-17.0.5
systemload.average                                                 -1.00
processors                                                         12
timestamp/uptime                                                   Sun Dec 18 15:04:55 CST 2022/1499s
[arthas@18824]$
```

**Comment by kimmking** [comment]
这不是个bug吧，JDK9+都需要add-opens，JDK的限制。
