### ISSUE TITLE
无法监控Service中的接口实现方法

### ISSUE THREAD

**Issue by Dog-Elder** [alibaba/arthas#2408]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.6.7
* 操作系统版本: win11
* 目标进程的JVM版本: 15
* 执行`arthas-boot`的版本: 3.6.7

### 重现问题的步骤

![图片](https://user-images.githubusercontent.com/56543937/212470718-174bc9c7-a62b-4a5f-8927-30379a23cd81.png)

### 期望的结果

正常使用

### 实际运行的结果

Enhance error! exception: java.lang.UnsupportedOperationException: class redefinition failed: attempted to delete a method
error happens when enhancing class: class redefinition failed: attempted to delete a method, check arthas log: C:\Users\Administrator\logs\arthas\arthas.log

```
2023-01-14 19:54:37 [arthas-command-execute] INFO  c.t.arthas.core.advisor.Enhancer -enhance matched classes: [class com.xxxxx.service.impl.SysEncodingSetRuleServiceImpl, class com.xxxxx.service.impl.SysEncodingSetRuleServiceImpl$$EnhancerBySpringCGLIB$$1]
2023-01-14 19:54:38 [arthas-command-execute] ERROR c.t.arthas.core.advisor.Enhancer -Enhancer error, matchingClasses: [class com.xxxxx.service.impl.SysEncodingSetRuleServiceImpl, class com.xxxxx.service.impl.SysEncodingSetRuleServiceImpl$$EnhancerBySpringCGLIB$$1]
java.lang.UnsupportedOperationException: class redefinition failed: attempted to add a method
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
	at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:446)
	at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:162)
	at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:109)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by Dog-Elder** [comment]
发现增加  @Transactional 注解时会报错 注释掉@Transactional 可以正常运行和监控
