### ISSUE TITLE
AnsiLog format NullPointerException

### ISSUE THREAD

**Issue by JoeCqupt** [alibaba/arthas#2410]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： master分支
* Arthas 版本:  master分支
* 操作系统版本:  操作系统无关
* 目标进程的JVM版本: JVM无关
* 执行`arthas-boot`的版本: master

### 重现问题的步骤

```
     AnsiLog.warn("Target VM JAVA_HOME is {}, arthas-boot JAVA_HOME is {}, try to set the same JAVA_HOME.",
               null, System.getProperty("java.home"));
```

### 期望的结果

What do you expected from the above steps？

日志输出

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
Exception in thread "main" java.lang.NullPointerException
	at com.taobao.arthas.common.AnsiLog.format(AnsiLog.java:281)
	at com.taobao.arthas.common.AnsiLog.warn(AnsiLog.java:244)
	at com.taobao.arthas.common.AnsiLog.main(AnsiLog.java:294)
```

**Comment by JoeCqupt** [comment]
```
Caused by: java.lang.NullPointerException: null
        at com.taobao.arthas.common.AnsiLog.format(AnsiLog.java:281)
        at com.taobao.arthas.common.AnsiLog.warn(AnsiLog.java:244)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:112)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:27)
        ... 9 common frames omitted
```

我的环境里面获取不到 "java.home"的值(为null)。这里会导致NullPointerException；导致 arthas-agent无法被load 
![image](https://user-images.githubusercontent.com/12369652/212722481-f696b033-3365-4c37-a42c-7b9afe528c59.png)

**Comment by JoeCqupt** [comment]
参考：https://github.com/oracle/graal/issues/1812
