### ISSUE TITLE
Unable to attach to 32-bit process running under  ?????

### ISSUE THREAD

**Issue by Huojunning** [alibaba/arthas#242]
com.sun.tools.attach.AttachNotSupportedException: Unable to attach to 32-bit process running under WOW64
        at sun.tools.attach.WindowsVirtualMachine.openProcess(Native Method)
        at sun.tools.attach.WindowsVirtualMachine.<init>(WindowsVirtualMachine.java:56)
        at sun.tools.attach.WindowsAttachProvider.attachVirtualMachine(WindowsAttachProvider.java:69)
        at com.sun.tools.attach.spi.AttachProvider.attachVirtualMachine(AttachProvider.java:194)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:69)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:25)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:96)

**Comment by hengyunabc** [comment]
检查是 JAVA_HOME 配置，看和目标进程是否用的同样的jdk。

**Comment by Huojunning** [comment]
> 检查是 JAVA_HOME 配置，看和目标进程是否用的同样的jdk。
感谢
