### ISSUE TITLE
http api server connection close 无连接复用也无 response header connection close 导致 client 使用已经被 server 半关闭的连接

### ISSUE THREAD

**Issue by lindzh** [alibaba/arthas#2428]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* java httpclient4 使用连接池调用 arthas http api

### 重现问题的步骤

1. java httpclient4 使用连接池调用本地 arthas http api。
2. 请求 response 返回后，在 2s 内发送第二次请求。
3. 第二次请求失败。

```java
String url = "http://127.0.0.1:8563/api";
String body = "{\n" +
    "  \"action\":\"exec\",\n" +
    "  \"command\":\"version\"\n" +
    "}";
for (int i = 0; i < 2; i++) {
    try{
        HttpResponseMeta meta = httpComponent.httpPost(url, null, null, body);
        System.out.println(meta.getResponseAsString());
        Thread.sleep(1000);
    }catch (Throwable e){
        e.printStackTrace();
    }
}
```

### 期望的结果

第二次连接复用的请求能够成功。
如果不复用连接，第一次的 response 需要带上 connection:close 符合 http 协议连接优雅关闭。

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

![](http://lindzh.oss-cn-hangzhou.aliyuncs.com/images/arthas_http_server_api_connection_close_bug.jpg)

```
{"body":{"command":"version","jobId":4,"jobStatus":"TERMINATED","results":[{"jobId":4,"type":"version","version":"3.5.4"},{"jobId":4,"statusCode":0,"type":"status"}],"timeExpired":false},"sessionId":"ddd458e3-b4f1-47f9-b261-b9dbf7310dab","state":"SUCCEEDED"}
[2023-02-16 14:14:45.463] ERROR http exception:127.0.0.1:8563 failed to respond
org.apache.http.NoHttpResponseException: 127.0.0.1:8563 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
```
### bug 代码位置

![](http://lindzh.oss-cn-hangzhou.aliyuncs.com/images/arthas_http_server_api_response_close_bug.jpg)

**Comment by hengyunabc** [comment]
![image](https://user-images.githubusercontent.com/1683936/219331128-af5f3246-5e03-4380-b6d8-3070da1b3681.png)

补张图。

欢迎提交pr修复。
