### ISSUE TITLE
我是在Netty的环境下使用 会遇到卡住 或者 链接不上

### ISSUE THREAD

**Issue by uhaorph1636** [alibaba/arthas#2450]
这是运行过程

JDK 11 

```
Resolving arthas.aliyun.com (arthas.aliyun.com)... 203.119.175.202
Connecting to arthas.aliyun.com (arthas.aliyun.com)|203.119.175.202|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 141819 (138K) [application/java-archive]
Saving to: ‘arthas-boot.jar’

arthas-boot.jar                                    100%[================================================================================================================>] 138.50K  --.-KB/s    in 0.04s

2023-03-16 21:39:28 (3.44 MB/s) - ‘arthas-boot.jar’ saved [141819/141819]

[INFO] JAVA_HOME: /usr/local/openjdk-11
[INFO] arthas-boot version: 3.6.7
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 1 com.xihang.im.ImWebSocketApp
1
[INFO] Start download arthas from remote server: https://arthas.aliyun.com/download/3.6.7?mirror=aliyun
[INFO] Download arthas success.
[INFO] arthas home: /root/.arthas/lib/3.6.7/arthas
[INFO] Try to attach process 1
Picked up JAVA_TOOL_OPTIONS:
[INFO] Attach process 1 success.
[INFO] arthas-client connect 127.0.0.1 3658
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
	at com.taobao.arthas.client.TelnetConsole.process(TelnetConsole.java:306)
	at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:166)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:629)
Usage: arthas-client [--help] [-c <value>] [-f <value>] [-w <value>] [-t
       <value>] [-h <value>] [target-ip] [port]

Arthas Telnet Client
```

**Comment by hengyunabc** [comment]
pid 1的问题，faq，或者issue里找下。
