### ISSUE TITLE
web-ui module build error

### ISSUE THREAD

**Issue by zinking** [alibaba/arthas#2650]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息
macos
➜  arthas git:(spark33) ✗ java -version
openjdk version "1.8.0_382"
OpenJDK Runtime Environment (Tencent Kona 8.0.15) (build 1.8.0_382-b1)
OpenJDK 64-Bit Server VM (Tencent Kona 8.0.15) (build 25.382-b1, mixed mode)

### 重现问题的步骤

mvn clean install

### 期望的结果

build success

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
[INFO] Found proxies: [dev http{protocol='http', host='web-proxy.oa.com', port=8080, nonProxyHosts='mirrors.tencent.com|localhost|127.0.0.1|*.oa.com|packages.confluent.io|maven.aliyun.com'}, dev https{protocol='https', host='web-proxy.oa.com', port=8080, nonProxyHosts='mirrors.tencent.com|localhost|127.0.0.1|*.oa.com|packages.confluent.io|maven.aliyun.com'}]
[INFO] Running 'yarn vite build --mode ui --https-proxy=http://web-proxy.oa.com:8080 --proxy=http://web-proxy.oa.com:8080' in /Users/zhnwang/zhenw/arthas/web-ui/arthasWebConsole
[INFO] yarn run v1.22.19
[INFO] warning package.json: No license field
[INFO] $ /Users/zhnwang/zhenw/arthas/web-ui/arthasWebConsole/node_modules/.bin/vite build --mode ui --https-proxy=http://web-proxy.oa.com:8080 --proxy=http://web-proxy.oa.com:8080
[INFO] /Users/zhnwang/zhenw/arthas/web-ui/arthasWebConsole/node_modules/vite/dist/node/cli.js:426
[INFO]           throw new CACError(`Unknown option \`${name.length > 1 ? `--${name}` : `-${name}`}\``);
[INFO]           ^
[INFO] 
[INFO] CACError: Unknown option `--httpsProxy`
[INFO]     at Command.checkUnknownOptions (/Users/zhnwang/zhenw/arthas/web-ui/arthasWebConsole/node_modules/vite/dist/node/cli.js:426:17)
[INFO]     at CAC.runMatchedCommand (/Users/zhnwang/zhenw/arthas/web-ui/arthasWebConsole/node_modules/vite/dist/node/cli.js:624:13)
[INFO]     at CAC.parse (/Users/zhnwang/zhenw/arthas/web-ui/arthasWebConsole/node_modules/vite/dist/node/cli.js:563:12)
[INFO]     at Object.<anonymous> (/Users/zhnwang/zhenw/arthas/web-ui/arthasWebConsole/node_modules/vite/dist/node/cli.js:806:5)
[INFO]     at Module._compile (node:internal/modules/cjs/loader:1105:14)
[INFO]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
[INFO]     at Module.load (node:internal/modules/cjs/loader:981:32)
[INFO]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[INFO]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[INFO]     at require (node:internal/modules/cjs/helpers:102:18)
[INFO] error Command failed with exit code 1.
[INFO] error Command failed with exit code 1.info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default) on project arthas-core: An Ant BuildException has occured: /Users/zhnwang/zhenw/arthas/web-ui/arthasWebConsole/dist/ui does not exist.
[ERROR] around Ant part ...<copy todir="/Users/zhnwang/zhenw/arthas/core/target/tmp_out/com/taobao/arthas/core/http/" overwrite="true">... @ 8:111 in /Users/zhnwang/zhenw/arthas/core/target/antrun/build-main.xml
[ERROR] -> [Help 1]
```

**Comment by zinking** [comment]
tried to exclude web-ui from the build, seems it will cause yarn-core to build break.

**Comment by zinking** [comment]
this patch worked as in maven ui plugin 
```
                         <configuration>
                             <arguments>vite build --mode tunnel</arguments>
+                            <arguments>install --no-proxy</arguments>
                         </configuration>
```

**Comment by RaymondLam1** [comment]
This may be an error caused by your network

**Comment by zinking** [comment]
I don't see any problem accessing my network. maybe there should be some option to skip build the ui parts as it not there previously.
