### ISSUE TITLE
arthas启动内存溢出

### ISSUE THREAD

**Issue by z-soulx** [alibaba/arthas#2776]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: arthas-boot version: 3.7.1
* 操作系统版本: Linux  5.10.109-1.el7.x86_64
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: arthas-boot version: 3.7.1

### 重现问题的步骤

1. java  -jar arthas-boot.jar
2. 1 enter

### 期望的结果

sucess

### 实际运行的结果

```
[INFO] arthas home: /root/.arthas/lib/3.7.1/arthas
[INFO] Try to attach process 1
Picked up JAVA_TOOL_OPTIONS:
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AttachOperationFailedException: java.lang.OutOfMemoryError: Java heap space
        at sun.tools.attach.LinuxVirtualMachine.execute(LinuxVirtualMachine.java:229)
        at sun.tools.attach.HotSpotVirtualMachine.executeCommand(HotSpotVirtualMachine.java:261)
        at sun.tools.attach.HotSpotVirtualMachine.getSystemProperties(HotSpotVirtualMachine.java:144)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:105)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:27)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:161)
[ERROR] attach fail, targetPid: 1
```

**Comment by hengyunabc** [comment]
arthas 本身是一个 java 代码，它加载到应用内部也是要占内存的。 当应用本身快要 OOM 时，arthas 会加载失败。
