### ISSUE TITLE
Run in JDK17 fail: Unsupported class file major version 61 in 3.7.2

### ISSUE THREAD

**Issue by dengweisysu** [alibaba/arthas#2840]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.7.2
* Arthas 版本: 3.7.2
* 操作系统版本: linux
* 目标进程的JVM版本: jdk 17
* 执行`arthas-boot`的版本: 3.7.2

### 重现问题的步骤
使用watch 
watch com.facebook.presto.orc.AbstractOrcRecordReader prepareNextBatch 'target.stripes' 'target.stripes.size()>0'  -n 2 -s  -x 1

### 期望的结果
正常watch

What do you expected from the above steps？

### 实际运行的结果

```
2024-05-26 17:47:48 [arthas-command-execute] WARN  c.t.arthas.core.advisor.Enhancer -transform loader[com.facebook.presto.server.PluginClassLoader@63513c1c]:class[com/facebook/presto/orc/OrcBatchRecordReader] failed.
java.lang.IllegalArgumentException: Unsupported class file major version 61
        at com.alibaba.deps.org.objectweb.asm.ClassReader.<init>(ClassReader.java:189)
        at com.alibaba.deps.org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
        at com.alibaba.deps.org.objectweb.asm.ClassReader.<init>(ClassReader.java:156)
        at com.alibaba.bytekit.utils.AsmUtils.toClassNode(AsmUtils.java:59)
        at com.taobao.arthas.core.advisor.Enhancer.transform(Enhancer.java:132)
        at com.taobao.arthas.core.advisor.TransformerManager$1.transform(TransformerManager.java:51)
```

**Comment by wwulfric** [comment]
我之前遇到过类似的问题，后来发现是执行Arthas的用户和执行Java进程的用户不一样，但是报错信息上没有区分开
