### ISSUE TITLE
运行arthas进程中的profiler start报错

### ISSUE THREAD

**Issue by molijun00** [alibaba/arthas#2855]
- [ √] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.72
* Arthas 版本: 3.72
* 操作系统版本: Linux  4.18.0-477.10.1.el8_8.x86_64 #1 SMP Tue May 16 11:07:48 PDT 2023 x86_64 x86_64 x86_64 GNU/Linux
* 目标进程的JVM版本: openjdk version "1.8.0_362"
* 执行`arthas-boot`的版本: 3.7.2

### 重现问题的步骤

1. ./as.sh
2. profiler start

### 期望的结果

开始执行信息收集

### 实际运行的结果

AsyncProfiler error: /tmp/ArthasJniLibrary7126202527535478252.tmp: /tmp/ArthasJniLibrary7126202527535478252.tmp: failed to map segment from shared object

```
2024-06-27 09:28:25 [arthas-command-execute] ERROR c.t.a.c.c.monitor200.ProfilerCommand -AsyncProfiler error
java.lang.UnsatisfiedLinkError: /tmp/ArthasJniLibrary7126202527535478252.tmp: /tmp/ArthasJniLibrary7126202527535478252.tmp: failed to map segment from shared object
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:782)
	at java.lang.System.load(System.java:1100)
	at one.profiler.AsyncProfiler.getInstance(AsyncProfiler.java:45)
	at com.taobao.arthas.core.command.monitor200.ProfilerCommand.profilerInstance(ProfilerCommand.java:271)
	at com.taobao.arthas.core.command.monitor200.ProfilerCommand.process(ProfilerCommand.java:358)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by molijun00** [comment]
[无法执行生成火焰图 #2143](https://github.com/alibaba/arthas/issues/2143)再该问题中有相同的异常，但是并未看到结果就关闭问题了

**Comment by 243300852** [comment]
如何解决的呢

**Comment by molijun00** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 你好，我在学习中，无法回复你邮件，请见谅

**Comment by 243300852** [comment]
1. 检查并修改 /tmp 目录挂载选项
Arthas 默认会将其 JNI 库提取到 /tmp 目录。如果 /tmp 目录被挂载为 noexec（禁止执行），就会导致此问题。

检查 /tmp 挂载选项：
在终端执行：

bash
mount | grep /tmp
如果输出中包含 noexec，例如 rw,noexec,nosuid,nodev，则这就是问题所在。

重新挂载 /tmp 目录（临时生效，重启后失效）：

bash
sudo mount -o remount,exec /tmp
注意：这可能会降低系统安全性，因为任何用户都可以在 /tmp 执行文件。操作后请尝试再次启动 Arthas。

为 Arthas 设置其他临时目录（更安全推荐）：
如果不想修改 /tmp 的挂载选项，可以为当前终端会话指定一个新的临时目录：

bash
export TMPDIR=/your/custom/tmp/dir  # 设置为一个用户有读写执行权限的目录
mkdir -p $TMPDIR
java -jar arthas-boot.jar
这样 Arthas 会使用 $TMPDIR 来存放临时库文件。

2. 检查文件和目录权限
确保当前用户对 Arthas 生成的临时 JNI 库文件及其所在目录有读、写、执行权限。

检查 /tmp 目录的权限通常是 drwxrwxrwt。

检查 Arthas 临时文件（如 /tmp/ArthasJniLibrary*.tmp）的权限。确保它们有执行权限 (x)。如果有问题，可以尝试：

bash
chmod +x /tmp/ArthasJniLibrary*.tmp
但请注意，每次启动 Arthas 生成的临时文件名不同，此方法可能更适用于一次性的情况。根本解决还需依赖上述修改挂载选项或设置 TMPDIR。

3. 清理临时文件并重试
有时旧的、损坏的临时文件也可能引发冲突。尝试手动清理 /tmp 目录下与 Arthas 相关的旧临时文件后重启 Arthas：

bash
rm -f /tmp/ArthasJniLibrary*.tmp
rm -f /tmp/arthas-*

**Comment by molijun00** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 你好，我在学习中，无法回复你邮件，请见谅
