### ISSUE TITLE
arthas、skywalking同时使用报错

### ISSUE THREAD

**Issue by cfy3133** [alibaba/arthas#2860]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.7.2
* 操作系统版本: centos7
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: 3.7.2
* skywalking版本为8.9.0、9.6.0、9.7.0、10.0都会报错

### 重现问题的步骤

1. pom.xml加入如下内容：
```
<dependency>
	<groupId>com.taobao.arthas</groupId>
	<artifactId>arthas-spring-boot-starter</artifactId>
	<version>3.7.2</version>
</dependency>
```
2. application-yace.yml
如下方式引入：
```
#arthas的配置
arthas:
  telnetPort: -1
  httpPort: -1
  appName: xxx
  agent-id: xxx
  username: xxx
  password: xxx
  tunnel-server: ws://127.0.0.1:7777/ws
```
4. 启动应用：
```
1)、java -javaagent:D:\BaiduNetdiskDownload\skywalking-agent\skywalking-agent.jar -Dskywalking.agent.service_name=yace-server -Dskywalking.collector.backend_service=192.168.3.232:11800 -jar xxx.jar  --server.port=28089 &
2)、java -jar /arthas-tunnel-server-3.7.2.jar --port=7777 --target-ip=127.0.0.1 --target-port=28089 --server.port=8086 &
```

### 期望的结果

正常启动应用，加入skywalking监控

### 实际运行的结果

运行报错

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'arthasAgent' defined in class path resource [com/alibaba/arthas/spring/ArthasConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.taobao.arthas.agent.attach.ArthasAgent]: Factory method 'arthasAgent' threw exception; nested exception is java.lang.IllegalStateException: java.lang.IllegalStateException: No compatible attachment provider is available
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
        at com.els.SrmApplication.main(SrmApplication.java:23)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.taobao.arthas.agent.attach.ArthasAgent]: Factory method 'arthasAgent' threw exception; nested exception is java.lang.IllegalStateException: java.lang.IllegalStateException: No compatible attachment provider is available
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
        ... 27 common frames omitted
Caused by: java.lang.IllegalStateException: java.lang.IllegalStateException: No compatible attachment provider is available
        at com.taobao.arthas.agent.attach.ArthasAgent.init(ArthasAgent.java:131)
        at com.alibaba.arthas.spring.ArthasConfiguration.arthasAgent(ArthasConfiguration.java:69)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 28 common frames omitted
Caused by: java.lang.IllegalStateException: No compatible attachment provider is available
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:627)
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:611)
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:563)
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:540)
        at com.taobao.arthas.agent.attach.ArthasAgent.init(ArthasAgent.java:90)
        ... 34 common frames omitted

网络解析为：遇到的问题在于SkyWalking agent和Arthas（Alibaba的Java诊断工具）之间存在冲突。具体来说，两者都试图对JVM进行字节码增强，
但它们可能不兼容，尤其是在初始化阶段。Arthas使用Byte Buddy库来实现其功能，而SkyWalking也使用了类似的技术，这可能导致了初始化时的冲突。
```

**Comment by yjqg6666** [comment]
https://arthas.aliyun.com/doc/faq.html#java-lang-classformaterror-null%E3%80%81skywalking-arthas-%E5%85%BC%E5%AE%B9%E4%BD%BF%E7%94%A8
