### ISSUE TITLE
使用arthas附上进程后，执行ognl命令异常

### ISSUE THREAD

**Issue by tkgup** [alibaba/arthas#2873]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.7.1
* Arthas 版本: 3.7.1
* 操作系统版本: centos7
* 目标进程的JVM版本: jdk1.8
* 
* 执行`arthas-boot`的版本: 1.8

### 重现问题的步骤

1：切换到指定进程的用户
2：调用arthjdk1.8.0_402/bin/java -jar arthas-boot.jar
3：输入1
4：执行命令：jad tkg.site.utils.RegexUtils match --source-only
5、结果异常

### 期望的结果

What do you expected from the above steps？

ognl执行成功，调用环境代码成功
返回True/false

### 实际运行的结果
arthas异常

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
[arthas@258974]$ jad tkg.site.utils.RegexUtils match --source-only
       public static boolean match(String type, String value) {
           Pattern pattern = REGEX_MAP.get(type);
/*20*/     if (Objects.isNull(pattern)) {
/*21*/         logger.error("Regex type {} is not defined.", (Object)type);
/*22*/         return false;
           }
/*24*/     return pattern.matcher(value).matches();
       }

[arthas@258974]$ sc tkg.site.utils.RegexUtils
tkg.site.utils.RegexUtils
Affect(row-cnt:1) cost in 20 ms.
[arthas@258974]$ ognl  -x  3 '@tkg.site.utils.RegexUtils@match("user_mame","arthas")'
Failed to execute ognl, exception message: ognl.MethodFailedException: Method "match" failed for object tkg.site.utils.RegexUtils [java.lang.ClassNotFoundException: Unable to resolve class: tkg.site.utils.RegexUtils], please check $HOME/logs/arthas/arthas.log for more details.

$HOME/logs/arthas/arthas.log:

2024-07-19 09:44:55 [arthas-command-execute] ERROR c.t.a.c.command.express.OgnlExpress -Error during evaluating the expression:
ognl.MethodFailedException: Method "match" failed for object tkg.site.utils.RegexUtils
	at ognl.OgnlRuntime.callStaticMethod(OgnlRuntime.java:1571)
	at ognl.ASTStaticMethod.getValueBody(ASTStaticMethod.java:77)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.Ognl.getValue(Ognl.java:470)
	at ognl.Ognl.getValue(Ognl.java:572)
	at ognl.Ognl.getValue(Ognl.java:542)
	at com.taobao.arthas.core.command.express.OgnlExpress.get(OgnlExpress.java:40)
	at com.taobao.arthas.core.command.klass100.OgnlCommand.process(OgnlCommand.java:105)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: Unable to resolve class: tkg.site.utils.RegexUtils
	at ognl.OgnlRuntime.classForName(OgnlRuntime.java:1189)
	at ognl.OgnlRuntime.callStaticMethod(OgnlRuntime.java:1563)
	... 20 common frames omitted
2024-07-19 09:44:55 [arthas-command-execute] WARN  c.t.a.c.command.klass100.OgnlCommand -ognl: failed execute express: @tkg.site.utils.RegexUtils@match("user_mame","arthas")
com.taobao.arthas.core.command.express.ExpressException: ognl.MethodFailedException: Method "match" failed for object tkg.site.utils.RegexUtils [java.lang.ClassNotFoundException: Unable to resolve class: tkg.site.utils.RegexUtils]
	at com.taobao.arthas.core.command.express.OgnlExpress.get(OgnlExpress.java:43)
	at com.taobao.arthas.core.command.klass100.OgnlCommand.process(OgnlCommand.java:105)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: ognl.MethodFailedException: Method "match" failed for object tkg.site.utils.RegexUtils
	at ognl.OgnlRuntime.callStaticMethod(OgnlRuntime.java:1571)
	at ognl.ASTStaticMethod.getValueBody(ASTStaticMethod.java:77)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.Ognl.getValue(Ognl.java:470)
	at ognl.Ognl.getValue(Ognl.java:572)
	at ognl.Ognl.getValue(Ognl.java:542)
	at com.taobao.arthas.core.command.express.OgnlExpress.get(OgnlExpress.java:40)
	... 13 common frames omitted
Caused by: java.lang.ClassNotFoundException: Unable to resolve class: tkg.site.utils.RegexUtils
	at ognl.OgnlRuntime.classForName(OgnlRuntime.java:1189)
	at ognl.OgnlRuntime.callStaticMethod(OgnlRuntime.java:1563)
	... 20 common frames omitted

```
把异常信息贴到这里
```
内网，无法贴截图，文字信息如上

**Comment by tkgup** [comment]
通过-c 指定classloader就可以了
