### ISSUE TITLE
在weblogic中使用报错

### ISSUE THREAD

**Issue by hexian** [alibaba/arthas#2969]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：arthas-all-4.0.4
* Arthas 版本: 4.0.4
* 操作系统版本: windows 2003 server
* 目标进程的JVM版本:   jdk1.8.0_111
* 执行`arthas-boot`的版本: 4.0.4

### 重现问题的步骤

1. weblogic部署了一个ejb项目
2. 执行 trace 20000 -skipJDKMethod false psdi.webclient.servlet.WebClientServlet handleRequest  -x 100
3. 报如下错误： ognl.NoSuchPropertyException: com.taobao.arthas.core.advisor.Advice.o

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
024-12-09 16:17:54 [[ACTIVE] ExecuteThread: '1' for queue: 'weblogic.kernel.Default (self-tuning)'] ERROR c.t.a.c.command.express.OgnlExpress -Error during evaluating the expression:
ognl.NoSuchPropertyException: com.taobao.arthas.core.advisor.Advice.o
2024-12-09 16:17:54 [[ACTIVE] ExecuteThread: '1' for queue: 'weblogic.kernel.Default (self-tuning)'] WARN  c.t.a.c.c.m.AbstractTraceAdviceListener -trace failed.
com.taobao.arthas.core.command.express.ExpressException: ognl.NoSuchPropertyException: com.taobao.arthas.core.advisor.Advice.o
	at com.taobao.arthas.core.command.express.OgnlExpress.get(OgnlExpress.java:39)
	at com.taobao.arthas.core.command.express.OgnlExpress.is(OgnlExpress.java:45)
	at com.taobao.arthas.core.advisor.AdviceListenerAdapter.isConditionMet(AdviceListenerAdapter.java:119)
	at com.taobao.arthas.core.command.monitor200.AbstractTraceAdviceListener.finishing(AbstractTraceAdviceListener.java:90)
	at com.taobao.arthas.core.command.monitor200.AbstractTraceAdviceListener.afterReturning(AbstractTraceAdviceListener.java:60)
	at com.taobao.arthas.core.advisor.AdviceListenerAdapter.afterReturning(AdviceListenerAdapter.java:57)
	at com.taobao.arthas.core.advisor.SpyImpl.atExit(SpyImpl.java:67)
	at java.arthas.SpyAPI.atExit(SpyAPI.java:64)
	at psdi.webclient.servlet.WebClientServlet.handleRequest(WebClientServlet.java:80)
	at psdi.webclient.servlet.WebClientServlet.doPost(WebClientServlet.java:21)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:751)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:844)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:280)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:254)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:136)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:346)
	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
	at psdi.webclient.system.filter.HttpCrossSiteScriptingSecurity.doFilter(HttpCrossSiteScriptingSecurity.java:66)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
	at psdi.webclient.system.filter.MXCorrelationFilter.doFilter(MXCorrelationFilter.java:137)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
	at psdi.webclient.system.filter.PerformanceMonitor.doFilter(PerformanceMonitor.java:126)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
	at psdi.webclient.system.filter.HttpXFrameOptionsFilter.doFilter(HttpXFrameOptionsFilter.java:38)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
	at psdi.webclient.system.filter.MTContextFilter.doFilter(MTContextFilter.java:53)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3436)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3402)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2285)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2201)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2179)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1572)
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:255)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:263)
```

**Comment by hexian** [comment]
不使用-x就不报错，但是我需要更深的调用链路

**Comment by hexian** [comment]
可否实现以及基于JPDA实现的链路追踪？  APM这个通过agent的需要对特定框架进行编码支持,而基于JPDA的应该不存在这个问题

**Comment by hexian** [comment]
不支持-x参数
