### ISSUE TITLE
离线内网安装arthas正常，但是启动as.sh 错误 

### ISSUE THREAD

**Issue by grainrain** [alibaba/arthas#33]
环境：
```
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.8 (Santiago)
Release:	6.8
Codename:	Santiago
```

arthas版本
```arthas-packaging-3.0.0-RC-bin```

JDK 版本 
```
java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)
```
错误如下：

```
Calculating attach execution time...
Attaching to 30267 using version 0.0...
Start arthas failed, exception stack trace: 
java.lang.IllegalStateException: as.sh is too old to support web console, please run the following command to upgrade to latest version:
curl -sLk http://arthas.io/arthas/install.sh | sh
	at com.taobao.arthas.core.Arthas.parse(Arthas.java:44)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:23)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:86)
错误: 找不到或无法加载主类 com.taobao.arthas.core.ArthasConsole
```

**Comment by grainrain** [comment]
只能内网安装  ./install_local.sh

**Comment by grainrain** [comment]
只能内网安装./install_local.sh

**Comment by grainrain** [comment]
```
/home/xxxxx/.arthas
`-- lib
    `-- 0.0
        `-- arthas
            |-- arthas-agent.jar
            |-- arthas-client.jar
            |-- arthas-core.jar
            `-- arthas-spy.jar
```
内网安装 ./install_local.sh

**Comment by hengyunabc** [comment]
主页上的安装说明更新了，可以试下新版本：https://alibaba.github.io/arthas/install-detail.html
