### ISSUE TITLE
win10启动报错

### ISSUE THREAD

**Issue by zgl1011** [alibaba/arthas#35]
![image](https://user-images.githubusercontent.com/26699764/45603979-43b07800-ba62-11e8-9a71-e690acec3e79.png)

**Comment by javacoderxxp** [comment]
同问

**Comment by ralf0131** [comment]
It looks like the port 3658 could not be connected. Please check the logs `$HOME/logs/arthas/arthas.log` to see if there is any exception.

**Comment by javacoderxxp** [comment]
01 2018-09-17 10:44:03.551 ERROR [arthas-binding-thread:arthas] [] [] [] Error during bind to port 3658
java.lang.ExceptionInInitializerError: null
	at com.taobao.arthas.core.shell.ShellServerOptions.<clinit>(ShellServerOptions.java:29) ~[na:na]
	at com.taobao.arthas.core.server.ArthasBootstrap.bind(ArthasBootstrap.java:82) ~[arthas-core.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at com.taobao.arthas.agent.AgentBootstrap.bind(AgentBootstrap.java:158) [arthas-agent.jar:na]
	at com.taobao.arthas.agent.AgentBootstrap.access$000(AgentBootstrap.java:15) [arthas-agent.jar:na]
	at com.taobao.arthas.agent.AgentBootstrap$1.run(AgentBootstrap.java:125) [arthas-agent.jar:na]
Caused by: java.lang.NullPointerException: null
	at java.io.Reader.<init>(Reader.java:78) ~[na:1.8.0_121]
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72) ~[na:1.8.0_121]
	at com.taobao.arthas.core.util.IOUtils.toString(IOUtils.java:134) ~[arthas-core.jar:na]
	at com.taobao.arthas.core.util.ArthasBanner.<clinit>(ArthasBanner.java:33) ~[na:na]
	... 9 common frames omitted

**Comment by javacoderxxp** [comment]
arthas的启动需要绑定3658端口吗

**Comment by nzomkxia** [comment]
是的 需要绑定3658端口

**Comment by javacoderxxp** [comment]
我看了下，win10下3658端口并没有被占用，为什么arthas会绑定失败啊

**Comment by ralf0131** [comment]
Hi, this is not because 3658 port is being used. I looks like some internal error during initialization.

**Comment by hengyunabc** [comment]
更新了文档，可以试下最新版本： https://alibaba.github.io/arthas/install-detail.html

**Comment by javacoderxxp** [comment]
可以了 666

**Comment by yonusona** [comment]
怎么解决的啊 @javacoderxxp
