### ISSUE TITLE
启动一个jvm进程（非tomcat或其他容器），使用arthas报错

### ISSUE THREAD

**Issue by zhengxgs** [alibaba/arthas#350]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0.5
* 操作系统版本: linux
* 目标进程的JVM版本: jdk1.8

### 实际运行的结果

[INFO] arthas home: /root/.arthas/lib/3.0.5/arthas
[INFO] Try to attach process 29201
[INFO] Attach process 29201 success.
[INFO] arthas-client connect 127.0.0.1 3658
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: 拒绝连接 (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
	at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:268)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:428)

**Comment by 595979101** [comment]
如何解决的@zhengxgs 我也遇到这个问题了。求分享下

**Comment by hengyunabc** [comment]
> 如何解决的@zhengxgs 我也遇到这个问题了。求分享下

可以先试下文档里的 arthas-demo

**Comment by zhengxgs** [comment]
> 如何解决的@zhengxgs 我也遇到这个问题了。求分享下

安装telnet

**Comment by gosenme** [comment]
@zhengxgs 已经有安装了telnet了。命令可以正常使用，但是报错和以上完全相同。

**Comment by cyril-x** [comment]
偶发性的connection refused，重启应用就好了。。求解
