### ISSUE TITLE
as.sh do not support batch mode

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#363]
```
as.sh -c 'sysprop; thread' 81719

Arthas script version: 3.0.5
```

```
com.taobao.middleware.cli.CLIException: Cannot inject value for argument '1'
	at com.taobao.middleware.cli.annotations.CLIConfigurator.inject(CLIConfigurator.java:270)
	at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:168)
Caused by: com.taobao.middleware.cli.InvalidValueException: The value '-p' is not accepted by the argument 'port'
	at com.taobao.middleware.cli.impl.DefaultCommandLine.create(DefaultCommandLine.java:315)
	at com.taobao.middleware.cli.impl.DefaultCommandLine.getArgumentValue(DefaultCommandLine.java:171)
	at com.taobao.middleware.cli.annotations.CLIConfigurator.getArgumentValue(CLIConfigurator.java:230)
	at com.taobao.middleware.cli.annotations.CLIConfigurator.inject(CLIConfigurator.java:264)
	... 1 more
Caused by: java.lang.IllegalArgumentException: java.lang.NumberFormatException: For input string: "-p"
	at com.taobao.middleware.cli.converters.ConstructorBasedConverter.fromString(ConstructorBasedConverter.java:70)
	at com.taobao.middleware.cli.converters.Converters.create(Converters.java:52)
	at com.taobao.middleware.cli.impl.DefaultCommandLine.create(DefaultCommandLine.java:312)
	... 4 more
Caused by: java.lang.NumberFormatException: For input string: "-p"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.<init>(Integer.java:867)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.taobao.middleware.cli.converters.ConstructorBasedConverter.fromString(ConstructorBasedConverter.java:67)
	... 6 more
Usage: arthas-client [-w <value>] [--help] [-c <value>] [-f <value>] [-h
       <value>] [target-ip] [port]
```

**Comment by hengyunabc** [comment]
Thanks to  @sishen .
