### ISSUE TITLE
如何attach到tomcat

### ISSUE THREAD

**Issue by suizhe** [alibaba/arthas#365]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

直接使用windows服务启动的tomcat如何进行监控？进程中只有tomcat7.exe，没有办法attach到这个进程上。

**Comment by hengyunabc** [comment]
贴出具体执行什么命令 和结果。

可以试下最新的 `wget https://alibaba.github.io/arthas/arthas-boot.jar` 。或者直接参数里指定 pid

**Comment by suizhe** [comment]
直接执行java -jar arthas-boot.jar  没有列出任何的进程id，指定tomcat.exe的进行id报错:
```
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AttachNotSupportedException: Insufficient memory or insuffi
cient privileges to attach
        at sun.tools.attach.WindowsVirtualMachine.<init>(WindowsVirtualMachine.j
ava:64)
        at sun.tools.attach.WindowsAttachProvider.attachVirtualMachine(WindowsAt
tachProvider.java:69)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:70)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:25)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:99)
```

**Comment by hengyunabc** [comment]
执行 jps 看有没有进程。

tomcat应该没问题。可以试下到tomcat目录，用bat启动tomcat。

**Comment by suizhe** [comment]
用bat是可以的， 使用 Commons Daemon Service Runner 这个工具把tomcat安装成了windows服务就不行了。

**Comment by gt2ming** [comment]
> 用bat是可以的， 使用 Commons Daemon Service Runner 这个工具把tomcat安装成了windows服务就不行了。

遇到了同样的问题，也是用Commons Daemon Service Runner 封装的，请问后来是如何解决的呢？

**Comment by kylixs** [comment]
诊断 windows 服务的tomcat请参考这里：https://arthas.aliyun.com/doc/manual-install.html?#windows

> 使用以下命令诊断windows服务模式运行的Java进程 (–interact 打开服务UI交互模式，方便诊断问题)：
> 
> ```
> as-service.bat -port <port>
> as-service.bat -pid <pid>
> as-service.bat -pid <pid> --interact
> ```
> 清理arthas windows服务执行以下命令：
> 
> `as-service.bat -remove`
