### ISSUE TITLE
Vmware虚拟机Centos，启动demo异常No such peocess

### ISSUE THREAD

**Issue by luoxiaoge** [alibaba/arthas#368]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* Arthas 版本: arthas-boot.jar
* 操作系统版本: centos
Linux version 3.10.0-957.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) )
* 目标进程的JVM版本: 
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

### 重现问题的步骤

1. java -jar arthas-boot.jar 8080

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
[root@localhost arthas]# java -jar arthas-boot.jar
[INFO] arthas-boot version: 3.0.5.1
[INFO] Can not find java process. Try to pass <pid> in command line.
Please select an avaliable pid.
[root@localhost arthas]# java -jar arthas-boot.jar 8080
[INFO] arthas-boot version: 3.0.5.1
[INFO] arthas home: /root/.arthas/lib/3.0.5/arthas
[INFO] Try to attach process 8080
[ERROR] Start arthas failed, exception stack trace: 
java.io.IOException: No such process
	at sun.tools.attach.LinuxVirtualMachine.sendQuitTo(Native Method)
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:91)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:70)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:25)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:99)
[ERROR] attach fail, targetPid: 8080

**Comment by hengyunabc** [comment]
* 执行 jps 看有没有java进程，没有的话，试下文档里的arthas-demo
* arthas-boot.jar 后面接的不是端口，是进程 pid
