### ISSUE TITLE
ProcessUtils查找tools.jar的方式错误，导致无法找到

### ISSUE THREAD

**Issue by yunzhongniao** [alibaba/arthas#383]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0.5.1
* Arthas 版本: 3.0.5.1
* 操作系统版本: win10
* 目标进程的JVM版本:jdk8
* 执行`arthas-boot`的版本: 3.0.5.1

### 重现问题的步骤

1. ProcessUtils查找tools.jar的方式错误，导致无法找到
实际路径：javahome + ./lib/tools.jar
代码查找路径：javahome +../lib/tools.jar

```
        at com.taobao.arthas.boot.ProcessUtils.findToolsJar(ProcessUtils.java:321)
        at com.taobao.arthas.boot.ProcessUtils.startArthasCore(ProcessUtils.java:203)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:411)
```

**Comment by hengyunabc** [comment]
可以测试下这个新的 arthas-boot.jar ，看能否工作：

[arthas-boot.jar.zip](https://github.com/alibaba/arthas/files/2694611/arthas-boot.jar.zip)

在我测试的结果里，即使是jdk/bin/java 启动的进程，获取到的`java.home`都是 jre 目录，所以打 tools.jar时，要向上一级。

**Comment by garenchan** [comment]
他的这种问题的确是存在的，`findJavaHome`有可能返回jdk目录(jdk目录不一定为jre目录的父目录)，这样后续通过找其父目录和祖父目录就会找不到`tools.jar`.

https://github.com/alibaba/arthas/blob/69a9f4f03b9f8ee2302cd5d37a81de45cf55392b/boot/src/main/java/com/taobao/arthas/boot/ProcessUtils.java#L313-L322

**Comment by hengyunabc** [comment]
已经更新了，可以再重新试下：

```sh
wget https://alibaba.github.io/arthas/arthas-boot.jar
java -jar arthas-boot.jar
```

**Comment by yunzhongniao** [comment]
问题已经修复了，windows下可以启动，赞！

**Comment by kenzhaoyihui** [comment]
![image](https://user-images.githubusercontent.com/18360375/118093298-d23a4a80-b3ff-11eb-9ce0-6889ad4778fd.png)

如果是jre 的， 只能把tools.jar 放到ext目录下， 但是会报找不到； 如果放到jre/lib/ 目录下， 会报java.lang.UnsatisfiedLinkError: no attach in java.library.path

**Comment by kenzhaoyihui** [comment]
@yunzhongniao 有空帮忙看下

**Comment by gaochengyidlmu** [comment]
@kenzhaoyihui 
@yunzhongniao 
我也有这个问题，java.lang.UnsatisfiedLinkError: no attach in java.library.path。
场景就是，公司环境不能用 jdk，只能用已有的 jre。然后将 tools.jar 包手动copy 到 jre/lib 中，会报这个错。

```bash
[INFO] JAVA_HOME: /opt/xxx/jre
[INFO] arthas-boot version: 3.6.7
[DEBUG] Repo mirror:aliyun
[INFO] arthas home: /home/xxx/arthas
[INFO] Try to attach process 65280
[DEBUG] Start arthas-core.jar args: [-jar, /home/xxx/arthas/arthas-core.jar, -pid, 65280, -core, /home/xxx/arthas/arthas-core.jar, -agent, /home/xxx/arthas/arthas-agent.jar]
[DEBUG] Found java: /opt/xxx/jre/bin/java
[DEBUG] Found tools.jar: /opt/xxx/jre/lib/tools.jar
Picked up JAVA_TOOL_OPTIONS: 
[ERROR] Start arthas failed, exception stack trace: 
java.lang.UnsatisfiedLinkError: no attach in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
        at java.lang.Runtime.loadLibrary0(Runtime.java:843)
        at java.lang.System.loadLibrary(System.java:1136)
        at sun.tools.attach.LinuxVirtualMachine.<clinit>(LinuxVirtualMachine.java:342)
        at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:102)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:27)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:161)
```

从日志上看，可以找到 tools.jar，但是仍有报错。
