### ISSUE TITLE
请问一下，NoSuchMethodError怎么定位到调用该方法的具体位置。

### ISSUE THREAD

**Issue by haiyes** [alibaba/arthas#394]
### 重现问题的步骤
最近小弟在使用hive执行数据导入到hbase时报错：
  java.lang.NoSuchMethodError: org.apache.hadoop.tracing.SpanReceiverHost.getInstance(Lorg/apache/hadoop/conf/Configuration;)Lorg/apache/hadoop/tracing/SpanReceiverHost;
	at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.initialize(LogicalIOProcessorRuntimeTask.java:271)
	at org.apache.tez.runtime.task.TaskRunner2Callable$1.run(TaskRunner2Callable.java:69)
	at org.apache.tez.runtime.task.TaskRunner2Callable$1.run(TaskRunner2Callable.java:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.tez.runtime.task.TaskRunner2Callable.callInternal(TaskRunner2Callable.java:61)
	at org.apache.tez.runtime.task.TaskRunner2Callable.callInternal(TaskRunner2Callable.java:37)
	at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
小弟通过查看hive\hadoop\tez源码确认了以下问题：
1. hadoop2.7确实没SpanReceiverHost.getInstance这个方法。
2. tez0.9\hive2.3源码里也没有调用SpanReceiverHost.getInstance的地方。

### 期望的结果
想请问下，arthas能否定位到是哪个类，哪个方法调用了SpanReceiverHost.getInstance导致的报错。

**Comment by hengyunabc** [comment]
参考下这个： https://github.com/alibaba/arthas/issues/160

**Comment by haiyes** [comment]
> 参考下这个： #160

刚才有看过这个的，也试着处理过。
能确定确实是没有这个方法，现在的问题是定位不到这个方法调用的具体位置。
