### ISSUE TITLE
 Unable to attach to 64-bit pro cess

### ISSUE THREAD

**Issue by freedomme** [alibaba/arthas#408]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.0.5
* 操作系统版本: win7
* 目标进程的JVM版本: jdk1.8
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

E:\arthas-packaging>as.bat 9112
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AttachNotSupportedException: Unable to attach to 64-bit pro
cess
        at sun.tools.attach.WindowsVirtualMachine.openProcess(Native Method)
        at sun.tools.attach.WindowsVirtualMachine.<init>(WindowsVirtualMachine.j
ava:56)
        at sun.tools.attach.WindowsAttachProvider.attachVirtualMachine(WindowsAt
tachProvider.java:69)
        at com.sun.tools.attach.spi.AttachProvider.attachVirtualMachine(AttachPr
ovider.java:194)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:72)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:25)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:99)

E:\arthas-packaging>

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
用和目标进程一致的jdk来attach。不要用32 bit的来attach 64 bit的jdk。

windows下建议用 `java -jar arthas-boot.jar`

**Comment by freedomme** [comment]
> 用和目标进程一致的jdk来attach。不要用32 bit的来attach 64 bit的jdk。
> 
> windows下建议用 `java -jar arthas-boot.jar`

不要用32 bit的来attach 64 bit的jdk ？能具体些吗，我是在不懂这句话含义，执行java -jar arthas-boot.jar命令是64位

**Comment by hengyunabc** [comment]
`E:\arthas-packaging>as.bat 9112` 里启动的jvm是32 bit的。要attach的进程9112所用的jvm是64 bit的。

`java -version` 会打印出它是32 bit还是 64 bit的。

最好是找到`9112`进程所用的jdk，然后用全路径来启动：`/xxx/jdk/bin/java -jar arthas-boot.jar`。

**Comment by hengyunabc** [comment]
先close掉，后续有需要再打开。
