### ISSUE TITLE
Linux web console功能支持报错

### ISSUE THREAD

**Issue by WengJim** [alibaba/arthas#436]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0.5.2
* Arthas 版本: 3.0.5.2
* 操作系统版本: Linux centos7
* 目标进程的JVM版本: jdk8
* 执行`arthas-boot`的版本: 3.0.5.2

### 重现问题的步骤

1. xterm.js下载了
2. 执行命令 java -jar arthas-boot.jar

### 期望的结果

What do you expected from the above steps？
连接正常

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

[root@localhost arthas]# java -jar arthas-boot.jar
[INFO] arthas-boot version: 3.0.5.2
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 4605 /usr/lib/jenkins/jenkins.war

[INFO] arthas home: /root/.arthas/lib/3.0.5/arthas
[INFO] Try to attach process 4605
[ERROR] Start arthas failed, exception stack trace: 
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:72)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:25)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:99)
[ERROR] attach fail, targetPid: 4605

把异常信息贴到这里

![image](https://user-images.githubusercontent.com/19164836/50804988-61645e80-132b-11e9-87de-aad230c50892.png)

**Comment by WengJim** [comment]
> * 这个是在attach时失败了，建议切换到和jenkins一样的用户来执行
> * web console不需要下面 xterm.js，attach成功的话，访问 http://localhost:8563/ 就可以了

已切换用户，处理完成。谢谢
