### ISSUE TITLE
AttachNotSupportedException

### ISSUE THREAD

**Issue by franciszhang** [alibaba/arthas#440]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

 * `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0.5.2
 * Arthas 版本: 3.0.5.2
 * 操作系统版本: Linux centos7
 * 目标进程的JVM版本: jdk8
 * 执行`arthas-boot`的版本: 3.0.5.2

### 重现问题的步骤

1. 执行命令 java -jar arthas-boot.jar

### 期望的结果

What do you expected from the above steps？
连接正常

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
```

[root@VM_51_224_centos ~]#  java -jar arthas-boot.jar
[INFO] arthas-boot version: 3.0.5.2
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 11630 org.apache.catalina.startup.Bootstrap

[INFO] arthas home: /root/.arthas/lib/3.0.5/arthas
[INFO] Try to attach process 11630
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:72)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:25)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:99)
[ERROR] attach fail, targetPid: 11630
[root@VM_51_224_centos ~]#
```
![image](https://user-images.githubusercontent.com/12781273/51011479-a8548d00-1593-11e9-8b88-902f8232265b.png)

**Comment by hengyunabc** [comment]
参考： https://github.com/alibaba/arthas/issues/347
