### ISSUE TITLE
jdk11.0.1 jad class 报错

### ISSUE THREAD

**Issue by ruokkkkk** [alibaba/arthas#450]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0.5.2
* Arthas 版本: 3.0.5
* 操作系统版本: Linux 4.9.0-0.bpo.6-amd64 
* 目标进程的JVM版本: openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

* 执行`arthas-boot`的版本:3.0.5

### 重现问题的步骤

1.  sc -d pleiades.business.gateway.view.module.view.service.LimitService
![image](https://user-images.githubusercontent.com/7558849/51156057-e49a2d00-18b4-11e9-8774-2ce02cb8bf9a.png)

2.  jad -c 7dc7cbad pleiades.business.gateway.view.module.view.service.LimitService

3. 
![image](https://user-images.githubusercontent.com/7558849/51156162-40fd4c80-18b5-11e9-97a3-3a75160bca74.png)

### 期望的结果
What do you expected from the above steps？

成功反编译该类
### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```反编译失败
把异常信息贴到这里
```
01 2019-01-15 10:54:45.183 ERROR [as-command-execute-daemon:arthas] [] [] [] jad: fail to decompile class: pleiades.business.gateway.view.module.view.service.LimitService
java.lang.instrument.UnmodifiableClassException: null
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method) ~[na:na]
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167) ~[na:na]
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:393) ~[arthas-core.jar:3.0.5]
        at com.taobao.arthas.core.command.klass100.JadCommand.processExactMatch(JadCommand.java:111) ~[arthas-core.jar:3.0.5]
        at com.taobao.arthas.core.command.klass100.JadCommand.process(JadCommand.java:96) ~[arthas-core.jar:3.0.5]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82) ~[arthas-core.jar:3.0.5]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18) ~[arthas-core.jar:3.0.5]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111) ~[arthas-core.jar:3.0.5]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108) ~[arthas-core.jar:3.0.5]
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370) ~[arthas-core.jar:3.0.5]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

其他stack, trace, monitor会出现下面错误
![image](https://user-images.githubusercontent.com/7558849/51156624-6ab77300-18b7-11e9-9e86-8298a60af2a9.png)
sm发现方法存在日志没报错
![image](https://user-images.githubusercontent.com/7558849/51156781-0a750100-18b8-11e9-80cf-881d28114b13.png)

**Comment by hengyunabc** [comment]
我测试openjdk 11.0.1+13 没有问题：

```
$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

使用的是 `arthas-boot.jar`。

OS: mac/linux 都测试过。测试程序是 https://alibaba.github.io/arthas/quick-start.html 里的 `arthas-demo.jar` 。

你可以试下`arthas-demo.jar` 或者提交一个测试Demo。

**Comment by moviewang** [comment]
额 quick-start的demo确实可以通过

**Comment by hengyunabc** [comment]
> 额 quick-start的demo确实可以通过

最好提供一个demo，有可能是目前Arthas依赖的asm版本比较低的问题。

**Comment by moviewang** [comment]
可以 看下这个https://github.com/moviewang/arthas-demo/blob/master/build/libs/demo-0.0.1-SNAPSHOT.jar
monitor stack trace 命令都有问题

**Comment by hengyunabc** [comment]
@moviewang 试下这个版本：

[arthas-3.0.6-SNAPSHOT-bin.zip](https://github.com/alibaba/arthas/files/2758987/arthas-3.0.6-SNAPSHOT-bin.zip)

**Comment by moviewang** [comment]
这个版本可以 
3.0,5版本不可以的原因是什么呢

**Comment by hengyunabc** [comment]
> 这个版本可以
> 3.0,5版本不可以的原因是什么呢

参考 #425 ，低版本的asm不支持 target为 11的`.class`。asm 7.0版本才正式支持。
