### ISSUE TITLE
初次使用下载arthas-boot.jar，使用--versions因目录~/.arthas/lib不存在导致listNames中dir.listFiles报空指针异常

### ISSUE THREAD

**Issue by alexzyp** [alibaba/arthas#456]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0.5.2
* Arthas 版本: 3.0.5.2
* 操作系统版本: CentOS Linux release 7.4.1708 (Core)
* 目标进程的JVM版本: Oracle JDK 1.8.0_111-b14
* 执行`arthas-boot`的版本: 3.0.5.2

### 重现问题的步骤

1. wget https://alibaba.github.io/arthas/arthas-boot.jar
2. java -jar arthas-boot.jar --versions

### 期望的结果

What do you expected from the above steps？

显示版本信息

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
[INFO] arthas-boot version: 3.0.5.2
Exception in thread "main" java.lang.NullPointerException
        at com.taobao.arthas.boot.Bootstrap.listNames(Bootstrap.java:472)
        at com.taobao.arthas.boot.Bootstrap.listVersions(Bootstrap.java:452)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:233)
```

**Comment by alexzyp** [comment]
可以简单判断修复嘛？
```
diff --git a/boot/src/main/java/com/taobao/arthas/boot/Bootstrap.java b/boot/src/main/java/com/taobao/arthas/boot/Bootstrap.java
index ad5e89d..788ec34 100644
--- a/boot/src/main/java/com/taobao/arthas/boot/Bootstrap.java
+++ b/boot/src/main/java/com/taobao/arthas/boot/Bootstrap.java
@@ -469,6 +469,10 @@ public class Bootstrap {

     private static List<String> listNames(File dir) {
         List<String> names = new ArrayList<String>();
+        File[] files = dir.listFiles();
+        if (files == null) {
+            return names;
+        }
         for (File file : dir.listFiles()) {
             String name = file.getName();
             if (name.startsWith(".") || file.isFile()) {
````

**Comment by hengyunabc** [comment]
可以提个PR来修复下 👍

**Comment by hengyunabc** [comment]
非常感谢，已经修复。
