### ISSUE TITLE
目标服务设置-Xss过小导致client创建失败

### ISSUE THREAD

**Issue by zhanglei86** [alibaba/arthas#487]
### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0.5
* Arthas 版本: 3.0.5
* 操作系统版本: mac
* 目标进程的JVM版本: oracle jdk 1.8.0_191
* 执行`arthas-boot`的版本: 3.0.5

### 重现问题的步骤

1. 目标服务设置了jvm参数，-Xss=160k

### 期望的结果
通过arthas能连接上该pid

### 实际运行的结果

```
[INFO] arthas-client connect 127.0.0.1 3658
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at org.apache.commons.net.telnet.TelnetInputStream.__read(TelnetInputStream.java:132)
	at org.apache.commons.net.telnet.TelnetInputStream.run(TelnetInputStream.java:603)
	at java.lang.Thread.run(Thread.java:748)
```

```
Arthas server agent start...
Arthas start to bind...
01 2019-01-30 10:16:26.703 INFO [arthas-binding-thread:arthas] [] [] [] arthas version: 3.0.5
01 2019-01-30 10:16:27.150 ERROR [arthas-binding-thread:arthas] [] [] [] Error during bind to port 3658
java.lang.StackOverflowError: null
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_191]

Arthas server port binding failed! Please check $HOME/logs/arthas/arthas.log for more details.
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.taobao.arthas.agent.AgentBootstrap.bind(AgentBootstrap.java:165)
        at com.taobao.arthas.agent.AgentBootstrap.access$000(AgentBootstrap.java:15)
        at com.taobao.arthas.agent.AgentBootstrap$1.run(AgentBootstrap.java:125)
Caused by: java.lang.StackOverflowError
```

### 优化后
经过一系列折腾后，终于发现是线程堆栈大小的问题。

-Xss=201k 连接成功

### 期望
`java -jar arthas-boot.jar`后报错原因不明，首次体验，通过以上log几乎看不出来，期望给具体点，像`The stack size specified is too small, Specify at least 160k`.

**Comment by hengyunabc** [comment]
😂 ，StackOverflowError 的异常信息还是很明确的。单独对这个处理感觉也不必要。后续再有用户遇到类似问题，再考虑处理。
