### ISSUE TITLE
arthas crash when attached to a program which is being debugged

### ISSUE THREAD

**Issue by andxu** [alibaba/arthas#489]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: arthas-boot version: 3.0.5.2
* Operating System version: Windows_NT x64 10.0.17763
* Java version of target JVM: java version "1.8.0_201
* Java version of JVM used to attach: java version "1.8.0_201

### Steps to reproduce this issue

1. Open the `MathGame` project in the `demo` folder in vscode(need to install java debugger plugin)
2. Set a breakpoint on method `primeFactors` and F5 to start debug the program
3. Start  `arthas` by `java -jar arthas-boot.jar` and select the process id running MathGame.
4. Keep on pressing F5 to continue when the breakpoint is hit and sometimes the jvm will crash.

### Expected Result

What do you expected from the above steps？

### Actual Result

The error from the MathGame
```
illegalArgumentCount: 47, number is: -76186, need >= 2
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (oops/constantPool.hpp:358), pid=99440, tid=0x000000000001d614
#  guarantee(tag_at(which).is_klass()) failed: Corrupted constant pool
#
# JRE version: Java(TM) SE Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.191-b12 mixed mode windows-amd64 compressed oops)
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# c:\work\arthas\demo\hs_err_pid99440.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

The error from arthas:
```
ts=2019-01-31 12:12:32; [cost=0.0787ms] result=null
ts=2019-01-31 12:12:33; [cost=0.1799ms] result=@ArrayList[
    @Integer[5],
    @Integer[35839],
]
ts=2019-01-31 12:12:36; [cost=0.245ms] result=null
ts=2019-01-31 12:12:39; [cost=0.0255ms] result=@ArrayList[
    @Integer[5],
    @Integer[7],
    @Integer[13],
    @Integer[103],
]
ts=2019-01-31 12:12:42; [cost=0.0474ms] result=null
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.io.BufferedInputStream.read1(Unknown Source)
        at java.io.BufferedInputStream.read(Unknown Source)
        at java.io.BufferedInputStream.fill(Unknown Source)
        at java.io.BufferedInputStream.read(Unknown Source)
        at org.apache.commons.net.telnet.TelnetInputStream.__read(TelnetInputStream.java:132)
        at org.apache.commons.net.telnet.TelnetInputStream.run(TelnetInputStream.java:603)
        at java.lang.Thread.run(Unknown Source)
```
The log file is uploaded:
[hs_err_pid99440.log](https://github.com/alibaba/arthas/files/2815678/hs_err_pid99440.log)

**Comment by hengyunabc** [comment]
My personal experience, after the JDK 1.8.0_112 version, it is easy to crash when using the agent attach, it is not clear what the problem is.

**Comment by hengyunabc** [comment]
再仔细看了下，可能是 禁止掉了JIT引起的，VM参数`-Djava.compiler=NONE` ：

```
VM Arguments:
jvm_args: -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=localhost:54792,server=n,suspend=y -Dfile.encoding=UTF-8
java_command: demo.MathGame
```

异常栈显示：

```
---------------  T H R E A D  ---------------

Current thread (0x000000000313e800):  JavaThread "main" [_thread_in_vm, id=120340, stack(0x0000000003240000,0x0000000003340000)]

Stack: [0x0000000003240000,0x0000000003340000]
[error occurred during error reporting (printing stack bounds), id 0xc0000005]

Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  demo.MathGame.primeFactors(I)Ljava/util/List;+-13688
j  demo.MathGame.run()V+13
j  demo.MathGame.main([Ljava/lang/String;)V+9
v  ~StubRoutines::call_stub
```


`-Xnoagent`这个参数也有点奇怪，好像是IBM才有的： https://www.ibm.com/support/knowledgecenter/SSYKE2_7.1.0/com.ibm.java.win.71.doc/diag/appendixes/cmdline/commands_jvm.html
