### ISSUE TITLE
能否通过Arthas显式close一个挂起的socket?

### ISSUE THREAD

**Issue by zhugw** [alibaba/arthas#507]
需求：

线上一个Thread 每隔1秒接收Socket服务端的数据 做相应的业务处理

```
while(true) {
    Socket socket = null;
    GZIPInputStream gzis = null;
    ObjectInputStream ois = null;
    try {
        socket = new Socket(IP, PORT);
        gzis = new GZIPInputStream(socket.getInputStream());
        ois = new ObjectInputStream(gzis);
        Map<Integer, Object> result = (Map<Integer, Object>) ois.readObject();
        doSomeBuziness(result);
    } catch(Exception e) {
        log.error(...);
    } finally {
        // clean work here
        sleep(1000);
    }
}
```
但是发现该线程不往下走了 卡住不动了
```
"Thread-5" daemon prio=10 tid=0x00002b54800cd000 nid=0x691f runnable [0x00002b5433be7000]
   java.lang.Thread.State: RUNNABLE
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:152)
    at java.net.SocketInputStream.read(SocketInputStream.java:122)
    at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
    at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
    at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:116)
```

问：
能否通过arthas中的什么工具 显式将这个socket给close掉 使得该线程可以继续往下执行？

**Comment by hengyunabc** [comment]
可以尝试用 tt 在某个调用里获取到这个 socket 或者 Stream ，然后再用 ognl表达式 close掉。

参考： https://github.com/alibaba/arthas/issues/482
