### ISSUE TITLE
使用root用户启动arthas-boot.jar 后选择其它用户启动Java进程 attach失败

### ISSUE THREAD

**Issue by gbf311** [alibaba/arthas#514]
异常信息:
[ERROR] Start arthas failed, exception stack trace: 
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:255)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:73)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:26)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:100)
[ERROR] attach fail, targetPid: 1736

**Comment by hengyunabc** [comment]
最好用同一个用户启动。这个最决于jvm本身的attach机制。 可以试下 jstack，应该也是出错。

**Comment by gbf311** [comment]
换成相同用户启动可以了，谢谢！

**Comment by livem** [comment]
> 换成相同用户启动可以了，谢谢！

@gbf311 求教 nobody 用户怎么使用呢
