### ISSUE TITLE
修改结果保存日志后报错

### ISSUE THREAD

**Issue by senlu** [alibaba/arthas#517]
### 环境信息
* Arthas 版本: 3.1.0
* 操作系统版本: windows7
* 目标进程的JVM版本: 1.6.0_17

### 重现问题的步骤

1. tomcat运行web（ssi）项目
2. 连接Arthas，使用options 查看配置信息，发现save-result为false
3. 执行`options save-result true`，修改成功

4. 再次执行 `options` ，具体报错如下：

```
Exception in thread "as-command-execute-daemon" java.lang.NullPointerException
	at com.taobao.arthas.core.shell.command.internal.RedirectHandler.close(RedirectHandler.java:53)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$ProcessOutput.close(ProcessImpl.java:618)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$ProcessOutput.access$100(ProcessImpl.java:562)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl.terminate(ProcessImpl.java:245)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl.access$400(ProcessImpl.java:34)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:374)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:619)
```

**Comment by hengyunabc** [comment]
#495 引入的问题。
