### ISSUE TITLE
网络断开后, 重新启动arthas报错

### ISSUE THREAD

**Issue by ivan-jiang** [alibaba/arthas#521]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.0
* Arthas 版本: 3.1.0
* 操作系统版本:  CentOS Linux release 7.3
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.1.0

### 重现问题的步骤

1. 登陆到远程服务器, 启动arthas, 并attach到一个java进程, 进入到arthas命令行交互界面
2. 网络中断, 和远程服务器的连接断开, 没有执行quit/shutdown
3. 网络正常后, 再次登陆到远程服务器, 启动arthas, 报错
[INFO] The target process already listen port 3658, skip attach.
[INFO] arthas-client connect 127.0.0.1 3658
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
        at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:268)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:481)

4,   telnet 127.0.0.1 3658 报错 connect to address 127.0.0.1: Connection refused
5,  目标进程正常对外提供服务

### 期望的结果
即使没有quit/shutdown异常退出, arthas也能够再次attach目标进程

**Comment by hengyunabc** [comment]
好像是在钉钉群里有回复过，先close。

**Comment by hnlsping** [comment]
怎么解决的呀？ 我也碰到了这个问题.....

**Comment by ivan-jiang** [comment]
试试telnet连接上去把arthas关了.我又用回greys了




------------------ 原始邮件 ------------------
发件人: "Perry"<notifications@github.com>; 
发送时间: 2019年4月28日(星期天) 下午3:38
收件人: "alibaba/arthas"<arthas@noreply.github.com>; 
抄送: "卫武"<79993067@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [alibaba/arthas] 网络断开后, 重新启动arthas报错 (#521)




怎么解决的呀？ 我也碰到了这个问题.....

**Comment by zhugw** [comment]
> 试试telnet连接上去把arthas关了.我又用回greys了
你好 遇到了同样的问题 请问是如何`telnet连接上去把arthas关了`的？

```
$ telnet 127.0.0.1 3658
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
```

**Comment by SETETERNAL** [comment]
请问有人能解决这个问题吗

**Comment by buerbl** [comment]
> 钉钉群里有回复过

是啥回复呀

**Comment by hengyunabc** [comment]
> > 钉钉群里有回复过
> 
> 是啥回复呀

如果是有问题的话，把具体重现的方法说明下，还有具体的异常。用netstat 检查是否有进程在 listen 3658 端口。
