### ISSUE TITLE
jad/watch/reset类失败

### ISSUE THREAD

**Issue by diecui1202** [alibaba/arthas#53]
sc可查到类，但jad/watch/reset都失败，错误日志：

```
01 2018-09-18 09:46:52.510 ERROR [as-command-execute-daemon:arthas] [] [] [] jad: fail to decompile class: com.xx.xx.serialize.Transformer
java.lang.InternalError: class redefinition failed: invalid class
  at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method) ~[na:1.8.0_66]
  at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144) ~[na:1.8.0_66]
  at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:393) ~[arthas-core.jar:na]
  at com.taobao.arthas.core.command.klass100.JadCommand.processExactMatch(JadCommand.java:111) [arthas-core.jar:na]
  at com.taobao.arthas.core.command.klass100.JadCommand.process(JadCommand.java:97) [arthas-core.jar:na]
  at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82) [arthas-core.jar:na]
  at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18) [arthas-core.jar:na]
  at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111) [arthas-core.jar:na]
  at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108) [arthas-core.jar:na]
  at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370) [arthas-core.jar:na]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
  at java.lang.Thread.run(Thread.java:756) [na:1.8.0_66]
```

**Comment by ted-wq-x** [comment]
see #47

**Comment by diecui1202** [comment]
The reason is com.xx.xx.serialize.Transformer static code block failed.
