### ISSUE TITLE
在wildfly下无法进行监控

### ISSUE THREAD

**Issue by dyj2012** [alibaba/arthas#566]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.0
* Arthas 版本: 3.1.0
* 操作系统版本: centos 7
MACHINE-NAME                                   5943@ecssrv170                                                                                                       
 JVM-START-TIME                                 2019-03-09 23:22:54                                                                                                  
 MANAGEMENT-SPEC-VERSION                        1.2                                                                                                                  
 SPEC-NAME                                      Java Virtual Machine Specification                                                                                   
 SPEC-VENDOR                                    Oracle Corporation                                                                                                   
 SPEC-VERSION                                   1.8                                                                                                                  
 VM-NAME                                        Java HotSpot(TM) 64-Bit Server VM                                                                                    
 VM-VENDOR                                      Oracle Corporation                                                                                                   
 VM-VERSION                                     25.161-b12                                                                                                           
 INPUT-ARGUMENTS                                -D[Standalone]                                                                                                       
                                                -Xms64m                                                                                                              
                                                -Xmx512m                                                                                                             
                                                -XX:MetaspaceSize=96M                                                                                                
                                                -XX:MaxMetaspaceSize=512m                                                                                            
                                                -Djava.net.preferIPv4Stack=true                                                                                      
                                                -Djboss.modules.system.pkgs=org.jboss.byteman                                                                        
                                                -Djava.awt.headless=true                                                                                             
                                                -Dorg.jboss.boot.log.file=/home/admin/wildfly-14.0.1.Final8081/standalone/log/server.log                             
                                                -Dlogging.configuration=file:/home/admin/wildfly-14.0.1.Final8081/standalone/configuration/logging.properties        
* 执行`arthas-boot`的版本: 3.1.0

### 重现问题的步骤

1. trace -j com.xxx.xxx.LoginController login

### 期望的结果

获取到监控结果

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

把异常信息贴到这里
01 2019-03-10 10:27:00.741 WARN [as-command-execute-daemon:arthas] [] [] [] transform loader[ModuleClassLoader for Module "deployment.xxx-console.war" from Service Module Loader]:class[com/xxx/console/controller/LoginController$$EnhancerBySpringCGLIB$$7360227a] failed.
java.lang.ClassNotFoundException: java.arthas.Spy from [Module "deployment.xxx-console.war" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255) ~[jboss-modules.jar:1.8.6.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410) ~[jboss-modules.jar:1.8.6.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398) ~[jboss-modules.jar:1.8.6.Final]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116) ~[jboss-modules.jar:1.8.6.Final]
	at com.taobao.arthas.core.advisor.Enhancer.spy(Enhancer.java:78) [arthas-core.jar:3.1.0]
	at com.taobao.arthas.core.advisor.Enhancer.transform(Enhancer.java:175) [arthas-core.jar:3.1.0]
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188) [na:1.8.0_161]
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428) [na:1.8.0_161]
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method) [na:1.8.0_161]
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144) [na:1.8.0_161]
	at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:302) [arthas-core.jar:3.1.0]
	at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:111) [arthas-core.jar:3.1.0]
	at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:66) [arthas-core.jar:3.1.0]
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82) [arthas-core.jar:3.1.0]
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18) [arthas-core.jar:3.1.0]
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111) [arthas-core.jar:3.1.0]
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108) [arthas-core.jar:3.1.0]
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370) [arthas-core.jar:3.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
01 2019-03-10 10:27:00.924 INFO [as-command-execute-daemon:arthas] [] [] [] Success to batch transform classes: [class com.xxx.console.controller.LoginController, class com.xxx.console.controller.LoginController$$EnhancerBySpringCGLIB$$7360227a]

**Comment by hengyunabc** [comment]
有没有具体的demo？

**Comment by tonylit** [comment]
兄弟，我这边用的 WildFly 8.1.0.Final，arthas-boot用的 3.1.0。 
执行./as.sh的时候报错：
```
[jbossuser@epp shell]$ ./as.sh 
Arthas script version: 3.1.0
[INFO] JAVA_HOME: /opt/wildfly/openjdk/openjdk-1.8.0_92
Found existing java process, please choose one and hit RETURN.
* [1]: 19091 /opt/wildfly/jboss-modules.jar
1
Arthas home: /home/shell
Calculating attach execution time...
Attaching to 19091 using version /home/shell...

real	0m0.160s
user	0m0.235s
sys	0m0.029s
Attach success.
telnet connecting to arthas server... current timestamp is 1552479328
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
```
有没有遇到这种情况啊？
ps:监控tomcat的服务是没问题的。

**Comment by glenn2wang** [comment]
有一样的 问题

**Comment by glenn2wang** [comment]
测试 widfly10版本，可以正常，但是widfly17版本异常
watch trace时  java.lang.ClassNotFoundException: java.arthas.Spy

**Comment by hengyunabc** [comment]
3.4.5 版本已支持，需要配置参数，参考 #1596
