### ISSUE TITLE
Start arthas failed, exception stack trace:

### ISSUE THREAD

**Issue by TrumanDu** [alibaba/arthas#58]
```
Start arthas failed, exception stack trace:
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file /tmp/.attach_pid1: target process 1 doesn't respond within 10500ms or HotSpot VM not loaded
        at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:103)
        at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:73)
        at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:249)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:69)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:25)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:96)
attach to target jvm (1) failed, check /usr/share/elasticsearch/logs/arthas/arthas.log or stderr of target jvm for any exceptions.
```

**Comment by ralf0131** [comment]
Please check `/usr/share/elasticsearch/logs/arthas/arthas.log` or stand output of target JVM for any exceptions.

What is the JVM version you are using to attach?  What is the JVM version you are attaching to?

**Comment by ted-wq-x** [comment]
check ‘/usr/share/elasticsearch/logs/.arthas/arthas.log’

**Comment by TrumanDu** [comment]
@ted-wq-x  ```bash: cd: /usr/share/elasticsearch/logs/.arthas/: No such file or directory
```

**Comment by ralf0131** [comment]
@TrumanDu Please check the stdout/stderr of target JVM to see if there are some exceptions. Where is the stdout/stderr of ElasticSearch located?

**Comment by DNGiveU** [comment]
look your photo of head is huitailang of china, why your spark english in talk? xixi ^-^ like

**Comment by TrumanDu** [comment]
@DNGiveU  It’s China’s, it’s the world’s
