### ISSUE TITLE
java.io.IOException

### ISSUE THREAD

**Issue by c0d4r** [alibaba/arthas#61]
```
Start arthas failed, exception stack trace:
java.io.IOException: Premature EOF
	at sun.tools.attach.HotSpotVirtualMachine.readInt(HotSpotVirtualMachine.java:226)
	at sun.tools.attach.LinuxVirtualMachine.execute(LinuxVirtualMachine.java:175)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:40)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:62)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:85)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:84)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:26)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:96)

java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
```

**Comment by ralf0131** [comment]
Hi, 

Please provide some additional information:

1. The version of JVM that you are attaching to
2. The version of JVM you are using to attach (which means the $JAVA_HOME you used to run as.sh)

**Comment by c0d4r** [comment]
both are
 java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
