### ISSUE TITLE
WIN10 64位 启动闪退(已解决 启动方式错误)

### ISSUE THREAD

**Issue by Very666** [alibaba/arthas#637]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 2019/2/14
* Arthas 版本: 2019/2/14
* 操作系统版本: win10 64位
* 目标进程的JVM版本:
 java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) Client VM (build 25.201-b09, mixed mode)
* 执行`arthas-boot`的版本:  3.10

### 重现问题的步骤
一.bat启动
1.windows版 解压后 已管理员方式运行as.bat文件
2. 黑窗口一闪而过
二.jar包启动
1.通过 java -jar arthas-boot.jar 启动
2.出现 [2]: 14420 org.apache.catalina.startup.Bootstrap
3.输入2后回车,报错

### 实际运行的结果
二.jar包启动
Start arthas failed, exception stack trace:
com.sun.tools.attach.AttachNotSupportedException: Unable to attach to 64-bit process
        at sun.tools.attach.WindowsVirtualMachine.openProcess(Native Method)
        at sun.tools.attach.WindowsVirtualMachine.<init>(WindowsVirtualMachine.java:56)
        at sun.tools.attach.WindowsAttachProvider.attachVirtualMachine(WindowsAttachProvider.java:69)
        at com.sun.tools.attach.spi.AttachProvider.attachVirtualMachine(AttachProvider.java:194)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:73)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:26)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:100)

**Comment by Very666** [comment]
好了好了 启动错了 应该以命令行方式启动 ./as.bat 14420
