### ISSUE TITLE
stack捕获方法被调用的调用路径,无法正常结束

### ISSUE THREAD

**Issue by hanboyuan** [alibaba/arthas#654]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.0
* Arthas 版本: 3.1.0
* 操作系统版本: 3.1.0
* 目标进程的JVM版本: 3.1.0
* 执行`arthas-boot`的版本: 3.1.0

### 重现问题的步骤

$ stack -n 1 com.test.etms.third.rpc.impl.OrderShipsServicerpcImpl getOrderShipsDto

### 期望的结果

最后结尾$正常退出

### 实际运行的结果

抓取完数据后停止，不动，手动敲回车后，出来$

```
$ stack -n 1 com.test.etms.third.rpc.impl.OrderShipsServicerpcImpl getOrderShipsDto
Press Q or Ctrl+C to abort.
Affect(class-cnt:2 , method-cnt:2) cost in 231 ms.
ts=2019-04-18 10:51:01;thread_name=rpc-BZ-22000-50-T-13353;id=4885;is_daemon=true;priority=5;TCCL=org.apache.catalina.loader.WebappClassLoader@2865804ts=2019-04-18 10:51:01;thread_name=rpc-BZ-22000-50-T-13382;id=48a5;is_daemon=true;priority=5;TCCL=org.apache.catalina.loader.WebappClassLoader@2865804

    @com.test.etms.third.rpc.impl.OrderShipsServicerpcImpl$$FastClassBySpringCGLIB$$4979cdd5.invoke()    @com.test.etms.third.rpc.impl.OrderShipsServicerpcImpl$$FastClassBySpringCGLIB$$4979cdd5.invoke()

        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:701)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)
        at com.test.monitor.x.JAnnotationX.execJAnnotationX(JAnnotationX.java:148)
        at sun.reflect.GeneratedMethodAccessor80.invoke(null:-1)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)ts=2019-04-18 10:51:01;thread_name=rpc-BZ-22000-50-T-13374;id=489b;is_daemon=true;priority=5;TCCL=org.apache.catalina.loader.WebappClassLoader@2865804

    @com.test.etms.third.rpc.impl.OrderShipsServicerpcImpl$$FastClassBySpringCGLIB$$4979cdd5.invoke()        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)

        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:701)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)

        at com.test.monitor.x.JAnnotationX.execJAnnotationX(JAnnotationX.java:148)        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)

        at sun.reflect.GeneratedMethodAccessor80.invoke(null:-1)        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)

        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)        at com.test.etms.third.rpc.impl.OrderShipsServicerpcImpl$$EnhancerBySpringCGLIB$$a11fdfd.getOrderShipsDto(<generated>:-1)

        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)        at sun.reflect.GeneratedMethodAccessor86.invoke(null:-1)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.test.rpc.gd.filter.ProviderInvokeFilter.reflectInvoke(ProviderInvokeFilter.java:140)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)        at com.test.rpc.gd.filter.ProviderInvokeFilter.invoke(ProviderInvokeFilter.java:100)

        at com.test.rpc.gd.filter.ProviderSecurityFilter.invoke(ProviderSecurityFilter.java:42)        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at com.test.rpc.gd.filter.ProviderConcurrentsFilter.invoke(ProviderConcurrentsFilter.java:62)

        at com.test.rpc.gd.filter.ProviderTimeoutFilter.invoke(ProviderTimeoutFilter.java:39)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)        at com.test.rpc.gd.filter.ProviderMethodCheckFilter.invoke(ProviderMethodCheckFilter.java:78)

        at com.test.etms.third.rpc.impl.OrderShipsServicerpcImpl$$EnhancerBySpringCGLIB$$a11fdfd.getOrderShipsDto(<generated>:-1)
        at com.test.rpc.gd.filter.ProviderInvokeLimitFilter.invoke(ProviderInvokeLimitFilter.java:54)        at sun.reflect.GeneratedMethodAccessor86.invoke(null:-1)

        at com.test.rpc.gd.filter.ProviderHttpGWFilter.invoke(ProviderHttpGWFilter.java:47)
        at com.test.rpc.gd.filter.ProviderGenericFilter.invoke(ProviderGenericFilter.java:118)        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:606)        at com.test.rpc.gd.filter.ProviderContextFilter.invoke(ProviderContextFilter.java:73)

        at com.test.rpc.gd.filter.ProviderInvokeFilter.reflectInvoke(ProviderInvokeFilter.java:140)        at com.test.rpc.gd.filter.ExceptionFilter.invoke(ExceptionFilter.java:49)

        at com.test.rpc.gd.filter.ProviderInvokeFilter.invoke(ProviderInvokeFilter.java:100)        at com.test.rpc.gd.filter.SystemTimeCheckFilter.invoke(SystemTimeCheckFilter.java:79)

        at com.test.rpc.gd.filter.ProviderSecurityFilter.invoke(ProviderSecurityFilter.java:42)        at com.test.rpc.gd.filter.FilterChain.invoke(FilterChain.java:277)

        at com.test.rpc.gd.filter.ProviderConcurrentsFilter.invoke(ProviderConcurrentsFilter.java:62)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:701)        at com.test.rpc.gd.server.ProviderProxyInvoker.invoke(ProviderProxyInvoker.java:66)        at com.test.rpc.gd.filter.ProviderTimeoutFilter.invoke(ProviderTimeoutFilter.java:39)


        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at com.test.rpc.gd.filter.ProviderMethodCheckFilter.invoke(ProviderMethodCheckFilter.java:78)        at com.test.rpc.gd.server.rpcTask.doRun(rpcTask.java:129)        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)


        at com.test.monitor.x.JAnnotationX.execJAnnotationX(JAnnotationX.java:148)        at com.test.rpc.gd.server.BaseTask.run(BaseTask.java:27)        at com.test.rpc.gd.filter.ProviderInvokeLimitFilter.invoke(ProviderInvokeLimitFilter.java:54)


        at sun.reflect.GeneratedMethodAccessor80.invoke(null:-1)        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at com.test.rpc.gd.filter.ProviderHttpGWFilter.invoke(ProviderHttpGWFilter.java:47)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.util.concurrent.FutureTask.run(FutureTask.java:262)        at java.lang.reflect.Method.invoke(Method.java:606)

        at com.test.rpc.gd.filter.ProviderGenericFilter.invoke(ProviderGenericFilter.java:118)        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)


        at com.test.rpc.gd.filter.ProviderContextFilter.invoke(ProviderContextFilter.java:73)        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
        at com.test.rpc.gd.filter.ExceptionFilter.invoke(ExceptionFilter.java:49)
        at java.lang.Thread.run(Thread.java:745)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)        at com.test.rpc.gd.filter.SystemTimeCheckFilter.invoke(SystemTimeCheckFilter.java:79)


        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)        at com.test.rpc.gd.filter.FilterChain.invoke(FilterChain.java:277)Command execution times exceed limit: 1, so command will exit. You can set it with -n option.


        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)
        at com.test.etms.third.rpc.impl.OrderShipsServicerpcImpl$$EnhancerBySpringCGLIB$$a11fdfd.getOrderShipsDto(<generated>:-1)        at com.test.rpc.gd.server.ProviderProxyInvoker.invoke(ProviderProxyInvoker.java:66)
$ 
        at sun.reflect.GeneratedMethodAccessor86.invoke(null:-1)        at com.test.rpc.gd.server.rpcTask.doRun(rpcTask.java:129)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.test.rpc.gd.server.BaseTask.run(BaseTask.java:27)        at com.test.rpc.gd.filter.ProviderInvokeFilter.reflectInvoke(ProviderInvokeFilter.java:140)

        at com.test.rpc.gd.filter.ProviderInvokeFilter.invoke(ProviderInvokeFilter.java:100)        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)

        at com.test.rpc.gd.filter.ProviderSecurityFilter.invoke(ProviderSecurityFilter.java:42)        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at com.test.rpc.gd.filter.ProviderConcurrentsFilter.invoke(ProviderConcurrentsFilter.java:62)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)        at com.test.rpc.gd.filter.ProviderTimeoutFilter.invoke(ProviderTimeoutFilter.java:39)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)        at com.test.rpc.gd.filter.ProviderMethodCheckFilter.invoke(ProviderMethodCheckFilter.java:78)

        at java.lang.Thread.run(Thread.java:745)        at com.test.rpc.gd.filter.ProviderInvokeLimitFilter.invoke(ProviderInvokeLimitFilter.java:54)


        at com.test.rpc.gd.filter.ProviderHttpGWFilter.invoke(ProviderHttpGWFilter.java:47)
        at com.test.rpc.gd.filter.ProviderGenericFilter.invoke(ProviderGenericFilter.java:118)
        at com.test.rpc.gd.filter.ProviderContextFilter.invoke(ProviderContextFilter.java:73)
        at com.test.rpc.gd.filter.ExceptionFilter.invoke(ExceptionFilter.java:49)
        at com.test.rpc.gd.filter.SystemTimeCheckFilter.invoke(SystemTimeCheckFilter.java:79)
        at com.test.rpc.gd.filter.FilterChain.invoke(FilterChain.java:277)
        at com.test.rpc.gd.server.ProviderProxyInvoker.invoke(ProviderProxyInvoker.java:66)
        at com.test.rpc.gd.server.rpcTask.doRun(rpcTask.java:129)
        at com.test.rpc.gd.server.BaseTask.run(BaseTask.java:27)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by hengyunabc** [comment]
有没有可重现的demo？

**Comment by xuzhiyiYoh** [comment]
上面的stack结果其实跟踪到了两次，且在第二次write中间close了。
![image](https://user-images.githubusercontent.com/48389485/56453279-b3793f00-6372-11e9-856c-c716d490a357.png)
![image](https://user-images.githubusercontent.com/48389485/56453283-bffd9780-6372-11e9-903f-e4f4d432aff7.png)
