### ISSUE TITLE
"Timer already cancelled" output when running any command after attached

### ISSUE THREAD

**Issue by bo11zhou** [alibaba/arthas#657]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.0
* Arthas 版本: 3.1.0
* 操作系统版本: CentOS Linux release 7.2.1511 (Core) 
* 目标进程的JVM版本: OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)
* 执行`arthas-boot`的版本: 3.1.0

### 重现问题的步骤

1. 在root用户下执行curl -L https://alibaba.github.io/arthas/install.sh | sh，然后运行 as.sh
2. 选择目标进程序号，提示Attach success.
telnet connecting to arthas server... current timestamp is 1555896633
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
3. 运行dashboard或者其它任何命令，均输出“Timer already cancelled.”

### 期望的结果

如arthas帮助文档上列出的，目标命令的正常输出。

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
wiki: https://alibaba.github.io/arthas
version: 3.1.0
pid: 28046
time: 2019-04-22 09:30:33

$ dashboard
Timer already cancelled.
$ thread
Timer already cancelled.

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
使用的是shell是什么版本的？有可能是shell自动输入了ctrl + c 或者 Q ？ 其它命令有问题不？

**Comment by bo11zhou** [comment]
> 使用的是shell是什么版本的？有可能是shell自动输入了ctrl + c 或者 Q ？ 其它命令有问题不？

shell的版本是，GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
其它Arthas命令的执行，都有问题。

**Comment by bo11zhou** [comment]
01 2019-04-22 09:17:35.255 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x0370cf99, L:/127.0.0.1:3658] READ: [id: 0x06eb5e92, L:/127.0.0.1:3658 - R:/127.0.0.1:55826]
01 2019-04-22 09:17:35.256 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x0370cf99, L:/127.0.0.1:3658] READ COMPLETE
01 2019-04-22 09:17:35.257 INFO [nioEventLoopGroup-2-3:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
01 2019-04-22 09:25:13.894 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x0370cf99, L:/127.0.0.1:3658] READ: [id: 0x5239981a, L:/127.0.0.1:3658 - R:/127.0.0.1:56138]
01 2019-04-22 09:25:13.894 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x0370cf99, L:/127.0.0.1:3658] READ COMPLETE
01 2019-04-22 09:25:13.895 INFO [nioEventLoopGroup-2-4:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
01 2019-04-22 09:30:33.579 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x0370cf99, L:/127.0.0.1:3658] READ: [id: 0xca292f93, L:/127.0.0.1:3658 - R:/127.0.0.1:56374]
01 2019-04-22 09:30:33.579 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x0370cf99, L:/127.0.0.1:3658] READ COMPLETE
01 2019-04-22 09:30:33.580 INFO [nioEventLoopGroup-2-5:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
01 2019-04-22 16:42:38.526 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x0370cf99, L:/127.0.0.1:3658] READ: [id: 0xe27f0845, L:/127.0.0.1:3658 - R:/127.0.0.1:39848]
01 2019-04-22 16:42:38.526 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x0370cf99, L:/127.0.0.1:3658] READ COMPLETE
01 2019-04-22 16:42:38.527 INFO [nioEventLoopGroup-2-6:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc

**Comment by hengyunabc** [comment]
https://alibaba.github.io/arthas/quick-start.html 执行arthas-demo 有没有问题？或者换个环境试下？

**Comment by bo11zhou** [comment]
> https://alibaba.github.io/arthas/quick-start.html 执行arthas-demo 有没有问题？或者换个环境试下？

执行arthas-demo，正常。

**Comment by hengyunabc** [comment]
可以提供重现的demo不？

**Comment by GLGGAG** [comment]
我也出现相同的问题，查看了arthas的日志后发现是端口被占用，启动时并不报端口被占用异常，可以正常进入，执行任何命令除了(quit)时出现Timer already cancelled.，解决端口冲突后恢复正常
wiki: https://alibaba.github.io/arthas
version: 3.1.0
pid: 26123
time: 2019-06-28 14:41:36

$ shutdown
Timer already cancelled.
$ history
Timer already cancelled.
$ help
Timer already cancelled.
---------------------------------------------------------
01 2019-06-28 14:41:36.727 ERROR [arthas-binding-thread:arthas] [] [] [] Error listening to port 3658
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.7.0_79]
	at sun.nio.ch.Net.bind(Net.java:444) ~[na:1.7.0_79]
	at sun.nio.ch.Net.bind(Net.java:436) ~[na:1.7.0_79]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214) ~[na:1.7.0_79]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:563) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1332) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.handler.logging.LoggingHandler.bind(LoggingHandler.java:191) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:259) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[arthas-core.jar:3.1.1]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[arthas-core.jar:3.1.1]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
01 2019-06-28 14:41:36.734 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x18afd58f] REGISTERED
01 2019-06-28 14:41:36.734 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x18afd58f] BIND: /127.0.0.1:8563
01 2019-06-28 14:41:36.735 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x18afd58f] CLOSE
01 2019-06-28 14:41:36.735 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x18afd58f] UNREGISTERED
01 2019-06-28 14:41:36.736 ERROR [arthas-binding-thread:arthas] [] [] [] Error listening to port 8563
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.7.0_79]
	at sun.nio.ch.Net.bind(Net.java:444) ~[na:1.7.0_79]
	at sun.nio.ch.Net.bind(Net.java:436) ~[na:1.7.0_79]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214) ~[na:1.7.0_79]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:563) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1332) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.handler.logging.LoggingHandler.bind(LoggingHandler.java:191) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:259) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[arthas-core.jar:3.1.1]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[arthas-core.jar:3.1.1]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
01 2019-06-28 14:41:36.737 ERROR [arthas-binding-thread:arthas] [] [] [] Error listening term server:
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.7.0_79]
	at sun.nio.ch.Net.bind(Net.java:444) ~[na:1.7.0_79]
	at sun.nio.ch.Net.bind(Net.java:436) ~[na:1.7.0_79]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214) ~[na:1.7.0_79]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:563) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1332) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.handler.logging.LoggingHandler.bind(LoggingHandler.java:191) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:259) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[arthas-core.jar:3.1.1]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[arthas-core.jar:3.1.1]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]

**Comment by bo11zhou** [comment]
> 我也出现相同的问题，查看了arthas的日志后发现是端口被占用，启动时并不报端口被占用异常，可以正常进入，执行任何命令除了(quit)时出现Timer already cancelled.，解决端口冲突后恢复正常
> wiki: https://alibaba.github.io/arthas
> version: 3.1.0
> pid: 26123
> time: 2019-06-28 14:41:36
> 
> ## $ shutdown
> Timer already cancelled.
> $ history
> Timer already cancelled.
> $ help
> Timer already cancelled.
> 01 2019-06-28 14:41:36.727 ERROR [arthas-binding-thread:arthas] [] [] [] Error listening to port 3658
> java.net.BindException: Address already in use
> at sun.nio.ch.Net.bind0(Native Method) ~[na:1.7.0_79]
> at sun.nio.ch.Net.bind(Net.java:444) ~[na:1.7.0_79]
> at sun.nio.ch.Net.bind(Net.java:436) ~[na:1.7.0_79]
> at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214) ~[na:1.7.0_79]
> at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:563) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1332) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.handler.logging.LoggingHandler.bind(LoggingHandler.java:191) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:259) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[arthas-core.jar:3.1.1]
> at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[arthas-core.jar:3.1.1]
> at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
> 01 2019-06-28 14:41:36.734 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x18afd58f] REGISTERED
> 01 2019-06-28 14:41:36.734 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x18afd58f] BIND: /127.0.0.1:8563
> 01 2019-06-28 14:41:36.735 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x18afd58f] CLOSE
> 01 2019-06-28 14:41:36.735 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x18afd58f] UNREGISTERED
> 01 2019-06-28 14:41:36.736 ERROR [arthas-binding-thread:arthas] [] [] [] Error listening to port 8563
> java.net.BindException: Address already in use
> at sun.nio.ch.Net.bind0(Native Method) ~[na:1.7.0_79]
> at sun.nio.ch.Net.bind(Net.java:444) ~[na:1.7.0_79]
> at sun.nio.ch.Net.bind(Net.java:436) ~[na:1.7.0_79]
> at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214) ~[na:1.7.0_79]
> at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:563) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1332) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.handler.logging.LoggingHandler.bind(LoggingHandler.java:191) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:259) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[arthas-core.jar:3.1.1]
> at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[arthas-core.jar:3.1.1]
> at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
> 01 2019-06-28 14:41:36.737 ERROR [arthas-binding-thread:arthas] [] [] [] Error listening term server:
> java.net.BindException: Address already in use
> at sun.nio.ch.Net.bind0(Native Method) ~[na:1.7.0_79]
> at sun.nio.ch.Net.bind(Net.java:444) ~[na:1.7.0_79]
> at sun.nio.ch.Net.bind(Net.java:436) ~[na:1.7.0_79]
> at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214) ~[na:1.7.0_79]
> at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:563) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1332) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.handler.logging.LoggingHandler.bind(LoggingHandler.java:191) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:259) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
> at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[arthas-core.jar:3.1.1]
> at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[arthas-core.jar:3.1.1]
> at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
多谢支持！
