### ISSUE TITLE
jad反编译报错

### ISSUE THREAD

**Issue by Leven9** [alibaba/arthas#664]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `as.sh` 的版本： 3.1.0
* Arthas 版本:  3.1.0
* 操作系统版本: CentOS release 6.3 (Final)
* 目标进程的JVM版本: 1.8.0_40
* 执行`arthas-boot`的版本: 3.1.0

### 重现问题的步骤

1. jad --source-only xxx.ClassA

### 期望的结果

输出源码

### 实际运行的结果

无任何输出

```
01 2019-04-24 19:48:32.125 ERROR [as-command-execute-daemon:arthas] [] [] [] jad: fail to decompile class: xxx.ClassA
java.lang.VerifyError: null
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method) ~[na:1.8.0_40]
        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144) ~[na:1.8.0_40]
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:386) ~[arthas-core.jar:3.1.0]
        at com.taobao.arthas.core.command.klass100.JadCommand.processExactMatch(JadCommand.java:128) [arthas-core.jar:3.1.0]
        at com.taobao.arthas.core.command.klass100.JadCommand.process(JadCommand.java:111) [arthas-core.jar:3.1.0]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82) [arthas-core.jar:3.1.0]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18) [arthas-core.jar:3.1.0]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111) [arthas-core.jar:3.1.0]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108) [arthas-core.jar:3.1.0]
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370) [arthas-core.jar:3.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
```

**Comment by hengyunabc** [comment]
最好提供可重现的demo，否则无从下手。

**Comment by hengyunabc** [comment]
参考这个： https://github.com/alibaba/arthas/issues/675#issuecomment-487856710
