### ISSUE TITLE
多次attach之后，报错 java.io.IOException: Premature EOF

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#674]
在多次attach之后，某一次attach报错：

```
$ bin/as.sh
Arthas script version: 3.1.0
[INFO] JAVA_HOME: /Users/hengyunabc/.sdkman/candidates/java/8.0.181-zulu
Found existing java process, please choose one and hit RETURN.
* [1]: 77507
  [2]: 80281
  [3]: 80138 org.springframework.boot.loader.JarLauncher
3
Arthas home: /Users/hengyunabc/.arthas/lib/3.1.1.20190430143039/arthas
Calculating attach execution time...
Attaching to 80138 using version /Users/hengyunabc/.arthas/lib/3.1.1.20190430143039/arthas...
[ERROR] Start arthas failed, exception stack trace:
java.io.IOException: Premature EOF
	at sun.tools.attach.HotSpotVirtualMachine.readInt(HotSpotVirtualMachine.java:292)
	at sun.tools.attach.BsdVirtualMachine.execute(BsdVirtualMachine.java:183)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:58)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:79)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:103)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:94)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:113)
attach to target jvm (80138) failed, check /Users/hengyunabc/logs/arthas/arthas.log or stderr of target jvm for any exceptions.
```

在进程的console打印出：

```
Tue Apr 30 14:32:09 CST 2019 com.taobao.arthas.agent.ArthasClassloader@717aafa2 JM.Log:INFO Log root path: /Users/hengyunabc/logs/
Tue Apr 30 14:32:09 CST 2019 com.taobao.arthas.agent.ArthasClassloader@717aafa2 JM.Log:INFO Set arthas log path: /Users/hengyunabc/logs/arthas
java(80138,0x70000f0f3000) malloc: *** error for object 0x7ff2746f6c00: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

不清楚是什么原因引起的，记录一下。

**Comment by RobertLiu0905** [comment]
@hengyunabc 请问这个问题原因找到了吗？我们生产环境也是出现这个报错，然后应用也被停了

**Comment by hengyunabc** [comment]
> @hengyunabc 请问这个问题原因找到了吗？我们生产环境也是出现这个报错，然后应用也被停了

没有，没找到稳定重现的办法。

另外，你们用的是什么版本的。

**Comment by RobertLiu0905** [comment]
> > @hengyunabc 请问这个问题原因找到了吗？我们生产环境也是出现这个报错，然后应用也被停了
> 
> 没有，没找到稳定重现的办法。
> 
> 另外，你们用的是什么版本的。

os版本
![image](https://user-images.githubusercontent.com/10494702/100561836-e7f60080-32f4-11eb-8afc-a20098b73782.png)
jdk版本
![image](https://user-images.githubusercontent.com/10494702/100561886-03f9a200-32f5-11eb-9148-dce248d7b75a.png)

**Comment by LALAnimeimei** [comment]
这个问题原因是什么？
