### ISSUE TITLE
jad command error log : java.lang.VerifyError: null

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#675]
应用刚启动时，jad可以执行成功，可以正常反编绎。

但是实际发现只匹配到一个类。

```
com.test.statussync.CheckoutStatusSynchronizerImpl
```

等应用运行一段时间之后，再执行jad，没有结果输出。

检查日志，发现`java.lang.VerifyError: null`

`~/logs/arthas/arthas.log`:

```
java.lang.VerifyError: null
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method) ~[na:1.8.0_181]
        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144) ~[na:1.8.0_181]
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:388) ~[arthas-core.jar:3.1.1-SNAPSHOT]
        at com.taobao.arthas.core.command.klass100.JadCommand.processExactMatch(JadCommand.java:156) [arthas-core.jar:3.1.1-SNAPSHOT]
        at com.taobao.arthas.core.command.klass100.JadCommand.process(JadCommand.java:115) [arthas-core.jar:3.1.1-SNAPSHOT]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82) [arthas-core.jar:3.1.1-SNAPSHOT]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18) [arthas-core.jar:3.1.1-SNAPSHOT]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111) [arthas-core.jar:3.1.1-SNAPSHOT]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108) [arthas-core.jar:3.1.1-SNAPSHOT]
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370) [arthas-core.jar:3.1.1-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
```

实际匹配到了下面的类：

```
com.test.statussync.CheckoutStatusSynchronizerImpl$2
com.test.statussync.CheckoutStatusSynchronizerImpl
com.test.statussync.CheckoutStatusSynchronizerImpl$1
com.test.statussync.CheckoutStatusSynchronizerImpl$4
com.test.statussync.CheckoutStatusSynchronizerImpl$$Lambda$181/213662707
```

可以看到 `com.test.statussync.CheckoutStatusSynchronizerImpl$$Lambda$181/213662707`是 lambda运行时生成的类。

当对这个类执行 `java.lang.instrument.Instrumentation.retransformClasses(Class<?>...)` 时，就会抛出 `java.lang.VerifyError: null`。 这个也许是JDK里的bug，没有对lambda生成的类做判断。

---

jad执行时，可以考虑忽略掉lambda动态生成的类？或者忽略`VerifyError`。

**Comment by hengyunabc** [comment]
可以用这个包来测试： [arthas-3.1.1-SNAPSHOT-bin.zip](https://github.com/alibaba/arthas/files/3130383/arthas-3.1.1-SNAPSHOT-bin.zip)

**Comment by hengyunabc** [comment]
测试的Demo：

```java
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class JadLambdaDemo {
	public static void main(String[] args) throws Exception {
		JadLambdaDemo demo = new JadLambdaDemo();
		try {
			demo.testLabmda(new ArrayList<>());
		} catch (Throwable e) {
			e.printStackTrace();
		}
		System.in.read();
	}

	private Map<Object, Object> map = new HashMap<>();

	public void testLabmda(List<Object> list) {
		list.forEach(it -> {
			map.put(it.getClass(), it);

		});
	}
}
```

在jdk11下面`sc`搜索类，结果是：

```
$ sc JadLambdaDemo*
JadLambdaDemo
JadLambdaDemo$$Lambda$1/0x0000000800067040
Affect(row-cnt:2) cost in 17 ms.
```

```
$ jad JadLambdaDemo
Affect(row-cnt:0) cost in 35 ms.
```

错误日志是：

```
01 2019-05-02 17:14:26.159 ERROR [as-command-execute-daemon:arthas] [] [] [] jad: fail to decompile class: JadLambdaDemo
java.lang.instrument.UnmodifiableClassException: null
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method) ~[na:na]
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167) ~[na:na]
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:386) ~[arthas-core.jar:3.1.0]
        at com.taobao.arthas.core.command.klass100.JadCommand.processExactMatch(JadCommand.java:128) ~[arthas-core.jar:3.1.0]
        at com.taobao.arthas.core.command.klass100.JadCommand.process(JadCommand.java:111) ~[arthas-core.jar:3.1.0]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82) ~[arthas-core.jar:3.1.0]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18) ~[arthas-core.jar:3.1.0]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111) ~[arthas-core.jar:3.1.0]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108) ~[arthas-core.jar:3.1.0]
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370) ~[arthas-core.jar:3.1.0]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

可以发现，在jdk11下面抛出来的异常是：

* java.lang.instrument.UnmodifiableClassException
* lambda动态生成的类里，数字是16进制的`0x`表示形式了

**Comment by Xue2015** [comment]
换了3.1.1 jad反编译依然没有结果

**Comment by hengyunabc** [comment]
@Xue2015 最好提交一个Demo，不然没法处理。

**Comment by cc-cfg** [comment]
这个问题我也遇到了   ，mc不成功
