### ISSUE TITLE
有些类monitor/watch/trace监控不到，用sc也找不出来

### ISSUE THREAD

**Issue by gong1989313** [alibaba/arthas#710]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： Arthas script version: 3.1.1
* Arthas 版本: 3.1.1
* 操作系统版本: 3.10.0-514.21.1.el7.x86_64
* 目标进程的JVM版本: 1.7.0_80-b15
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. 我的tomcat中有以下的class的，如图：
![image](https://user-images.githubusercontent.com/10339238/58142001-0bf47280-7c78-11e9-8622-cec62f5375a6.png)
2. 但是我用watch/trace等命令监控不到
![image](https://user-images.githubusercontent.com/10339238/58142075-465e0f80-7c78-11e9-83f8-0034d50cbbe3.png)
![image](https://user-images.githubusercontent.com/10339238/58142097-583fb280-7c78-11e9-80a8-b8b5524c7bc4.png)

3. 使用sc查看加载的类，也没有查到。但是我的功能是没有问题的
![image](https://user-images.githubusercontent.com/10339238/58142188-abb20080-7c78-11e9-952c-ce815cea559e.png)

### 期望的结果
使用SC能看到VerificaAction，使用trace和watch也能正常监控。
What do you expected from the above steps？

### 实际运行的结果
没有监控到。
实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```
[tomcat@vip2_lightapp_dev funds]$ tail -100f /home/tomcat/logs/arthas/arthas.log
	at ognl.OgnlParser.exclusiveOrExpression(OgnlParser.java:299) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.inclusiveOrExpression(OgnlParser.java:246) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.logicalAndExpression(OgnlParser.java:193) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.logicalOrExpression(OgnlParser.java:140) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.conditionalTestExpression(OgnlParser.java:101) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.assignmentExpression(OgnlParser.java:64) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.expression(OgnlParser.java:23) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.topLevelExpression(OgnlParser.java:15) ~[arthas-core.jar:3.1.1]
	at ognl.Ognl.parseExpression(Ognl.java:110) ~[arthas-core.jar:3.1.1]
	... 12 common frames omitted
01 2019-05-22 09:26:23.415 WARN [as-command-execute-daemon:arthas] [] [] [] ognl: failed execute express: *VerificaAction*
com.taobao.arthas.core.command.express.ExpressException: ognl.ExpressionSyntaxException: Malformed OGNL expression: *VerificaAction* [ognl.ParseException: Encountered " "*" "* "" at line 1, column 1.
Was expecting one of:
    ":" ...
    "not" ...
    "+" ...
    "-" ...
    "~" ...
    "!" ...
    "(" ...
    "true" ...
    "false" ...
    "null" ...
    "#this" ...
    "#root" ...
    "#" ...
    "[" ...
    "{" ...
    "@" ...
    "new" ...
    <IDENT> ...
    <DYNAMIC_SUBSCRIPT> ...
    "\'" ...
    "`" ...
    "\"" ...
    <INT_LITERAL> ...
    <FLT_LITERAL> ...
    ]
	at com.taobao.arthas.core.command.express.OgnlExpress.get(OgnlExpress.java:40) ~[arthas-core.jar:3.1.1]
	at com.taobao.arthas.core.command.klass100.OgnlCommand.process(OgnlCommand.java:82) ~[arthas-core.jar:3.1.1]
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82) [arthas-core.jar:3.1.1]
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18) [arthas-core.jar:3.1.1]
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111) [arthas-core.jar:3.1.1]
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108) [arthas-core.jar:3.1.1]
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370) [arthas-core.jar:3.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
Caused by: ognl.ExpressionSyntaxException: Malformed OGNL expression: *VerificaAction*
	at ognl.Ognl.parseExpression(Ognl.java:112) ~[arthas-core.jar:3.1.1]
	at ognl.Ognl.getValue(Ognl.java:572) ~[arthas-core.jar:3.1.1]
	at ognl.Ognl.getValue(Ognl.java:542) ~[arthas-core.jar:3.1.1]
	at com.taobao.arthas.core.command.express.OgnlExpress.get(OgnlExpress.java:37) ~[arthas-core.jar:3.1.1]
	... 9 common frames omitted
Caused by: ognl.ParseException: Encountered " "*" "* "" at line 1, column 1.
Was expecting one of:
    ":" ...
    "not" ...
    "+" ...
    "-" ...
    "~" ...
    "!" ...
    "(" ...
    "true" ...
    "false" ...
    "null" ...
    "#this" ...
    "#root" ...
    "#" ...
    "[" ...
    "{" ...
    "@" ...
    "new" ...
    <IDENT> ...
    <DYNAMIC_SUBSCRIPT> ...
    "\'" ...
    "`" ...
    "\"" ...
    <INT_LITERAL> ...
    <FLT_LITERAL> ...
    
	at ognl.OgnlParser.generateParseException(OgnlParser.java:3172) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.jj_consume_token(OgnlParser.java:3051) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.unaryExpression(OgnlParser.java:1236) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.multiplicativeExpression(OgnlParser.java:971) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.additiveExpression(OgnlParser.java:894) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.shiftExpression(OgnlParser.java:750) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.relationalExpression(OgnlParser.java:508) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.equalityExpression(OgnlParser.java:405) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.andExpression(OgnlParser.java:352) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.exclusiveOrExpression(OgnlParser.java:299) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.inclusiveOrExpression(OgnlParser.java:246) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.logicalAndExpression(OgnlParser.java:193) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.logicalOrExpression(OgnlParser.java:140) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.conditionalTestExpression(OgnlParser.java:101) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.assignmentExpression(OgnlParser.java:64) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.expression(OgnlParser.java:23) ~[arthas-core.jar:3.1.1]
	at ognl.OgnlParser.topLevelExpression(OgnlParser.java:15) ~[arthas-core.jar:3.1.1]
	at ognl.Ognl.parseExpression(Ognl.java:110) ~[arthas-core.jar:3.1.1]
	... 12 common frames omitted

**Comment by hengyunabc** [comment]
sc 查找不到，说明没有被加载。可以自己用 ognl -c xxxxxx 'Class.forName(className)` 把类加载起来，再 sc 查找

**Comment by gong1989313** [comment]
> sc 查找不到，说明没有被加载。可以自己用 ognl -c xxxxxx 'Class.forName(className)` 把类加载起来，再 sc 查找

你好，这你表达式是怎么用的呢，我试了下好像不行呢。官方手册上也没有相关的介绍。如下图：
![image](https://user-images.githubusercontent.com/10339238/58145474-d1450700-7c84-11e9-87a4-49682c4cb8d5.png)

**Comment by hengyunabc** [comment]
`ognl -h`     。   `-c`是指定 hashcode 。

**Comment by littleBurro** [comment]
遇到了同样的问题

**Comment by MetaRunning** [comment]
也可以使用classloader 主动加载。
文档地址：https://alibaba.github.io/arthas/classloader.html
