### ISSUE TITLE
 Could not initialize class com.taobao.arthas.core.config.Configure

### ISSUE THREAD

**Issue by Lutyison** [alibaba/arthas#728]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.1
* Arthas 版本: 3.1.1
* 操作系统版本: xxx
* 目标进程的JVM版本: jdk1.8
* 执行`arthas-boot`的版本:3.1.1

### 重现问题的步骤

java -jar arthas-boot.jar
选取进程号
### 期望的结果
进入arthas 面版
What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
        at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:268)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
把异常信息贴到这里
java.lang.NoClassDefFoundError: Could not initialize class com.taobao.arthas.core.config.Configure
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.taobao.arthas.agent.AgentBootstrap.bind(AgentBootstrap.java:172)
        at com.taobao.arthas.agent.AgentBootstrap.access$000(AgentBootstrap.java:16)
        at com.taobao.arthas.agent.AgentBootstrap$1.run(AgentBootstrap.java:140)

偶尔还会报第二个异常：
 java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_4fb87apf4/utils/JacocoDataMap
        at com.taobao.arthas.core.config.Configure.$jacocoInit(Configure.java)
        at com.taobao.arthas.core.config.Configure.<clinit>(Configure.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.taobao.arthas.agent.AgentBootstrap.bind(AgentBootstrap.java:172)
        at com.taobao.arthas.agent.AgentBootstrap.access$000(AgentBootstrap.java:16)
        at com.taobao.arthas.agent.AgentBootstrap$1.run(AgentBootstrap.java:140)
Caused by: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_4fb87f4.utils.JacocoDataMap
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at com.taobao.arthas.agent.ArthasClassloader.loadClass(ArthasClassloader.java:34)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by hengyunabc** [comment]
试下去掉 /jacoco/agent

**Comment by Lutyison** [comment]
> 试下去掉 /jacoco/agent

去掉后，就报第一种错误

**Comment by hengyunabc** [comment]
试下 arthas-demo.jar 。重启下进程。

**Comment by Lutyison** [comment]
> 试下 arthas-demo.jar 。重启下进程。

arthas-demo.jar 启动没有问题。无论是进程重启或者说换一台机器部署，都是报相同的错误。但机器中只有这个java 进程启动arthas不成功，其他java进程都是没问题的。会不会和java进程本身有关系？

**Comment by Lutyison** [comment]
> 试下 arthas-demo.jar 。重启下进程。

进程的服务本身是正常稳定的

**Comment by hengyunabc** [comment]
试下Debug： https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md

**Comment by Lutyison** [comment]
> 试下Debug： https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md
你好云神， debug 的结果也是 Connection refused 我测试了其他的java进程都没debug都没问题，就这个进程会出问题

**Comment by hengyunabc** [comment]
最好有可以重现的demo

**Comment by gosenme** [comment]
遇到相同的问题，解决了吗 @Lutyison
