### ISSUE TITLE
centos7 jdk8启动报错

### ISSUE THREAD

**Issue by shuchaang** [alibaba/arthas#73]
```
Calculating attach execution time...
Attaching to 21664 using version 3.0.4...
Start arthas failed, exception stack trace:
java.lang.UnsatisfiedLinkError: no attach in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at sun.tools.attach.LinuxVirtualMachine.<clinit>(LinuxVirtualMachine.java:342)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:69)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:25)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:96)
attach to target jvm (21664) failed, check /home/mwop/logs/arthas/arthas.log or stderr of target jvm for any exceptions.
```

**Comment by ralf0131** [comment]
What is your `$JAVA_HOME` looks like?
It seems that your `$JAVA_HOME` is missing some files.
