### ISSUE TITLE
在k8s种使用这个镜像fabric8/java-alpine-openjdk8-jdk不能使用arthas

### ISSUE THREAD

**Issue by huangxincheng** [alibaba/arthas#734]
[INFO] arthas-boot version: 3.1.1
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 1 /home/ci/ci-user-web.jar
1
[INFO] arthas home: /opt/arthas
[INFO] Try to attach process 1
[ERROR] Start arthas failed, exception stack trace: 
com.sun.tools.attach.AttachNotSupportedException: Unable to get pid of LinuxThreads manager thread
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:86)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:75)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:113)
[ERROR] attach fail, targetPid: 1

**Comment by huangxincheng** [comment]
修改下Dockerfile就行了
# 有arthas版本
COPY --from=hengyunabc/arthas:latest /opt/arthas /opt/arthas
RUN apk add --no-cache tini
ENTRYPOINT ["/sbin/tini", "--"]
#CMD ["/your/program", "-and", "-its", "arguments"]
CMD ["java","-jar","/home/ci/ci-user-web.jar"]

**Comment by hengyunabc** [comment]
把 issue关联起来： https://github.com/alibaba/arthas/issues/362
