### ISSUE TITLE
参数异常，arthas直接关闭

### ISSUE THREAD

**Issue by githublms** [alibaba/arthas#770]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.1.1
* Arthas 版本: xxx
* 操作系统版本: centos7
* 目标进程的JVM版本: jdk1.8
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

有一个简单的springboot项目，里面有一个定时任务和一个正常访问接口，启动程序后，程序正常执行，启动arthas-boot.jar 捕捉到java进程，但是又异常关闭了

### 期望的结果
捕捉java 进程

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
[root@localhost arthas_test]# java -jar arthas-boot.jar 
[INFO] arthas-boot version: 3.1.1
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 38386 sbbase2.jar
1
[INFO] arthas home: /home/lms/arthas_test
[INFO] Try to attach process 38386
[INFO] Attach process 38386 success.
[INFO] arthas-client connect 127.0.0.1 3658
HTTP/1.1 400 
Content-Type: text/html;charset=utf-8
Content-Language: en
Content-Length: 800
Date: Tue, 09 Jul 2019 03:56:02 GMT
Connection: close
<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;bord
[root@localhost arthas_test]# 
```
在springboot基础项目中报错：
```
2019-07-09 11:56:02.784  INFO 38386 --- [nio-3658-exec-1] o.apache.coyote.http11.Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG 

java.lang.IllegalArgumentException: Invalid character found in method name. HTTP  names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11Inpur.java:430) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLigh:66) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractPl.java:808) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoia:1498) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase49) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.j49) [na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.24) [na:1.8.0_211]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThrva:61) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_211]

```

**Comment by githublms** [comment]
springboot基础代码
```
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HelloController {

	@RequestMapping("/hello")
	public String hello() {
		return "hello";
	}
	
	@Scheduled(cron = "*/5 * * * * ?") // 每一分钟执行一次
	public void pushMessage() {
		System.out.println("当前时间是：" + System.currentTimeMillis() + "ms");
	}
}
```

**Comment by hengyunabc** [comment]
没看明白是怎么回事。

具体什么步骤出错，arthas执行了什么命令。

没使用arthas是否会出错。

**Comment by 15178955723** [comment]
我也遇到一模一样的问题,启动arthas-boot.jar后,选择我的java 项目进程,直接报错

![image](https://github.com/alibaba/arthas/assets/54241658/3d6bb198-18d2-4231-a00d-c9d4ff54b336)

![image](https://github.com/alibaba/arthas/assets/54241658/92d73b70-8f84-411a-b73e-821a22107128)

当选择别的java进程,就正常
![image](https://github.com/alibaba/arthas/assets/54241658/0582e6ba-b9b5-4e5a-babc-19ea5b2d93f4)
