### ISSUE TITLE
mc命令编译一直报错, 提示找不到JavaInfo.jar

### ISSUE THREAD

**Issue by imbadark** [alibaba/arthas#773]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.1
* Arthas 版本: 3.1.1
* 操作系统版本: Cent7.5
* 目标进程的JVM版本: JDK8
* 执行`arthas-boot`的版本: JDK8

### 重现问题的步骤

1. 通过`sc -d Xxx.java` 找到classloader
2. 通过 `mc -c classSHA /tmp/Xxx.java -d /tmp` 编译
3. 之前都是正常的, 在mc的时候多次使用`tab` 补全路径之后, 再编译就突然一直报错了, 找了一下相关issue感觉不太符合, 也不知道重启attach的进程之后是否还能复现... 

**PS:** 顺便补充一下, Arthas在`watch/monitor/trace`的时候, 如果当前行字符串稍长(比如超过40字符), console也会经常出现错行光标到处跳的问题, 缩短字符数就会恢复.

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```bash
ClassLoader: sun.misc.Launcher$AppClassLoader@18b4aac2
01 2019-07-10 18:54:46.054 WARN [as-command-execute-daemon:arthas] [] [] [] Memory compiler error
java.lang.RuntimeException: java.lang.RuntimeException: Wasn't able to open jar:file:/tmp/JavaInfo.jar!/org as a jar file
        at com.sun.tools.javac.main.Main.compile(Main.java:559) ~[na:na]
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129) ~[na:na]
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138) ~[na:na]
        at com.taobao.arthas.compiler.DynamicCompiler.buildByteCodes(DynamicCompiler.java:114) ~[arthas-core.jar:3.1.1]
        at com.taobao.arthas.core.command.klass100.MemoryCompilerCommand.process(MemoryCompilerCommand.java:123) ~[arthas-core.jar:3.1.1]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82) [arthas-core.jar:3.1.1]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18) [arthas-core.jar:3.1.1]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111) [arthas-core.jar:3.1.1]
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108) [arthas-core.jar:3.1.1]
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370) [arthas-core.jar:3.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
Caused by: java.lang.RuntimeException: Wasn't able to open jar:file:/tmp/JavaInfo.jar!/org as a jar file
        at com.taobao.arthas.compiler.PackageInternalsFinder.processJar(PackageInternalsFinder.java:88) ~[arthas-core.jar:3.1.1]
        at com.taobao.arthas.compiler.PackageInternalsFinder.listUnder(PackageInternalsFinder.java:62) ~[arthas-core.jar:3.1.1]
        at com.taobao.arthas.compiler.PackageInternalsFinder.find(PackageInternalsFinder.java:51) ~[arthas-core.jar:3.1.1]
        at com.taobao.arthas.compiler.DynamicJavaFileManager.list(DynamicJavaFileManager.java:81) ~[arthas-core.jar:3.1.1]
        at com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager.list(ClientCodeWrapper.java:231) ~[na:na]
        at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2796) ~[na:na]
        at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2446) ~[na:na]
        at com.sun.tools.javac.jvm.ClassReader.access$000(ClassReader.java:76) ~[na:na]
        at com.sun.tools.javac.jvm.ClassReader$1.complete(ClassReader.java:240) ~[na:na]
        at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574) ~[na:na]
        at com.sun.tools.javac.code.Symbol$PackageSymbol.flags(Symbol.java:863) ~[na:na]
        at com.sun.tools.javac.comp.Check.checkDeprecated(Check.java:3163) ~[na:na]
        at com.sun.tools.javac.comp.Attr.checkIdInternal(Attr.java:3635) ~[na:na]
        at com.sun.tools.javac.comp.Attr.checkId(Attr.java:3490) ~[na:na]
        at com.sun.tools.javac.comp.Attr.visitIdent(Attr.java:3233) ~[na:na]
at com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2011) ~[na:na]
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576) ~[na:na]
        at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250) ~[na:na]
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897) ~[na:na]
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576) ~[na:na]
        at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250) ~[na:na]
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897) ~[na:na]
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576) ~[na:na]
        at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250) ~[na:na]
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897) ~[na:na]
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576) ~[na:na]
        at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250) ~[na:na]
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897) ~[na:na]
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576) ~[na:na]
        at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250) ~[na:na]
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897) ~[na:na]
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576) ~[na:na]
        at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250) ~[na:na]
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897) ~[na:na]
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576) ~[na:na]
        at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250) ~[na:na]
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897) ~[na:na]
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576) ~[na:na]
        at com.sun.tools.javac.comp.Attr.attribImportQualifier(Attr.java:410) ~[na:na]
        at com.sun.tools.javac.comp.MemberEnter.visitImport(MemberEnter.java:544) ~[na:na]
        at com.sun.tools.javac.tree.JCTree$JCImport.accept(JCTree.java:571) ~[na:na]
        at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:437) ~[na:na]
        at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:449) ~[na:na]
        at com.sun.tools.javac.comp.MemberEnter.visitTopLevel(MemberEnter.java:528) ~[na:na]
        at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518) ~[na:na]
        at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:437) ~[na:na]
        at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:1038) ~[na:na]
        at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574) ~[na:na]
        at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1037) ~[na:na]
        at com.sun.tools.javac.comp.Enter.complete(Enter.java:493) ~[na:na]
        at com.sun.tools.javac.comp.Enter.main(Enter.java:471) ~[na:na]
        at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982) ~[na:na]
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:857) ~[na:na]
        at com.sun.tools.javac.main.Main.compile(Main.java:523) ~[na:na]
        ... 12 common frames omitted
Caused by: java.io.FileNotFoundException: /tmp/JavaInfo.jar (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method) ~[na:1.8.0_144]
        at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[na:1.8.0_144]
        at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[na:1.8.0_144]
        at java.util.jar.JarFile.<init>(JarFile.java:166) ~[na:1.8.0_144]
        at java.util.jar.JarFile.<init>(JarFile.java:103) ~[na:1.8.0_144]
        at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93) ~[na:1.8.0_144]
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69) ~[na:1.8.0_144]
        at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84) ~[na:1.8.0_144]
        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122) ~[na:1.8.0_144]
        at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89) ~[na:1.8.0_144]
        at com.taobao.arthas.compiler.PackageInternalsFinder.processJar(PackageInternalsFinder.java:75) ~[arthas-core.jar:3.1.1]
        ... 65 common frames omitted
```

**Comment by hengyunabc** [comment]
```
Caused by: java.io.FileNotFoundException: /tmp/JavaInfo.jar (No such file or directory)
```

最有可能是这个jar被删掉了，或者被替换了，然后进程打开不了这个jar了。

**Comment by imbadark** [comment]
但是奇怪的是, 这个Jar到底是做什么的呢?
原本`/tmp`下是没有这个jar文件的, 我之前以为是`Arthas` 自己临时拷贝引用了, 关于这个jar的信息也很少, 这有个win下提示不存在的[排错参考](https://www.solvusoft.com/en/files/error-missing-download/jar/windows/websense-inc/websense-enterprise/javainfo-jar/)
而且似乎这个问题还很难复现出来, 就有点没头绪定位root-case...

**Comment by 1ibo** [comment]
我也遇到类似的错误
- arthas版本: 3.2.0
- jdk版本: Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

执行命令 mc -c 239af6b8 /tmp/PayChannel4WxServiceImpl.java -d /tmp
```
[arthas@12099]$ mc -c 239af6b8 /tmp/PayChannel4WxServiceImpl.java -d /tmp
Memory compiler error, exception message: java.lang.RuntimeException: Wasn't able to open jar:file:/usr/local/apache-tomcat-8.5.20/webapps/ROOT/WEB-INF/lib/spring-boot-starter-logging-2.0.4.RELEASE.jar!/ as a jar file, please check $HOME/logs/arthas/arthas.log for more details. 
Affect(row-cnt:0) cost in 396 ms.
```
错误日志
```
2020-07-22 14:22:03 [as-command-execute-daemon] WARN  c.t.a.c.c.k.MemoryCompilerCommand -Memory compiler error
java.lang.RuntimeException: java.lang.RuntimeException: Wasn't able to open jar:file:/usr/local/apache-tomcat-8.5.20/webapps/ROOT/WEB-INF/lib/spring-boot-starter-logging-2.0.4.RELEASE.jar!/ as a jar file
        at com.sun.tools.javac.main.Main.compile(Main.java:559)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at com.taobao.arthas.compiler.DynamicCompiler.buildByteCodes(DynamicCompiler.java:111)
        at com.taobao.arthas.core.command.klass100.MemoryCompilerCommand.process(MemoryCompilerCommand.java:106)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:371)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Wasn't able to open jar:file:/usr/local/apache-tomcat-8.5.20/webapps/ROOT/WEB-INF/lib/spring-boot-starter-logging-2.0.4.RELEASE.jar!/ as a jar file
        at com.taobao.arthas.compiler.PackageInternalsFinder.processJar(PackageInternalsFinder.java:88)
        at com.taobao.arthas.compiler.PackageInternalsFinder.listUnder(PackageInternalsFinder.java:62)
        at com.taobao.arthas.compiler.PackageInternalsFinder.find(PackageInternalsFinder.java:51)
        at com.taobao.arthas.compiler.DynamicJavaFileManager.list(DynamicJavaFileManager.java:81)
        at com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager.list(ClientCodeWrapper.java:231)
        at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2796)
        at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2446)
        at com.sun.tools.javac.jvm.ClassReader.access$000(ClassReader.java:76)
        at com.sun.tools.javac.jvm.ClassReader$1.complete(ClassReader.java:240)
        at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
        at com.sun.tools.javac.code.Symbol$PackageSymbol.members(Symbol.java:858)
        at com.sun.tools.javac.comp.Resolve.findType(Resolve.java:2081)
        at com.sun.tools.javac.comp.Resolve.findIdent(Resolve.java:2110)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitIdentifier(Attr.java:393)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitIdentifier(Attr.java:375)
        at com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2017)
        at com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:378)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:375)
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1903)
        at com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:378)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:375)
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1903)
        at com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:378)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:375)
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1903)
        at com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:378)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:375)
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1903)
        at com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:378)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:375)
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1903)
        at com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:378)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:375)
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1903)
        at com.sun.tools.javac.comp.Attr.attribIdent(Attr.java:371)
        at com.sun.tools.javac.main.JavaCompiler.resolveIdent(JavaCompiler.java:705)
        at com.sun.tools.javac.model.JavacElements.nameToSymbol(JavacElements.java:125)
        at com.sun.tools.javac.model.JavacElements.getTypeElement(JavacElements.java:108)
        at com.sun.tools.javac.model.JavacElements.getTypeElement(JavacElements.java:61)
        at org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor.process(ConfigurationMetadataAnnotationProcessor.java:172)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 12 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.taobao.arthas.compiler.PackageInternalsFinder.processJar(PackageInternalsFinder.java:73)
        ... 65 common frames omitted
```

**Comment by 1ibo** [comment]
@hengyunabc

**Comment by hengyunabc** [comment]
@1ibo 可以调试下代码： https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md

或者试下用代码打开这个jar，看下 rootEntryName 为什么是  null 。

```java
            JarURLConnection jarConn = (JarURLConnection) packageFolderURL.openConnection();
            String rootEntryName = jarConn.getEntryName();
            int rootEnd = rootEntryName.length() + 1;
```

**Comment by 1ibo** [comment]
好的，我试试，谢谢。

**Comment by devh0407** [comment]
@hengyunabc 我按照这个代码片段尝试, 发现是在 jarConn.getEntryName(); 时异常的, getEntryName 的注释提示了
> This method returns null if the JAR file URL corresponding to this connection points to a JAR file and not a JAR file entry.
然后JarURLConnection 中注释表明 !/之后没有spec的为Jar File
> Examples:
> A Jar entry
> jar:http://www.foo.com/bar/baz.jar!/COM/foo/Quux.class
> A Jar file
> jar:http://www.foo.com/bar/baz.jar!/
所以问题是 JarFile 情况时的 packageFolderURL 不应该再进行后续处理吧

> @1ibo 可以调试下代码： https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md
> 
> 或者试下用代码打开这个jar，看下 rootEntryName 为什么是 null 。
> 
> ```java
>             JarURLConnection jarConn = (JarURLConnection) packageFolderURL.openConnection();
>             String rootEntryName = jarConn.getEntryName();
>             int rootEnd = rootEntryName.length() + 1;
> ```

**Comment by hengyunabc** [comment]
@devh0407 最好提交一个demo

**Comment by guoyuansun** [comment]
求问，这个问题有解决的分支吗

**Comment by ysdlb** [comment]
我今天也碰到了，rootEntryName 为 null
