### ISSUE TITLE
启动后，监听程序时无法运行

### ISSUE THREAD

**Issue by rggaoxin** [alibaba/arthas#794]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.1
* Arthas 版本: xxx
* 操作系统版本: centos7
* 目标进程的JVM版本: arthas_demo
* 执行`arthas-boot`的版本: xxx

### 报错
[root@maximodb01 opt]# java -jar arthas-boot.jar
[INFO] arthas-boot version: 3.1.1
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 20359 org.apache.catalina.startup.Bootstrap
  [2]: 25806 arthas-demo.jar
2
[INFO] arthas home: /root/.arthas/lib/3.1.1/arthas
[INFO] Try to attach process 25806
[ERROR] Start arthas failed, exception stack trace: 
java.lang.UnsatisfiedLinkError: sun.tools.attach.WindowsAttachProvider.tempPath()Ljava/lang/String;
	at sun.tools.attach.WindowsAttachProvider.tempPath(Native Method)
	at sun.tools.attach.WindowsAttachProvider.isTempPathSecure(WindowsAttachProvider.java:91)
	at sun.tools.attach.WindowsAttachProvider.listVirtualMachines(WindowsAttachProvider.java:75)
	at com.sun.tools.attach.VirtualMachine.list(VirtualMachine.java:147)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:64)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:113)
[ERROR] attach fail, targetPid: 25806

**Comment by hengyunabc** [comment]
检查 jdk版本是不是一致的

**Comment by rggaoxin** [comment]
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)


jdk版本为openjdk，64位

**Comment by rggaoxin** [comment]
使用openjdk 1.8启动arthas-demo.jar后，同一个版本的jdk启动arthas-boot.jar，仍和上面报相同错误

**Comment by hengyunabc** [comment]
同一个用户启动应该不会有问题。在线教程里跑的就是 openjdk 

https://alibaba.github.io/arthas/arthas-tutorials?language=cn

**Comment by rggaoxin** [comment]
理论上没有问题，不知道是不是使用ibm was的原因，使用的jdk是was中自带的版本。但是使用服务器中的其他版本同时启动demo和boot还是会出现相同的错误
