### ISSUE TITLE
首次agent失败，后续重新agent不会输出错误log

### ISSUE THREAD

**Issue by zyllt** [alibaba/arthas#795]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.1
* Arthas 版本: 3.1.1
* 操作系统版本: ubuntu14
* 目标进程的JVM版本: 1.7.0_79
* 执行`arthas-boot`的版本:  3.1.1

### 重现问题的步骤

1. 启动arthas对resin目标进程进行attach，提示agent failed
2.此时查看arthas.log，可以查看到有错误日志输出。但是如果重新执行arthas对原进程进行attach，就不会再有log输出了，必须重启目标进程才可以。
3.看了下AgentBootstrap的源码和resin的文档已经把agent failed的问题解决了，只是对如果失败后必须重启目标进程才可以有log输出的问题比较疑惑。
### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
```
www-data@switcher-195:/tmp/.arthas/lib/3.1.1/arthas$ /usr/local/jdk1.7.0_79/bin/java -jar ./arthas-boot.jar -v
[INFO] arthas-boot version: 3.1.1
[DEBUG] Repo mirror:aliyun
[DEBUG] Java version is 1.7, only support http, set useHttp to true.
[DEBUG] Found jps: /usr/local/jdk1.7.0_79/jre/../bin/jps
[DEBUG] Try use jps to lis java process, jps: /usr/local/jdk1.7.0_79/jre/../bin/jps
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 3282 com.caucho.server.resin.Resin -Xms3072m -Xmx3072m -Xss1m -XX:MaxGCPauseMillis=200 -Dnetworkaddress.cache.ttl=600 -XX:PermSize=128M -XX:MaxPermSize=256M -Dresin.server=1 -Djava.util.logging.manager=com.caucho.log.LogManagerImpl -Djava.system.class.loader=com.caucho.loader.SystemClassLoader -Djavax.management.builder.initial=com.caucho.jmx.MBeanServerBuilderImpl -Djava.awt.headless=true -Dresin.home=/usr/local/resin/ -Dresin.watchdog=a -Djava.util.logging.manager=com.caucho.log.LogManagerImpl -Djavax.management.builder.initial=com.caucho.jmx.MBeanServerBuilderImpl -Djava.awt.headless=true -Dresin.home=/usr/local/resin/ -Dresin.root=/usr/local/resin -Dresin.watchdog=a -Djava.util.logging.manager=com.caucho.log.LogManagerImpl -Djavax.management.builder.initial=com.caucho.jmx.MBeanServerBuilderImpl -Djava.awt.headless=true -Dresin.home=/usr/local/resin/ -Dresin.root=/usr/local/resin
1
[INFO] arthas home: /tmp/.arthas/lib/3.1.1/arthas
[INFO] Try to attach process 3282
[DEBUG] Start arthas-core.jar args: [-jar, /tmp/.arthas/lib/3.1.1/arthas/arthas-core.jar, -pid, 3282, -target-ip, 127.0.0.1, -telnet-port, 3658, -http-port, 8563, -core, /tmp/.arthas/lib/3.1.1/arthas/arthas-core.jar, -agent, /tmp/.arthas/lib/3.1.1/arthas/arthas-agent.jar]
[DEBUG] Found java: /usr/local/jdk1.7.0_79/jre/bin/java
[DEBUG] Found java: /usr/local/jdk1.7.0_79/jre/../bin/java
[DEBUG] Found tools.jar: /usr/local/jdk1.7.0_79/jre/../lib/tools.jar
[ERROR] Start arthas failed, exception stack trace: 
com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:94)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:113)
[ERROR] attach fail, targetPid: 3282
```
```
java.lang.NoClassDefFoundError: java/arthas/Spy
	at com.taobao.arthas.agent.AgentBootstrap.initSpy(AgentBootstrap.java:190)
	at com.taobao.arthas.agent.AgentBootstrap.main(AgentBootstrap.java:218)
	at com.taobao.arthas.agent.AgentBootstrap.agentmain(AgentBootstrap.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:382)
	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:407)
Caused by: java.lang.ClassNotFoundException: java.arthas.Spy in SystemClassLoader[system,new]
	at com.caucho.loader.DynamicClassLoader.loadClass(DynamicClassLoader.java:1358)
	at com.caucho.loader.DynamicClassLoader.loadClass(DynamicClassLoader.java:1334)
	... 9 more
```

**Comment by hengyunabc** [comment]
`java.arthas.Spy`是在SystemClassLoader里加载的。

`com.caucho.loader.DynamicClassLoader` 没有从SystemClassLoader 加载到，也许是它本身做了一个class not found缓存

**Comment by zyllt** [comment]
> `java.arthas.Spy`是在SystemClassLoader里加载的。
> 
> `com.caucho.loader.DynamicClassLoader` 没有从SystemClassLoader 加载到，也许是它本身做了一个class not found缓存

嗯，这个了解。在resin启动时指定了`-Djava.system.class.loader=com.caucho.loader.SystemClassLoader`，这个resin版本的classloader有点问题，已经修复。
我主要困惑的是在对这个resin进程执行`java -jar arthas-boot.jar`时，因为抛出了`AgentInitializationException`，此时我在`~/logs/arthas/arthas.log`可以查看到此次启动失败的log。
但是如果我后续再对同个resin进程执行`java -jar arthas-boot.jar`，即使还是出现了`AgentInitializationException`，但是在`~/logs/arthas/arthas.log`不再有AgentBootstrap的错误日志输出，必须重启resin进程才可以。
目前这个log问题只是在`java -jar arthas-boot.jar`对目标进程出现失败时才会发生，arthas-agent正常启动和shutdown的话不会有这个问题。

**Comment by zyllt** [comment]
我在定位这个resin attach失败问题时对`AgentBootstrap`的源码加了一些调试log，发现替换了`arthas-agent.jar`后增加的调试log不能正常输出到`~/logs/arthas/arthas.log`，需要重启相应的resin进程才可以正常输出log，我对这个log问题很困惑。

**Comment by hengyunabc** [comment]
因为jvm加载类失败之后，就会标记状态，后续再次attach时，不会再加载agent里失败的类，所以再次attach逻辑就会很诡异了。

参考这个： http://hengyunabc.github.io/hibernate-validar-noclassdefounderror/

**Comment by zyllt** [comment]
原来如此，thanks

**Comment by moreOsun** [comment]
resin容器的agent failed的问题解决了
这个是如何解决的？可以说下吗

**Comment by hengyunabc** [comment]
> resin容器的agent failed的问题解决了
> 这个是如何解决的？可以说下吗

@moreOsun  参考下这个 https://github.com/alibaba/arthas/issues/795#issuecomment-517517973
