### ISSUE TITLE
com.sun.tools.attach.AttachNotSupportedException: Unable to get pid of LinuxThreads manager thread

### ISSUE THREAD

**Issue by weihc02** [alibaba/arthas#800]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.1
* Arthas 版本: 3.1.1
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: 3.1.1

### 重现问题的步骤

1. k8s 集群中，java程序，容器中
# ps aux|grep java
    1 root      2:02 java -Xms3000m -Xmx3000m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -jar /usr/local/ocr/app.jar
 6000 root      0:00 grep java

2. 基础镜像
![image](https://user-images.githubusercontent.com/17331776/62508795-778fba00-b83b-11e9-9d43-36f098dc3c28.png)

### 期望的结果

监测到进程为1 ，选择1时，提示报错，

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 1 /usr/local/ocr/app.jar
1
[INFO] arthas home: /opt/arthas
[INFO] Try to attach process 1
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2019-08-06 11:04:09 [WARN ](com.navercorp.pinpoint.bootstrap.PinpointBootStrap) arms agent start cost: 3430ms
[ERROR] Start arthas failed, exception stack trace: 
com.sun.tools.attach.AttachNotSupportedException: Unable to get pid of LinuxThreads manager thread
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:86)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:75)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:113)
[INFO] Attach process 1 success.
[INFO] arthas-client connect 127.0.0.1 3658
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
	at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:268)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:503)

```

**Comment by weihc02** [comment]
根据已经关闭的issue，https://cloud.docker.com/repository/docker/hengyunabc/arthas  ，仍然报上面错误。

**Comment by hengyunabc** [comment]
pid 1的问题，参考： https://github.com/alibaba/arthas/issues/362

**Comment by D-T-Y** [comment]
我用rancher2 也有这种情况

**Comment by weihc02** [comment]
![image](https://user-images.githubusercontent.com/17331776/62521236-d536fd00-b861-11e9-87ce-f1bf87fb8055.png)
可以解决
