### ISSUE TITLE
arthas 出现 java.net.BindException

### ISSUE THREAD

**Issue by superguopeng** [alibaba/arthas#82]
```
error info 
01 2018-09-20 09:07:36.633 INFO [arthas-binding-thread:arthas] [] [] [] arthas version: 3.0.4
01 2018-09-20 09:07:37.785 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0xb7f9d932] REGISTERED
01 2018-09-20 09:07:37.788 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0xb7f9d932] BIND: /0.0.0.0:3658
01 2018-09-20 09:07:37.819 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0xb7f9d932] CLOSE
01 2018-09-20 09:07:37.847 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0xb7f9d932] UNREGISTERED
01 2018-09-20 09:07:37.857 ERROR [arthas-binding-thread:arthas] [] [] [] Error listening to port 3658
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_60]
        at sun.nio.ch.Net.bind(Net.java:433) ~[na:1.8.0_60]
        at sun.nio.ch.Net.bind(Net.java:425) ~[na:1.8.0_60]
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[na:1.8.0_60]
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:130) ~[arthas-core.jar:3.0.4]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558) ~[arthas-core.jar:3.0.4]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1358) ~[arthas-core.jar:3.0.4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501) ~[arthas-core.jar:3.0.4]
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486) ~[arthas-core.jar:3.0.4]
        at io.netty.handler.logging.LoggingHandler.bind(LoggingHandler.java:191) ~[arthas-core.jar:3.0.4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501) ~[arthas-core.jar:3.0.4]
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486) ~[arthas-core.jar:3.0.4]
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1019) ~[arthas-core.jar:3.0.4]
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254) ~[arthas-core.jar:3.0.4]
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366) ~[arthas-core.jar:3.0.4]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[arthas-core.jar:3.0.4]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[arthas-core.jar:3.0.4]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446) ~[arthas-core.jar:3.0.4]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[arthas-core.jar:3.0.4]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[arthas-core.jar:3.0.4]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]

jdk_home /opt/jdk/jdk1.8.0_60
java-version   java version "1.8.0_60"
```

**Comment by ralf0131** [comment]
Hi, 

This is because 3658 has been already binded. Please check which process is using 3658. For linux you can try:

```
sudo netstat -anop | grep 3658
```

You have to shutdown the previous started Arthas so that you can use 3658. If you would like to keep both, you have to use different port number.

```
./as.sh <PID>@[IP:PORT]
```

**Comment by superguopeng** [comment]
> Hi,
> 
> This is because 3658 has been already binded. Please check which process is using 3658. For linux you can try:
> 
> ```
> sudo netstat -anop | grep 3658
> ```
> You have to shutdown the previous started Arthas so that you can use 3658. If you would like to keep both, you have to use different port number.
> 
> ```
> ./as.sh <PID>@[IP:PORT]
> ```
According to your answer,The following error message appears
./as.sh 1265@127.0.0.1:3659
Arthas script version: 3.0.4
Calculating attach execution time...
Attaching to 1265 using version 3.0.4...

real	0m0.229s
user	0m0.259s
sys	0m0.042s
Attach success.
Connecting to arthas server... current timestamp is 1537407953
./as.sh: line 423: type: telnet: not found
'telnet' is required.

**Comment by ralf0131** [comment]
Did you have telnet installed? Telnet is a requirement for Arthas.

**Comment by superguopeng** [comment]
> Did you have telnet installed? Telnet is a requirement for Arthas.

thank you very much ! I have successfully used it.
