### ISSUE TITLE
Git bash 貌似不支持

### ISSUE THREAD

**Issue by NichenFly** [alibaba/arthas#833]
习惯使用git bash运行命令, 本地windows的命令大部分也被git bash的替换了, 所以就出现了这个, cmd,貌似没报错

### 环境信息

* 操作系统版本:  Windows 10

### 实际运行的结果
```
Administrator@DESKTOP-KOVN4CB MINGW64 /e/Arthas
$ java -jar arthas-boot.jar --repo-mirror aliyun --use-http
[INFO] arthas-boot version: 3.1.1
[INFO] Process 7544 already using port 3658
[INFO] Process 7544 already using port 8563
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 7544 finalshell.jar
  [2]: 13956 org.jetbrains.idea.maven.server.RemoteMavenServer36
  [3]: 12264
1
[INFO] arthas home: C:\Users\Administrator\.arthas\lib\3.1.1\arthas
[INFO] The target process already listen port 3658, skip attach.
[INFO] arthas-client connect 127.0.0.1 3658
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.IllegalArgumentException: Invalid terminal type: jline.UnixTerminal
        at jline.TerminalFactory.create(TerminalFactory.java:103)
        at jline.TerminalFactory.get(TerminalFactory.java:180)
        at jline.TerminalFactory.get(TerminalFactory.java:186)
        at jline.console.ConsoleReader.<init>(ConsoleReader.java:244)
        at jline.console.ConsoleReader.<init>(ConsoleReader.java:236)
        at jline.console.ConsoleReader.<init>(ConsoleReader.java:228)
        at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:190)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:503)
Caused by: java.lang.ClassNotFoundException: jline.UnixTerminal
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at jline.TerminalFactory.create(TerminalFactory.java:100)
        ... 11 more

  ,---.  ,------. ,--------.,--.  ,--.  ,---.   ,---.
 /  O  \ |  .--. ''--.  .--'|  '--'  | /  O  \ '   .-'
|  .-.  ||  '--'.'   |  |   |  .--.  ||  .-.  |`.  `-.
|  | |  ||  |\  \    |  |   |  |  |  ||  | |  |.-'    |
`--' `--'`--' '--'   `--'   `--'  `--'`--' `--'`-----'


wiki      https://alibaba.github.io/arthas
tutorials https://alibaba.github.io/arthas/arthas-tutorials
version   3.1.1
pid       7544
time      2019-08-27 09:52:00
```

**Comment by hengyunabc** [comment]
之前测试过支持的😂，欢迎提交PR修复

**Comment by jiangwh** [comment]
的确是支持的。再boot的模块打包的时候缺少依赖。

**Comment by hengyunabc** [comment]
@jiangwh 尽管你的修改可以工作，但是boot模块本身不应该依赖 jline的。boot模块是用一个ClassLoader加载起 arthas-client的，可能是classloader的一些问题？

**Comment by jiangwh** [comment]
@hengyunabc 嗯。我看到了，在client模块中有引用jline。这个问题要再看下。

**Comment by jiangwh** [comment]
跟这之前的提交记录一起，比较乱。我关闭了PR。重推

**Comment by jiangwh** [comment]
重新提交了一把。

**Comment by hengyunabc** [comment]
看了下jline的代码，它是用TCCL来加载类的：

`                        t = (Terminal) Thread.currentThread().getContextClassLoader().loadClass(type).newInstance();`

```java
    public static synchronized Terminal create(String ttyDevice) {
        if (Log.TRACE) {
            //noinspection ThrowableInstanceNeverThrown
            Log.trace(new Throwable("CREATE MARKER"));
        }

        String defaultType = "dumb".equals(System.getenv("TERM")) ? NONE : AUTO;
        String type  = Configuration.getString(JLINE_TERMINAL, defaultType);

        Log.debug("Creating terminal; type=", type);

        Terminal t;
        try {
            String tmp = type.toLowerCase();

            if (tmp.equals(UNIX)) {
                t = getFlavor(Flavor.UNIX);
            }
            else if (tmp.equals(OSV)) {
                t = getFlavor(Flavor.OSV);
            }
            else if (tmp.equals(WIN) || tmp.equals(WINDOWS)) {
                t = getFlavor(Flavor.WINDOWS);
            }
            else if (tmp.equals(NONE) || tmp.equals(OFF) || tmp.equals(FALSE)) {
                if (System.getenv("INSIDE_EMACS") != null) {
                    // emacs requires ansi on and echo off
                    t = new UnsupportedTerminal(true, false);
                } else  {
                    // others the other way round
                    t = new UnsupportedTerminal(false, true);
                }
            }
            else {
                if (tmp.equals(AUTO)) {
                    String os = Configuration.getOsName();
                    Flavor flavor = Flavor.UNIX;
                    if (os.contains(WINDOWS)) {
                        flavor = Flavor.WINDOWS;
                    } else if (System.getenv("OSV_CPUS") != null) {
                        flavor = Flavor.OSV;
                    }
                    t = getFlavor(flavor, ttyDevice);
                }
                else {
                    try {
                        t = (Terminal) Thread.currentThread().getContextClassLoader().loadClass(type).newInstance();
                    }
                    catch (Exception e) {
                        throw new IllegalArgumentException(MessageFormat.format("Invalid terminal type: {0}", type), e);
                    }
                }
            }
        }
```

所以只要设置好TCCL就可以了
