### ISSUE TITLE
使用monitor、watch命令，被监控的系统出现异常

### ISSUE THREAD

**Issue by vic-liang** [alibaba/arthas#842]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.1
* Arthas 版本: 3.1.1
* 操作系统版本: Ubuntu 16.04.4 LTS
* 目标进程的JVM版本: 1.8.0_181
* 执行`arthas-boot`的版本: 1.8.0_181

### 重现问题的步骤

1. 系统的rpc框架使用的dubbo，然后有自定义的filter
2. 使用monitor -c 5 xx.xx.Filter invoke 观察方法调用情况
3. 使用watch xx.xx.Filter 内部方法 "{params,returnObj}" -x 2查看内部方法的返回值

### 期望的结果

正常显示监控结果

### 实际运行的结果

问题1：
执行命令后返回如下结果，但是没有具体的信息
Press Ctrl+C to abort.
Affect(class-cnt:1 , method-cnt:1) cost in 38 ms.

问题2：
系统的dubbo consumer端，出现了 
com.alibaba.dubbo.rpc.RpcException: Failed to invoke remote method:  xxx

```
com.alibaba.dubbo.rpc.RpcException: Failed to invoke remote method: xxxMethod, provider: dubbo:....., cause: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
 at sun.reflect.GeneratedMethodAccessor812.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at xxx.xxx.xxxFilter.invoke(xxxFilter.java:98)
 at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
 at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:70)
 at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
 at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:132)
 at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
 at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
 at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
 at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
 at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
 at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:113)
 at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84)
 at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)
 at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
 at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.NoSuchElementException
 at com.taobao.arthas.core.util.collection.ThreadUnsafeGaStack.checkForPopOrPeek(ThreadUnsafeGaStack.java:52)
 at com.taobao.arthas.core.util.collection.ThreadUnsafeGaStack.pop(ThreadUnsafeGaStack.java:59)
 at com.taobao.arthas.core.advisor.AdviceWeaver.threadFrameStackPop(AdviceWeaver.java:237)
 at com.taobao.arthas.core.advisor.AdviceWeaver.methodOnEnd(AdviceWeaver.java:140)
 at com.taobao.arthas.core.advisor.AdviceWeaver.methodOnThrowingEnd(AdviceWeaver.java:121)
 ... 21 more
```

**Comment by hengyunabc** [comment]
可以提供重现的demo不？
