### ISSUE TITLE
mc  编译报错 Memory compiler error, exception message: Can not load JavaCompiler from javax.tools.ToolProvider#getSystemJavaCompiler()

### ISSUE THREAD

**Issue by vimilai** [alibaba/arthas#846]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* Arthas 版本: 3.1.2
* 操作系统版本: centos
* 目标进程的JVM版本: jdk1.7.0_79
* 执行`arthas-boot`的版本:3.1.1
![image](https://user-images.githubusercontent.com/19221051/64507660-e619d900-d30d-11e9-91fc-00b3117531a3.png)

### 重现问题的步骤

1. /opt/jdk1.7.0_79/bin/java  -jar arthas-boot.jar 24494  （成功）
2. jad --source-only com.lvmama.scenic.api.prod.service.impl.ScenicSuppGoodsServiceImpl > /root/ScenicSuppGoodsServiceImpl .java（成功）
3.   mc   /root/ScenicSuppGoodsServiceImpl.java （### error）
mc   /root/ScenicSuppGoodsServiceImpl.java  -d /root（### error）
### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

Memory compiler error, exception message: Can not load JavaCompiler from javax.tools.ToolProvider#getSystemJavaCompiler(), please confirm the application running in JDK not JRE., please check $HOME/logs/arthas/arthas.log for more details. 
把异常信息贴到这里
1 2019-09-09 13:55:47.626 WARN [as-command-execute-daemon:arthas] [] [] [] Memory compiler error
java.lang.IllegalStateException: Can not load JavaCompiler from javax.tools.ToolProvider#getSystemJavaCompiler(), please confirm the application running in JDK not JRE.
        at com.taobao.arthas.compiler.DynamicCompiler.<init>(DynamicCompiler.java:29)
        at com.taobao.arthas.core.command.klass100.MemoryCompilerCommand.process(MemoryCompilerCommand.java:90)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)

**Comment by hengyunabc** [comment]
试下jdk 1.8

**Comment by heartMa** [comment]
把你要监控的项目用对应的jdk下的java命令去启动  /opt/jdk1.7.0_79/bin/java -jar arthas-demo.jar

**Comment by tsgkim** [comment]
我还是遇到同样的问题，

我的环境变量：

**Comment by tsgkim** [comment]
我还是遇到同样的问题，搜遍全网都没找到解决方案

**Comment by carry555** [comment]
> 我还是遇到同样的问题，搜遍全网都没找到解决方案

这个报错的问题我解决了，就是你运行arthas的jdk要跟你监控的服务器的jdk同一个就行  不如你服务器的jdk都装在 /usr/local/java/  那么你运行的jar包的时候 都用  /uar/local/java/bin/java 来运行

**Comment by Mengleijin** [comment]
我也遇到了同样的问题，原因可能是找不到jdk lib目录下tools.jar文件，没法编译，之前我设置JAVA_HOME在java\jdk
 更改为Java\jdk\jre，同时将jdk\lib下将tools.jar复制到jre\lib下
