### ISSUE TITLE
trace 异常

### ISSUE THREAD

**Issue by mituuupeng** [alibaba/arthas#850]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.1.1-3.1.2
* 操作系统版本: window
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. trace com.xxx.pdts.service.xxx.impl.XxxxImportService threadImport
2. [arthas@952]$ sm com.xxx.pdts.service.xxx.impl.XxxxImportService threadImport
com.xxx.pdts.service.xxx.impl.XxxxImportService threadImport(Ljava/util/List;)V
Affect(row-cnt:1) cost in 13 ms.

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
01 2019-09-11 18:07:50.776 WARN [as-command-execute-daemon:arthas] [] [] [] transform loader[sun.misc.Launcher$AppClassLoader@18b4aac2]:class[com/xxx/pdts/service/xxx/impl/XxxxImportService] failed.
java.lang.ArrayIndexOutOfBoundsException: -1
	at org.objectweb.asm.Frame.merge(Frame.java:1155)
	at org.objectweb.asm.CurrentFrame.execute(CurrentFrame.java:53)
	at org.objectweb.asm.MethodWriter.visitVarInsn(MethodWriter.java:937)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2168)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1275)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:679)
	at org.objectweb.asm.ClassWriter.replaceAsmInstructions(ClassWriter.java:692)
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:659)
	at com.taobao.arthas.core.advisor.Enhancer.transform(Enhancer.java:163)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:304)
	at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:111)
	at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:66)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
01 2019-09-11 18:07:50.811 INFO [as-command-execute-daemon:arthas] [] [] [] Success to batch transform classes: [class com.zxelec.pdts.service.sensetime.impl.SensetimeImportService]
```

**Comment by hengyunabc** [comment]
最好提供一个可重现的demo，不然无从下手
