### ISSUE TITLE
3.1.2版本 jad命令在jdk低于1.8的环境下异常

### ISSUE THREAD

**Issue by yinbifen** [alibaba/arthas#851]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.2
* Arthas 版本: 3.1.2
* 操作系统版本: win10 1903
* 目标进程的JVM版本: 1.7.0_80
* 执行`arthas-boot`的版本: 1.7.0_80

### 重现问题的步骤

1. java -jar arthas-demo.jar
2. java -jar arthas-boot.jar
3. jad demo.MathGame

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
01 2019-09-10 18:00:49.435 ERROR [as-command-execute-daemon:arthas] [] [] [] jad: fail to decompile class: demo.MathGame
java.lang.UnsupportedOperationException: null
	at java.util.AbstractList.set(AbstractList.java:132)
	at java.util.AbstractList$ListItr.set(AbstractList.java:426)
	at java.util.Collections.sort(Collections.java:159)
	at org.benf.cfr.reader.CfrDriverImpl.analyse(CfrDriverImpl.java:48)
	at com.taobao.arthas.core.util.Decompiler.decompile(Decompiler.java:60)
	at com.taobao.arthas.core.command.klass100.JadCommand.processExactMatch(JadCommand.java:156)
	at com.taobao.arthas.core.command.klass100.JadCommand.process(JadCommand.java:113)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by hengyunabc** [comment]
3.1.2版本里升级了cfr，然后在反编译时用`Collections.singletonList`创建了一个参数，传递给cfr使用：

```java
        CfrDriver driver = new CfrDriver.Builder().withOptions(options).withOutputSink(mySink).build();
        driver.analyse(Collections.singletonList(classFilePath));
```

但cfr里调用了`Collections.sort`来处理这个list ，所以导致出问题。

---

根本原因是 jdk 6/7 和 jdk8的 Collections.sort 的实现不同导致的。

jdk7下面的实现是：

```java
    public static <T extends Comparable<? super T>> void sort(List<T> list) {
        Object[] a = list.toArray();
        Arrays.sort(a);
        ListIterator<T> i = list.listIterator();
        for (int j=0; j<a.length; j++) {
            i.next();
            i.set((T)a[j]);
        }
    }
```
这里的`i.set((T)a[j]);` 要修改 list里的元素。所以抛出了一个`UnsupportedOperationException`异常。

在jdk8里的实现是：

```java
    public static <T extends Comparable<? super T>> void sort(List<T> list) {
        list.sort(null);
    }
```

实际上`Collections.singletonList` 返回的是`SingletonList`：

```java
    public static <T> List<T> singletonList(T o) {
        return new SingletonList<>(o);
    }
```

它的 sort函数是空的，所以在jdk8下面可以正常工作：

```java
    /**
     * @serial include
     */
    private static class SingletonList<E>
        extends AbstractList<E>
        implements RandomAccess, Serializable {
        @Override
        public void sort(Comparator<? super E> c) {
        }
```

**Comment by vanTryMyBest** [comment]
遇到同样的问题，重新下载新的jar包，现在已经解决了
01 2019-09-19 10:14:10.276 ERROR [as-command-execute-daemon:arthas] [] [] [] jad: fail to decompile class: demo.MathGame
java.lang.UnsupportedOperationException: null
	at java.util.AbstractList.set(AbstractList.java:132)
	at java.util.AbstractList$ListItr.set(AbstractList.java:426)
	at java.util.Collections.sort(Collections.java:159)
	at org.benf.cfr.reader.CfrDriverImpl.analyse(CfrDriverImpl.java:48)
	at com.taobao.arthas.core.util.Decompiler.decompile(Decompiler.java:60)
	at com.taobao.arthas.core.command.klass100.JadCommand.processExactMatch(JadCommand.java:156)
	at com.taobao.arthas.core.command.klass100.JadCommand.process(JadCommand.java:113)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
