### ISSUE TITLE
jad: fail to decompile class: java.lang.String

### ISSUE THREAD

**Issue by zhugw** [alibaba/arthas#860]
```
$ java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

[arthas@1789]$ version
3.1.2
[arthas@1789]$ jad java.lang.String
Affect(row-cnt:0) cost in 206 ms.

$ tail -f ~/logs/arthas/arthas.log
01 2019-09-18 21:04:41.417 ERROR [as-command-execute-daemon:arthas] [] [] [] jad: fail to decompile class: java.lang.String
java.lang.UnsupportedOperationException: null
	at java.util.AbstractList.set(AbstractList.java:132)
	at java.util.AbstractList$ListItr.set(AbstractList.java:426)
	at java.util.Collections.sort(Collections.java:159)
	at org.benf.cfr.reader.CfrDriverImpl.analyse(CfrDriverImpl.java:48)
	at com.taobao.arthas.core.util.Decompiler.decompile(Decompiler.java:60)
	at com.taobao.arthas.core.command.klass100.JadCommand.processExactMatch(JadCommand.java:156)
	at com.taobao.arthas.core.command.klass100.JadCommand.process(JadCommand.java:113)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by hengyunabc** [comment]
参考： https://github.com/alibaba/arthas/issues/851
