### ISSUE TITLE
初次windows使用arthas始终绑定失败，端口没有被占用

### ISSUE THREAD

**Issue by Jsonxuja** [alibaba/arthas#869]
01 2019-09-23 18:14:30.391 ERROR [arthas-binding-thread:arthas] [] [] [] Error during bind to port 3658
java.lang.ExceptionInInitializerError: null
	at com.taobao.arthas.core.shell.ShellServerOptions.<clinit>(ShellServerOptions.java:29) ~[na:na]
	at com.taobao.arthas.core.server.ArthasBootstrap.bind(ArthasBootstrap.java:82) ~[arthas-core.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31]
	at com.taobao.arthas.agent.AgentBootstrap.bind(AgentBootstrap.java:158) [arthas-agent.jar:na]
	at com.taobao.arthas.agent.AgentBootstrap.access$000(AgentBootstrap.java:15) [arthas-agent.jar:na]
	at com.taobao.arthas.agent.AgentBootstrap$1.run(AgentBootstrap.java:125) [arthas-agent.jar:na]
Caused by: java.lang.NullPointerException: null
	at java.io.Reader.<init>(Reader.java:78) ~[na:1.8.0_31]
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72) ~[na:1.8.0_31]
	at com.taobao.arthas.core.util.IOUtils.toString(IOUtils.java:134) ~[arthas-core.jar:na]
	at com.taobao.arthas.core.util.ArthasBanner.<clinit>(ArthasBanner.java:33) ~[na:na]
	... 9 common frames omitted
Arthas server port binding failed! Please check $HOME/logs/arthas/arthas.log for more details.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.taobao.arthas.agent.AgentBootstrap.bind(AgentBootstrap.java:158)
	at com.taobao.arthas.agent.AgentBootstrap.access$000(AgentBootstrap.java:15)
	at com.taobao.arthas.agent.AgentBootstrap$1.run(AgentBootstrap.java:125)
Caused by: java.lang.ExceptionInInitializerError
	at com.taobao.arthas.core.shell.ShellServerOptions.<clinit>(ShellServerOptions.java:29)
	at com.taobao.arthas.core.server.ArthasBootstrap.bind(ArthasBootstrap.java:82)
	... 7 more
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at com.taobao.arthas.core.util.IOUtils.toString(IOUtils.java:134)
	at com.taobao.arthas.core.util.ArthasBanner.<clinit>(ArthasBanner.java:33)
	... 9 more

**Comment by hengyunabc** [comment]
Please check $HOME/logs/arthas/arthas.log for more details.
