### ISSUE TITLE
Attach Jetty应用时出现Connection refused 

### ISSUE THREAD

**Issue by dohu123** [alibaba/arthas#874]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.2
* Arthas 版本: 3.1.2
* 操作系统版本: Linux version 3.10.0-957.12.2.el7.x86_64
* 目标进程的JVM版本: jdk1.8.0_121
* 执行`arthas-boot`的版本: jdk1.8.0_121

### 重现问题的步骤

1. 启动 /usr/lib/java/jdk1.8.0_121/bin/java -jar  arthas-boot.jar
2. 选择进程
3. xxx

### 期望的结果

成功attach

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
[INFO] arthas home: /home/jeeapp/.arthas/lib/3.1.2/arthas
[INFO] Try to attach process 32279
[INFO] Attach process 32279 success.
[INFO] arthas-client connect 127.0.0.1 3658
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
	at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:268)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:527)
Usage: arthas-client [--help] [-c <value>] [-f <value>] [-w <value>] [-h
       <value>] [target-ip] [port]

Arthas Telnet Client

**Comment by hengyunabc** [comment]
查看 `~/logs/arthas/arthas.log`

**Comment by dohu123** [comment]
> 查看 `~/logs/arthas/arthas.log`

Arthas server agent start...
java.lang.NoClassDefFoundError: Could not initialize class com.taobao.arthas.core.server.ArthasBootstrap
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.taobao.arthas.agent.AgentBootstrap.bind(AgentBootstrap.java:175)
        at com.taobao.arthas.agent.AgentBootstrap.access$000(AgentBootstrap.java:16)
        at com.taobao.arthas.agent.AgentBootstrap$1.run(AgentBootstrap.java:140)

**Comment by hengyunabc** [comment]
有没有可重现有demo？

**Comment by hengyunabc** [comment]
试下重启应用，或者试下文档里的  arthas-demo

**Comment by dohu123** [comment]
> 试下重启应用，或者试下文档里的 arthas-demo

用demo是可以的。

**Comment by hengyunabc** [comment]
重启下应用，试下最新的 3.1.4 版本

**Comment by dohu123** [comment]
> 重启下应用，试下最新的 3.1.4 版本

3.14版本可attach上了，谢谢。
