### ISSUE TITLE
在mac上尝试demo时遇到IOException: Connection reset by peer

### ISSUE THREAD

**Issue by kanye0405** [alibaba/arthas#89]
完整错误日志如下：

```
01 2018-09-20 11:37:04.528 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0xf5635a7f, L:/0:0:0:0:0:0:0:0:3658] READ: [id: 0x0812cd1a, L:/127.0.0.1:3658 - R:/127.0.0.1:53590]
01 2018-09-20 11:37:04.529 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0xf5635a7f, L:/0:0:0:0:0:0:0:0:3658] READ COMPLETE
01 2018-09-20 11:37:04.530 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0xf5635a7f, L:/0:0:0:0:0:0:0:0:3658] READ: [id: 0x384a660b, L:/127.0.0.1:3658 - R:/127.0.0.1:53591]
01 2018-09-20 11:37:04.530 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0xf5635a7f, L:/0:0:0:0:0:0:0:0:3658] READ COMPLETE
01 2018-09-20 11:37:04.571 INFO [nioEventLoopGroup-2-2:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
01 2018-09-20 11:37:04.571 INFO [nioEventLoopGroup-2-3:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
01 2018-09-20 11:37:05.209 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0xf5635a7f, L:/0:0:0:0:0:0:0:0:3658] READ: [id: 0x18660177, L:/127.0.0.1:3658 - R:/127.0.0.1:53592]
01 2018-09-20 11:37:05.210 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0xf5635a7f, L:/0:0:0:0:0:0:0:0:3658] READ COMPLETE
01 2018-09-20 11:37:05.215 INFO [nioEventLoopGroup-2-4:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
**01 2018-09-20 11:37:49.215 ERROR [nioEventLoopGroup-2-4:i.t.c.io_error] Reported io error => closing
java.io.IOException: Connection reset by peer**
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_131]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[arthas-core.jar:3.0.4]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108) ~[arthas-core.jar:3.0.4]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[arthas-core.jar:3.0.4]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[arthas-core.jar:3.0.4]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628) [arthas-core.jar:3.0.4]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563) [arthas-core.jar:3.0.4]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480) [arthas-core.jar:3.0.4]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [arthas-core.jar:3.0.4]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [arthas-core.jar:3.0.4]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [arthas-core.jar:3.0.4]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
01 2018-09-20 11:42:46.000 INFO [as-shutdown-hooker:arthas] [] [] [] as-server destroy completed.
01 2018-09-20 11:44:21.170 INFO [arthas-binding-thread:arthas] [] [] [] arthas version: 3.0.4
01 2018-09-20 11:44:21.624 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0xa43d35ce] REGISTERED
01 2018-09-20 11:44:21.626 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0xa43d35ce] BIND: /0.0.0.0:3658
01 2018-09-20 11:44:21.632 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0xa43d35ce, L:/0:0:0:0:0:0:0:0:3658] ACTIVE
01 2018-09-20 11:44:21.633 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x23287c37] REGISTERED
01 2018-09-20 11:44:21.633 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x23287c37] BIND: /0.0.0.0:8563
01 2018-09-20 11:44:21.634 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x23287c37, L:/0:0:0:0:0:0:0:0:8563] ACTIVE
01 2018-09-20 11:44:21.635 INFO [arthas-binding-thread:arthas] [as-server listening on network=3658;telnet=8563;http=6000;timeout={};] [] [] 0.0.0.0
01 2018-09-20 11:44:21.638 INFO [arthas-binding-thread:arthas] [] [] [] as-server started in 502 ms
```

按照demo尝试的，java version "1.8.0_131"
使用sudo也是不行，请问这是什么原因？我是否需要重新安装？

**Comment by hengyunabc** [comment]
尝试“手动拼接命令行启动”：   https://alibaba.github.io/arthas/install-detail.html

**Comment by kanye0405** [comment]
> 尝试“手动拼接命令行启动”： https://alibaba.github.io/arthas/install-detail.html

Start arthas failed, exception stack trace: 
com.sun.tools.attach.AgentLoadException: Agent JAR not found or no Agent-Class attribute
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:117)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:84)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:25)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:96)

遇到这样的报错，但是我确定-agent arthas-agent.jar 没有写错（我在~/.arthas/lib/3.0.4/arthas下执行的），删除后重新安装还是这个报错。

**Comment by kanye0405** [comment]
![image](https://user-images.githubusercontent.com/14052043/45803268-bed88f00-bceb-11e8-984c-d0c8f50e492f.png)
~/.arthas/lib/3.0.4/arthas目录下结构，然后sudo管理员执行，还是这样

**Comment by hengyunabc** [comment]
仔细检查是否jar来源自 bin.zip 里的。从maven仓库里下载的 http://search.maven.org/classic/#search%7Cga%7C1%7Cg%3A%22com.taobao.arthas%22%20AND%20a%3A%22arthas-packaging%22  bin.zip里的 `arthas-agent.jar` 的`META-INF/MANIFEST.MF` 内容是

```
Manifest-Version: 1.0
Premain-Class: com.taobao.arthas.agent.AgentBootstrap
Built-By: hengyunabc
Agent-Class: com.taobao.arthas.agent.AgentBootstrap
Can-Redefine-Classes: true
Can-Retransform-Classes: true
Created-By: Apache Maven 3.5.3
Build-Jdk: 1.8.0_162
```

**Comment by kanye0405** [comment]
> 仔细检查是否jar来源自 bin.zip 里的。从maven仓库里下载的 http://search.maven.org/classic/#search%7Cga%7C1%7Cg%3A%22com.taobao.arthas%22%20AND%20a%3A%22arthas-packaging%22 bin.zip里的 `arthas-agent.jar` 的`META-INF/MANIFEST.MF` 内容是
> 
> ```
> Manifest-Version: 1.0
> Premain-Class: com.taobao.arthas.agent.AgentBootstrap
> Built-By: hengyunabc
> Agent-Class: com.taobao.arthas.agent.AgentBootstrap
> Can-Redefine-Classes: true
> Can-Retransform-Classes: true
> Created-By: Apache Maven 3.5.3
> Build-Jdk: 1.8.0_162
> ```

我本地的arthas-agent.jar的META-INF/MANIFEST.MF与你贴的一致。
然后我去maven仓库里下了arthas-agent-3.0.4.jar 还是会报这个错误。

**Comment by hengyunabc** [comment]
下载 arthas-packaging bin.zip ，里面解压就有 arthas-agent.jar ，不需要另外从仓库里下载 arthas-agent-3.0.4.jar
