### ISSUE TITLE
skywalking 6.4.0 版本兼容性

### ISSUE THREAD

**Issue by jiangwh** [alibaba/arthas#898]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.1.4
* 操作系统版本: mac
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.1.4

### 重现问题的步骤

1. springboot 应用
```
pom.xml
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.1.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
```
2. 启动方式
java -jar -javaagent:/Users/jiangwh/work/apm/apache-skywalking-apm/agent/skywalking-agent.jar 
3. 针对controller类，所有涉及 enhancer 的命令（tracer、watch...）都是无法使用的。

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```

命令行提示：
Error during processing the command: class redefinition failed: attempted to change superclass or interfaces
```
```
log信息
01 2019-10-18 14:05:31.055 ERROR [as-command-execute-daemon:arthas] [] [] [] Error during processing the command:
java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:304)
	at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:111)
	at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:66)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
	at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
```
利用jad反编译之后，发现skywalking增加了代码
    private volatile Object _$EnhancedClassField_ws;
    public static volatile /* synthetic */ InstMethodsInter delegate$u0hd2k1;
    public static volatile /* synthetic */ InstMethodsInter delegate$460rga0;
    public static volatile /* synthetic */ ConstructorInter delegate$6jajft0;
    private static final /* synthetic */ Method cachedValue$dOCHe5Or$4s1o1e2;
    private static final /* synthetic */ Method cachedValue$dOCHe5Or$ksuhpf2;
    private static final /* synthetic */ Method cachedValue$dOCHe5Or$uvgf0r1;
    private static final /* synthetic */ Method cachedValue$dOCHe5Or$t8csph3;
    public static volatile /* synthetic */ InstMethodsInter delegate$2tn3l40;
    public static volatile /* synthetic */ InstMethodsInter delegate$leucot1;
    public static volatile /* synthetic */ ConstructorInter delegate$c7fkhv0;
    private static final /* synthetic */ Method cachedValue$CJkQImHA$4s1o1e2;
    private static final /* synthetic */ Method cachedValue$CJkQImHA$ksuhpf2;
    private static final /* synthetic */ Method cachedValue$CJkQImHA$uvgf0r1;
    private static final /* synthetic */ Method cachedValue$CJkQImHA$t8csph3;

```
还有一个静态方法。不一一列举了

**Comment by jiangwh** [comment]
感觉是jdk的bug

**Comment by hengyunabc** [comment]
和 arthas无关，参考： https://github.com/alibaba/arthas/issues/1141
