### ISSUE TITLE
Windows命令行启动报错：com.sun.tools.attach.AttachNotSupportedException: 拒绝访问。

### ISSUE THREAD

**Issue by smileMurphy** [alibaba/arthas#903]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 的版本： 3.1.4
* Arthas 版本: 3.1.4
* 操作系统版本: Windows 10
* 目标进程的JVM版本: Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
                                    Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
* 执行`arthas-boot`的版本:  3.1.4

### 重现问题的步骤

1. 
D:\Project\Java\jdk1.8.0_131\bin>java -jar C:\Users\Administrator\Desktop\Arthas\arthas-packaging-3.1.4-bin\arthas-boot.jar
[INFO] arthas-boot version: 3.1.4
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 87792 org.jetbrains.jps.cmdline.Launcher
  [2]: 60100 org.jetbrains.jps.cmdline.Launcher
  [3]: 68324 org.jetbrains.jps.cmdline.Launcher
  [4]: 84116 org.jetbrains.jps.cmdline.Launcher
  [5]: 98100 org.jetbrains.jps.cmdline.Launcher
  [6]: 40472
  [7]: 63304 org.apache.catalina.startup.Bootstrap
  [8]: 29436 org.jetbrains.jps.cmdline.Launcher
2. 输入7
3.报错
[INFO] arthas home: C:\Users\Administrator\Desktop\Arthas\arthas-packaging-3.1.4-bin
[INFO] Try to attach process 63304
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AttachNotSupportedException: 拒绝访问。
        at sun.tools.attach.WindowsVirtualMachine.<init>(WindowsVirtualMachine.java:64)
        at sun.tools.attach.WindowsAttachProvider.attachVirtualMachine(WindowsAttachProvider.java:69)
        at com.sun.tools.attach.spi.AttachProvider.attachVirtualMachine(AttachProvider.java:194)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:85)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:123)
### 期望的结果

What do you expected from the above steps？

### 实际运行的结果
D:\Project\Java\jdk1.8.0_131\bin>java -jar C:\Users\Administrator\Desktop\Arthas\arthas-packaging-3.1.4-bin\arthas-boot.jar
[INFO] arthas-boot version: 3.1.4
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 87792 org.jetbrains.jps.cmdline.Launcher
  [2]: 60100 org.jetbrains.jps.cmdline.Launcher
  [3]: 68324 org.jetbrains.jps.cmdline.Launcher
  [4]: 84116 org.jetbrains.jps.cmdline.Launcher
  [5]: 98100 org.jetbrains.jps.cmdline.Launcher
  [6]: 40472
  [7]: 63304 org.apache.catalina.startup.Bootstrap
  [8]: 29436 org.jetbrains.jps.cmdline.Launcher
7
[INFO] arthas home: C:\Users\Administrator\Desktop\Arthas\arthas-packaging-3.1.4-bin
[INFO] Try to attach process 63304
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AttachNotSupportedException: 拒绝访问。
        at sun.tools.attach.WindowsVirtualMachine.<init>(WindowsVirtualMachine.java:64)
        at sun.tools.attach.WindowsAttachProvider.attachVirtualMachine(WindowsAttachProvider.java:69)
        at com.sun.tools.attach.spi.AttachProvider.attachVirtualMachine(AttachProvider.java:194)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:85)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:123)
[ERROR] attach fail, targetPid: 63304

**Comment by hengyunabc** [comment]
试下 jstack 

查看 ~/logs/arthas/arthas.log

**Comment by xuxiaohongok** [comment]
我没有解决方案呢，我也遇到了这种情况。win10，启动不起来com.sun.tools.attach.AttachNotSupportedException: 拒绝访问

**Comment by 312527814** [comment]
把杀毒软件给关了，我的就是360给拦截了
