### ISSUE TITLE
在一个container里对另一个container里的进程使用时报错

### ISSUE THREAD

**Issue by lh404** [alibaba/arthas#914]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.4
* Arthas 版本: 3.1.4
* 操作系统版本: CentOS Linux release 7.6.1810 (Core)
* 目标进程的JVM版本: jdk1.8.0_172
* 执行`arthas-boot`的版本: openjdk version "13" 2019-09-17

### 重现问题的步骤

1. 起一个容器A，内部正常运行一个java进程
2. 在同一个宿主机上起一个容器B，目的是对A进行debug，B加入A的pid namespace，在B中能看到A中的java进程，使用 java -jar arthas-boot.jar $PID 时会报错

### 期望的结果

能正常使用

### 实际运行的结果

```
[INFO] arthas-boot version: 3.1.4
[INFO] arthas home: /root/.arthas/lib/3.1.4/arthas
[INFO] Try to attach process 1
[WARN] Current VM java version: 13 do not match target VM java version: 1.8, attach may fail.
[WARN] Target VM JAVA_HOME is /usr/lib/jvm/jdk1.8.0_172/jre, arthas-boot JAVA_HOME is /opt/jdk-13, try to set the same JAVA_HOME.
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AgentLoadException: 0
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:108)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:119)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:147)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:104)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:123)
[ERROR] attach fail, targetPid: 1
```

**Comment by hengyunabc** [comment]
参考： https://github.com/alibaba/arthas/issues/362
