### ISSUE TITLE
Istio下，选择进程号后报错：Can not find Arthas under local: /root/.arthas/lib and remote: center

### ISSUE THREAD

**Issue by hechuan73** [alibaba/arthas#929]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.4
* Arthas 版本: 3.1.4
* 操作系统版本: CentOS 7
* 目标进程的JVM版本: openjdk8
* 执行`arthas-boot`的版本: 3.1.4

* docker: 18.09
* kubernetes: 1.14
* istio: 1.0

### 重现问题的步骤

1. java -jar arthas-boot.jar
2. java -jar arthas-boot.jar --use-http

### 期望的结果

成功关联到相关进程

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
root@ts-auth-service-67d8f9c7f7-7f5tk:/# java -jar arthas-boot.jar 
[INFO] arthas-boot version: 3.1.4
1
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 1 /app/ts-auth-service-1.0.jar
[ERROR] TLS connect error, please try to use --use-http argument.
[ERROR] URL: https://repo1.maven.org/maven2/com/taobao/arthas/arthas-packaging/maven-metadata.xml
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:994)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
        at com.taobao.arthas.boot.DownloadUtils.openURLConnection(DownloadUtils.java:208)
        at com.taobao.arthas.boot.DownloadUtils.readMavenMetaData(DownloadUtils.java:83)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:424)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.read(InputRecord.java:505)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
        ... 12 more
[ERROR] Can not find Arthas under local: /root/.arthas/lib and remote: center
```
添加--use-http之后，还是不行
```
root@ts-auth-service-67d8f9c7f7-7f5tk:/# java -jar arthas-boot.jar --use-http
[INFO] arthas-boot version: 3.1.4
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 1 /app/ts-auth-service-1.0.jar
1
[ERROR] Can not read maven-metadata.xml from: http://repo1.maven.org/maven2/com/taobao/arthas/arthas-packaging/maven-metadata.xml
[ERROR] Can not find Arthas under local: /root/.arthas/lib and remote: center
```

请教：
1. 由于使用了istio，不知道是否和sidecar代理有关？如果有关，这个地方的安全协议应该怎么设置？
2. 此外，这个地方是去远端仓库加载maven-metadata.xml，有没有可能本地下载该文件，重新打包Arthas，如果可行，应该怎么操作？

谢谢！

**Comment by hechuan73** [comment]
由于在容器中拉jar包报错：
```
root@ts-auth-service-67d8f9c7f7-7f5tk:/# wget https://alibaba.github.io/arthas/arthas-boot.jar
--2019-11-13 14:13:56--  https://alibaba.github.io/arthas/arthas-boot.jar
Resolving alibaba.github.io (alibaba.github.io)... 185.199.108.153, 185.199.109.153, 185.199.111.153, ...
Connecting to alibaba.github.io (alibaba.github.io)|185.199.108.153|:443... connected.
GnuTLS: The TLS connection was non-properly terminated.
Unable to establish SSL connection.
```
所以，我是把arthas-boot.jar放在base镜像中运行的。

**Comment by hechuan73** [comment]
这两个网站都是能ping通的，感觉应该是协议的问题，但是使用上面使用--use-http也报错，不知道应该怎么修改。
```
root@ts-auth-service-67d8f9c7f7-v4g2x:/# ping repo1.maven.org -c 5
PING sonatype.map.fastly.net (151.101.24.209) 56(84) bytes of data.
64 bytes from 151.101.24.209 (151.101.24.209): icmp_seq=1 ttl=43 time=188 ms
64 bytes from 151.101.24.209 (151.101.24.209): icmp_seq=2 ttl=43 time=187 ms
64 bytes from 151.101.24.209 (151.101.24.209): icmp_seq=3 ttl=43 time=187 ms
64 bytes from 151.101.24.209 (151.101.24.209): icmp_seq=4 ttl=43 time=187 ms
64 bytes from 151.101.24.209 (151.101.24.209): icmp_seq=5 ttl=43 time=187 ms

--- sonatype.map.fastly.net ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4005ms
rtt min/avg/max/mdev = 187.411/187.779/188.197/0.249 ms
root@ts-auth-service-67d8f9c7f7-v4g2x:/# 
root@ts-auth-service-67d8f9c7f7-v4g2x:/# 
root@ts-auth-service-67d8f9c7f7-v4g2x:/# ping alibaba.github.io -c 5
PING alibaba.github.io (185.199.108.153) 56(84) bytes of data.
64 bytes from 185.199.108.153 (185.199.108.153): icmp_seq=1 ttl=43 time=172 ms
64 bytes from 185.199.108.153 (185.199.108.153): icmp_seq=2 ttl=43 time=172 ms
64 bytes from 185.199.108.153 (185.199.108.153): icmp_seq=3 ttl=43 time=172 ms
64 bytes from 185.199.108.153 (185.199.108.153): icmp_seq=4 ttl=43 time=172 ms
64 bytes from 185.199.108.153 (185.199.108.153): icmp_seq=5 ttl=43 time=172 ms

--- alibaba.github.io ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4003ms
rtt min/avg/max/mdev = 172.243/172.419/172.977/0.282 ms
```

**Comment by hengyunabc** [comment]
下载是 http下载，你直接wget就知道了。网络不通，参考wiki直接下载全量包。

**Comment by hechuan73** [comment]
wiki中下载arthas-boot.jar是写的：
```
wget https://alibaba.github.io/arthas/arthas-boot.jar
```
arthas-boot.jar包运行后加载maven-metadata.xml，资源地址也是写的https://xxxx。 在Istio下无法下载资源本质的原因是因为，往外发的请求，没有配置路由规则，所以无法建立连接下载资源。解决办法：
1. 参考[wiki](https://alibaba.github.io/arthas/download.html)中下载全量包，放在容器中，相当于离线运行。
2. 配置Istio的的转发规则[TLS origination for egress traffic](https://istio.io/docs/tasks/traffic-management/egress/egress-tls-origination/)，将host的地址替换成alibaba.github.io和repo1.maven.org即可。
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: edition-cnn-com
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  - number: 443
    name: https-port-for-tls-origination
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: edition-cnn-com
spec:
  hosts:
  - edition.cnn.com
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: edition-cnn-com
spec:
  host: edition.cnn.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE # initiates HTTPS when accessing edition.cnn.com
EOF
```
然后，在下载arthas-boot.jar和运行jar包时，需要使用http而不是https。
```
wget http://alibaba.github.io/arthas/arthas-boot.jar
java -jar arthas-boot.jar --use-http
```
官网关于配置转发规则的一段解释：

_“As you can see, the VirtualService redirects HTTP requests on port 80 to port 443 where the corresponding DestinationRule then performs the TLS origination. Notice that unlike the ServiceEntry in the previous section, this time the protocol on port 443 is HTTP, instead of HTTPS. This is because clients will only send HTTP requests and Istio will upgrade the connection to HTTPS.”_

以上是关于在Service Mesh (Istio)下配置使用Arthas所遇到的问题和解决办法。

**Comment by hechuan73** [comment]
再补一下：
在配置了转发规则之后，直接执行：
```
root@ts-auth-service-67d8f9c7f7-v4g2x:/# java -jar arthas-boot.jar -v
[INFO] arthas-boot version: 3.1.4
[DEBUG] Repo mirror:center
[TRACE] Couldn't run command [lsof, -t, -s, TCP:LISTEN, -i, TCP:3658]:
java.io.IOException: Cannot run program "lsof": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at java.lang.Runtime.exec(Runtime.java:485)
        at com.taobao.arthas.common.ExecutingCommand.runNative(ExecutingCommand.java:46)
        at com.taobao.arthas.common.ExecutingCommand.runNative(ExecutingCommand.java:31)
        at com.taobao.arthas.common.ExecutingCommand.getAnswerAt(ExecutingCommand.java:102)
        at com.taobao.arthas.common.ExecutingCommand.getFirstAnswer(ExecutingCommand.java:87)
        at com.taobao.arthas.common.SocketUtils.findTcpListenProcess(SocketUtils.java:36)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:320)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 8 more
[TRACE] Couldn't run command [lsof, -t, -s, TCP:LISTEN, -i, TCP:8563]:
java.io.IOException: Cannot run program "lsof": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at java.lang.Runtime.exec(Runtime.java:485)
        at com.taobao.arthas.common.ExecutingCommand.runNative(ExecutingCommand.java:46)
        at com.taobao.arthas.common.ExecutingCommand.runNative(ExecutingCommand.java:31)
        at com.taobao.arthas.common.ExecutingCommand.getAnswerAt(ExecutingCommand.java:102)
        at com.taobao.arthas.common.ExecutingCommand.getFirstAnswer(ExecutingCommand.java:87)
        at com.taobao.arthas.common.SocketUtils.findTcpListenProcess(SocketUtils.java:36)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:326)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 8 more
[DEBUG] Found jps: /usr/local/openjdk-8/jre/../bin/jps
[DEBUG] Try use jps to lis java process, jps: /usr/local/openjdk-8/jre/../bin/jps
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 1 /app/ts-auth-service-1.0.jar -Xmx200m
1
[DEBUG] Download maven-metadata.xml from: https://repo1.maven.org/maven2/com/taobao/arthas/arthas-packaging/maven-metadata.xml
[ERROR] TLS connect error, please try to use --use-http argument.
[ERROR] URL: https://repo1.maven.org/maven2/com/taobao/arthas/arthas-packaging/maven-metadata.xml
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
        at sun.security.ssl.InputRecord.read(InputRecord.java:527)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
        at com.taobao.arthas.boot.DownloadUtils.openURLConnection(DownloadUtils.java:208)
        at com.taobao.arthas.boot.DownloadUtils.readMavenMetaData(DownloadUtils.java:83)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:424)
[INFO] arthas home: /root/.arthas/lib/3.1.4/arthas
[INFO] Try to attach process 1
[DEBUG] Start arthas-core.jar args: [-jar, /root/.arthas/lib/3.1.4/arthas/arthas-core.jar, -pid, 1, -target-ip, 127.0.0.1, -telnet-port, 3658, -http-port, 8563, -core, /root/.arthas/lib/3.1.4/arthas/arthas-core.jar, -agent, /root/.a]
[DEBUG] Found java: /usr/local/openjdk-8/jre/bin/java
[DEBUG] Found java: /usr/local/openjdk-8/jre/../bin/java
[DEBUG] Found tools.jar: /usr/local/openjdk-8/jre/../lib/tools.jar
[INFO] Attach process 1 success.
[INFO] arthas-client connect 127.0.0.1 3658
[DEBUG] Start arthas-client.jar args: [127.0.0.1, 3658]
  ,---.  ,------. ,--------.,--.  ,--.  ,---.   ,---.                           
 /  O  \ |  .--. ''--.  .--'|  '--'  | /  O  \ '   .-'                          
|  .-.  ||  '--'.'   |  |   |  .--.  ||  .-.  |`.  `-.                          
|  | |  ||  |\  \    |  |   |  |  |  ||  | |  |.-'    |                         
`--' `--'`--' '--'   `--'   `--'  `--'`--' `--'`-----'                          
                                                                                

wiki      https://alibaba.github.io/arthas                                      
tutorials https://alibaba.github.io/arthas/arthas-tutorials                     
version   3.1.4                                                                 
pid       1                                                                     
time      2019-11-14 07:05:38
```
会出现两个异常：
1. 第一个是容器内没有安装lsof，所导致的命令执行异常，没来得及拜读源码，不知道这个异常会不会产生其它影响。
2. 第二个是不识别SSL message，推荐使用--use-http，不过最终也正常运行起来了，可以先使用着，后面再考虑下这个问题。
