### ISSUE TITLE
watch ongl表达式太长出错

### ISSUE THREAD

**Issue by p1v07** [alibaba/arthas#948]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.4
* Arthas 版本: 3.1.4
* 操作系统版本: CentOS7.2
* 目标进程的JVM版本: jdk1.8.0_201
* 执行`arthas-boot`的版本: 3.1.4

### 重现问题的步骤

```
watch org.apache.catalina.mapper.Mapper map -n 1 'LONG OGNL EXPRESS'
```

### 期望的结果

正常执行ognl表达式

### 实际运行的结果

交互式命令行报错退出：
```
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at org.apache.commons.net.telnet.TelnetInputStream.__read(TelnetInputStream.java:132)
        at org.apache.commons.net.telnet.TelnetInputStream.run(TelnetInputStream.java:603)
        at java.lang.Thread.run(Thread.java:748)
```

arthas.log：

```
01 2019-11-26 19:03:08.155 ERROR [nioEventLoopGroup-2-11:i.t.c.io_error] Reported io error => closing
java.lang.ArrayIndexOutOfBoundsException: null
```

**Comment by p1v07** [comment]
update:
所有命令长度超过一定值（如1000）就会异常退出

**Comment by hengyunabc** [comment]
termd里直接写死了是 1000。

https://github.com/alibaba/termd/blob/termd-core-1.1.7.5/src/main/java/io/termd/core/readline/LineBuffer.java#L36
