### ISSUE TITLE
设置环境变量`_JAVA_OPTIONS` 导致启动失败

### ISSUE THREAD

**Issue by anjia0532** [alibaba/arthas#970]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.7
* Arthas 版本: 3.1.7
* 操作系统版本: alpine
* 目标进程的JVM版本: jdk8
* 执行`arthas-boot`的版本: 3.1.7

### 重现问题的步骤
1. 设置环境变量 `_JAVA_OPTIONS`
```
export _JAVA_OPTIONS="-Xmx512m -Xms512m -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCApplicationStoppedTime -XX:+PrintCommandLineFlags -XX:+HeapDumpOnOutOfMemoryError -Xloggc:/var/log/heap_trace.log -XX:HeapDumpPath=/var/log/ -XX:-OmitStackTraceInFastThrow"
```
2. 启动 `arthas-boot.jar` 
```
java -jar arthas-boot.jar
```
### 期望的结果

正常启动

### 实际运行的结果

```
Picked up _JAVA_OPTIONS: -Xmx512m -Xms512m -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCApplicationStoppedTime -XX:+PrintCommandLineFlags -XX:+HeapDumpOnOutOfMemoryError -Xloggc:/var/log/heap_trace.log -XX:HeapDumpPath=/var/log/ -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/ -XX:InitialHeapSize=536870912 -XX:MaxHeapSize=536870912 -XX:-OmitStackTraceInFastThrow -XX:+PrintCommandLineFlags -XX:+PrintGC -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+UseCompressedClassPointers -XX:+UseCompressedOops

[INFO] arthas-boot version: 3.1.7
Exception in thread "main" java.lang.NumberFormatException: For input string: "-XX:+HeapDumpOnOutOfMemoryError"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.taobao.arthas.boot.ProcessUtils.listProcessByJps(ProcessUtils.java:110)
        at com.taobao.arthas.boot.ProcessUtils.select(ProcessUtils.java:32)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:336)

```
把异常信息贴到这里
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "-XX:+HeapDumpOnOutOfMemoryError"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.taobao.arthas.boot.ProcessUtils.listProcessByJps(ProcessUtils.java:110)
        at com.taobao.arthas.boot.ProcessUtils.select(ProcessUtils.java:32)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:336)
```

**Comment by LinXuanran** [comment]
今天晚上本来打算解决这个bug，首先承认这个问题存在于官网下载的arthas-boot.jar的版本里，但是不是bug，而是官网jar版本存在构建的问题，从源码构建的结果是没有错误。希望可以解决你的问题，另在
as.sh 的版本中也不存在这个问题
![image](https://user-images.githubusercontent.com/28882272/70802622-e504b600-1dec-11ea-82b9-8c56d60d3d3b.png)

**Comment by anjia0532** [comment]
@LinXuanran 感谢回复，用的时候，手动 `unset` 也是可以的。只是还是希望官方能默认解决这个问题，不然对于一些不太懂的人，会造成困扰。
