### ISSUE TITLE
tunnel-server连接到远程的arthas-boot有时候会断，然后就连不上了。

### ISSUE THREAD

**Issue by ezrio** [alibaba/arthas#975]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： docker镜像
* Arthas 版本: docker镜像
* 操作系统版本: CentOS Linux release 7.5.1804
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: docker镜像

### 重现问题的步骤
1、制作了一个webconsole用来连接远程机器上面的arthas。
2. docker上面启动了arthas-boot.jar后，启动成功，但是tunnel-server的ws连不上。需要重启应用然后再次启动arthas-boot才能连上。连接一段时间，webconsole就有无法连接远程机器的arthas了。远程机器上面的arthas日志无异常。

tunnel-server报错：

2019-12-13 16:18:24.049  INFO 32673 --- [tLoopGroup-3-13] c.a.a.t.server.TunnelSocketFrameHandler  : websocket handshake complete, uri: /wstunnel/ws?method=connectArthas&id=10.232.24.56
2019-12-13 16:18:24.049  INFO 32673 --- [tLoopGroup-3-13] c.a.a.t.server.TunnelSocketFrameHandler  : try to connect to arthas agent, id: 10.232.24.56
2019-12-13 16:18:24.050 ERROR 32673 --- [tLoopGroup-3-13] c.a.a.t.server.TunnelSocketFrameHandler  : Can not find arthas agent by id: [10.232.24.56]
2019-12-13 16:18:24.051  WARN 32673 --- [tLoopGroup-3-13] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

java.lang.IllegalArgumentException: Can not find arthas agent by id: [10.232.24.56]
        at com.alibaba.arthas.tunnel.server.TunnelSocketFrameHandler.connectArthas(TunnelSocketFrameHandler.java:159) ~[classes!/:na]
        at com.alibaba.arthas.tunnel.server.TunnelSocketFrameHandler.userEventTriggered(TunnelSocketFrameHandler.java:59) ~[classes!/:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:341) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:327) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:319) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandshakeHandler$1.operationComplete(WebSocketServerProtocolHandshakeHandler.java:103) [netty-codec-http-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandshakeHandler$1.operationComplete(WebSocketServerProtocolHandshakeHandler.java:92) [netty-codec-http-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500) [netty-common-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474) [netty-common-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413) [netty-common-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:149) [netty-common-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandshakeHandler.channelRead(WebSocketServerProtocolHandshakeHandler.java:92) [netty-codec-http-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:102) [netty-codec-http-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328) [netty-codec-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302) [netty-codec-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) [netty-common-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.38.Final.jar!/:4.1.38.Final]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

2019-12-13 16:18:24.052  WARN 32673 --- [tLoopGroup-3-13] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Invalid close frame getStatus code: 2000
        at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:426) ~[netty-codec-http-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:422) ~[netty-codec-http-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.checkCloseFrameBody(WebSocket08FrameDecoder.java:479) ~[netty-codec-http-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:339) ~[netty-codec-http-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505) ~[netty-codec-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444) ~[netty-codec-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283) ~[netty-codec-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511) [netty-transport-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) [netty-common-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.38.Final.jar!/:4.1.38.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.38.Final.jar!/:4.1.38.Final]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

**Comment by ezrio** [comment]
前端用ws协议连接tunnel-server服务器。

**Comment by ezrio** [comment]
前端用：ws://' +url+ '/ws?method=connectArthas&id=xxxx  连接的

**Comment by ezrio** [comment]
arthas-boot端日志：

**Comment by ezrio** [comment]
Arthas server agent start...
Arthas server already bind.
01 2019-12-13 15:56:00.059 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x53e06ea4, L:/127.0.0.1:3658] READ: [id: 0x40917118, L:/127.0.0.1:3658 - R:/127.0.0.1:54246]
01 2019-12-13 15:56:00.060 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x53e06ea4, L:/127.0.0.1:3658] READ COMPLETE
01 2019-12-13 15:56:00.062 INFO [nioEventLoopGroup-3-4:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
01 2019-12-13 16:18:02.726 INFO [nioEventLoopGroup-3-4:arthas] [] [] [] Session acacf302-9732-4667-864c-87cfef7a2c77 closed, so terminate foreground job, id: 43, line: sc com.auto*
Arthas server agent start...
Arthas server already bind.

**Comment by hengyunabc** [comment]
检查应用机器上的 ~/logs/arthas/arthas.log 如果断连的话，会有重连的信息。

**Comment by ezrio** [comment]
没有重连信息， ~/logs/arthas/arthas.log 日志就是：
Arthas server agent start...
Arthas server already bind.
01 2019-12-13 15:56:00.059 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x53e06ea4, L:/127.0.0.1:3658] READ: [id: 0x40917118, L:/127.0.0.1:3658 - R:/127.0.0.1:54246]
01 2019-12-13 15:56:00.060 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x53e06ea4, L:/127.0.0.1:3658] READ COMPLETE
01 2019-12-13 15:56:00.062 INFO [nioEventLoopGroup-3-4:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
01 2019-12-13 16:18:02.726 INFO [nioEventLoopGroup-3-4:arthas] [] [] [] Session acacf302-9732-4667-864c-87cfef7a2c77 closed, so terminate foreground job, id: 43, line: sc com.auto*

我kill掉arthas-boot的进程以后再次启动。日志就是这样的。但是前端web去连接tunnel-server的时候（ws://' +域名+ '/ws?method=connectArthas&id=xxxx ），tunnel-server的日志报错。找不到agent id。感觉是启动arthas-boot的时候，没用注册上去。但是启动的时候用了命令：java -jar arthas-boot.jar --tunnel-server ws://域名/ws --agent-id xxxxx

**Comment by ezrio** [comment]
启动arthas-boot是没问题的。arthas正常启动了。但是只能在机器上面去敲命令。不能远程界面去操作。远程的web界面就连不上了。

**Comment by ezrio** [comment]
如果我重启了我机器上面的应用，然后再次启动arthas。远程web就可以正常连接了。但是也存在连接一段时间后，我关闭web页面后在打开，web页面连接tunnel-server的时候就又连不上了。tunnel-server报错：找不到相应的agent id。就是最上面粘贴的错误。web关闭应该不需要给tunnel-server传递什么信息吧。直接关闭ws不就断开了嘛。

**Comment by hengyunabc** [comment]
arthas-boot 只是一个辅助启动类，真正跑的代码在应用的进程里。 用`as.sh`启动也是一样的。

**Comment by ezrio** [comment]
这个跟用哪个启动应该没关系，举个实例场景，我用ssh登录了一个远程服务器，当我启动arthas，并制定了tunnel-server地址，然后用浏览器去连接tunnel-server。成功连接。我关闭了ssh终端再次打开，然后ps进程看到arthas进程依然存活。这是我再次用浏览器去连接tunnel-server就连接不上了。tunnel-server报错：Can not find arthas agent by id: [xxxxx]。 除非我重启我服务器的应用，否则arthas将无法远程使用。只能在服务器上面使用。  这个不应该是网络问题吧。

**Comment by hengyunabc** [comment]
> 这个跟用哪个启动应该没关系，举个实例场景，我用ssh登录了一个远程服务器，当我启动arthas，并制定了tunnel-server地址，然后用浏览器去连接tunnel-server。成功连接。我关闭了ssh终端再次打开，然后ps进程看到arthas进程依然存活。这是我再次用浏览器去连接tunnel-server就连接不上了。tunnel-server报错：Can not find arthas agent by id: [xxxxx]。 除非我重启我服务器的应用，否则arthas将无法远程使用。只能在服务器上面使用。 这个不应该是网络问题吧。

可以开两个shell窗口：

* A窗口正常attach应用

* B窗口查看tcp连接，确定连接到tunnel-server的socket。 再观察Socket是否在窗口A关掉时断开。

**Comment by ezrio** [comment]
监控了一下发现，session有的时候会结束。在启动也连不上server，因为程序里面还运行着。所以用stop命令后，再次连接就可以连上了。

**Comment by cookiejoo** [comment]
> 监控了一下发现，session有的时候会结束。在启动也连不上server，因为程序里面还运行着。所以用stop命令后，再次连接就可以连上了。

我的也有类似这个问题,但我的server是ip是变化的,一旦注册了一个ip成功后,如果不执行stop,就无法注册其他的ip了,必须回到这台机器,重新注册一下,然后stop掉,才能注册到其他的ip去.

**Comment by maofan0314** [comment]
我也遇到这个问题，咋解决的

**Comment by maofan0314** [comment]
楼主有没有解决，我的是过段时间不连就再也连不上了，除非重启agent

**Comment by hengyunabc** [comment]
试下最新版本，应该解决了。
