### ISSUE TITLE
arthas home lib目录下突然多出来的一个html目录导致arthas不可用问题反馈

### ISSUE THREAD

**Issue by zhugw** [alibaba/arthas#979]
**问题反馈**
突然Arthas就使用不了了 报错信息如下 
```
/arthason in thread "main" java.lang.IllegalArgumentException: illegal arthas home: /Users/zhugw/.arthas/lib/<html>
	at com.taobao.arthas.boot.Bootstrap.verifyArthasHome(Bootstrap.java:559)
	at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:433)
```
查看提到的lib目录 确实多了一个莫名其妙的`<html>?`文件夹 

```
ls -lt  /Users/zhugw/.arthas/lib
total 0
drwxr-xr-x  2 zhugw  staff  64 Dec 20 22:21 <html>?
drwxr-xr-x  3 zhugw  staff  96 Dec  6 12:33 3.1.7

```
删除了这个奇怪的html文件之后 就恢复正常了 不知道为什么会多出一个html文件夹来

**Comment by hengyunabc** [comment]
没有后续，先关掉了
